### ISSUE TITLE
[BUG] Engines property not working

### ISSUE THREAD

**Issue by luchillo17** [npm/cli#692] opened 2020-01-14 16:21 UTC
# What / Why
Engines property in packaje.json does nothing, if i put `"node": ">=9.0.0 <=9.11.2"` but use version `13.6.0` npm doesn't block nor warns about the node version being wrong.

## Where
* node: 9.11.2 & 13.6.0
* npm: 6.13.4

### Current Behavior
When installing with a node version that doesn't match the version in `engines`, npm doesn't block nor warns the user of the engines difference.

### Steps to Reproduce
* Install latest node with latest npm
* Initialize an npm folder
* Set engines to something prior to node 10
* Run npm install and observe no warning for the npm version happens

### Expected Behavior
* Install should exit with a clear message that the engine doesn't match, or at least warn about it.

## Who
* npm/cli

**Comment by nicolas-charrier** [comment] 2020-03-11 16:21
This is an ancient bug apparently :
https://github.com/npm/npm/issues/12486

**Comment by luchillo17** [comment] 2020-03-11 16:32
@nicolas-charrier It is indeed but the original one is in the archived repo so it's disabled.

**Comment by ljharb** [comment] 2020-03-11 17:30
It's not a bug, it's a design decision. "engines" is purely advisory, and should never block installs.

(There may be an issue with `engineStrict`, but nothing *should* happen by default)

**Comment by luchillo17** [comment] 2020-03-11 18:33
At least should warn, in a project, things will break if not using the right node version, so at least it should warn the user that it's using the wrong engine version.

**Comment by ljharb** [comment] 2020-03-11 18:34
That would be reasonable.

You can use `npx ls-engines` in `postinstall`, in the meantime, to check this for yourself ;-)

**Comment by luchillo17** [comment] 2020-03-11 18:35
Well, I guess a workaround in the meantime is ok.

**Comment by erichstark** [comment] 2020-06-25 11:07
Any update on this?

**Comment by scotch83** [comment] 2020-11-18 16:53
it works on my side if I add the .npmrc file in the project root, with `engine-strict=true` in it.
`npm -v` 
`6.14.6`

**Comment by darcyclarke** [comment] 2021-06-02 21:45
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 21:45 UTC
Labels: Bug
