### ISSUE TITLE
[BUG] confused with peerDependencies version

### ISSUE THREAD

**Issue by wangxdmm** [npm/cli#3897] opened 2021-10-15 02:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**peer-test/package.json**
```json
{
  "name": "peer-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "peertest-a": "^1.0.0",
    "peertest-b": "^1.0.0"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```
**peertest-a have 1.0.0 and 2.0.0(latest) all of them have dependencies and peerDependencies are empty**
**peertest-b/package.json 1.0.0(latest)** 
```json
{
  "name": "peertest-b",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "peertest-c": "^1.0.0"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```
**peertest-c/package.json(latest)**
```json
{
  "name": "peertest-c",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "peerDependencies": {
    "peertest-a": ">=1.0.0"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```

### Expected Behavior

```shell
cd peer-test
npm i
```
**expect peer-test/node_modules**  
```shell
node_modules
  -peertest-a 1.0.0
  -peertest-b 1.0.0
  -peertest-c 1.0.0
````

**but the fact is**
```shell
node_modules
  -peertest-a 1.0.0
  -peertest-b 1.0.0
      -node_modules
        -peertest-c 1.0.0
````

so , I want to know why peertest-c `can not move to ROOT`.
But, I change peertest-c `peerDependencies` to `^1.0.0`，the result is true.

### Steps To Reproduce

```shell
cd peer-test
npm i
```

### Environment

- OS: win10
- Node: v14.17.5
- npm: 8.0.0

**Comment by lukekarrys** [comment] 2021-10-20 17:52
This is a duplicate of #3881, but a simpler case to see what the actual tree looked like when installing a sub-dependency with a peerDependency with a wider semver range than in the root. The expected behavior should now happen with https://github.com/npm/arborist/pull/337 which will be released in the cli tomorrow.

**Closed as completed by lukekarrys** 2021-10-20 17:52 UTC
Labels: Release 8.x, Bug, Priority 1
