### ISSUE TITLE
[BUG] Lockfile generation by `npm install` is not idempotent

### ISSUE THREAD

**Issue by H12** [npm/cli#3652] opened 2021-08-14 17:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running `npm install` can produce slightly different `package-lock.json` files on successive runs.

### Expected Behavior

The `package-lock.json` file does not change between `npm install`s for a given project/environment.

### Steps To Reproduce

1. Using [this project](https://github.com/H12/sample_liveview_app) as an example...
    1. `git clone git@github.com:H12/sample_liveview_app.git`
    2. `cd sample_liveview_app`
    3. ` cd assets` (This is where npm deps live in [Phoenix](https://github.com/phoenixframework/phoenix) projects)
2. Re-generate the `package-lock.json`
    1. `rm package-lock.json`
    2. `npm install`
3. Notice that there are differences between new package-lock.json and the committed one
    1. `git diff`
4. Notice the differences go away if you run `npm install` again
    1. `npm install`
    2. `git diff`

### Note

This can be a little tricky to reproduce based on timing -- if dependency versions change between the time of my writing this, and when regenerating the `package-lock.json` is attempted, there will be version-related differences that are unrelated to the issue at hand.

To get around this, create a new commit with the new `package-lock.json` with the updated dependency versions and attempt the steps to reproduce again.

```
// ~/<path-to-project>/sample_liveview_app/assets

$ rm package-lock.json
$ npm install
$ git diff

// See a bunch of version differences, so commit and retry

$ npm install
$ git commit --amend
$ rm package-lock.json
$ npm install
$ git diff

// Should see more reasonable diff

$ npm install
$ git diff

// Diff should go away
```

### Environment

- OS: MacOS 11.4
- Node: 14.17.4
- npm: 7.20.6

**Comment by wraithgar** [comment] 2022-03-16 17:12
Is this still a problem? A lot of these types of issues were fixed in npm since this was opened

**Comment by nlf** [comment] 2022-04-27 18:57
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.

**Closed as not planned by nlf** 2022-04-27 18:57 UTC
Labels: Release 7.x, Bug, Needs Triage
