### ISSUE TITLE
[BUG] must not have multiple workspaces with the same name

### ISSUE THREAD

**Issue by jakobrosenberg** [npm/cli#2544] opened 2021-01-26 07:33 UTC
### Current Behavior:
In a normal terminal `npm install` yields `must not have multiple workspaces with the same name` without any mention of conflicting namespaces.

Opening a debug terminal in VSCode and running the same command in same folder clears the problem and `npm install` now works in both terminals.

### Expected Behavior:
Conflicting workspaces should be named.

### Steps To Reproduce:
See `Current behavior`

### Environment:
- OS: Windows 10
- Node: 15.6.0
- npm: 7.4.0

**Comment by darcyclarke** [comment] 2021-02-12 19:53
Sorry, not quite sure how to help here. If you can provide more details/context I can potentially help narrow in on the problem you're seeing. Closing for now.

**Closed as completed by darcyclarke** 2021-02-12 19:53 UTC
Labels: Release 7.x, Bug

**Comment by jakobrosenberg** [comment] 2021-02-13 09:52
@darcyclarke In the event of conflicting package names, the path or name of the conflicting packages should be specified in the error. Otherwise we're left in the dark to figure out which packages are conflicting.

**Comment by darcyclarke** [comment] 2021-02-13 09:56
@jakobrosenberg 🤔 weird, I feel like we've actually improved this experience. Can you maybe provide specific examples/reproduction cases with changes you'd like to see &/or create a [new RFC](https://github.com/npm/rfcs/) for this behavior?

**Comment by jakobrosenberg** [comment] 2021-02-15 08:33
Sure.

**To reproduce:**
```bash
$ mkdir package1
$ mkdir package1b
$ echo '{ "name": "package1" }' >> package1/package.json
$ echo '{ "name": "package1" }' >> package1b/package.json
$ echo '{ "workspaces": ["*"] }' >> package.json
$ npm install
npm ERR! code EDUPLICATEWORKSPACE
npm ERR! must not have multiple workspaces with the same name

npm ERR! A complete log of this run can be found in:
npm ERR!     <path-to-log>\2021-02-15T08_24_51_875Z-debug.log
```

It would be far more helpful if the error was
```
npm ERR! code EDUPLICATEWORKSPACE
npm ERR! package1 has conflicts:
npm ERR! [path-to]/package1 
npm ERR! [path-to]/package1b

**Comment by gjermundgaraba** [comment] 2021-04-30 17:34
Should this potentially be reopened? I have the exact same problem. I was trying to use some "clever" wildcarding to avoid having list them all separately (only relevant for why this is especially tricky), and I have no idea what npm is finding as duplicates. 

Listing conflicts would be a very useful error. 

Edit: In my case the problem was some refactoring had changed the name of two packages to be the same, so the error was legit. However it was quite tedious to debug. In fact I ended up adding some console logs to by local map-workspaces/index.js file to make it print the problem. As soon as it did it became obvious where the problem came from.

**Comment by denik1981** [comment] 2021-05-14 02:56
It happened the same to me. Unfortunately, I cannot reproduce the error to help debug the issue and there is no too much information in the log file. I backed up a workspace making a full copy of it with a different name, then I work in there and later decide to remove the original. I rename the workspace (probably to the original name as I was not under my directory tree anymore). In the workspace folders, I had only 2 workspaces with different names but NPM INSTALL shown me the same error until I made a copy of that workspace (yes, once again) removed the original, and renamed it to the same name. After all this, the issue was gone. 

PD: I tried deleting the npm cache but the problem persists.

**Comment by nathanhall-dev** [comment] 2021-08-03 17:28
Agreed with @bjaanes comment. After creating a workspace at path: packages/alpha, packages/beta - I had used the same name in both workspaces package.json 

Example:
```
monorepo/package.json
  "workspaces": [
    "packages\\foo",
    "packages\\bar"
  ]

monorepo/package/alpha/package.json
"name": "my-new-package"

monorepo/package/beta/package.json
"name" : "my-new-package"
```

Having the above configuration, then running 
`npm install`

throws error:
```
$ npm run test --workspaces
npm ERR! code EDUPLICATEWORKSPACE
npm ERR! must not have multiple workspaces with the same name

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\<path-removed>\npm-cache\_logs\2021-08-03T17_21_06_479Z-debug.log

```

The debug log was not useful in finding this that the workspace is pointing to the name referenced in the package.json - not the path.

**Comment by JuanmaMenendez** [comment] 2023-03-30 15:02
The problem for me was that _package-lock.json_ was trying to get some packages from an old registry.

The solution was to 'search and replace' in package-lock.json the old registry by the new one:

eg:

OLD CODE TO REPLACE
`"resolved": "https://OLD.REGISTRY.org/axios/-/axios-0.21.4.tgz",`

NEW CODE
`"resolved": "https://registry.npmjs.org/axios/-/axios-0.21.4.tgz",`
