### ISSUE TITLE
[BUG] Install progress bar jumps around

### ISSUE THREAD

**Issue by billyjanitsch** [npm/cli#1744] opened 2020-08-29 22:34 UTC
### Current Behavior:
During `npm install`, the progress bar moves backwards and forwards intermittently.

![npm-progress-bar](https://user-images.githubusercontent.com/1158733/91647198-f3037100-ea25-11ea-8ff7-9184e0f45962.gif)

### Expected Behavior:
The progress bar should never move backwards.

### Steps To Reproduce:
1. Create a package.json with several dependencies. [This](https://github.com/billyjanitsch/mixcreant/blob/42f363d7f63f811f2dd3c2714ee4fbff5205a6c6/package.json#L19-L65) is the one I was using to test.
2. Run `npm install`.

### Environment:
- OS: macOS 10.15.6
- node: 14.9.0
- npm: 7.0.0-beta.7

**Comment by darcyclarke** [comment] 2020-10-01 19:44
Closing: Unfortunately, this is working as intended. We're considering some new UI/UX for `install` & some other commands output to better communicate what is happening.

**Closed as completed by darcyclarke** 2020-10-01 19:44 UTC
Labels: Release 7.x, Bug, Needs Triage

**Comment by billyjanitsch** [comment] 2020-10-01 20:10
@darcyclarke Just to clarify, npm@6 doesn't ever do this. So this behavior was intentionally introduced in npm@7?

**Comment by voltuer** [comment] 2021-07-26 06:55
how can such bad UI e intended? mind explaining the reasoning behind this behavior?
