### ISSUE TITLE
[BUG] npm exec doesn't honor package version

### ISSUE THREAD

**Issue by jcayzac** [npm/cli#3667] opened 2021-08-20 00:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`npm x -q --yes --package=<package>@<version> -- <command>` doesn't honor `<version>`, uses incompatible package that is locally available instead.

### Expected Behavior

`npm x -q --yes --package=<package>@<version> -- <command>` honors `<version>`, does not uses incompatible package that is locally available instead.

### Steps To Reproduce

1. Write this `package.json`:
   ```json
   {
     "private": true,
     "devDependencies": {
       "pnpm": "=6.12.1"
     }
   }
   ```
2. Run `npm i`
3. `pnpm@6.12.1` is now installed locally.
   ```sh
   $ npm x  -q --yes -- pnpm --version
   6.12.1
   ```
4. Run pnpm 6.13.0 now: `npm x` won't honor the version
   ```sh
   $ npm x -q --yes --package="pnpm@6.13.0" -- pnpm --version
   6.12.1
   ```

The docs for `npm exec` state:

> Package names provided without a specifier will be matched with whatever version exists in the local project. **Package names with a specifier will only be considered a match if they have the exact same name and version as the local dependency.**

### Environment

- OS: macOS 11.4
- Node: 16.5.0
- npm: 7.21.0

**Comment by janpio** [comment] 2022-04-06 19:29
I think this issue is a duplicate of https://github.com/npm/cli/issues/3210 (also read comments).

**Comment by nlf** [comment] 2022-04-27 18:59
closing as duplicate of #3210

**Closed as not planned by nlf** 2022-04-27 18:59 UTC
Labels: Release 7.x, Bug, Needs Triage
