### ISSUE TITLE
[BUG] <Getting errors when ng new project and npm install is run >

### ISSUE THREAD

**Issue by sbadavanahalli** [npm/cli#521] opened 2019-11-26 08:11 UTC
# What / Why
I reinstalled node and npm many times and I also cleared the buffer many times running npm cache clean --force.  I am running from the command prompt in Administrator mode. I am using node version v12.13.1 and npm version 6.13.1. 
I am getting below errors. I am attaching the screen shots and error log files. 
Please let me know how to resolve these errors.

1. when trying to create new project by running - ng new MyAngApp. The project is created but getting npm error
npm ERR! Unexpected end of JSON input while parsing near '...t","@types/chai":"lat'
2. When I ran npm install with in project path getting these errors. 
Error description 1
npm ERR! Verification failed while extracting @angular/compiler@~8.2.14:
npm ERR! sha512-ABZO4E7eeFA1QyJ2trDezxeQM5ZFa1dXw1Mpl/+1vuXDKNjJgNyWYwKp/NwRkLmrsuV0yv4UDCDe4kJOGbPKnw== integrity checksum failed when using sha512: wanted sha512-ABZO4E7eeFA1QyJ2trDezxeQM5ZFa1dXw1Mpl/+1vuXDKNjJgNyWYwKp/NwRkLmrsuV0yv4UDCDe4kJOGbPKnw== but got sha512-hhwCOnAJuQkH5VBN3QiP++tgdmIGlq8cYG4Sd9xA0T4BC0aqgcF9fewuhf7GXsPhXcPI9lrVWXXtoXi3p6hFwQ==. (131052 bytes)
------------------------------------------------------------------------------
Error description 2
npm ERR! code EPERM
npm ERR! syscall unlink
npm ERR! path C:\artifacts\MyAngApp\node_modules\.staging\@angular\platform-browser-496c65c1\bundles\platform-browser.umd.js.map
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\artifacts\MyAngApp\node_modules\.staging\@angular\platform-browser-496c65c1\bundles\platform-browser.umd.js.map'
npm ERR!  [OperationalError: EPERM: operation not permitted, unlink 'C:\artifacts\MyAngApp\node_modules\.staging\@angular\platform-browser-496c65c1\bundles\platform-browser.umd.js.map'] {
npm ERR!   cause: [Error: EPERM: operation not permitted, unlink 'C:\artifacts\MyAngApp\node_modules\.staging\@angular\platform-browser-496c65c1\bundles\platform-browser.umd.js.map'] {
npm ERR!     errno: -4048,
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'unlink',
npm ERR!     path: 'C:\\artifacts\\MyAngApp\\node_modules\\.staging\\@angular\\platform-browser-496c65c1\\bundles\\platform-browser.umd.js.map'
npm ERR!   },
npm ERR!   stack: "Error: EPERM: operation not permitted, unlink 'C:\\artifacts\\MyAngApp\\node_modules\\.staging\\@angular\\platform-browser-496c65c1\\bundles\\platform-browser.umd.js.map'",
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\artifacts\\MyAngApp\\node_modules\\.staging\\@angular\\platform-browser-496c65c1\\bundles\\platform-browser.umd.js.map',
npm ERR!   parent: 'MyAngApp'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

> n/a

## When
<Every time when I run I am getting same errors or similar errors. Today 26 Nov 2019 also getting same.
<img width="960" alt="ng_new_proj_errors1" src="https://user-images.githubusercontent.com/40761473/69610499-f494a880-1051-11ea-9dbe-d2658ab82682.png">
<img width="960" alt="npm_Install_errors2" src="https://user-images.githubusercontent.com/40761473/69610555-0aa26900-1052-11ea-95a6-917fb7655578.png">
<img width="960" alt="npm_Install_errors3" src="https://user-images.githubusercontent.com/40761473/69610577-14c46780-1052-11ea-835e-8e2f9a4cd975.png">
[2019-11-26T06_04_12_334Z-debug.log](https://github.com/npm/cli/files/3890680/2019-11-26T06_04_12_334Z-debug.log)
[2019-11-26T06_12_37_999Z-debug.log](https://github.com/npm/cli/files/3890682/2019-11-26T06_12_37_999Z-debug.log)
[2019-11-26T06_19_27_590Z-debug.log](https://github.com/npm/cli/files/3890683/2019-11-26T06_19_27_590Z-debug.log)

-->
* n/a

## Where

* n/a

### Current Behavior

* n/a

### Steps to Reproduce

* n/a

### Expected Behavior

* n/a

## Who

* n/a

## References

* n/a

**Comment by DanielRuf** [comment] 2019-11-30 14:27
Try to clear your npm cache and run the command again.

**Comment by vince1995** [comment] 2019-12-03 13:28
@DanielRuf this doesn't help.

Refers to #298 and https://stackoverflow.com/questions/58435024/npm-install-verfication-failed-while-extracting

**Comment by DanielRuf** [comment] 2019-12-03 13:40
Please provide the full outputs and the npm version that you use.

**Comment by vince1995** [comment] 2019-12-04 12:36
v6.9.0 is the latest version I can use (due to AWS settings).

```

  npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
  npm WARN deprecated core-js@2.6.10: core-js@<3.0 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
  npm WARN deprecated fsevents@1.2.9: One of your dependencies needs to upgrade to fsevents v2: 1) Proper nodejs v10+ support 2) No more fetching binaries from AWS, smaller package size
  npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
  npm WARN tarball tarball data for @my-private-component@^1.3.4 (sha512-RSOz-SHA-CODE-+kww==) seems to be corrupted. Trying one more time.
  npm WARN tarball tarball data for @my-private-component@^1.3.4 (sha512-RSOz-SHA-CODE-+kww==) seems to be corrupted. Trying one more time.
  npm WARN tar ENOENT: no such file or directory, open '/tmp/deployment/application/node_modules/.staging/rxjs-45e6acb2/operator/timeInterval.js'
.
. a lot of "npm WARN tar ENOENT:"
. 

  npm WARN tar ENOENT: no such file or directory, open '/tmp/deployment/application/node_modules/.staging/core-js-9916953d/modules/web.timers.js'
  npm WARN react-addons-css-transition-group@15.6.2 requires a peer of react@^15.4.2 but none is installed. You must install peer dependencies yourself.
  npm WARN slick-carousel@1.8.1 requires a peer of jquery@>=1.8.0 but none is installed. You must install peer dependencies yourself.
  npm WARN ts-pnp@1.1.4 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
  npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
  npm WARN react-mapbox-gl@4.7.3 requires a peer of react@^16.11.0 but none is installed. You must install peer dependencies yourself.
  npm WARN react-mapbox-gl@4.7.3 requires a peer of react-dom@^16.11.0 but none is installed. You must install peer dependencies yourself.
  npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/jest-haste-map/node_modules/fsevents):
  npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/deployment/application/node_modules/.staging/fsevents-db9a21a3/node_modules/abbrev' -> '/tmp/deployment/application/node_modules/.staging/abbrev-ee110bfb'
  npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/chokidar/node_modules/fsevents):
  npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/tmp/deployment/application/node_modules/.staging/fsevents-0e5879b2/node_modules/abbrev' -> '/tmp/deployment/application/node_modules/.staging/abbrev-d58b7943'
  
  npm ERR! code EINTEGRITY
  npm ERR! Verification failed while extracting @my-private-component@^1.3.4:
  npm ERR! Verification failed while extracting @my-private-component@^1.3.4:
  npm ERR! sha512-RSOz-SHA-CODE-+kww== integrity checksum failed when using sha512: wanted sha512-RSOz-SHA-CODE-+kww== but got sha512-yJiQ-ANOTHER-SHA-CODE-69ce+scg==. (2313048 bytes)
  
  npm ERR! A complete log of this run can be found in:
  npm ERR!     /tmp/.npm/_logs/2019-12-03T13_23_59_646Z-debug.log

```

And what the AWS instance outputs:

```
  Running npm install:  /opt/elasticbeanstalk/node-install/node-v10.16.3-linux-x64/bin/npm
  Setting npm config jobs to 1
  npm config jobs set to 1
  Running npm with --production flag
  Failed to run npm install. Snapshot logs for more details.
  UTC 2019/12/03 13:24:00 cannot find application npm debug log at /tmp/deployment/application/npm-debug.log 
  
  Traceback (most recent call last):
    File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 695, in <module>
      main()
    File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 677, in main
      node_version_manager.run_npm_install(options.app_path)
    File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 136, in run_npm_install
      self.npm_install(bin_path, self.config_manager.get_container_config('app_staging_dir'))
    File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 180, in npm_install
      raise e
  subprocess.CalledProcessError: Command '['/opt/elasticbeanstalk/node-install/node-v10.16.3-linux-x64/bin/npm', '--production', 'install']' returned non-zero exit status 1 (Executor::NonZeroExitStatus)

```

**Comment by DanielRuf** [comment] 2019-12-04 13:30
You can not run `npm i -g npm@latest` there?

**Comment by vince1995** [comment] 2019-12-09 11:49
No. That's on AWS impossible. And it even fails on my local machine wich has version `6.13.2`.

**Comment by DanielRuf** [comment] 2019-12-09 12:08
I think it is best when you create a separate issue @vince1995.

**Comment by vince1995** [comment] 2019-12-09 12:35
See #298.

**Comment by vince1995** [comment] 2020-01-08 10:46
BTW, we've switched from npm to GitHub packages and there works everything fine. That means it's not a bug in the npm cli but at the npm servers.

**Comment by jozefizso** [comment] 2020-04-18 08:08
```
2 info using npm@6.13.7
3 info using node@v13.11.0
...
5312 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
5313 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
5314 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
5314 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
5314 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
5314 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
5315 verbose stack Error: EPERM: operation not permitted, rename 'C:\dev\github\gitattributes.io\src\node_modules\invert-kv\package.json.367639709' -> 'C:\dev\github\gitattributes.io\src\node_modules\invert-kv\package.json'
5316 verbose cwd C:\dev\github\gitattributes.io\src
5317 verbose Windows_NT 10.0.18363
5318 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--ignore-scripts" "--no-fund"
5319 verbose node v13.11.0
5320 verbose npm  v6.13.7
5321 error code EPERM
5322 error syscall rename
5323 error path C:\dev\github\gitattributes.io\src\node_modules\invert-kv\package.json.367639709
5324 error dest C:\dev\github\gitattributes.io\src\node_modules\invert-kv\package.json
5325 error errno -4048
5326 error Error: EPERM: operation not permitted, rename 'C:\dev\github\gitattributes.io\src\node_modules\invert-kv\package.json.367639709' -> 'C:\dev\github\gitattributes.io\src\node_modules\invert-kv\package.json'
5326 error  [OperationalError: EPERM: operation not permitted, rename 'C:\dev\github\gitattributes.io\src\node_modules\invert-kv\package.json.367639709' -> 'C:\dev\github\gitattributes.io\src\node_modules\invert-kv\package.json'] {
5326 error   cause: [Error: EPERM: operation not permitted, rename 'C:\dev\github\gitattributes.io\src\node_modules\invert-kv\package.json.367639709' -> 'C:\dev\github\gitattributes.io\src\node_modules\invert-kv\package.json'] {
5326 error     errno: -4048,
5326 error     code: 'EPERM',
5326 error     syscall: 'rename',
5326 error     path: 'C:\\dev\\github\\gitattributes.io\\src\\node_modules\\invert-kv\\package.json.367639709',
5326 error     dest: 'C:\\dev\\github\\gitattributes.io\\src\\node_modules\\invert-kv\\package.json'
5326 error   },
5326 error   stack: "Error: EPERM: operation not permitted, rename 'C:\\dev\\github\\gitattributes.io\\src\\node_modules\\invert-kv\\package.json.367639709' -> 'C:\\dev\\github\\gitattributes.io\\src\\node_modules\\invert-kv\\package.json'",
5326 error   errno: -4048,
5326 error   code: 'EPERM',
5326 error   syscall: 'rename',
5326 error   path: 'C:\\dev\\github\\gitattributes.io\\src\\node_modules\\invert-kv\\package.json.367639709',
5326 error   dest: 'C:\\dev\\github\\gitattributes.io\\src\\node_modules\\invert-kv\\package.json',
5326 error   parent: 'src'
5326 error }
```

**Comment by DanielRuf** [comment] 2020-04-18 08:14
@jozefizso your issue is a different one. Please check if you need `sudo` and also search for relevant issues.

> EPERM: operation not permitted, rename

**Comment by x-yuri** [comment] 2020-05-28 23:57
The issue seem to describe a number of bugs, but since the one of them is the "integrity checksum failed" error, I gave a detailed report about it [here][1].

[1]: https://github.com/npm/cli/issues/473#issuecomment-635677353

**Comment by darcyclarke** [comment] 2021-06-02 21:45
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 21:45 UTC
Labels: Bug
