### ISSUE TITLE
[BUG] Files under directories already added to `files` of package.json cannot be excluded by adding them to `files` (like `!some_directory`).

### ISSUE THREAD

**Issue by korosuke613** [npm/cli#2649] opened 2021-02-08 08:03 UTC
### Current Behavior
Files under directories already added to `files` of package.json cannot be excluded by adding them to `files` (like `!some_directory`). Up to npm 6.14.11 it was possible to exclude, but from npm 7.5.2 it is no longer possible.

* `package.json`, `src/index.js`, **`src/__tests__/indexTest.js`** are added to the npm package.
```
❯ npm pack --dry-run      
...
npm notice === Tarball Contents === 
npm notice 97B package.json              
npm notice 0B  src/__tests__/indexTest.js
npm notice 21B src/index.js              
npm notice === Tarball Details === 
...
npm notice total files:   3                                       
...
```

### Expected Behavior

* `package.json`, `src/index.js` are added to the npm package. (use  npm 6.14.11)
```
❯ npm pack --dry-run
...
npm notice === Tarball Contents === 
npm notice 21B src/index.js
npm notice 97B package.json
npm notice === Tarball Details === 
...
npm notice total files:   2                                       
...
```

### Steps to Reproduce

1. Create a package.json

```json
{
  "name": "some-package",
  "files": [
    "src",
    "!__tests__"
  ],
  "version": "0.0.0"
}
```

2. Create the following file structure:
```
  .
  └── src
     ├── index.js
     └── __tests__
        └── indexTest.js
```

3. run `npm pack --dry-run`

### Other
By using wildcards, you can exclude them in both npm v6/v7. (ex. `!__tests__` -> `!**/__tests__`)

### Environment:
* OS: macOS 11.1
* Node: 12.18.2
* npm: 7.5.2

**Comment by ljharb** [comment] 2021-02-08 15:34
Seems like a duplicate of #2441?

**Comment by korosuke613** [comment] 2021-02-09 00:42
Oh, I'm sorry.  As you say, this issue was a duplicate of the linked issue. Thank you.

**Closed as completed** 2021-02-09 00:46 UTC
