### ISSUE TITLE
Npm install 

### ISSUE THREAD

**Issue by R0N1n-dev** [npm/cli#7550] opened 2024-05-22 06:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

On trying to install packages using 'npm install', it just hangs and goes on forever. Along with the fact that the progress indicator is gone, It is just giving me a hard time.
Since updating to 10.7.0, only had one successful install of 'npm install' in any of my folders

![Screenshot from 2024-05-22 09-16-27](https://github.com/npm/cli/assets/83344872/73401d39-035d-44a5-a9b5-aed5cde57720)

### Expected Behavior

It install packages

### Steps To Reproduce

1. Run npm install in a nuxt 3 app

### Environment

- npm: 10.7.0
- Node.js: 22.2.0
- OS Name: POP OS
- System Model Name: Lenovo Thinkpad
- npm config:
```ini
; node bin location = /home/mozeik/.nvm/versions/node/v22.2.0/bin/node
; node version = v22.2.0
; npm local prefix = /home/mozeik
; npm version = 10.7.0
; cwd = /home/mozeik
; HOME = /home/mozeik
```

**Comment by milaninfy** [comment] 2024-05-22 13:25
@R0N1n-dev Could you please try with `npm install --ddd` to run install command with log level silly to get more information about the issue?
Also you can try updating npm@10.8.0 which is latest.

**Comment by R0N1n-dev** [comment] 2024-05-27 06:11
Is there any default better way of telling progress in 10.8

**Comment by milaninfy** [comment] 2024-05-27 19:43
@R0N1n-dev spinner is indicative of the progress, also you can use various log levels to see progress. You can follow the discussions on progress bar removal on this issue https://github.com/npm/cli/issues/7425 
Let us know if you still are facing installation issue with logs to check further.

**Comment by milaninfy** [comment] 2024-06-05 11:56
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.

**Closed as not planned by milaninfy** 2024-06-05 11:56 UTC
Labels: Bug, Needs Triage

**Comment by voltuer** [comment] 2024-06-05 13:55
no more progress bar then? why? where is it documented?

**Comment by ZachSARAO** [comment] 2024-06-12 06:43
This is a problem for me as well - `npm install --force` just hangs indefinitely. v10.5 works fine (with node 21)

**Comment by voltuer** [comment] 2024-06-23 04:51
we're microsoft, we can't handle complicate things like progress bars
