### ISSUE TITLE
[BUG] shasum check failed for preset-env-7.8.4.tgz

### ISSUE THREAD

**Issue by derMart** [npm/cli#802] opened 2020-02-12 16:15 UTC
running 
`npm install --save babel-loader @babel/core @babel/preset-env`
gives the following error:
```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Martin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "babel-loader" "@babel/core" "@babel/preset-env"
npm ERR! node v10.0.0
npm ERR! npm  v3.9.5

npm ERR! shasum check failed for C:\Users\Martin\AppData\Local\Temp\npm-7220-32b6c023\registry.npmjs.org\_40babel\preset-env\-\preset-env-7.8.4.tgz
npm ERR! Expected: 9dac6df5f423015d3d49b6e9e5fa3413e4a72c4e
npm ERR! Actual:   72c9f2f0e7f8d30ca282aa98c7577c69f004c6f6
npm ERR! From:     https://registry.npmjs.org/@babel/preset-env/-/preset-env-7.8.4.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Projekte\trovent-vulscan\npm-debug.log
```

kind regards
[npm-debug.log](https://github.com/npm/cli/files/4193334/npm-debug.log)

**Comment by DanielRuf** [comment] 2020-02-18 06:18
Please report in the relevant babel repository. This is not a bug in npm.

You can also clear the cache, or add `--force` to the install command which should redownload the package and its hashes.

**Comment by derMart** [comment] 2020-02-18 08:08
Thank you. I reported this bug here since the log output states:
 ```
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

I will open an issue in the babel repository

kind regards

**Comment by DanielRuf** [comment] 2020-02-18 08:27
> You can also clear the cache, or add `--force` to the install command which should redownload the package and its hashes.

Did you already try to clear your npm cache?

**Comment by nicolo-ribaudo** [comment] 2020-02-18 08:41
@DanielRuf What could be causing this problem on the Babel side?

**Comment by DanielRuf** [comment] 2020-02-18 09:19
> @DanielRuf What could be causing this problem on the Babel side?

Probably not on the code side but on the registry side or local proxies on your system can affect this. But it's better to ask about this in the babel repo if others had this issue too.

Sometimes there are also small issues with the npmjs registry and clearing the cache may resolve these on your side.

**Comment by darcyclarke** [comment] 2021-06-02 21:55
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 21:55 UTC
Labels: Bug
