### ISSUE TITLE
[BUG] NPM --omit=optional results in dependency version not being installed

### ISSUE THREAD

**Issue by ScriptedFluff** [npm/cli#7618] opened 2024-06-29 06:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Have installed a local package into optional, while also have an alternative path in the "dependencies" section of package.json

Running the install command with no flag:
`npm install
node node_modules/node-red/red.js`

![image](https://github.com/npm/cli/assets/32648619/ab20702c-e9db-4d61-bb45-eac456ef66ac)

Results in the "lower-case2" function showing in node-red. Also if I remove "lower-case": "file:./lower-case2" from "optionalDependencies" and re-run the above commands the result in similar to the previous behavior except "lower-case2" becomes "lower-case"

![image](https://github.com/npm/cli/assets/32648619/f7b32447-b339-4997-8d1e-387654fd78b3)

Now when I run install with the flag omit for optional dependencies:
`npm install --omit=optional
node node_modules/node-red/red.js`

The result is that neither "lower-case" or "lower-case2" shows under the functions panel.

![image](https://github.com/npm/cli/assets/32648619/92003ed4-c535-4a07-838f-de6310461533)

### Expected Behavior

I expect that when I omit optional dependencies, that the package under the same name but in the "dependencies" section of package.json to install.

Commands:
`npm install --omit=optional
node node_modules/node-red/red.js`

Expect:
"lower-case" to show in the functions panel.

![image](https://github.com/npm/cli/assets/32648619/75eca2f1-f6d0-43a6-8335-7b6e9897cf00)

### Steps To Reproduce

1. Go to [https://stackblitz.com/edit/stackblitz-starters-d1ax1g?file=package.json](https://stackblitz.com/edit/stackblitz-starters-d1ax1g?file=package.json)
2. Run 'npm install'
3. Run 'node node_modules/node-red/red.js'

### Environment

- npm: 10.2.3 + 10.7.0
- Node.js: 18.20.3 + 20.15.0
- OS Name: Windows 11

**Comment by kchindam-infy** [comment] 2024-07-19 21:35
Hi @flanagansshenanigans  same named dependencies should not appear in two different dependencies category like optionalDependency and dependencies if it does and you use omit then it will remove that as you are essentially asking them to remove these.

There is a similar ticket already [https://github.com/npm/cli/issues/7296](url)

**Comment by milaninfy** [comment] 2024-07-19 21:49
**Closing:** this looks to be similar if not a duplicate of an existing issue, #7296 . If you believe your instance is unique, please provide further clarifying details.

**Closed as not planned by milaninfy** 2024-07-19 21:49 UTC
Labels: Bug, Needs Triage
