### ISSUE TITLE
"npm update" deletes npm itself

### ISSUE THREAD

**Issue by michaelestermann** [npm/cli#2014] opened 2020-10-22 09:21 UTC
We've updated our node installation from the latest 14 version to the current version 15.0.1.
After updating and executing the "npm update" command, the npm folder gets deleted.

In our environment, we've included the node standalone installation (along with npm)  in our git repository. The package.json is located in the same directory as the node executable. Therefor its not the same situation as described in this issue https://github.com/npm/npm/issues/5050. 

I just created a repro here: https://github.com/michaelestermann/NpmUpdateRepro

### Current Behavior:
When executing npm update in the described environment above. The npm folder in the node_modules directory gets deleted.

### Expected Behavior:
It should ignore the npm folder.

### Steps To Reproduce:
1. Clone the repro from https://github.com/michaelestermann/NpmUpdateRepro
2. Execute npm update

### Environment:
- OS: Windows 10 (Version 2004)
- Node: 15.0.1
- npm: 7.0.3

**Comment by Mys73rion** [comment] 2020-11-05 07:22
We tried again to update, now with version 15.1.0, and we still have the same issue.

**Comment by nlf** [comment] 2020-11-30 17:57
this is the intended behavior.

when npm attempts to turn your requested package dependencies into reality part of that process involves removing packages that are not required. you can see this in your repo if you run `npm ls`, example output is below (ignore the UNMET DEPENDENCY lines, i cloned the repo and ran `npm ls` without installing anything so those are expected)

```
> npm ls
npmupdaterepro@1.0.0 C:\Users\Nathan LaFreniere\Projects\NpmUpdateRepro
├── UNMET DEPENDENCY eslint-plugin-jquery@1.5.1
├── UNMET DEPENDENCY eslint@7.10.0 deduped
├── npm@7.0.3 extraneous
├── UNMET DEPENDENCY stylelint-checkstyle-formatter@0.1.2 deduped
├── UNMET DEPENDENCY stylelint-config-recommended@3.0.0 deduped
├── UNMET DEPENDENCY stylelint-config-standard@20.0.0 deduped
├── UNMET DEPENDENCY stylelint@13.7.2 deduped
└── UNMET DEPENDENCY uglify-es@3.3.9 deduped
```

above you'll note the line that tells us that `npm@7.0.3` is extraneous, this means that the next time we try to resolve your dependencies it will be removed.

you can correct this by adding npm itself to your package.json's dependencies field like `"npm": "7.0.3"`

a repeated run of `npm ls` shows that it is no longer marked as extraneous:

```
> npm ls
npmupdaterepro@1.0.0 C:\Users\Nathan LaFreniere\Projects\NpmUpdateRepro
├── UNMET DEPENDENCY eslint-plugin-jquery@1.5.1
├── UNMET DEPENDENCY eslint@7.10.0 deduped
├── npm@7.0.3
├── UNMET DEPENDENCY stylelint-checkstyle-formatter@0.1.2 deduped
├── UNMET DEPENDENCY stylelint-config-recommended@3.0.0 deduped
├── UNMET DEPENDENCY stylelint-config-standard@20.0.0 deduped
├── UNMET DEPENDENCY stylelint@13.7.2 deduped
└── UNMET DEPENDENCY uglify-es@3.3.9 deduped
```

and running `npm update` no longer removes it.

**Closed as completed by nlf** 2020-11-30 17:57 UTC
Labels: Release 7.x, Bug

**Comment by myudak** [comment] 2024-07-27 21:35
i still running into this issue
