### ISSUE TITLE
[BUG] Can't run install due to python issue

### ISSUE THREAD

**Issue by zdnk** [npm/cli#4729] opened 2022-04-11 14:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /opt/homebrew/bin/python3 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:398:12)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1090:16)
gyp ERR! stack     at Socket.<anonymous> (node:internal/child_process:449:11)
gyp ERR! stack     at Socket.emit (node:events:527:28)
gyp ERR! stack     at Pipe.<anonymous> (node:net:709:12)

### Expected Behavior

installs and builds fine

### Steps To Reproduce

i have no idea, its happening on both of my macos envs, probably some dependency causing it
`poppler-simple` probably

### Environment

- npm: 8.5.5
- Node.js: v17.8.0
- OS Name: macos
- System Model Name:
- npm config:
```ini
; "builtin" config from /usr/local/lib/node_modules/npm/npmrc

prefix = "/usr/local" 

; node bin location = /usr/local/Cellar/node/17.8.0/bin/node
; cwd = <redacted>
; HOME = /Users/<redacted>
```

**Comment by lukekarrys** [comment] 2022-04-11 19:41
Can you post the package.json or full command you are using to install?

**Comment by lukekarrys** [comment] 2022-12-07 02:21
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.

**Closed as completed by lukekarrys** 2022-12-07 02:21 UTC
Labels: Awaiting Information, Release 8.x, Bug
