### ISSUE TITLE
[BUG] Using command "npm install" on the root folder to installl node_modules into sub folder project not working

### ISSUE THREAD

**Issue by chendra07** [npm/cli#5808] opened 2022-11-03 12:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Using command "npm install" on the root folder to installl node_modules into sub folder project not working.

ex:
(root folder)
./package.json (with script):
    "install-a": "npm install --prefix folder-a",
    "install-b": "npm install --prefix folder-b",
    "install": "npm run install-a && npm run install-b"

./folder-a & ./folder-b with added dependencies

the result:
![image](https://user-images.githubusercontent.com/48231923/199723486-088b2bf8-ab44-4c91-a3bd-230435d48355.png)

I have tried to fix this error but the  listed solution below are not really helping:
- downgrade nodejs from the latest LTS to lower version (node v18 -> v16, but it didn't work so i upgrade it again to v18)
- adding nodejs to environment path (no effect even after restaring my computer)
- running "npm cache clean --force"

### Expected Behavior

npm install node_modules on each folder normally

### Steps To Reproduce

1. Run "npm install" on the root folder

### Environment

- npm: 8.19.2
- Node.js: 18.12.0
- OS Name: Windows 10
- System Model Name: Dell Inspiron 7472
- npm config:
```ini
; node bin location = C:\Program Files\nodejs\node.exe
; node version = v18.12.0
; npm local prefix = D:\Development\Complete NodeJS Developer\test-npm
; npm version = 8.19.2
; cwd = D:\Development\Complete NodeJS Developer\test-npm
; HOME = C:\Users\cendr
; Run `npm config ls -l` to show all defaults.
```

**Comment by wraithgar** [comment] 2022-11-16 22:32
There is not enough here to reproduce the issue.

**Comment by nlf** [comment] 2023-02-16 22:28
as you can see by the logged error, this is creating an endless loop of package installations. the "install" script runs after you install something. since your "install" script is installing things, it runs and then it runs again infinitely forever. installing packages inside a script is not advisable because of issues like this one. it may work in some cases, but certainly will not be reliable and in many cases can cause outright failures like you're experiencing.

i think [workspaces](https://docs.npmjs.com/cli/v9/using-npm/workspaces) are a feature that would help you out here as they are designed to allow you to manage a monorepo, which it appears is what you're trying to do.

i'm going to close this issue since what you're trying to do is very much unsupported, but if workspaces do not fill your needs feel free to open a new issue explaining what you're trying to do in more detail and we can try to help you find a workaround.

**Closed as completed by nlf** 2023-02-16 22:28 UTC
Labels: Release 8.x, Bug, Needs Triage

**Comment by chendra07** [comment] 2023-02-17 05:14
i see, thank you for the information
