### ISSUE TITLE
[BUG] Exit handler never called in `npm publish`

### ISSUE THREAD

**Issue by gigamonkey** [npm/cli#7642] opened 2024-07-12 17:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Running `npm publish` 

```
npm notice Publishing to https://registry.npmjs.org/ with tag latest and default access
Authenticate your account at:
https://www.npmjs.com/auth/cli/125bfb47-0887-4f90-8c02-4f6ccd77c256
Press ENTER to open in the browser...


npm error Exit handler never called!
npm error This is an error with npm itself. Please report this error at:
npm error   <https://github.com/npm/cli/issues>
npm error A complete log of this run can be found in: /Users/peter/.npm/_logs/2024-07-12T17_15_25_808Z-debug-0.log
```

If I tick the box on the authentication page to not challenge for five minutes, and then run `npm publish` again it works so this is not a showstopper. But obviously it should work, right?

### Expected Behavior

The publish to work the first time.

### Steps To Reproduce

1. In this environment... see below
2. With this config... see below
3. Run `npm pulish`
4. See error... 

```
0 verbose cli /usr/local/Cellar/node/22.4.1/bin/node /usr/local/bin/npm
1 info using npm@10.8.2
2 info using node@v22.4.1
3 silly config load:file:/usr/local/lib/node_modules/npm/npmrc
4 silly config load:file:/Users/peter/hacks/pugsql.js/.npmrc
5 silly config load:file:/Users/peter/.npmrc
6 silly config load:file:/usr/local/etc/npmrc
7 verbose title npm publish
8 verbose argv "publish"
9 verbose logfile logs-max:10 dir:/Users/peter/.npm/_logs/2024-07-12T17_15_25_808Z-
10 verbose logfile /Users/peter/.npm/_logs/2024-07-12T17_15_25_808Z-debug-0.log
11 verbose publish [ '.' ]
12 silly logfile start cleaning logs, removing 1 files
13 silly logfile done cleaning log files
14 silly packumentCache heap:4345298944 maxSize:1086324736 maxEntrySize:543162368
15 warn publish npm auto-corrected some errors in your package.json when publishing.  Please run "npm pkg fix" to address these errors.
16 warn publish errors corrected:
16 warn publish "bin[puglify]" script name was cleaned
16 warn publish "repository.url" was normalized to "git+https://github.com/gigamonkey/pugsql.js.git"
17 notice
18 notice 📦  pugsql@0.0.8
19 notice Tarball Contents
20 notice 401B README.md
20 notice 291B data/puglify.sql
20 notice 628B package.json
20 notice 1.6kB puglify.js
20 notice 4.3kB pugsql.js
21 notice Tarball Details
22 notice name: pugsql
23 notice version: 0.0.8
24 notice filename: pugsql-0.0.8.tgz
25 notice package size: 2.9 kB
26 notice unpacked size: 7.2 kB
27 notice shasum: 834f739245e91f9aa83e2b1c5dada145c0642b0f
28 notice integrity: sha512-3b+P1GgX4jPp0[...]A/4IJqe+yQ3ig==
29 notice total files: 5
30 notice
31 notice Publishing to https://registry.npmjs.org/ with tag latest and default access
32 http fetch PUT 401 https://registry.npmjs.org/pugsql 254ms
33 verbose web auth opening url pair
34 http fetch GET 202 https://registry.npmjs.org/-/v1/done?authId=*** 89ms
35 verbose cwd /Users/peter/hacks/pugsql.js
36 verbose os Darwin 23.5.0
37 verbose node v22.4.1
38 verbose npm  v10.8.2
39 error Exit handler never called!
40 error This is an error with npm itself. Please report this error at:
41 error   <https://github.com/npm/cli/issues>
42 verbose exit 0
43 info ok
44 error A complete log of this run can be found in: /Users/peter/.npm/_logs/2024-07-12T17_15_25_808Z-debug-0.log
```

### Environment

- npm: 10.8.2
- Node.js: v22.4.1
- OS Name: Darwin Kernel Version 23.5.0: Wed May  1 20:09:52 PDT 2024; root:xnu-10063.121.3~5/RELEASE_X86_64
- System Model Name: Macbook Pro
- npm config:
```ini
; "builtin" config from /usr/local/lib/node_modules/npm/npmrc

prefix = "/usr/local"

; "user" config from /Users/peter/.npmrc

//registry.npmjs.org/:_authToken = (protected)
init-author-email = "peter@gigamonkeys.com"
init-author-name = "Peter Seibel"
init-license = "MIT"

; node bin location = /usr/local/Cellar/node/22.4.1/bin/node
; node version = v22.4.1
; npm local prefix = /Users/peter/hacks/pugsql.js
; npm version = 10.8.2
; cwd = /Users/peter/hacks/pugsql.js
; HOME = /Users/peter
; Run `npm config ls -l` to show all defaults.
```

**Comment by melroy89** [comment] 2024-07-19 09:29
Duplicate of: https://github.com/npm/cli/issues/7657?

**Comment by avivkeller** [comment] 2024-07-19 14:19
Resolved in Node.js v22.5.1. See #7667 and https://github.com/nodejs/node/issues/53902.

**Comment by wraithgar** [comment] 2024-07-19 14:35
@RedYetiDev no this was unrelated. We were seeing these issues in npm before the node.js outage.  It's likely some issue w/ the url opener for web auth, and does not affect a large percentage of the population.

**Comment by avivkeller** [comment] 2024-07-19 14:47
Sorry!

**Comment by milaninfy** [comment] 2024-07-19 14:55
Tracking this here as https://github.com/npm/cli/issues/7612
Closing this as Duplicate or similer of #7612

**Closed as not planned by milaninfy** 2024-07-19 14:55 UTC
Labels: Bug, Needs Triage
