### ISSUE TITLE
[QUESTION] Why does not npm run the local installed executable with npm run command?

### ISSUE THREAD

**Issue by ajaymathur** [npm/cli#610] opened 2019-12-18 06:00 UTC
# What
If I install an executable as a local dependency in my project. Why does not npm run those executable when called as `npm run <executable>`?
Install `jest` in your repository and then you we need add script like `"jest": "jest"` in our package.json. I just want to know the reason here. I am happy to contribute if it is something we want in npm cli.

## Where
npm/cli

## Who
* n/a

## References
https://stackoverflow.com/questions/9679932/how-to-use-package-installed-locally-in-node-modules

**Comment by LitoMore** [comment] 2019-12-19 05:51
You should use [`npx`](https://github.com/npm/npx) instead.

**Comment by ajaymathur** [comment] 2019-12-20 06:56
Hey @LitoMore , thanks a lot for responding. However, with the existence of `npx` I am still not sure why we would want to not support running local installed executable with `npm run` command.
Do you know of a reasoning why we should run it using npx only and npm should not support it?

**Comment by ljharb** [comment] 2019-12-20 07:00
I don't know the original reason, but `npm run` simply never worked that way before, and it would likely break a lot of people to have `npm run foo` suddenly start doing what `npx foo` does.

`npx` ships with `npm`, so the barrier to using it should be close to zero.

**Comment by ajaymathur** [comment] 2019-12-20 07:15
Hey @ljharb, Thanks a lot for responding.

My use case is I am writing docs on how to work with repository. I am using certain tools like https://github.com/atlassian/changesets who's name is actually the relevant command. Now I want to tell user to:

```
# Install dependencies
$ npm install

# run other scripts with npm

# run changesets
$ npm run changesets # Here I want to maintain using the same command `npm` to avoid confusion
```

Now I also add a script in package.json as:

```
"changesets": "changesets"
```

which seemed not so useful to me. Unless I am missing to see some user aspect here. 🙂 

It is not blocking me but I would like to know if there is any strong reason like it will break existing apps or something on similar lines. If not, and we want to consider this then I am happy to contribute. 🙂

**Comment by ljharb** [comment] 2019-12-20 08:10
I would imagine that it would hide bugs, since `npx foo` will install foo if it isn't already installed.

I think your docs would be clearer if the "run the command that the project set up", was not the same one as "run the command whether the project's set it up or not".

**Comment by darcyclarke** [comment] 2021-06-02 21:45
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 21:45 UTC
Labels: Awaiting Information
