### ISSUE TITLE
[BUG] When invoked from PowerShell prompt on Windows, positional arguments are not properly passed to NPM scripts

### ISSUE THREAD

**Issue by noseratio** [npm/cli#7440] opened 2024-04-29 21:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`process.argv` is missing CLI arguments.

Using Node.js v22.0.0, NPM v10.6.0 and PowerShell v7.4.2 on Windows 11. 

package.js:
```json
{
  "name": "cli-test",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "start": "node index.js"
  }
}
```   

index.js:
```javascript
console.dir(process.argv);
```

Running it from a PowerShell prompt:
```text
PS C:\temp\cli-test> npm start -- command --arg=value

> cli-test@1.0.0 start
> node index.js command

[
  'C:\\Program Files\\nodejs\\node.exe',
  'C:\\temp\\cli-test\\index.js',
  'command'
]
```

Note how `--arg=value` is missing from  `process.argv`.

### Expected Behavior

`--arg=value` must be present in `process.argv`. It works properly if invoked from `cmd` (rather than PowerShell):

```text
PS C:\temp\cli-test> cmd
Microsoft Windows [Version 10.0.22631.3527]
(c) Microsoft Corporation. All rights reserved.

C:\temp\cli-test>npm start -- command --arg=value

> cli-test@1.0.0 start
> node index.js command --arg=value

[
  'C:\\Program Files\\nodejs\\node.exe',
  'C:\\temp\\cli-test\\index.js',
  'command',
  '--arg=value'
]
```

It also works as expected under previous versions of Node v21.7.3 and NPM v10.5.0 and the same version of PowerShell v7.4.2. 

### Steps To Reproduce

See above in "Current Behavior".

### Environment

- npm: 10.6.0
- Node.js: 22.0.0
- OS Name: Windows 11 23H2 Build 22631.3527
- System Model Name:
- npm config:
```ini
; "builtin" config from C:\Users\User\AppData\Roaming\npm\node_modules\npm\npmrc

prefix = "C:\\Users\\User\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v22.0.0
; npm local prefix = C:\temp\cli-test
; npm version = 10.6.0
; cwd = C:\temp\cli-test
; HOME = C:\Users\User
; Run `npm config ls -l` to show all defaults.
```

**Comment by wraithgar** [comment] 2024-04-29 23:14
Duplicate of https://github.com/npm/cli/issues/7375

**Closed as completed by wraithgar** 2024-04-29 23:14 UTC
Labels: Bug, Needs Triage, Release 10.x
