### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by mohammedshine17** [npm/cli#7668] opened 2024-07-19 08:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

#27 [22/26] RUN npm install --legacy-peer-deps --ignore-scripts
#27 19.12 npm error Exit handler never called!
#27 19.12 npm error This is an error with npm itself. Please report this error at:
#27 19.12 npm error   <https://github.com/npm/cli/issues>
#27 19.12 npm error A complete log of this run can be found in: /root/.npm/_logs/2024-07-19T06_49_07_815Z-debug-0.log
#27 DONE 22.1s

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by AsifNawaz-cnic** [comment] 2024-07-19 09:05
+1

**Comment by melroy89** [comment] 2024-07-19 09:26
Duplicate of: https://github.com/npm/cli/issues/7666

**Comment by milaninfy** [comment] 2024-07-19 12:22
Closing Seems similer if not duplicate of https://github.com/npm/cli/issues/7657.
Try node 22.4.1 with npm 10.8.2.

**Closed as completed by milaninfy** 2024-07-19 12:22 UTC
Labels: Bug, Needs Triage

**Comment by milaninfy** [comment] 2024-07-19 14:36
Fixed in Node.js v22.5.1 https://github.com/nodejs/node/issues/53902#issuecomment-2239263377
