### ISSUE TITLE
[BUG] Multiple substitutions of npm_package_config_* variables is not working

### ISSUE THREAD

**Issue by enawder** [npm/cli#1899] opened 2020-10-04 18:22 UTC
A configuration variable defined using another one, is not properly substituted when used in npm scripts.

Here is a `package.json` example:
```
{
  "name": "example",
  "version": "1.0.0",
  "config": {
    "foo": "foo",
    "bar": "$npm_package_config_foo"
  },
  "scripts": {
    "echo": "echo $npm_package_config_bar"
  }
}
```
### Current Behavior:
```
$ npm run echo
> echo $npm_package_config_bar

$npm_package_config_foo
```

### Expected Behavior:

```
$ npm run echo
> echo $npm_package_config_bar

foo
```
### Steps To Reproduce:

1. Use the `package.json` provided above.
2. Run `npm run echo`.

### Environment:

- OS: Linux archlinux 5.4.2-arch1-1
- Node: 13.3.0
- npm: 6.12.1

**Comment by ljharb** [comment] 2020-10-04 21:23
I would not expect that to happen. `FOO=foo BAR='$FOO' ; echo $BAR` doesn't echo "foo", it echoes "$FOO". You'd need something like `eval echo "$BAR"` to end up with `foo`.

**Comment by enawder** [comment] 2020-10-05 11:20
Thanks for your reply @ljharb.

Indeed, using single quotes does not trigger the substitution, but double quotes do, as well as no quotes when dealing directly with the shell (`bash` in my case).

`FOO=foo BAR="$FOO" ; echo $BAR` does echo `foo`. Same for `FOO=foo BAR=$FOO ; echo $BAR`.

I tried using `"echo \"$npm_package_config_bar\""`, to somehow force the substitution, but it didn't work.

I did one more test by adding an npm script `"env": "env"` to list environment variables and ran:

```
npm run env | grep npm_package_config_
```
which outputs
```
npm_package_config_bar=$npm_package_config_foo
npm_package_scripts_echo=echo $npm_package_config_bar
npm_package_config_foo=foo
```
I would have expected the following:
```
npm_package_config_bar=foo
npm_package_scripts_echo=echo $npm_package_config_bar
npm_package_config_foo=foo
```

**Comment by ljharb** [comment] 2020-10-05 17:32
To be clear tho, that's because that evaluates the value of BAR *immediately* - not dynamically later, when BAR is echoed.

**Comment by darcyclarke** [comment] 2021-06-02 21:08
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 21:08 UTC
Labels: Release 6.x, Bug
