### ISSUE TITLE
[BUG] Can't run `npm install` and can't even run `npm whoami` without errors using GitHub Packages

### ISSUE THREAD

**Issue by joshuarobs** [npm/cli#2758] opened 2021-02-22 23:52 UTC
### Current Behavior:
If I run these various commands, I get these errors. Everything seemed to be working fine a month ago and often if things broke, I'd typically look towards regenerating a github token and putting that into my `~/.npmrc` file. This started from a few versions ago, around 7.4.3 I believe.

My goal is to have this work normally as usual: install public npm packages as you would without any additional configuration, yet be able to access private packages hosted on GitHub packages.

My `.npmrc` file in the project folder is:
````
registry=https://npm.pkg.github.com/joshuarobs
````

I regenerated a token in this url on GitHub: https://github.com/settings/tokens/ and I copied and pasted it into `~/.npmrc` with the contents as follows:
````
//registry.npmjs.org/:_authToken=XXX
//npm.pkg.github.com/:_authToken=XXX
fund=false
````

````
// Running `npm whoami`
joshua@Joshuas-MBP fashion-app-cms-ts % npm whoami
npm ERR! code E404
npm ERR! 404 Not Found - GET https://npm.pkg.github.com/joshuarobs/-/whoami
npm ERR! 404 
npm ERR! 404  'whoami' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/joshua/.npm/_logs/2021-02-22T23_31_44_906Z-debug.log
````

Not sure why it would consider `whoami` as a package when clearly its a command.

Anyway, if I also try to run `npm install` I get a similar issue:

````
joshua@Joshuas-MBP fashion-app-cms-ts % npm install
npm ERR! code E401
npm ERR! Incorrect or missing password.
npm ERR! If you were trying to login, change your password, create an
npm ERR! authentication token or enable two-factor authentication then
npm ERR! that means you likely typed your password in incorrectly.
npm ERR! Please try again, or recover your password at:
npm ERR!     https://www.npmjs.com/forgot
npm ERR! 
npm ERR! If you were doing some other operation then your saved credentials are
npm ERR! probably out of date. To correct this please try logging in again with:
npm ERR!     npm login
````

If I try to do as suggested, when I try to run `npm login` I get:

````
joshua@Joshuas-MBP fashion-app-cms-ts % npm login
npm notice Log in on https://npm.pkg.github.com/joshuarobs
Username: joshuarobs
Password: 
Email: (this IS public) XXX
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://npm.pkg.github.com/joshuarobs/-/user/org.couchdb.user:joshuarobs
npm ERR! 404 
npm ERR! 404  'org.couchdb.user:joshuarobs' is not in the npm registry.
npm ERR! 404 This package name is not valid, because 
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
````

Not sure why I get an error like this, seeing as I entered my details properly and copied and pasted the token in properly.

### Expected Behavior:
Everything should work as intended. `npm whoami` should give a simple result of the username/alias and `npm install` should install packages.

### Steps To Reproduce:
1. Create an `.npmrc` file locally in a nodejs project with contents: `registry=https://npm.pkg.github.com/[MY_GITHUB_USERNAME]`
2. Create a new token at https://github.com/settings/tokens/ with permissions: `repo, workflow and write:packages` checked
3. Create a `~/.npmrc` and paste `//npm.pkg.github.com/:_authToken=XXX`
4. Copy token that was created in step 2 and replace XXX with that
5. Try to run `npm whoami`
6. Try to install some packages with `npm install`

### Environment:
- OS: MacOS Big Sur 11.2.1
- Node: 14.15.1
- npm: 7.5.6

**Comment by joshuarobs** [comment] 2021-02-23 00:07
Downgrading to `6.14.11` works for me.

I still get an error running `npm whoami`, but I can successfully install packages with `npm install`

**Comment by TwoCupsofSteve** [comment] 2021-02-23 14:54
Have you used "APT" to install "NPM"? I encountered a silimar issues and had to install several dependencies to fetch NPM. I needed node-gyp, nodejs-dev, and the root issue stemming from libssl1.0-dev. I believe default I was using was libcurl4-openssl-dev. Lmk if that does anything for you!

**Comment by nlf** [comment] 2021-02-24 18:17
you have your registry specified as `https://npm.pkg.github.com/joshuarobs` however i think the url you want is `https://npm.pkg.github.com` without the username as part of the path

this change makes the request to whoami be `https://npm.pkg.github.com/-/whoami` which is a valid url and succeeds.

this working in npm 6 i think is actually a bug in npm 6 where the path is being ignored..

**Comment by bradydoll** [comment] 2021-02-24 19:27
I'm running into this same issue after upgrading to v7.5.6 from v6.14.10.

GitHub repositories require the owner in the path, ex `registry=https://npm.pkg.github.com/OWNER`. This is documented in their [configuration guide](https://docs.github.com/en/packages/guides/configuring-npm-for-use-with-github-packages#installing-a-package).

**Comment by leepowelldev** [comment] 2021-02-25 10:33
For the login issue, see if this works (https://docs.github.com/en/packages/guides/configuring-npm-for-use-with-github-packages#authenticating-to-github-packages):

```
npm login --scope=@joshuarobs --registry=https://npm.pkg.github.com
```

**Comment by nlf** [comment] 2021-02-25 16:11
I know those docs instruct you to append your username, but if you can try without it and let me know what that changes I'd appreciate it. If that works I'll make sure the docs are modified to reflect that

**Comment by o0x2a** [comment] 2021-04-22 09:41
I needed to add registry command line option to make it work
```
npm login --registry=https://npm.pkg.github.com
```

**Comment by nlf** [comment] 2022-04-04 19:45
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.

**Closed as completed by nlf** 2022-04-04 19:45 UTC
Labels: Release 7.x, Bug

**Comment by WarrenWongCodes** [comment] 2022-08-24 14:26
Noting here if anyone had organizational issues after running the above steps. Ensure that your Personal Access token is authorized by your company as well.

**Comment by bradydoll** [comment] 2022-08-24 15:15
I was able to resolve my issue by changing the syntax in the `.npmrc` file. Instead of `registry=https://npm.pkg.github.com/OWNER`, I changed it to `@OWNER:registry=https://npm.pkg.github.com` (the [documentation on GitHub](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry#installing-a-package) was also updated with this).
