### ISSUE TITLE
[DOCS] package.json has duplicate `#description`

### ISSUE THREAD

**Issue by hyunbinseo** [npm/cli#6238] opened 2023-03-10 01:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Problem, not another kind of Docs Problem.

- [X] This is a CLI Docs Problem.

### Description of Problem

There are duplicate `#description`. As the result, the ToC to `description` field does not work.

Table of contents
- [Description](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#description)
- [name](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#name)
- [version](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#version)
- [description](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#description-1) // Does not work

### Affected URL

https://docs.npmjs.com/cli/v9/configuring-npm/package-json

**Comment by wraithgar** [comment] 2023-03-30 21:05
Duplicate of https://github.com/npm/documentation/issues/34

**Closed as completed by wraithgar** 2023-03-30 21:05 UTC
Labels: Needs Triage, Documentation
