### ISSUE TITLE
[BUG] Cache corruptions when multiple installs occur concurrently. 

### ISSUE THREAD

**Issue by sfrycertinia** [npm/cli#1484] opened 2020-07-02 12:41 UTC
# What / Why

On our CI environments (Jenkins/AWS ECS). We regularly run into an issue when a new slave comes online and launches a set of jobs. We see npm corruptions. We have to ditch the slave as it never recovers. It does seem that there is an issue with the caching and multiple processes. Additional information, we are running an Artifactory instance as the registry.

## When
Several times a week.

## Where
npm install or npm ci

## How
npm install or npm ci

### Current Behavior

We see errors like.

     [exec] npm ERR! Unexpected end of JSON input while parsing near '...i" : "latest",
     [exec] npm ERR!       '
     [exec] 
     [exec] npm ERR! A complete log of this run can be found in:
     [exec] npm ERR!     /home/ec2-user/.npm/_logs/2020-07-02T12_08_07_422Z-debug.log

These are sometime preceded by lots of errors like

npm WARN tar ENOENT: no such file or directory

There doesn't seem to be a pattern in which modules are listed in the logs.

### Steps to Reproduce

Launch a Jenkins slave (AWS Linux) and run multiple jobs immediately.

### Expected Behavior

What happens mostly. That all the builds can install npm modules successfully.

## Who
* n/a

## References
* n/a

**Comment by sfrycertinia** [comment] 2020-07-08 11:08
This is really causing us issues. If you think this could be a problem with our usage we are keen to know what we are doing wrong. At the moment though this does genuinely seem to be a concurrency issue, at least on the platform we are using. Is no one else seeing this?

**Comment by isaacs** [comment] 2020-07-29 16:50
So, concurrency _shouldn't_ cause any problems with the cache.  If the JSON.parse fails there, it treats that as a cache miss and hits the registry.  That being said, I have been wrong before :)

You can test whether it's _cache_ related concurrency by setting a job-specific cache folder in your Jenkins environment.  It'll make it less efficient, of course, since the cache won't be shared, but if that works without issues, it'll be a valuable data point to indicate it might be a cache management issue.

You could do something like this:

```
npm_config_cache=$PWD/.npm-cache-$$-$RANDOM npm install
```

Also, what version of npm are you using?

**Comment by sfrycertinia** [comment] 2020-07-30 08:42
Hi, thanks for your response. We are using npm 6.14.5. We are trying using a local cache as you suggest but are using the following command. It would appear that it is equivalent, is that so?

`npm ci --cache local-cache-folder`

**Comment by darcyclarke** [comment] 2021-06-02 21:16
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 21:16 UTC
Labels: Release 6.x, Bug
