### ISSUE TITLE
[BUG] `npm --workspace [w] version [v]` doesn't update root level package-lock

### ISSUE THREAD

**Issue by MustafaHaddara** [npm/cli#3756] opened 2021-09-14 20:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a project using NPM 7 workspaces. One package is named `button`. 

If I run `npm -w button version minor`, then the version number in button's `package.json` gets incremented as I would expect. However, the root-level `package-lock.json` does not get modified.

If I later run an `npm -w button install` then the value in `packages.button.version` gets updated to reflect the current version.

### Expected Behavior

I would expect the value at `packages.button.version` in the root-level `package-lock.json` file to get updated at the same time as button's `package.json`, when the `npm version` command is run.

### Steps To Reproduce

1. Set up a project with one package, run `npm --workspaces install` to generate basic `package-lock.json`
2. Run `npm -w [package name] version minor`
3. See that the package's `package.json` has been updated but the root level `package-lock.json` has not
4. Run `npm -w [package name] install`
5. See that the root level `package-lock.json` has one change in it: the sub-package's version number.

### Environment

- OS: macOS 11.5.2
- Node: 16.7.0
- npm: 7.20.3

**Comment by ruyadorno** [comment] 2022-01-25 00:43
**Closing:** this looks to be similar if not a duplicate of an existing issue, #3403. If you believe your instance is unique, please provide further clarifying details.

**Closed as completed by ruyadorno** 2022-01-25 00:43 UTC
Labels: Release 7.x, Bug
