### ISSUE TITLE
[BUG] "npm install github:..." creates "git+ssh://" in the lockfile, which breaks GitHub Actions.

### ISSUE THREAD

**Issue by WeeJeWel** [npm/cli#3247] opened 2021-05-14 15:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Since NPM v7:

When installing a new dependency from a public repository (`github:foo/bar`), this creates a `git+ssh://git@github.com/foo/bar`) in the `package-lock.json`.

This breaks when running `npm ci` in  a GitHub Action because it doesn't have the SSH agent configured. And it shouldn't need to, because the dependency is public.

### Expected Behavior

Don't put `git+ssh` there but `github:`.

### Steps To Reproduce

`npm i github:foo/bar`

### Environment

- OS: macOS Big Sur
- Node 16
- npm v7.12.1

**Comment by joebowbeer** [comment] 2021-05-18 17:27
Duplicates #2610?

**Comment by wraithgar** [comment] 2021-06-18 21:20
Yes this is a duplicate of #2610

**Closed as completed by wraithgar** 2021-06-18 21:20 UTC
Labels: Release 7.x, Bug, Needs Triage
