### ISSUE TITLE
[BUG] package-lock custom resolved url

### ISSUE THREAD

**Issue by fishcharlie** [npm/cli#3533] opened 2021-07-10 17:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`package-lock.json` uses private verdaccio endpoint for the `resolved` field as opposed to the NPM registry.

One work around for this is to do a find all and replace in the `package-lock.json` whenever you run `npm i`. But that is a real hassle.

### Expected Behavior

There to be an option to not use the private verdaccio endpoint for the `resolved` field so when other users run `npm i` they don't run into errors.

### Steps To Reproduce

1. Set `.npmjs` to `registry=http://thisismyprivateverdaccioendpoint.com/`
2. Create a project (`npm init`)
3. Run `npm i --save express` (or any package)
4. Notice how `package-lock.json` will have the `resolved` property set to the registry set in `.npmjs`
5. Send project to someone else without node_modules folder
6. Have them run `npm i`
7. Notice that there is an error

### Environment

- OS: macOS 12.0 Beta (21A5268h)
- Node: v16.4.2
- npm: 7.18.1

**Comment by wraithgar** [comment] 2021-07-12 13:46
Closing as duplicate of https://github.com/npm/cli/issues/3530

**Closed as completed by wraithgar** 2021-07-12 13:46 UTC
Labels: Release 7.x, Bug, Needs Triage
