### ISSUE TITLE
[BUG] NPM install enters an infinite loop while using `--force`

### ISSUE THREAD

**Issue by yeikel** [npm/cli#6720] opened 2023-08-18 14:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Reproducer : 

https://github.com/yeikel/npm-infinite-loop-test/blob/main/.github/workflows/node.js.yml#L30-L31

### Expected Behavior

`npm install` should fail or at least terminate with an exception rather than to enter an infinite loop

### Steps To Reproduce

Using `npm=9.8.0` and `node=20.5.1` 

1. Run `git clone https://github.com/yeikel/npm-infinite-loop-test.git` 
2. Navigate to the folder `cd npm-infinite-loop-test`
3. Run `npm install`
4. Run `npm install react@18.2.0  --force --dry-run false --ignore-scripts --package-lock-only`

Expected : The `npm install` steps fails or terminates
Actual : It enters an infinite loop 

CI logs : https://github.com/yeikel/npm-infinite-loop-test/actions/runs/5904014044/job/16015196142

### Environment

Environment
npm: 9.8.0 but seems to happen for older versions as well
Node.js: 20.5.1 but seems to happen for older versions as well
OS Name: Any

Reproducer : https://github.com/yeikel/npm-infinite-loop-test

**Comment by milaninfy** [comment] 2024-05-08 19:32
**Closing:** this looks to be similar if not a duplicate of an existing issue, #7349. If you believe your instance is unique, please provide further clarifying details.

**Closed as completed by milaninfy** 2024-05-08 19:32 UTC
Labels: Bug, Needs Triage, Release 9.x

**Comment by yeikel** [comment] 2024-05-11 05:11
> **Closing:** this looks to be similar if not a duplicate of an existing issue, #7349. If you believe your instance is unique, please provide further clarifying details.
> 

That other issue is 1m old when I reported this much earlier. Did you mean to say that other one is a duplicate of this?
