### ISSUE TITLE
Feature Request: `--esm` or similar flag for `npm init`

### ISSUE THREAD

**Issue by trevor-scheer** [npm/cli#6298] opened 2023-03-28 23:46 UTC
Hello, I'd like to suggest a flag for `npm init` which creates a project using `"type": "module"`. `--esm`, `--module`, or similar. Would this change be welcome? Assuming it's trivial in the way I imagine I'd consider opening the PR for it. Thanks in advance!

**Comment by ljharb** [comment] 2023-03-29 05:14
Duplicate of https://github.com/npm/feedback/discussions/480.

**Closed as not planned by ljharb** 2023-03-29 05:14 UTC
