### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by sushil8383** [npm/cli#2112] opened 2020-11-03 14:03 UTC
npm ERR! cb() never called!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\abc\AppData\Roaming\npm-cache\_logs\2020-11-03T13_58_52_163Z-de

**Comment by ljharb** [comment] 2020-11-03 15:34
Duplicate of #2111.

**Closed as completed by ljharb** 2020-11-03 15:34 UTC
