### ISSUE TITLE
[BUG] npm 7.10 does not recursively install modules in local filesystem

### ISSUE THREAD

**Issue by andreash** [npm/cli#3100] opened 2021-04-19 09:05 UTC
### Current Behavior:
I have
<pre><code>
    +- main_project  
    |  +-package.json
    +- packages
       +- package1
          +-package.json
</code></pre>

In `package1` as cwd I do `npm install express` and then `rm -rf node_modules` and `rm package-lock.json`. Then, in main_project as cwd I do `npm install`. The `express` module does not get installed in `package1` with npm 7.10. If I use npm 6.14.12 everything is fine and npm installs recursively and express and its dependencies show up in the `node_modules` subdirectory of `package1`.

### Expected Behavior:
I expect npm 7.10 to behave the same way as npm 6.14.12

### Steps To Reproduce:
See steps above and zip attached - pretty simple.

### Environment:
- OS: Ubuntu 20.04
- Node:  v14.16.1 with npm 7.10 and v12.22.1 with npm 6.14.12
- npm: 7.10 / 6.14.12

[npm_7.0-test.zip](https://github.com/npm/cli/files/6334677/npm_7.0-test.zip)

**Comment by tangkunyin** [comment] 2021-04-19 11:15
I'm experiencing this same issue：https://github.com/sindresorhus/gulp-imagemin/issues/338

**Comment by andreash** [comment] 2021-04-22 18:08
> I'm experiencing this same issue：[sindresorhus/gulp-imagemin#338](https://github.com/sindresorhus/gulp-imagemin/issues/338)

Did you find a solution?

**Comment by tangkunyin** [comment] 2021-04-23 11:18
> > I'm experiencing this same issue：[sindresorhus/gulp-imagemin#338](https://github.com/sindresorhus/gulp-imagemin/issues/338)
> 
> Did you find a solution?

@andreash Downgrade npm to 6x or use yarn instead.

**Comment by andreash** [comment] 2021-04-23 12:34
Yeah, that's what I am doing (user npm 6.x). Yarn doesn't work for me for other reasons. But I still see this as a bug in npm 7.

**Comment by ath0mas** [comment] 2021-04-24 14:26
Seems duplicate of #2339 (and #3028): npm 7 issue with transient dependencies for local path deps (referenced through `file:`)

**Comment by darcyclarke** [comment] 2021-06-04 18:38
`v7` doesn't install package's dependencies that are outside of the root (ie. any package defined as `../...` isn't going to get it's dependencies reified) - this is indeed a duplicate

**Closed as completed by darcyclarke** 2021-06-04 18:38 UTC
Labels: Release 7.x, Bug, Duplicate
