### ISSUE TITLE
[BUG] Npm install silently fails with an invalid version number

### ISSUE THREAD

**Issue by alexduf** [npm/cli#1392] opened 2020-06-04 13:51 UTC
# What / Why
It seems like `npm install` fails if the version in the `package.json` is invalid. Failing would be fine if there was an error message or a non 0 return code, but instead NPM only outputs a warning. Other warnings such as lack of description or missing license don't stop the command line the same way.

## When
The version number in the `package.json` is invalid.

## Where
`npm install`

## How

Successful case:

```json
{
  "name": "@guardian/content-api-models",
  "version": "15.9.0-SNAPSHOT",
  "dependencies": {
    "thrift": "^0.12.0"
  }
}
```

output:
```
npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @guardian/content-api-models@15.9.0-SNAPSHOT No description
npm WARN @guardian/content-api-models@15.9.0-SNAPSHOT No repository field.
npm WARN @guardian/content-api-models@15.9.0-SNAPSHOT No license field.
```

Failing case:
```json
{
  "name": "@guardian/content-api-models",
  "version": "15.9-SNAPSHOT",
  "dependencies": {
    "thrift": "^0.12.0"
  }
}
```

```
npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN Invalid version: "15.9-SNAPSHOT"
npm WARN deleteme No description
npm WARN deleteme No repository field.
npm WARN deleteme No README data
npm WARN deleteme No license field.
```

### Current Behavior
Returns with a 0 exit-code, only warnings, but no node_modules directory after the install.

### Steps to Reproduce
See `How` section

### Expected Behavior
Either an error in the terminal, with a return code > 0, or the version number should be ignored and the installation of dependencies should proceed. Whichever makes sense to the maintainers of the project.

## Who

* n/a

## References

* n/a

**Comment by bcnorwood** [comment] 2021-05-10 13:50
This is still broken in v6.14.13. While it appears to be fixed in v7.12, v7 is incompatible with Node 14, the latest version supported by Lambda.

At a bare minimum, v6 needs to report an error. I wasted far too long trying to figure out why my dependencies wouldn't install only to discover that this "warning" was anything but.

**Comment by ljharb** [comment] 2021-05-10 15:27
@bcnorwood npm 7 is quite compatible with node 10, 12, and 14+.

**Comment by bcnorwood** [comment] 2021-05-10 21:41
> @bcnorwood npm 7 is quite compatible with node 10, 12, and 14+.

So it is - mea culpa. I got an error about a missing module when I upgraded earlier, as well as a message about an "ancient" version of NPM which I assumed to be v6. Upon confirming that v7 came with Node v15, it seemed obvious what was going on. Naturally, I can't reproduce either of these behaviors, and NPM v7 is working fine with every version of Node I've tried. Oh well.

Still, given that Node v14 installs with NPM v6 by default, this is far from ideal - if someone installs Node v14 with NVM to work on Lambda functions and runs `npm i` in an unfamiliar package with an invalid version (as I did), there's no indication of why no packages get installed, much less that upgrading to NPM v7 will fix it.

I also totally get that it's a minor edge case in an older version, which is why I think simply changing the warning to an error (I'm hoping this is just a matter of swapping out a constant?) would be sufficient to prevent future developers from chasing their tails over this.

**Comment by ljharb** [comment] 2021-05-10 21:51
with nvm, you can run `nvm install whatever --latest-npm` safely.

**Comment by darcyclarke** [comment] 2021-06-02 22:20
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is reproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 22:20 UTC
Labels: Bug
