### ISSUE TITLE
[BUG] Pre-release version does not work with peer dependencies

### ISSUE THREAD

**Issue by koditio** [npm/cli#3135] opened 2021-04-23 18:02 UTC
### Current Behavior:

Consider following dependency structure:
 * Package test1@1.0.0 with no dependencies
 * Package test2@1.0.0 with a peer dependency "test1@>=1.0.0"
 * Package test3 with dependencies: "test1@>=1.0.0" and "test2@>=1.0.0"
 This works fine, however if I publish a pre-release version of test1, let's say "1.0.1-rc.0" and update test3 to use that,
I get a "Could not resolve dependency" error ("Found: @koditio/test1@1.0.1-rc.0 ...  peer @koditio/test1@">= 1.0.0).

If I modify test2 to use regular dependencies instead, the same setup works (I can specify pre-release version in test3 and I get a single version of test1 installed in test3, not two).

### Expected Behavior:

With npm 6 the same sequence works (and I expect "1.0.1-rc.0" version to match ">= 1.0.0" condition
with npm 7 changes regarding peer dependencies).

### Steps To Reproduce:

The package structure described above, test1/package.json:
```
{
  "name": "test1",
  "version": "1.0.1-rc.0"
}
```

test2/package.json:
```
{
  "name": "test2",
  "version": "1.0.0",
  "peerDependencies": {
    "test1": ">= 1.0.0"
  }
}
```
test3/package.json:
```
{
  "name": "test3",
  "version": "1.0.0",
  "dependencies": {
    "test1": "1.0.1-rc.0",
    "test2": ">= 1.0.0"
  }
}
```

### Environment:
 - Node: 12.20.0
 - npm: 7.11.0

**Comment by wraithgar** [comment] 2021-05-07 14:24
This is by design https://github.com/npm/node-semver#prerelease-tags

Resolving peerDependendies in `includePrerelease:true` mode is something that would have to be changed via the RFC process: https://github.com/npm/rfcs

**Closed as completed by wraithgar** 2021-05-07 14:24 UTC
Labels: Release 7.x, Bug, Needs Triage
