### ISSUE TITLE
[BUG] npm audit fix command is deleting npm sections from package.json

### ISSUE THREAD

**Issue by alvarocamillont** [npm/cli#1690] opened 2020-08-18 20:51 UTC
### Current Behavior:
When I run npm audit fix on my project, it is deleting sessions of my package.json file such as "description" and "scripts"

### Expected Behavior:
I expect the command only change my dependencies.

### Steps To Reproduce:

1. clone this repo https://github.com/po-ui/po-angular.git
2. Run npm i
3. Run npm audit fix
4. See package.json

### Environment:
- OS: Ubuntu 20.04
- Node: v12.18.2
- NPM: 7.0.0-beta.5

**Comment by ruyadorno** [comment] 2020-08-18 20:56
## Minimal reproduction steps:

### BEFORE

```sh
$ cat package-lock.json
{
  "name": "test-npm-audit-messing-up-package-json",
  "version": "1.0.0",
  "lockfileVersion": 2,
  "requires": true,
  "packages": {
    "": {
      "version": "1.0.0",
      "license": "ISC",
      "dependencies": {
        "dot-prop": "^4.2.0"
      }
    },
    "node_modules/dot-prop": {
      "version": "4.2.0",
      "resolved": "https://registry.npmjs.org/dot-prop/-/dot-prop-4.2.0.tgz",
      "integrity": "sha512-tUMXrxlExSW6U2EXiiKGSBVdYgtV8qlHL+C10TsW4PURY/ic+eaysnSkwB4kA/mBlCyy/IKDJ+Lc3wbWeaXtuQ==",
      "dependencies": {
        "is-obj": "^1.0.0"
      },
      "engines": {
        "node": ">=4"
      }
    },
    "node_modules/is-obj": {
      "version": "1.0.1",
      "resolved": "https://registry.npmjs.org/is-obj/-/is-obj-1.0.1.tgz",
      "integrity": "sha1-PkcprB9f3gJc19g6iW2rn09n2w8=",
      "engines": {
        "node": ">=0.10.0"
      }
    }
  },
  "dependencies": {
    "dot-prop": {
      "version": "4.2.0",
      "resolved": "https://registry.npmjs.org/dot-prop/-/dot-prop-4.2.0.tgz",
      "integrity": "sha512-tUMXrxlExSW6U2EXiiKGSBVdYgtV8qlHL+C10TsW4PURY/ic+eaysnSkwB4kA/mBlCyy/IKDJ+Lc3wbWeaXtuQ==",
      "requires": {
        "is-obj": "^1.0.0"
      }
    },
    "is-obj": {
      "version": "1.0.1",
      "resolved": "https://registry.npmjs.org/is-obj/-/is-obj-1.0.1.tgz",
      "integrity": "sha1-PkcprB9f3gJc19g6iW2rn09n2w8="
    }
  }
}

$ cat package.json
{
  "name": "test-npm-audit-messing-up-package-json",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "repository": "ruyadorno/test-npm-audit-messing-up-package-json",
  "scripts": {
    "hello": "echo \"Hello\"",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "dot-prop": "^4.2.0"
  }
}
```

### AFTER

```patch
$ npm audit fix
$ git diff
diff --git a/package-lock.json b/package-lock.json
index 8f79ef5..cbe450e 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -12,9 +12,9 @@
       }
     },
     "node_modules/dot-prop": {
-      "version": "4.2.0",
-      "resolved": "https://registry.npmjs.org/dot-prop/-/dot-prop-4.2.0.tgz",
-      "integrity": "sha512-tUMXrxlExSW6U2EXiiKGSBVdYgtV8qlHL+C10TsW4PURY/ic+eaysnSkwB4kA/mBlCyy/IKDJ+Lc3wbWeaXtuQ==",
+      "version": "4.2.1",
+      "resolved": "https://registry.npmjs.org/dot-prop/-/dot-prop-4.2.1.tgz",
+      "integrity": "sha512-l0p4+mIuJIua0mhxGoh4a+iNL9bmeK5DvnSVQa6T0OhrVmaEa1XScX5Etc673FePCJOArq/4Pa2cLGODUWTPOQ==",
       "dependencies": {
         "is-obj": "^1.0.0"
       },
@@ -33,9 +33,9 @@
   },
   "dependencies": {
     "dot-prop": {
-      "version": "4.2.0",
-      "resolved": "https://registry.npmjs.org/dot-prop/-/dot-prop-4.2.0.tgz",
-      "integrity": "sha512-tUMXrxlExSW6U2EXiiKGSBVdYgtV8qlHL+C10TsW4PURY/ic+eaysnSkwB4kA/mBlCyy/IKDJ+Lc3wbWeaXtuQ==",
+      "version": "4.2.1",
+      "resolved": "https://registry.npmjs.org/dot-prop/-/dot-prop-4.2.1.tgz",
+      "integrity": "sha512-l0p4+mIuJIua0mhxGoh4a+iNL9bmeK5DvnSVQa6T0OhrVmaEa1XScX5Etc673FePCJOArq/4Pa2cLGODUWTPOQ==",
       "requires": {
         "is-obj": "^1.0.0"
       }
diff --git a/package.json b/package.json
index 72be34c..608c9ff 100644
--- a/package.json
+++ b/package.json
@@ -1,17 +1,8 @@
 {
-  "name": "test-npm-audit-messing-up-package-json",
   "version": "1.0.0",
-  "description": "",
-  "main": "index.js",
-  "repository": "ruyadorno/test-npm-audit-messing-up-package-json",
-  "scripts": {
-    "hello": "echo \"Hello\"",
-    "test": "echo \"Error: no test specified\" && exit 1"
-  },
-  "keywords": [],
-  "author": "",
   "license": "ISC",
   "dependencies": {
     "dot-prop": "^4.2.0"
-  }
+  },
+  "name": "test-npm-audit-messing-up-package-json"
 }
```

**Comment by ruyadorno** [comment] 2020-08-18 21:09
It happens only on `npm audit fix`, tried it with `npm install dot-prop@legacy` and can't reproduce the problem.

**Comment by alvarocamillont** [comment] 2020-08-18 21:12
**BEFORE**
```bash
{
  "name": "po-ui-sources",
  "version": "3.2.0",
  "description": "PO UI",
  "homepage": "https://po-ui.io",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "https://github.com/po-ui/po-angular"
  },
  "scripts": {
    "ng": "ng",
    "tsc": "tsc",
    "start": "ng serve",
    "lint": "ng lint --type-check --format=stylish",
    "lint:storage": "ng lint storage --type-check --format=stylish",
    "lint:sync": "ng lint sync --type-check --format=stylish",
    "lint:ui": "ng lint ui --type-check --format=stylish",
    "lint:templates": "ng lint templates --type-check --format=stylish",
    "lint:code-editor": "ng lint code-editor --type-check --format=stylish",
    "e2e": "ng e2e",
    "test": "ng test --watch=false --code-coverage --browsers=ChromeHeadless --source-map",
    "test:storage": "ng test storage --watch=false --code-coverage --browsers=ChromeHeadless --source-map",
    "test:sync": "ng test sync --watch=false --code-coverage --browsers=ChromeHeadless --source-map",
    "test:sync:browse": "ng test sync --code-coverage --browsers=Chrome --source-map",
    "test:ui": "ng test ui --watch=false --code-coverage --browsers=ChromeHeadless --source-map",
    "test:ui:browse": "ng test ui --code-coverage --browsers=Chrome --source-map",
    "test:templates": "ng test templates --watch=false --code-coverage --browsers=ChromeHeadless --source-map",
    "test:templates:browse": "ng test templates --code-coverage --browsers=Chrome --source-map",
    "test:code-editor": "ng test code-editor --watch=false --code-coverage --browsers=ChromeHeadless --source-map",
    "test:code-editor:browse": "ng test code-editor --code-coverage --browsers=Chrome --source-map",
    "test:dev": "ng test --browsers=ChromeHeadless",
    "build:schematics": "cd ./projects/schematics && npm run build",
    "build:ui": "ng build ui --prod && gulp build:schematics --lib ui && gulp replaceVersion && cd dist/ng-components && npm pack",
    "build:ui:lite": "ng build ui --prod",
    "build:code-editor": "ng build code-editor --prod && gulp build:schematics --lib code-editor && gulp replaceVersion && cd dist/ng-code-editor && npm pack",
    "build:templates": "ng build templates --prod && gulp build:schematics --lib templates && gulp replaceVersion && cd dist/ng-templates && npm pack",
    "build:storage": "ng build storage --prod && gulp build:schematics --lib storage && gulp replaceVersion && cd dist/ng-storage && npm pack",
    "build:storage:lite": "ng build storage --prod",
    "build:sync": "ng build sync --prod && gulp build:schematics --lib sync && gulp replaceVersion && cd dist/ng-sync && npm pack",
    "build": "npm run build:schematics && npm run build:ui && npm run build:templates && npm run build:storage && npm run build:sync && npm run build:code-editor",
    "build:portal:prod": "node --max-old-space-size=4096 node_modules/@angular/cli/bin/ng build portal --prod --build-optimizer=false",
    "build:portal": "cd projects/portal && gulp build",
    "release": "standard-version --preset angular",
    "sonarqube": "gulp sonarqube",
    "format:fix": "pretty-quick --staged",
    "format:check": "prettier --check --loglevel error \"**/*{.ts,.js,.json,.css,.scss,.html}\"",
    "format:all": "prettier --write \"**/*{.ts,.js,.json,.css,.scss,.html}\"",
    "publish:ui:local": "npm publish dist/ng-components --registry http://localhost:4873",
    "publish:templates:local": "npm publish dist/ng-templates --registry http://localhost:4873",
    "publish:sync:local": "npm publish dist/ng-sync --registry http://localhost:4873",
    "publish:storage:local": "npm publish dist/ng-storage --registry http://localhost:4873",
    "publish:code-editor:local": "npm publish dist/ng-code-editor --registry http://localhost:4873",
    "publish:schematics:local": "npm publish dist/ng-schematics --registry http://localhost:4873",
    "publish:local": "npm run publish:schematics:local && npm run publish:ui:local && npm run publish:templates:local && npm run publish:code-editor:local && npm run publish:sync:local && npm run publish:storage:local"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^10.0.3",
    "@angular/common": "^10.0.3",
    "@angular/compiler": "^10.0.3",
    "@angular/core": "^10.0.3",
    "@angular/forms": "^10.0.3",
    "@angular/platform-browser": "^10.0.3",
    "@angular/platform-browser-dynamic": "^10.0.3",
    "@angular/router": "^10.0.3",
    "@ionic-native/core": "5.23.0",
    "@ionic-native/network": "5.23.0",
    "@po-ui/style": "3.2.0",
    "capitalize": "^2.0.3",
    "colors": "^1.4.0",
    "core-js": "3.6.4",
    "custom-idle-queue": "2.1.2",
    "gulp-clean": "^0.4.0",
    "gulp-run": "^1.7.1",
    "highlight.js": "^10.1.2",
    "http-status-codes": "^1.4.0",
    "localforage": "1.4.0",
    "lokijs": "1.5.8",
    "monaco-editor": "0.20.0",
    "ngx-markdown": "^10.1.0",
    "run-sequence": "^2.2.1",
    "rxjs": "~6.5.5",
    "rxjs-compat": "~6.5.5",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1000.2",
    "@angular-devkit/build-ng-packagr": "~0.1000.2",
    "@angular/cli": "^10.0.2",
    "@angular/compiler-cli": "^10.0.3",
    "@angular/language-service": "^10.0.3",
    "@commitlint/cli": "^8.3.5",
    "@commitlint/config-angular": "^8.3.4",
    "@commitlint/travis-cli": "^8.3.5",
    "@po-ui/ng-tslint": "3.0.0",
    "@types/jasmine": "~3.5.10",
    "@types/jasminewd2": "~2.0.8",
    "@types/node": "^13.13.4",
    "@types/systemjs": "^6.1.0",
    "codelyzer": "^5.2.2",
    "del": "^5.1.0",
    "dgeni": "^0.4.10",
    "dgeni-packages": "0.26.12",
    "gulp": "^4.0.2",
    "gulp-filter": "^6.0.0",
    "gulp-foreach": "^0.1.0",
    "gulp-git": "^2.10.0",
    "gulp-sync": "^0.1.4",
    "gulp-tap": "^2.0.0",
    "gulp-util": "^3.0.8",
    "husky": "^4.2.3",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~3.3.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "ng-packagr": "^10.0.0",
    "prettier": "2.0.2",
    "pretty-quick": "^2.0.1",
    "protractor": "~7.0.0",
    "rollup": "^1.20.0",
    "sonarqube-scanner": "^2.6.0",
    "standard-version": "^8.0.1",
    "ts-node": "~8.8.1",
    "tsickle": "^0.39.1",
    "tslint": "~6.1.0",
    "tslint-config-prettier": "^1.18.0",
    "tslint-plugin-prettier": "^2.3.0",
    "typemoq": "^2.1.0",
    "typescript": "~3.9.6"
  },
  "standard-version": {
    "skip": {
      "commit": true,
      "tag": true
    }
  }
}

```

**AFTER**
```bash
diff --git a/package.json b/package.json
index 47a64de..bc06e44 100644
--- a/package.json
+++ b/package.json
@@ -1,60 +1,7 @@
 {
   "name": "po-ui-sources",
   "version": "3.2.0",
-  "description": "PO UI",
-  "homepage": "https://po-ui.io",
   "license": "MIT",
-  "repository": {
-    "type": "git",
-    "url": "https://github.com/po-ui/po-angular"
-  },
-  "scripts": {
-    "ng": "ng",
-    "tsc": "tsc",
-    "start": "ng serve",
-    "lint": "ng lint --type-check --format=stylish",
-    "lint:storage": "ng lint storage --type-check --format=stylish",
-    "lint:sync": "ng lint sync --type-check --format=stylish",
-    "lint:ui": "ng lint ui --type-check --format=stylish",
-    "lint:templates": "ng lint templates --type-check --format=stylish",
-    "lint:code-editor": "ng lint code-editor --type-check --format=stylish",
-    "e2e": "ng e2e",
-    "test": "ng test --watch=false --code-coverage --browsers=ChromeHeadless --source-map",
-    "test:storage": "ng test storage --watch=false --code-coverage --browsers=ChromeHeadless --source-map",
-    "test:sync": "ng test sync --watch=false --code-coverage --browsers=ChromeHeadless --source-map",
-    "test:sync:browse": "ng test sync --code-coverage --browsers=Chrome --source-map",
-    "test:ui": "ng test ui --watch=false --code-coverage --browsers=ChromeHeadless --source-map",
-    "test:ui:browse": "ng test ui --code-coverage --browsers=Chrome --source-map",
-    "test:templates": "ng test templates --watch=false --code-coverage --browsers=ChromeHeadless --source-map",
-    "test:templates:browse": "ng test templates --code-coverage --browsers=Chrome --source-map",
-    "test:code-editor": "ng test code-editor --watch=false --code-coverage --browsers=ChromeHeadless --source-map",
-    "test:code-editor:browse": "ng test code-editor --code-coverage --browsers=Chrome --source-map",
-    "test:dev": "ng test --browsers=ChromeHeadless",
-    "build:schematics": "cd ./projects/schematics && npm run build",
-    "build:ui": "ng build ui --prod && gulp build:schematics --lib ui && gulp replaceVersion && cd dist/ng-components && npm pack",
-    "build:ui:lite": "ng build ui --prod",
-    "build:code-editor": "ng build code-editor --prod && gulp build:schematics --lib code-editor && gulp replaceVersion && cd dist/ng-code-editor && npm pack",
-    "build:templates": "ng build templates --prod && gulp build:schematics --lib templates && gulp replaceVersion && cd dist/ng-templates && npm pack",
-    "build:storage": "ng build storage --prod && gulp build:schematics --lib storage && gulp replaceVersion && cd dist/ng-storage && npm pack",
-    "build:storage:lite": "ng build storage --prod",
-    "build:sync": "ng build sync --prod && gulp build:schematics --lib sync && gulp replaceVersion && cd dist/ng-sync && npm pack",
-    "build": "npm run build:schematics && npm run build:ui && npm run build:templates && npm run build:storage && npm run build:sync && npm run build:code-editor",
-    "build:portal:prod": "node --max-old-space-size=4096 node_modules/@angular/cli/bin/ng build portal --prod --build-optimizer=false",
-    "build:portal": "cd projects/portal && gulp build",
-    "release": "standard-version --preset angular",
-    "sonarqube": "gulp sonarqube",
-    "format:fix": "pretty-quick --staged",
-    "format:check": "prettier --check --loglevel error \"**/*{.ts,.js,.json,.css,.scss,.html}\"",
-    "format:all": "prettier --write \"**/*{.ts,.js,.json,.css,.scss,.html}\"",
-    "publish:ui:local": "npm publish dist/ng-components --registry http://localhost:4873",
-    "publish:templates:local": "npm publish dist/ng-templates --registry http://localhost:4873",
-    "publish:sync:local": "npm publish dist/ng-sync --registry http://localhost:4873",
-    "publish:storage:local": "npm publish dist/ng-storage --registry http://localhost:4873",
-    "publish:code-editor:local": "npm publish dist/ng-code-editor --registry http://localhost:4873",
-    "publish:schematics:local": "npm publish dist/ng-schematics --registry http://localhost:4873",
-    "publish:local": "npm run publish:schematics:local && npm run publish:ui:local && npm run publish:templates:local && npm run publish:code-editor:local && npm run publish:sync:local && npm run publish:storage:local"
-  },
-  "private": true,
   "dependencies": {
     "@angular/animations": "^10.0.3",
     "@angular/common": "^10.0.3",
@@ -132,11 +79,5 @@
     "tslint-plugin-prettier": "^2.3.0",
     "typemoq": "^2.1.0",
     "typescript": "~3.9.6"
-  },
-  "standard-version": {
-    "skip": {
-      "commit": true,
-      "tag": true
-    }
   }
 }
```

**Comment by snypelife** [comment] 2020-08-19 15:37
I have also experienced this with `npm ci`. Perhaps I should open another issue for this?

**Comment by isaacs** [comment] 2020-08-19 16:24
@snypelife Nah, one is fine.  I'm thinking it's the same core issue in Arborist anyway.

**Comment by isaacs** [comment] 2020-08-23 20:20
Fixed in latest v7 beta.  Thanks!

**Closed as completed by isaacs** 2020-08-23 20:20 UTC
Labels: Release 7.x, Bug
