### ISSUE TITLE
[BUG] npm install --no-save removes other dependencies

### ISSUE THREAD

**Issue by vanpana** [npm/cli#1460] opened 2020-06-25 09:39 UTC
# What / Why
Installing npm dependencies with the `--no-save` flag will remove other dependencies that were installed in the same manner.

## When
Always.

## Where
* npm public registry

### Current Behavior
Installing npm dependencies with the `--no-save` flag will remove other dependencies that were installed in the same manner.

### Steps to Reproduce
1. Init a folder with a package.json
2. Run `npm install {package1} --no-save`. (replace package1 with whatever you want)
3. Check `node_modules` for {package1}, you'll find it.
4. Run `npm install {package2} --no-save`. (replace package2 with whatever you want)
5. Check `node_modules` for {package2}, you'll find it.
6. Check `node_modules` for {package1}, you WON'T find it.

### Expected Behavior
Both packages should exist in `node_modules`

**Comment by jonchurch** [comment] 2020-06-25 21:04
I'm not sure this is a bug. Dependency resolution relies heavily on package.json as the source of truth. According to [the docs](https://docs.npmjs.com/cli/install#algorithm), npm will merge the dep tree from node_modules (during an install) with what is described by package.json, and add, move, or remove deps as necessary. It's not documented specifically, but I assume that what's happening is the package.json's dep tree takes precedence over what is described by node_modules (which is by design).

What usecase do you have for installing with `--no-save`? Without the deps being listed in package.json, it's impossible to have a reproducible build. If you're interested in installing deps that aren't deployed, use devDependencies and `--save-dev` to keep them out of your production build.

**Comment by ljharb** [comment] 2020-06-25 21:53
I think the auto-pruning behavior is very bad UX, but it's not a bug when that feature is enabled.

**Comment by vanpana** [comment] 2020-06-26 09:07
> I'm not sure this is a bug. Dependency resolution relies heavily on package.json as the source of truth. According to [the docs](https://docs.npmjs.com/cli/install#algorithm), npm will merge the dep tree from node_modules (during an install) with what is described by package.json, and add, move, or remove deps as necessary. It's not documented specifically, but I assume that what's happening is the package.json's dep tree takes precedence over what is described by node_modules (which is by design).
> 
> What usecase do you have for installing with `--no-save`? Without the deps being listed in package.json, it's impossible to have a reproducible build. If you're interested in installing deps that aren't deployed, use devDependencies and `--save-dev` to keep them out of your production build.

I have some dependencies that take a lot of time to be installed and not all of the devs on the project need them. So I just want to install them when the script that  requires them is being called, but without having to persist  them into the package.json.

**Comment by darcyclarke** [comment] 2021-06-02 22:20
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is reproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 22:20 UTC
Labels: Bug
