### ISSUE TITLE
Longer time for Installation

### ISSUE THREAD

**Issue by PradyumnaA** [npm/cli#6700] opened 2023-08-09 22:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Hey there I am using npm 9.8.1 and there is a longer time in installation,
there is no problem in firebase server but there is a problem in react js folder,
can anyone please help,
thanks in advance

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by milaninfy** [comment] 2024-03-13 16:44
@PradyumnaA  Please describe the issue clearly. Include steps to reproduce along with any other details like environment.

**Comment by milaninfy** [comment] 2024-03-22 14:34
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.

**Closed as not planned by milaninfy** 2024-03-22 14:34 UTC
Labels: Awaiting Information, Bug, Release 9.x
