### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by theunderdogdev** [npm/cli#4348] opened 2022-01-31 14:15 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

npm install doesn't work either way. After upgrading Node JS to v17.4.0 and npm to v8.4.0 npm install gives two errors with different packages every time which completely halts or crashes the process.
```
PS E:\VS projs\react-app> npx create-react-app app

Creating a new React app in E:\VS projs\react-app\app.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...
npm ERR! code ERR_SSL_CIPHER_OPERATION_FAILED
npm ERR! A4250000:error:1C800066:Provider routines:ossl_gcm_stream_update:cipher operation
failed:c:\ws\deps\openssl\openssl\providers\implementations\ciphers\ciphercommon_gcm.c:312:
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ruturaj_k\AppData\Local\npm-cache\_logs\2022-01-30T09_11_05_521Z-debug-0.log

Aborting installation.
  npm install --no-audit --save --save-exact --loglevel error react react-dom react-scripts cra-template has failed.

Deleting generated file... node_modules
Deleting generated file... package.json
Deleting app/ from E:\VS projs\react-app
Done.
```
I felt I had this issue only on my machine so I checked out on different machine with macOS platform and firstly it produces the above error and then when ran second time it give the SOCKET_TIMEOUT error. 

There's still more to this 
I checked with another machine with windows platform and sadly it doesn't work there either. I tested it with a highspeed connection and it's still the same :( .
[2022-01-31T09_34_56_431Z-debug-0.log](https://github.com/npm/cli/files/7971163/2022-01-31T09_34_56_431Z-debug-0.log)

 

### Expected Behavior

>  1. Expected to install the required packages and create a react app.
>  2. Expected to install global modules without any error

  Expected output

 ![image](https://user-images.githubusercontent.com/65947291/151805817-aca37524-177e-43e7-a113-65e21114e1cf.png)

### Steps To Reproduce

1. Open Terminal / Command Prompt
2. Type ``` npm install -g nodemon ``` or  ``` npx create-react-app my-app ```
3. Fetches some packages.
```
Creating a new React app in E:\VS projs\react-app\app.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...
```
4. Then suddenly logs an error stoping the install.
```
npm ERR! code ERR_SSL_CIPHER_OPERATION_FAILED
npm ERR! A4250000:error:1C800066:Provider routines:ossl_gcm_stream_update:cipher operation
failed:c:\ws\deps\openssl\openssl\providers\implementations\ciphers\ciphercommon_gcm.c:312:
npm ERR!
```
and sometimes
```
verbose npm  v8.4.0
4743 error code ERR_SOCKET_TIMEOUT
4744 error errno ERR_SOCKET_TIMEOUT
4745 error network Invalid response body while trying to fetch https://registry.npmjs.org/dotenv: Socket timeout
4746 error network This is a problem related to network connectivity.
4746 error network In most cases you are behind a proxy or have bad network settings.
4746 error network
4746 error network If you are behind a proxy, please make sure that the
4746 error network 'proxy' config is set properly.  See: 'npm help config
```

### Environment

- npm: v8.4.0
- Node.js: v17.4.0
- OS Name: Windows 10 Pro Build 9043.1503 Version 21H1
- npm config:
```ini
npm config ls `; "builtin" config from C:\Users\ruturaj_k\AppData\Roaming\npm\node_modules\npm\npmrc

prefix = "C:\\Users\\ruturaj_k\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\WINDOWS\system32
; HOME = C:\Users\ruturaj_k
; Run `npm config ls -l` to show all defaults.` here


```

**Comment by nlf** [comment] 2022-02-01 19:44
does this only occur in node 17.4.0? we don't officially support node 17, so it's possible there's some breakage there that would be resolved by using node 16. if possible, i would start by giving that a try.

**Comment by ljharb** [comment] 2022-02-01 21:21
@nlf yes, you do. https://github.com/npm/cli/blob/latest/package.json#L262

**Comment by nlf** [comment] 2022-02-01 22:17
> @nlf yes, you do. https://github.com/npm/cli/blob/latest/package.json#L262

🤦 why so we do. just the same, i'm curious if node 16 resolves this for you. i'll investigate node 17 in windows.

**Comment by theunderdogdev** [comment] 2022-02-02 07:40
I have checked node v16 with the latest npm on windows. Though it doesn’t give the same error as above. But yells [this](https://stackoverflow.com/questions/69615175/how-to-resolve-reading-isserver-error-in-npm) error 

```
npm  ERR! Cannot read properties of undefined (reading 'isServer')
 ``` 

On a windows machine. 



But wait, on macOS node v16, with a good network connection it gives the 
```ERR_SOCKET_TIMEOUT ``` 

moreover I was concerned about knowing if this was for a specific set of packages, it turns out I couldn’t install other modules like vue-cli, next/nuxt 


```
npm install -g @vue/cli


npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! errno ERR_SOCKET_TIMEOUT
npm ERR! network Invalid response body while trying to fetch https://registry.npmjs.org/express: Socket timeout
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ruturajkalshetti/.npm/_logs/2022-02-04T08_30_03_310Z-debug-0.log
ruturajkalshetti@RUTURAJs-MacBook-Air Webdesign % 
```

[2022-02-04T08_30_03_310Z-debug-0.log](https://github.com/npm/cli/files/8001269/2022-02-04T08_30_03_310Z-debug-0.log)



Platform macOS

**Comment by martinburger** [comment] 2022-02-19 06:52
FYI: This issue might be related to #3078.

**Comment by nlf** [comment] 2022-03-08 19:38
this does indeed seem to be a duplicate of #3078, the SSL cipher issue i can reproduce by lowering my timeout values low enough that the socket is closed during the tls handshake. i'm going to close this as a duplicate and we will continue investigation and debugging in #3078

**Closed as completed by nlf** 2022-03-08 19:38 UTC
Labels: Release 8.x, Bug, Needs Triage, platform:windows

**Comment by bottomless-emergency** [comment] 2025-10-20 14:11
@nlf https://recreation-mandango38.github.io/memoization/
