### ISSUE TITLE
npm ERROR! Exit handler never called!

### ISSUE THREAD

**Issue by amispam** [npm/cli#3765] opened 2021-09-16 10:38 UTC
In Termux(android app)

npx create-react-app myapp failed

Installation aborted

All the newly created directories were rolled back and deleted

You can see Error log below:

[2021-09-16T10_09_09_239Z-debug.log](https://github.com/npm/cli/files/7177025/2021-09-16T10_09_09_239Z-debug.log)

**Comment by Theo13111** [comment] 2021-09-16 14:47
> In Termux(android app)
> 
> npx create-react-app myapp failed
> 
> Installation aborted
> 
> All the newly created directories were rolled back and deleted
> 
> You can see Error log below:
> 
> [2021-09-16T10_09_09_239Z-debug.log](https://github.com/npm/cli/files/7177025/2021-09-16T10_09_09_239Z-debug.log)

**Comment by amispam** [comment] 2021-09-16 15:00
I am able to find the issue, I am getting error because of core-js package of npm, but the moment I try to uninstall it, I recieve the same error what I was getting while creating new app that is: exit handler is not called.
I tried updating core-js as it is deprecated, but again I'm getting same error, how to fix this problem? @ext

**Comment by TheEriss** [comment] 2021-09-17 13:57
> I am able to find the issue, I am getting error because of core-js package of npm, but the moment I try to uninstall it, I recieve the same error what I was getting while creating new app that is: exit handler is not called.
> I tried updating core-js as it is deprecated, but again I'm getting same error, how to fix this problem? @ext

Same error :( my says  "Exit Handler never called" and this is problem with npm itself

**Comment by amispam** [comment] 2021-09-18 03:06
There can be many reasons for the error: "Exit Handler never called"  you can share your error log file so that I can tell you if it is really because of core-js or some other issue! However meanwhile you can install all the required packages for 'create-react-app' MANUALLY !!! I recently tried doing it manually and my React App is working quite fine!

**Comment by Whysoseriouz19** [comment] 2021-09-22 03:09
npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2021-09-22T02_58_47_927Z-debug.log


Same error here

**Comment by amispam** [comment] 2021-09-22 08:00
Instead of going for CRA template, go for manual Boilerplate installation, that's the only solution until this bug is fixed!

**Comment by lukekarrys** [comment] 2021-09-23 00:08
**Closing:** this error can arise for a number of reasons; Please read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) & refile an issue with as much information as possible if you're able to **consistently reproduce** this error.

**Closed as completed by lukekarrys** 2021-09-23 00:08 UTC

**Comment by amispam** [comment] 2021-09-23 04:45
@lukekarrys if you don't know the reason behind it: let me tell you: it is happening because of CRA template, deprecated version of core-js is trying to run something in shell, but 'create-react-app' somehow always refers to wrong bash path, obviously if one is getting this error during installation, then this is the only possible reasons, so I suggest you: THINK TWICE BEFORE CLOSING A QUESTION AND ATLEAST USE YOUR BRAIN.

**Comment by lukekarrys** [comment] 2021-09-23 17:01
I'm not able to reproduce this on the latest version of npm (`7.24.0`) and create-react-app (`4.0.3`),  when running `npx create-react-app test-app --use-npm` so I think the issue is more complex than that and could be due to the large number of dependencies being installed in your local android environment. I'd still recommend reading [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) and trying to come up with a minimal set of commands that involve only installing/uninstalling `core-js` to help us better reproduce the issue.

**Comment by amispam** [comment] 2021-09-23 18:33
@lukekarrys I'll suggest you to have a look at log file, I don't think you have seen the log file yet!
