### ISSUE TITLE
[QUESTION] <npm install takes so long on windows>

### ISSUE THREAD

**Issue by hugopedro** [npm/cli#1599] opened 2020-08-01 00:05 UTC
# What / Why
When I type "npm install" it takes ~5-10 minutes on windows, on linux is 1 minute

These lines caught my attention:

npm timing action:extract Completed in **234805ms**
npm timing action:finalize Completed in **21198ms**
npm timing action:refresh-package-json Completed in **128891ms**
npm verb unlock done using C:\Users\Hugo\AppData\Roaming\npm-cache\_locks\staging-2acf162e836ea64f.lock for C:\...\node_modules\.staging
npm timing stage:executeActions Completed in **395181ms**
npm info lifecycle stock-trader@0.1.0~prepare: stock-trader@0.1.0
npm timing stage:runTopLevelLifecycles Completed in **399677ms**
npm verb saving []

So, what can I do to fix this very slow performance when 'npm install'?

**Comment by hugopedro** [comment] 2020-08-10 13:58
bump

**Comment by pburkindine** [comment] 2020-12-08 14:07
We were experiencing a similar issue; it turned out to be the result of our antivirus policy.  There is a folder which on a linux machine is normally `~/.npm/_lock` which our AV needed to ignore.

**Comment by darcyclarke** [comment] 2021-06-02 21:16
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Comment by darcyclarke** [comment] 2021-06-02 21:21
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 21:21 UTC
Labels: Awaiting Information, Release 6.x, platform:windows

**Comment by conallprendergast** [comment] 2022-06-15 12:33
@hugopedro Did you ever find out what was causing this issue?

**Comment by diegodelico** [comment] 2023-07-18 13:41
@hugopedro we are experiencing the same issue here, we are using Centos7 and it take 40 min only in "npm timing action:extract Completed in 2474343ms"

![Capture d’écran, le 2023-07-18 à 09 41 14](https://github.com/npm/cli/assets/4643503/22d3a6bd-ff17-4a2f-858e-0e58b2ccc3a0)

**Comment by conallprendergast** [comment] 2023-07-18 14:26
@diegodelico for me this problem was caused by a particular dependency in my package.json, that was attempting to pull from GitHub using the git protocol.
This was disabled by GitHub, see https://blog.readthedocs.com/github-git-protocol-deprecation/

Have a look at results from "--loglevel silly" and see if there are any timeouts

**Comment by diegodelico** [comment] 2023-07-18 15:46
@conallprendergast thank you so much!! I found the problem 
![Capture d’écran, le 2023-07-18 à 11 45 41](https://github.com/npm/cli/assets/4643503/f06f6724-69e6-4890-ae79-bd6b697aa9ef)
I just need to find a solution now, but thanks again!

**Comment by conallprendergast** [comment] 2023-07-18 16:07
@diegodelico glad to help. Solution should be to use the "git+https://" protocol instead in your package.json

**Comment by diegodelico** [comment] 2023-07-18 17:40
@conallprendergast it works!, thanks again! 💪
