### ISSUE TITLE
[BUG] My npm install does nothing while trying to install a package

### ISSUE THREAD

**Issue by tttylerr** [npm/cli#7221] opened 2024-02-13 21:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Whenever I try to install a npm package the install does nothing. In this case I am installing express and socket.io. It doesnt output anything when i use --verbose and when I clear the cache. I have also reinstalled multiple times. I am doing this on a raspberry pi os full server.

### Expected Behavior

It should install the package

### Steps To Reproduce

1. On a Raspberry PI OS Full Server
2. No modified config
3. Run 'npm i express socket.io'
4. See nothing happen

### Environment

- npm: 9.2.0
- Node.js:  18.19
- OS Name: Raspberry PI OS Full Server
- System Model Name: Raspberry PI 4
- npm config:
```ini
; "builtin" config from /usr/share/nodejs/npm/npmrc

globalignorefile = "/etc/npmignore"
prefix = "/usr/local"

; "project" config from /home/tyler/.panel/.npmrc

registry = "https://registry.npmjs.org/"

; "cli" config from command line options

location = "project"

; node bin location = /usr/bin/node
; node version = v18.19.0
; npm local prefix = /home/tyler/.panel
; npm version = 9.2.0
; cwd = /home/tyler/.panel
; HOME = /home/tyler
; Run `npm config ls -l` to show all defaults.
```

**Comment by milaninfy** [comment] 2024-05-21 16:30
@tttylerr Could you please try and update npm to latest version to check if that fixes your issue ?

**Comment by milaninfy** [comment] 2024-06-12 17:15
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.

**Closed as not planned by milaninfy** 2024-06-12 17:15 UTC
Labels: Bug, Needs Triage, Release 9.x
