### ISSUE TITLE
[BUG] `bundledDependencies` (still) does not bundle relevant executables

### ISSUE THREAD

**Issue by thw0rted** [npm/cli#3357] opened 2021-06-03 08:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Bundled dependencies do not export executables when packing.

### Expected Behavior

`npm pack` output should include scripts under `.bin` to launch any executables provided by the bundled depdency.

### Steps To Reproduce

1. Install any dependency that exposes an executable, e.g. `lws`.
2. Include this dependency in `bundledDependencies`
3. `npm pack`

The resulting artifact includes the `bundledDependency` under `node_modules`, but does not create a `.bin` directory at all, and so the depdency's executable(s) will not be available.

### Environment

* Win10 20H2
* Node: 14.15.4
* npm: 7.4.0

**Comment by thw0rted** [comment] 2021-06-03 08:04
As requested in #2491, I've re-filed this.

As an aside, your triage process is kind of a pain.  In the above issue, I had the same details using the same template, except that the original issue said npm v6.14 -- but a followup question asked if it was still reproducible in 7.4.0 and I said it was.  Instead of closing that issue with a boilerplate response about opening a new one, you could have looked at the tags ("Release 7.x" is included), noticed that the template has not changed, and left it open.

**Comment by ljharb** [comment] 2021-06-03 16:01
Sorry about the mistake; I’ve reopened the original.

Closing as a duplicate of #2491.

**Closed as completed by ljharb** 2021-06-03 16:01 UTC
Labels: Release 7.x, Bug, Needs Triage
