### ISSUE TITLE
Delay in "npm config get prefix"

### ISSUE THREAD

**Issue by ghost** [npm/cli#1260] opened 2020-05-08 08:58 UTC
I am not sure if its just me but when I run `npm config get prefix` it hangs around 1-2 seconds.

I am using this [https://github.com/nvm-sh/nvm](url) to manage my Node versions which uses that npm command internally when new bash shell opens.

**Comment by ljharb** [comment] 2020-05-08 16:29
Duplicate of #1243.

**Closed as completed** 2021-03-26 04:29 UTC
