### ISSUE TITLE
[BUG] npx doesn't work when in child workspace

### ISSUE THREAD

**Issue by felipecrs** [npm/cli#2826] opened 2021-03-04 22:11 UTC
### Current Behavior:

If I run `npx <binary>` of a binary installed by a child's `package.json`, it doesn't find the binary as npm v7 now install the binaries under the parent `node_modules`.

### Expected Behavior:

This used to work, as there was no workspaces concept before and therefore all the projects were linking binaries to their `node_modules`.

### Steps To Reproduce:

Should be simple.

### Suggestion

I think this should not be fixed by `npx` itself, but instead, `npm` should create symlinks under the children's `node_modules/.bin` at least for the packages referenced in the children's `package.json`.

**Comment by ljharb** [comment] 2021-03-04 23:05
I don't think this is something that was ever truly reliable. If you're expecting to run a local binary, it should be a direct dep/devDep.

If anything, it's a bug that bins are created at all for transitive deps.

**Comment by felipecrs** [comment] 2021-03-05 01:30
This can be replicated:

1. Open my repository: https://gitpod.io/#https://github.com/felipecrs/megatar
   - It has a `package.json` in the root, and another in the website subfolder.
   - `docusaurus` is set as dependency in the website folder.
   - `docusaurus` is NOT set as dependency in the root project
   - website is in the list of workspace of the root project
   - Gitpod will run `npm install` automatically in the root project, but feel free to `git clean -fdx` and run `npm install` by yourself
2. Run `cd website; npx docusaurus --version`
   - It will fail: `docusaurus` is not in `website/node_modules/.bin` but in `node_modules/.bin` (from the root folder).

**Comment by ljharb** [comment] 2021-03-05 02:08
Ah, in the context of workspaces, i see what you mean. The bins should surely not be hoisted to the parent, even if the module itself is.

**Comment by darcyclarke** [comment] 2021-04-09 18:38
Can replicate & we're discussing internally how to fix this bug

**Comment by felipecrs** [comment] 2021-04-09 18:47
I have some ideas:

1. Make `npx` look up for `node_modules/.bin` folder up to the root folder `/`
2. Create a symbolic link of the root's bin folder: `website/node_modules/.bin -> ../node_modules/.bin`
3. Create a symbolic link of the modules defined in the child workspace: `website/node_modules/.bin/docusaurus -> ../node_modules/.bin/docusaurus` **(seems to be the best approach to me)**
4. Install the `bins` only to where they belong, instead of installing `docusaurus` on the `node_modules`, install to `website/node_modules`. Seems reasonable, but it would be too bad as I would lose the ability to run `npx docusaurus` from the root folder

**Comment by ljharb** [comment] 2021-04-09 19:06
The last option makes the most sense to me; if you wanted to run a bin from the root it'd be in the root's package.json.

**Comment by felipecrs** [comment] 2021-04-09 20:12
What if there are two child projects which has `docusaurus` as dependencies? Would be good if npm would be smart enough to download it once (if the version constraints match of course), instead of downloading it twice in each repo. 

That's why I think the third option would be better than the fourth.

**Comment by ljharb** [comment] 2021-04-09 21:13
Hoisting the dependency itself would make sense - but not the bin.

**Comment by felipecrs** [comment] 2021-04-09 21:34
In a monorepo, I would like to have `semantic-release` defined in the root project, so it would be available for all the child projects, even the binary because I would need to run `npx semantic-release` in all the child projects.

The only solution which would match this requirement would be 1 and 2. But now I thought in a new one which builds on 4:

5. Install the `bins` only to the project they belong, instead of installing child's binaries on the root's `node_modules/.bin`, install to child's `node_modules/.bin`. Exceptionally for the `bins` defined in the root project, install the `bins` into root's `node_modules/.bin` and create symbolic links of all the binaries from the root project to all the child projects (unless they collide, of course).

Now, this is the one which makes more sense to me.

**Comment by ljharb** [comment] 2021-04-09 21:39
Yes, option 5 is what I'm expecting, with npm's current hoisting model.

**Comment by felipecrs** [comment] 2021-04-09 21:44
Apart from that, I think option 1 could be implemented as well, together with 5, and it would be harmless. No? It would only make `npx` smarter IMHO. [As the `require.resolve` works](https://nodejs.org/api/modules.html#modules_require_resolve_request_options).

**Comment by ljharb** [comment] 2021-04-09 22:11
Either or both could be done, yes, but workspace correctness would still require option 2, 3, 4, or 5.

**Comment by ruyadorno** [comment] 2021-04-21 21:31
>     1. Make `npx` look up for `node_modules/.bin` folder up to the root folder `/`

That's the current behavior today: https://github.com/npm/run-script/blob/2a2f1b637ffa2463a82df477e17ea4e146682f5b/lib/set-path.js#L19

---

I'm not sure if there was something that was fixed between your original post and now but this is working as intended when I test with **npm@7.10.0**, I have the following structure (with `@ruyadorno/create-index` being a dep of my workspace `a`):

```
├── a
│  └── package.json
├── node_modules
│  ├── .bin
│  │  └── create-index -> ../@ruyadorno/create-index/create-index.js
│  ├── .package-lock.json
│  ├── @ruyadorno
│  │  └── create-index
│  │     ├── create-index.js
│  │     ├── package.json
│  │     └── README.md
│  └── a -> ../a
├── package-lock.json
└── package.json
```

it works as intended when I `cd ./a && npm exec @ruyadorno/create-index`

This is what both `package.json` files look like:

```patch
diff --git a/a/package.json b/a/package.json
new file mode 100644
index 0000000..c845857
--- a/a/package.json
+++ b/a/package.json
+{
+  "name": "a",
+  "version": "1.0.0",
+  "dependencies": {
+    "@ruyadorno/create-index": "^1.0.0"
+  }
+}
diff --git a/package.json b/package.json
new file mode 100644
index 0000000..23dd3e2
--- a/package.json
+++ b/package.json
+{
+  "name": "test-npx-workspaces",
+  "workspaces": [
+    "a"
+  ]
+}
```

---

I'll sync up internally with @darcyclarke again to see if he can still reproduce it but would appreciate if you can give it a try again @felipecrs, vlw!

**Comment by felipecrs** [comment] 2021-04-22 14:28
The issue can still be replicated with the [steps I suggested](https://github.com/npm/cli/issues/2826#issuecomment-791076148):

![image](https://user-images.githubusercontent.com/29582865/115731875-df629d00-a35d-11eb-9481-8c8b4301f8e4.png)

---

> That's the current behavior today: https://github.com/npm/run-script/blob/2a2f1b637ffa2463a82df477e17ea4e146682f5b/lib/set-path.js#L19

If that would be the case, the example above would have worked. Perhaps such logic only applies to `npm run` and not `npx`?

**Comment by ruyadorno** [comment] 2021-04-26 22:33
@felipecrs thanks for following up, that specific problem running the `docusaurus` package looks related to the way the package is published and unrelated to workspaces support in **npm**. I get the same problem as you when I'm trying to run the package in my system **\*in any directory\***:

> npm ERR! could not determine executable to run

From a quick inspection [it doesn't look like the package provides a recognizable single entry point for **npx**](https://github.com/facebook/docusaurus/blob/master/packages/docusaurus-1.x/package.json#L22-L30), you can [read more on how the `bin` property of a `package.json` needs to be formated in our `npm exec` docs](https://docs.npmjs.com/cli/v7/commands/npm-exec#description), here is the gist of it:

> - If the package has a single entry in its bin field in package.json, or if all entries are aliases of the same command, then that command will be used.
> - If the package has multiple bin entries, and one of them matches the unscoped portion of the name field, then that command will be used.
> - If this does not result in exactly one option (either because there are no bin entries, or none of them match the name of the package), then npm exec exits with an error.

It might or not be helpful to bubble this information up to the package maintainers, depending on how they document the usage of their application it might be expected that users install the package in the global space and run each of these binaries as a different command.

---

Now in the case you want to execute one of the available binaries from this `docusaurus` package, **npm** also provides a syntax that allows for calling a custom binary name (assuming you want to run docusaurus-version from your previous example) here is how you can call one of these defined binaries using `npm exec` or its `npx` alias:

- `npx -p docusaurus -c "docusaurus-version"`
- `npm exec --package docusaurus -c "docusaurus-version"`
---

I'm going to go ahead and close this issue since the originally reported problem regarding npx in the context of a workspace doesn't really applies.

Thank you so much for bringing this up and let us know if there's anything else we can help with :blush:

**Comment by felipecrs** [comment] 2021-04-26 22:52
@ruyadorno I'm sorry, but did you note that `npx docusaurus` in the root workspace works? And it's not only about `docusaurus`, it also happens with `typedoc`, which follows the rule you pointed:

```console
> gitpod /workspace/megatar/website $ npx typedoc --version
Need to install the following packages:
  typedoc
Ok to proceed? (y) 
> gitpod /workspace/megatar/website $ cd ..
> gitpod /workspace/megatar $ npx typedoc --version
Info: Loaded plugin /workspace/megatar/node_modules/typedoc-plugin-markdown
Info: Loaded plugin /workspace/megatar/node_modules/typedoc-plugin-merge-modules

TypeDoc 0.20.32
Using TypeScript 4.2.4 from /workspace/megatar/node_modules/typescript/lib
```

So, the issue remains valid.

**Comment by ruyadorno** [comment] 2021-04-27 15:56
@felipecrs you're right! I totally got confused by the name of the packages there, now I realize the actual package that install the `docusaurus` name you're using is `@docusaurus/core` that is inside your `website` workspace 🤦 I'm really sorry for the confusion.

I believe I'm on the right track now and I think this issue should be solved by looking up as you suggested in your `#1` option in `libnpmexec` since that's the behavior of `@npmcli/run-script` which is used to actually run these (the final solution might differ but I'll open a PR to discuss it with the rest of the team). Thanks again!

**Comment by ljharb** [comment] 2021-04-27 16:22
@ruyadorno https://github.com/npm/cli/issues/2826#issuecomment-816998744

**Comment by ruyadorno** [comment] 2021-04-27 16:57
> @ruyadorno [#2826 (comment)](https://github.com/npm/cli/issues/2826#issuecomment-816998744)

@ljharb I'm carefully avoiding that topic here since I believe it's going to be better addressed as part of the upcoming workspaces-revamp RFC we have been alluding to in the last OpenRFC meetings 😉 

That said, I'm not excluding the possibility the solution to the problem surfaced by this issue might have to pass through that major overhaul. For now I'm exploring the possibility of fixing this by simply reusing the lookup algo from run-script (which btw might not be so simple) either way I'll keep you posted 😊 Thanks!

**Comment by ljharb** [comment] 2021-04-27 18:16
Thanks, as long as it's not ignored :-)

**Comment by ruyadorno** [comment] 2021-04-28 02:20
@felipecrs I also forgot to mention that alternatively you can also use `npm exec` workspaces support (I don't remember exactly when we shipped this feature, might have been after you originally opened the issue), from the root level:

```sh
$ npm exec -w website -- docusaurus
```

so you can also use that while you wait for the fix 😊

**Comment by felipecrs** [comment] 2021-04-28 13:32
Thank you @ruyadorno. Very nice feature.

**Closed as completed** 2021-04-30 20:29 UTC
Labels: Release 7.x, Bug, Priority 1
