### ISSUE TITLE
[BUG] Install with --no-optional flag causes an update of optional peer dependency

### ISSUE THREAD

**Issue by danyacodes** [npm/cli#6731] opened 2023-08-24 11:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I'm using following command to install three-custom-shader-material:
`npm install three-custom-shader-material --no-optional`
This package is compatible with react-three-fiber and therefore has React as peer dependency. But it's possible to use this package with vanilla three.js, so React is marked as optional.
The problem is I already have React 17 as peer dependency, because I'm also using swagger-ui, and installation of three-custom-shader-material causes an React update to version 18.2.0, with which that package is not compatible.

### Expected Behavior

I don't need React features of three-custom-shader-material and want to keep React 17 for compatibility with swagger-ui. So expected behavior is to not update existing optional peer dependencies when installing with --no-optional flag.

### Steps To Reproduce

1. `npm install swagger-ui`
2. `npm install three`
3. `npm install three-custom-shader-material --no-optional`
or
`npm install three-custom-shader-material --omit=optional`
4. swagger-ui is not working because React is updated to version 18

### Environment

- npm: 9.8.1
- Node.js: 16.20.0
- OS Name: Windows 11 Pro 22H2

**Comment by kchindam-infy** [comment] 2024-08-30 19:06
@danyacodes After installing swagger-ui and then three-custom-shader-material with the --no-optional flag, i ran npm ls react and got the following output
├─┬ swagger-ui@4.19.1
│ ├─┬ react-copy-to-clipboard@5.1.0
│ │ └── react@18.3.1 deduped
│ ├─┬ react-debounce-input@3.3.0
│ │ └── react@18.3.1 deduped
│ ├─┬ react-dom@17.0.2
│ │ └── react@17.0.2 deduped
│ ├─┬ react-immutable-pure-component@2.2.2
│ │ └── react@17.0.2 deduped
│ ├─┬ react-inspector@6.0.2
│ │ └── react@18.3.1 deduped
│ ├─┬ react-redux@8.1.3
│ │ ├── react@17.0.2 deduped
│ │ └─┬ use-sync-external-store@1.2.2
│ │   └── react@18.3.1 deduped
│ ├─┬ react-syntax-highlighter@15.5.0
│ │ └── react@18.3.1 deduped
│ └── react@17.0.2
└─┬ three-custom-shader-material@5.4.0
  └── react@18.3.1
  
  Both react 17.02 and react 18.3.1 are present in the dependency tree, swagger-ui and some of its dependencies are still using the react 17.0.2. npm is using technique called peer dependency hoisting to allow multiple versions of react to co exist. --no-optional flag did not replace the existing react 17.0.2 that swagger-ui is using.

**Comment by milaninfy** [comment] 2024-09-06 21:05
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.

**Closed as not planned by milaninfy** 2024-09-06 21:05 UTC
Labels: Bug, Needs Triage, Release 9.x
