### ISSUE TITLE
[BUG] npm install rename .gitignore to .npmignore.

### ISSUE THREAD

**Issue by wmzy** [npm/cli#3545] opened 2021-07-14 10:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/5526525/125607633-98a0a4fb-755a-4841-93ed-52e917614e9f.png)

![image](https://user-images.githubusercontent.com/5526525/125608212-bc57795b-85da-4530-94fd-64ab20f2a1ca.png)

### Expected Behavior

Don't rename the `.gitignore`.

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- OS:  macOS
- Node: v15.10.0
- npm: 7.5.3

**Comment by ruyadorno** [comment] 2022-01-25 00:12
hi @wmzy thanks for taking the time to report the issue!

I'm going to close it since I can not reproduce it and it had no traction in the last 6 months. I'll be happy to reopen again in case you're able to provide more details about the environment or a minimal reproduction.

**Closed as completed by ruyadorno** 2022-01-25 00:12 UTC
Labels: Release 7.x, Bug, Needs Triage

**Comment by wmzy** [comment] 2022-02-11 03:02
@ruyadorno I can still reproduce it:
![image](https://user-images.githubusercontent.com/5526525/153531360-6ed3a445-c595-4178-9022-19d3b6c01f80.png)
