### ISSUE TITLE
ERR_SSL_CIPHER_OPERATION_FAILED

### ISSUE THREAD

**Issue by zerodeathsO6** [npm/cli#4901] opened 2022-05-15 11:03 UTC
Installing any package causes this error. I am currently using Windows 10 and NodeJS v17.

**Comment by darcyclarke** [comment] 2022-05-16 21:27
Looks like this may be a duplicate of https://github.com/npm/cli/issues/4348 & https://github.com/npm/cli/issues/3078 which should have been resolved by https://github.com/npm/minipass-fetch/pull/53. I'd update your version of npm & node to the latest versions & see if that resolve your problem (re. `npm@8.10.0` & `node@18.1.0`).

**Closed as completed by darcyclarke** 2022-05-16 21:27 UTC
