### ISSUE TITLE
[BUG] npm view --json sompackage dist-tags has invalid json

### ISSUE THREAD

**Issue by dopecodez** [npm/cli#3075] opened 2021-04-14 18:25 UTC
### Current Behavior:
Running `npm view --json sompackage dist-tags` gives an error output in case no tags exist like:

```js
{
    "shortMessage": "Command failed with exit code 1: npm view --json sompackage dist-tags",
    "command": "npm view --json sompackage dist-tags",
    "exitCode": 1,
    "stdout": "",
    "stderr": "npm ERR! code E404\nnpm ERR! 404 Not Found - GET https://registry.npmjs.org/hayden-test-repo - Not found\nnpm ERR! 404 \nnpm ERR! 404  'hayden-test-repo@latest' is not in the npm registry.\nnpm ERR! 404 You should bug the author to publish it (or use the name yourself!)\nnpm ERR! 404 \nnpm ERR! 404 Note that you can also install from a\nnpm ERR! 404 tarball, folder, http url, or git url.\n{\n  \"error\": {\n    \"code\": \"E404\",\n    \"summary\": \"Not Found - GET https://registry.npmjs.org/hayden-test-repo - Not found\",\n    \"detail\": \"\\n 'hayden-test-repo@latest' is not in the npm registry.\\nYou should bug the author to publish it (or use the name yourself!)\\n\\nNote that you can also install from a\\ntarball, folder, http url, or git url.\"\n  }\n}\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /Users/hayden/.npm/_logs/2021-04-12T14_41_53_367Z-debug.log",
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "killed": false
}
```

The `stderr` contains the `json` response but also contains some text making the JSON unparsable.

### Expected Behavior:
We should be able to get a valid json in `stderr` without the extra string.

### Steps To Reproduce:
1. Run npm view --json sompackage dist-tags
2. Observe the stderr being given.

[This issue](https://github.com/sindresorhus/np/issues/600) on `np` has more detailed info in case it is needed.

### Environment:
- OS: Ubuntu 20.04
- Node: v14.16.1
- npm: 7.9.0

**Comment by pabra** [comment] 2021-05-18 19:17
seems to be duplicate of #2740

**Comment by lukekarrys** [comment] 2021-10-07 00:46
I agree that this is a duplicate of #2740. I'm going to close this one and track this over there. Thanks for the report!

**Closed as completed by lukekarrys** 2021-10-07 00:46 UTC
Labels: Release 7.x, Bug, Priority 2
