### ISSUE TITLE
[BUG] Could not resolve dependency even though found version should satisfy peer version spec

### ISSUE THREAD

**Issue by jemucino** [npm/cli#3440] opened 2021-06-19 01:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to run npm audit fix, I get the following error:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: webpack@4.44.2
npm ERR! node_modules/webpack
npm ERR!   peer webpack@">=2" from babel-loader@8.1.0
npm ERR!   node_modules/babel-loader
npm ERR!     babel-loader@"8.1.0" from react-scripts@4.0.3
npm ERR!     node_modules/react-scripts
npm ERR!       react-scripts@"^4.0.3" from the root project
npm ERR!   peer webpack@"^4.27.0 || ^5.0.0" from css-loader@4.3.0
npm ERR!   node_modules/css-loader
npm ERR!     css-loader@"4.3.0" from react-scripts@4.0.3
npm ERR!     node_modules/react-scripts
npm ERR!       react-scripts@"^4.0.3" from the root project
npm ERR!   16 more (eslint-webpack-plugin, file-loader, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@">=4.43.0 <6.0.0" from @pmmmwh/react-refresh-webpack-plugin@0.4.3
npm ERR! node_modules/react-scripts/node_modules/@pmmmwh/react-refresh-webpack-plugin
npm ERR!   @pmmmwh/react-refresh-webpack-plugin@"0.4.3" from react-scripts@4.0.3
npm ERR!   node_modules/react-scripts
npm ERR!     react-scripts@"^4.0.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/jemucino/.npm/eresolve-report.txt for a full report.
```

### Expected Behavior

I don't know enough about NPM to say what the expected behavior should be, but shouldn't the found version (4.44.2) satisfy the peer dependency(>=4.43.0 <6.0.0)?

### Steps To Reproduce

1. In my PC (on WSL with Ubuntu 20.04) and using npm@7.16.0
2. Within a React app created with create-react-app
3. Run 'npm audit fix'
4. See error:

```npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: webpack@4.44.2
npm ERR! node_modules/webpack
npm ERR!   peer webpack@">=2" from babel-loader@8.1.0
npm ERR!   node_modules/babel-loader
npm ERR!     babel-loader@"8.1.0" from react-scripts@4.0.3
npm ERR!     node_modules/react-scripts
npm ERR!       react-scripts@"^4.0.3" from the root project
npm ERR!   peer webpack@"^4.27.0 || ^5.0.0" from css-loader@4.3.0
npm ERR!   node_modules/css-loader
npm ERR!     css-loader@"4.3.0" from react-scripts@4.0.3
npm ERR!     node_modules/react-scripts
npm ERR!       react-scripts@"^4.0.3" from the root project
npm ERR!   16 more (eslint-webpack-plugin, file-loader, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@">=4.43.0 <6.0.0" from @pmmmwh/react-refresh-webpack-plugin@0.4.3
npm ERR! node_modules/react-scripts/node_modules/@pmmmwh/react-refresh-webpack-plugin
npm ERR!   @pmmmwh/react-refresh-webpack-plugin@"0.4.3" from react-scripts@4.0.3
npm ERR!   node_modules/react-scripts
npm ERR!     react-scripts@"^4.0.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/jemucino/.npm/eresolve-report.txt for a full report.
```

### Environment

- OS: WSL (Ubuntu-20.04)
- Node: v14.17.0
- npm: 7.16.0

**Comment by talsi** [comment] 2021-06-27 09:08
same as #3171

**Comment by wraithgar** [comment] 2021-07-01 15:00
Closing as a duplicate of https://github.com/npm/cli/issues/3171

**Closed as completed by wraithgar** 2021-07-01 15:00 UTC
Labels: Release 7.x, Bug, Needs Triage

**Comment by talsi** [comment] 2021-11-08 16:37
@wraithgar it still happens to me using 7.24.2

![image](https://user-images.githubusercontent.com/5717665/140781821-bf04d7ea-a9d1-4f03-bb6c-838321ec6bab.png)
