### ISSUE TITLE
[BUG] prepare not run on npm publish

### ISSUE THREAD

**Issue by clshortfuse** [npm/cli#6293] opened 2023-03-27 16:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Hi, all!

I have a package.json with a `prepare` script.
 
When I call `npm run prepare` it does what it should and compiles everything.

When I call `npm publish` prepare is never run, despite what it says on the documentation.

I understand `npm publish --dry-run` won't prepare, but it's not running at all. Right now my script is to do:

`npm run prepare && npm publish` which the documentation says I don't need to do.

### Expected Behavior

The documentations states:

>These are run from the scripts of <pkg-name>

>
>[npm pack](https://docs.npmjs.com/cli/v9/commands/npm-pack)
>* prepack
>* prepare
>* postpack
>
>[npm publish](https://docs.npmjs.com/cli/v9/commands/npm-publish)
>* prepublishOnly
>* prepack
>* prepare
>* postpack
>* publish
>* postpublish
>
>prepare will not run during --dry-run

https://docs.npmjs.com/cli/v9/using-npm/scripts#npm-publish

### Steps To Reproduce

This is the exact package.json I'm using:

````json
{
  "name": "@shortfuse/materialdesignweb",
  "version": "0.7.1-8",
  "description": "Material Design for Web",
  "type": "module",
  "scripts": {
    "prepare": "node build/esbuild.js index.js --outdir=dist --minify --metafile --production",
    "predocs": "node bin/generate-css.js --custom=yellow,orange:orange,green:0f0,alias:aqua | npx esbuild --minify --loader=css > docs/theme.css",
    "predocs-alt": "node bin/generate-css.js --color=a46750 --custom=yellow,orange:orange,green:0f0,alias:aqua | npx esbuild --minify --loader=css > docs/alt-theme.css",
    "docs": "node build/esbuild.js docs/demo.js --outdir=docs --minify --metafile",
    "watch": "node build/esbuild.js docs/demo.js --outdir=docs --watch --metafile",
    "serve": "node build/esbuild.js docs/demo.js --outdir=docs --watch --metafile --serve --live",
    "pretest": "eslint --ignore-path .gitignore",
    "test": "c8 tap --no-coverage"
  },
  "browser": "dist/index.min.js",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/clshortfuse/materialdesignweb.git"
  },
  "keywords": [
    "material",
    "design",
    "web",
    "materialyou",
    "md3",
    "web-components"
  ],
  "files": [
    "/bin",
    "/dist",
    "/components",
    "/core",
    "/theming",
    "/mixins",
    "/utils"
  ],
  "exports": {
    "/components": "./components",
    "/core": "./core",
    "/theming": "./theming",
    "/mixins": "./mixins",
    "/utils": "./utils"
  },
  "author": "Carlos Lopez Jr. <clshortfuse@gmail.com> (https://shortfuse.org/)",
  "license": "ISC",
  "sideEffects": [
    "./polyfills.js",
    "./components/*.js",
    "./utils/metadata.js",
    "./theming/loader.js",
    "./docs/demo/*.js"
  ],
  "bugs": {
    "url": "https://github.com/clshortfuse/materialdesignweb/issues"
  },
  "homepage": "https://github.com/clshortfuse/materialdesignweb#readme",
  "devDependencies": {
    "@types/html-minifier-terser": "^7.0.0",
    "@types/tap": "^15.0.7",
    "@typescript-eslint/eslint-plugin": "^5.30.7",
    "@typescript-eslint/parser": "^5.30.7",
    "acorn": "^8.8.2",
    "acorn-walk": "^8.2.0",
    "browserslist-to-esbuild": "^1.1.1",
    "c8": "^7.12.0",
    "element-internals-polyfill": "^1.1.11",
    "esbuild": "^0.17.12",
    "eslint": "^8.24.0",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-plugin-compat": "^4.0.2",
    "eslint-plugin-github": "^4.3.5",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-jsdoc": "^40.0.3",
    "eslint-plugin-sort-class-members": "^1.15.2",
    "eslint-plugin-unicorn": "^46.0.0",
    "html-minifier-terser": "^7.1.0",
    "http-server": "^14.1.1",
    "magic-string": "^0.30.0",
    "postcss-styled": "^0.34.0",
    "postcss-styled-syntax": "^0.4.0",
    "stylelint": "^15.2.0",
    "stylelint-no-unsupported-browser-features": "github:clshortfuse/stylelint-no-unsupported-browser-features#0a51157",
    "stylelint-order": "^6.0.2",
    "stylelint-use-logical-spec": "^5.0.0",
    "tap": "^16.3.0",
    "typescript": "^5.0.2",
    "webdriverio": "^7.23.0"
  }
}
````

### Environment

- npm: 9.6.2
- Node.js: v18.14.2
- OS Name: Ubuntu 22.04.1 LTS
- System Model Name: Windows PC (WSLv2)
- npm config:
```ini
; "user" config from /home/carlos/.npmrc

//registry.npmjs.org/:_authToken = (protected) 

; node bin location = /home/carlos/.nvm/versions/node/v18.14.2/bin/node
; node version = v18.14.2
; npm local prefix = /home/carlos/projects/materialdesignweb
; npm version = 9.6.2
; cwd = /home/carlos/projects/materialdesignweb
; HOME = /home/carlos
; Run `npm config ls -l` to show all defaults.
```

**Comment by wraithgar** [comment] 2023-04-03 02:43
Prepare does run from what I can tell.  Please note that you won't see the output of the prepare script unless you tell npm to use `--forground-scripts`

```sh
~/D/n/s/scripts $ npm pkg set scripts.prepare='touch prepare-ran.txt'
~/D/n/s/scripts $ ls prepare-ran.txt
ls: prepare-ran.txt: No such file or directory
~/D/n/s/scripts $ npm publish
[I hit CTRL-C when it asked for my 2fa]
~/D/n/s/scripts $ ls prepare-ran.txt
prepare-ran.txt
```

**Comment by ilya-lopukhin** [comment] 2023-11-09 14:45
npm 8.19.2

**prepublishOnly is not ran before the publish**

It's been five major versions and six years since it could not be fixed. I just want a hook to be ran before the publish, but all I see is issues asking for that indefinitely.

**Comment by wraithgar** [comment] 2023-11-09 14:59
Can't reproduce this so we're closing. Please note also that `prepublishOnly` does run before publish

```sh
~/D/n/s/scripts $ npm pkg set scripts.prepublishOnly='echo prepublishOnly'
~/D/n/s/scripts $ npm publish --dry-run

> @gar/scripts@0.0.0 prepublishOnly
> echo prepublishOnly

prepublishOnly
npm notice 
npm notice 📦  @gar/scripts@0.0.0
npm notice === Tarball Contents ===
...
npm notice Publishing to https://registry.npmjs.org/ with tag latest and default access (dry-run)
+ @gar/scripts@0.0.0
~/D/n/s/scripts $

**Closed as completed by wraithgar** 2023-11-09 14:59 UTC
Labels: Bug, Needs Triage, Release 9.x, Cannot Reproduce
