### ISSUE TITLE
[QUESTION] npm version doesn't create git commit/tag in subpackages

### ISSUE THREAD

**Issue by gmrchk** [npm/cli#1082] opened 2020-03-30 20:06 UTC
# What / Why
When running `npm version major` or any other `npm version` command in sub-package (eg. monorepo with `packages/subpackage` folder), git commit and git tag is not created for the git repository, while the `package.json` and `package-lock.json` files are updated in a subpackage. 
Is this expected behavior? 

## Where
* n/a

## Who
* n/a

## References
* n/a

**Comment by bradym** [comment] 2020-04-08 21:39
Looking into this myself today I came across https://github.com/npm/npm/issues/9111

**Comment by ZYinMD** [comment] 2020-07-07 02:56
Had this issue too. I think it's reasonable that a tag should not be created, because there may be multiple sub folders that contain different package.json files with different versions, so none of them should dictate the git tag. However, I do think it's reasonable to create a commit. Without the commit I'm left with a dirty tree after `npm version patch`. Maybe the commit message could be `` `${project name} {version}` ``

**Comment by gmrchk** [comment] 2020-07-10 12:29
@ZYinMD I think the same goes for the git tag, which could have the same format in general, so we would be on a safe side whether it's a monorepo containing more packages or just single package repo. But you're right, at least the commit would be enough.

**Comment by darcyclarke** [comment] 2021-06-02 21:55
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Comment by darcyclarke** [comment] 2021-06-02 22:07
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 22:07 UTC
Labels: Awaiting Information
