### ISSUE TITLE
[QUESTION] Why does “npm install git repo url” rewrite package-lock.json?

### ISSUE THREAD

**Issue by nabeel-nazir-confiz** [npm/cli#1108] opened 2020-04-03 20:23 UTC
I am running the `npm install` in a public GitHub [repo][1] and it has locked the express at `4.17.0` in `package-lock.json` file which is the correct behavior of `package-lock.json` file. 

However, when I execute `npm install git+https://github.com/nabeel-nazir confiz/package.lock.master.git` in an empty folder then a [package-lock.json][2] file created with the new version of express locked at `4.17.1`. I know there is a caret `^` sign in the source [package.json][3] but why the source [package-lock.json][4] is ignored this time?

My problem here is that when I execute `npm install git+https://github.com/nabeel-nazir confiz/package.lock.master.git` on the server it should create a `package-lock.json` file with express locked at `4.17.0` not with the `4.17.1` because the source [package-lock.json][2] file on the [repo][4] has locked the express on 4.17.0. 

Is there any way I can achieve this i.e `npm install git+https://github.com/nabeel-nazir confiz/package.lock.master.git` will consider the source [package-lock.json][2] file and should not ignore it?

I am using the following versions:

`npm version: 5.4.1`

`node version: 8.9.3`

`npm config get registry prints: https://registry.npmjs.org/`

`OS: Ubuntu 18.04`

Side note:
I have tried `npm install git+https://github.com/nabeel-nazir confiz/package.lock.master.git` with followings as well but the issue was same i.e. it locked the express at `4.17.1`

`npm version: 6.14.4`

`node version: 13.12.0`

`npm config get registry prints: https://registry.npmjs.org/`

`OS: Ubuntu 18.04`

Please comment If there is a need to provide more information on this question.

Thank you.
 

  [1]: https://github.com/nabeel-nazir-confiz/package.lock.master
  [2]: https://github.com/nabeel-nazir-confiz/package.lock.master/blob/master/more_files/package-lock.json#L103
  [3]: https://github.com/nabeel-nazir-confiz/package.lock.master/blob/master/package.json#L20
  [4]: https://github.com/nabeel-nazir-confiz/package.lock.master/blob/master/package-lock.json#L105

**Comment by aaaidan** [comment] 2021-03-13 04:24
I'm also encountering this behavior on npm 6. I can't find this documented or talked about much. I _assume_ it's an npm bug. It's certainly surprising behavior, to me at least, and I can't think of a good reason for it.

Interestingly, this weirdness is _not present_ on npm 7. That is, If you install a repo url dependency, fresh clones will correctly install at the changeset it was originally installed with. And `npm update` works as expected.

There is a workaround that might help those struggling with this: include the git changeset hash in the repo url in `package.json`. E.g.

```
"dependencies": {
  // ...
  "your-library": "git+ssh://your-library.org/repo.git#7ae2ba478365e3ec638442dd69bf5923298afd88"
}
```

The workaround is a bit ugly because `npm update` will not work as it does for other packages. You have to remember to manually find the changeset and replace it in package.json. If there are many repos like this, or you update the dependency often, you'll want to write a script.

**Comment by aaaidan** [comment] 2021-03-13 05:23
Just confirmed that this issue can be reproduced with file urls to local git repos, which is much easier to play around with than remote urls.

Assuming a "client" project at 
`/Users/me/absolute/path/to/client` 

and a `library` npm package and git repo at 
`/Users/me/absolute/path/to/test-library` ...

Let's install the library.

```sh
# in client project dir
npm i --save git+file:/Users/me/absolute/path/to/test-library
```

As expected, this installs to `node_modules`, and updates `package.json` and `package-lock.json`. In the lock there is something like:
```js
  // ...
  "dependencies": {
    "library": {
      "version": "git+file:/Users/me/absolute/path/to/test-library#26100954d25f88b1d214826e5da7411e254d4499"
    }
  }
  // ...
```

Then we update the main branch on the `test-library` repo. Any change at all.

```sh
# in library repo dir
echo wumpus-wumpus-wumpus > foo.txt
git add .
git commit -m "test commit"
```

Cleaning the client project and reinstalling ...

```sh
# in client project dir
rm -rf node_modules
npm i
```

At this point we expect there to be no change to the installed library dependency in `node_modules`, nor the `package-lock.json`. Let's check this...

```sh
# in client project dir

npm ls
# client@1.0.0 /Users/me/absolute/path/to/client
# └── library@1.0.0 (git+file:/Users/me/absolute/path/to/test-library#ae59d4fe4ee57befffaca36d269e553f6769f56f)

ls -1 node_modules/library/
# package.json
# foo.txt 
```

Unfortunately, the package lock and library has been updated, as if there was no lock for the library. 

On npm 7, this behaves as expected. It also behaves as expected on npm 6 for npm registry urls.

This seems very much like a bug to me. Can we confirm whether this is by design, or should we promote this issue to "bug"?

**Comment by darcyclarke** [comment] 2021-06-02 21:21
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 21:21 UTC
Labels: Awaiting Information, Release 6.x
