### ISSUE TITLE
[BUG] Unable to install packages because of Unable to resolve reference $@types/react-dom

### ISSUE THREAD

**Issue by Artur-** [npm/cli#7154] opened 2024-01-18 13:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

package.json:

```
{
  "name": "no-name",
  "license": "UNLICENSED",
  "type": "module",
  "dependencies": {
    "@hilla/react-crud": "2.5.5",
    "@types/react-dom": "18.2.15"
  },
  "overrides": {
    "@types/react-dom": "$@types/react-dom"
  }
}
```

```
npx npm@10.3.0 install
```
fails with
```
npm ERR! Unable to resolve reference $@types/react-dom
```

and the log says
```
69 verbose stack Error: Unable to resolve reference $@types/react-dom
69 verbose stack     at get spec [as spec] (/Users/artur/.npm/_npx/b66e65489868d75c/node_modules/npm/node_modules/@npmcli/arborist/lib/edge.js:202:15)
69 verbose stack     at #nodeFromEdge (/Users/artur/.npm/_npx/b66e65489868d75c/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1048:46)
69 verbose stack     at #loadPeerSet (/Users/artur/.npm/_npx/b66e65489868d75c/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1310:35)
69 verbose stack     at async #buildDepStep (/Users/artur/.npm/_npx/b66e65489868d75c/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:917:11)
69 verbose stack     at async Arborist.buildIdealTree (/Users/artur/.npm/_npx/b66e65489868d75c/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:196:7)
69 verbose stack     at async Promise.all (index 1)
69 verbose stack     at async Arborist.reify (/Users/artur/.npm/_npx/b66e65489868d75c/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:159:5)
69 verbose stack     at async Install.exec (/Users/artur/.npm/_npx/b66e65489868d75c/node_modules/npm/lib/commands/install.js:153:5)
69 verbose stack     at async module.exports (/Users/artur/.npm/_npx/b66e65489868d75c/node_modules/npm/lib/cli-entry.js:61:5)
```

putting debug logging into `/Users/artur/.npm/_npx/b66e65489868d75c/node_modules/npm/node_modules/@npmcli/arborist/lib/edge.js:202` reveals that 
```
this.#name === @types/react-dom
this.#from.sourceReference === null
this.#from.root.package  === {
  name: '@hilla/react-crud',
  version: '2.5.5',

```
so it tries to find the version of `@types/react-dom` from `@hilla/react-crud` which is just plainly the wrong package

### Expected Behavior

npm install works and it resolves the version of `@types/react-dom` from the given package.json

### Steps To Reproduce

See above

### Environment

- npm: 10.3.0
- Node.js: v20.9.0
- OS Name: macOS Sonoma 14.2.1
- System Model Name: Macbook M1
- npm config:
```ini
ignore-scripts = true 
```

**Comment by Artur-** [comment] 2024-01-18 13:11
npm 9.9.2 and 8.9.14 fails the same way

**Comment by Artur-** [comment] 2024-01-18 13:14
npm 8.2.0 works, npm 8.3.0 fails
all npm 9+ and 10+ versions fail

**Comment by Artur-** [comment] 2024-01-18 13:15
8.3.0 introduces overrides so it seems like it has never worked

**Comment by Artur-** [comment] 2024-01-18 13:23
The only relation between `@hilla/react-crud` and `@types/react-dom` I can find is that `@hilla/react-crud` depends on `@hilla/react-components` which has a peer dependency on `@types/react-dom`:

```
      "peerDependencies": {
        "@lit-labs/react": "^1.1.0",
        "@types/react": "^18.0.25",
        "@types/react-dom": "^18.0.8",
        "react": "^18.2.0",
        "react-dom": "^18.2.0"
      },
      "peerDependenciesMeta": {
        "@types/react": {
          "optional": true
        },
        "@types/react-dom": {
          "optional": true
        }
      }
```

**Comment by milaninfy** [comment] 2024-03-13 15:50
**Closing:** this looks to be similar if not a duplicate of an existing issue, #5730. If you believe your instance is unique, please provide further clarifying details.

**Closed as completed by milaninfy** 2024-03-13 15:50 UTC
Labels: Bug, Needs Triage, Duplicate, Release 10.x
