### ISSUE TITLE
[BUG] npx should not resolve environment variables

### ISSUE THREAD

**Issue by lachrist** [npm/cli#4039] opened 2021-11-11 10:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Environment variables are resolved by npx instead of being left intact to be dealt with by the invoked node executable.

```sh
> npx --version
8.1.3
> npx argv-to-list $HOME '$HOME' 'price = $100' 
/Users/soft # regular shell environment variable resolution 
/Users/soft # why does npx resolve environment variables?
price = 00  # *ugh* this is bad...
```

### Expected Behavior

```sh
> npx argv-to-list $HOME '$HOME' 'price = $100' 
/Users/soft
$HOME
price = $100
```

### Steps To Reproduce

cf above

### Environment

- npm: 8.1.3
- Node: 16.13.0
- OS: macOS 10.15.7 (19H1419)
- platform: Darwin 19.6.0
- npm config:
```ini
; "user" config from /Users/soft/.npmrc

@engine262:registry = "https://npm.pkg.github.com/" 
//npm.pkg.github.com/:_authToken = (protected) 
//registry.npmjs.org/:_authToken = (protected) 
node_gyp = "/Users/soft/.nvm/versions/node/v14.18.0/lib/node_modules/node-gyp/bin/node-gyp.js" 

; node bin location = /Users/soft/.nvm/versions/node/v16.13.0/bin/node
; cwd = /Users/soft/Desktop/swag
; HOME = /Users/soft
; Run `npm config ls -l` to show all defaults.
```

**Comment by ljharb** [comment] 2021-11-11 16:06
That’s not npx doing it, that’s the shell doing it. It’s how everything works, without exception, afaik.

**Comment by lachrist** [comment] 2021-11-11 16:11
Hi thanks for your answer.
No it is not?
Did you miss the quote?

```sh
> echo 'price = $100'
price = $100
```

**Comment by ljharb** [comment] 2021-11-11 16:13
Ah i see what you mean; the single-quoted part indeed shouldn’t be evaluated.

**Comment by zbigg** [comment] 2021-11-18 00:28
Note, that this is regression from node14/npm6

```
$ nvm use 16
Now using node v16.12.0 (npm v8.1.0)
$ npx node -e 'console.log("-$A-")'
--
$ nvm use 14
Now using node v14.17.5 (npm v6.14.14)
$ npx node -e 'console.log("-$A-")'
-$A-
```

Note, `v15.14.0 (npm v7.7.6)` also uses shell and thus resolves quotes _again_.

**Comment by zbigg** [comment] 2021-11-18 00:34
Possibly dup of https://github.com/npm/cli/issues/3600 which pinpoints exact release when it happened

**Comment by lachrist** [comment] 2021-11-18 08:24
Yes it is. A thought that for such a common problem there would already be an issue but I could not find it. I'm astonished that this does not draw more attention.

**Comment by wraithgar** [comment] 2022-03-16 14:42
**Closing:** this looks to be similar if not a duplicate of an existing issue, #3600. If you believe your instance is unique, please provide further clarifying details.

**Closed as completed by wraithgar** 2022-03-16 14:42 UTC
Labels: Release 8.x, Bug, Needs Triage
