### ISSUE TITLE
[BUG] dist files were not packed

### ISSUE THREAD

**Issue by aladdin-add** [npm/cli#4813] opened 2022-04-27 08:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

package.json :
```js
{
"name": "xxx",
"files": ["./dist/"]
}
```
running `npm publish`, the dist will not be packed.

### Expected Behavior

the dist should be packed.

I just found a workaround: `"files": ["dist/"]`

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm: 8.5.5
- Node.js: v16.15.0
- OS Name: macos
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by wraithgar** [comment] 2022-05-04 16:25
Closing as a duplicate of https://github.com/npm/cli/issues/4850

**Closed as completed by wraithgar** 2022-05-04 16:25 UTC
Labels: Release 8.x, Bug, Needs Triage
