### ISSUE TITLE
[BUG] Suggested package name doesn't cope with multiple spaces in the folder name

### ISSUE THREAD

**Issue by ChildishGiant** [npm/cli#1030] opened 2020-03-16 19:47 UTC
# What / Why

When initing a package a name is suggested but only the first space is replaced with a hypen

### Current Behavior
```
PS C:\Users\allie\Downloads\test with spaces> npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
package name: (test-with spaces)
Sorry, name can only contain URL-friendly characters.       
```                                                                                                                   

### Steps to Reproduce

* Create a folder with multiple spaces in its name
* Run `npm init`

### Expected Behavior

```
PS C:\Users\allie\Downloads\test with spaces> npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
package name: (test-with-spaces)
```

**Comment by cinderblock** [comment] 2021-03-10 21:00
```log
cameron@server:~$ npm --version
6.14.11
cameron@server:~$ node --version
v14.15.5
cameron@server:~$ mkdir 'test project with spaces'
cameron@server:~$ cd 'test project with spaces'
cameron@server:~/test project with spaces$ npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help init` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
package name: (test-project with spaces)
Sorry, name can only contain URL-friendly characters.
package name: (test-project with spaces) npm WARN init canceled
```

**Comment by darcyclarke** [comment] 2021-06-02 21:55
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Comment by darcyclarke** [comment] 2021-06-02 22:05
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 22:05 UTC
Labels: Bug

**Comment by cinderblock** [comment] 2021-06-02 22:18
This seems to be fixed in Npm `v7`
