### ISSUE TITLE
[DOCS] npm 10 docs list refers to upcoming changes in node 8

### ISSUE THREAD

**Issue by rotu** [npm/cli#6773] opened 2023-09-08 03:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This is a CLI Docs Problem, not another kind of Docs Problem.

- [X] This is a CLI Docs Problem.

### Description of Problem

npm 10 docs say:

> A thorough re-examination of the use cases, intention, behavior, and output of this command, is currently underway. Expect significant changes to at least the default human-readable npm ls output in npm v8.

### Affected URL

https://docs.npmjs.com/cli/v10/commands/npm-ls?v=true#note-design-changes-pending

**Comment by punndcoder28** [comment] 2023-09-08 17:55
Hi @rotu should this be removed since the current version is v10? I can work on removing the outdated documentation

**Comment by rotu** [comment] 2023-09-08 18:03
> Hi @rotu should this be removed since the current version is v10? I can work on removing the outdated documentation

I guess it should be removed, but probably also updated to reflect how the redesign shook out. I would guess that there were some changes since that also bear mention.

**Comment by punndcoder28** [comment] 2023-09-08 18:23
Understood. Could you point me to the relevant changes so that I can come up with a valid suggestion for the change?

**Comment by rotu** [comment] 2023-09-08 18:33
Wish I could, but I'm about as clueless as you. I would look here: https://github.com/npm/cli/blob/latest/CHANGELOG.md

Maybe @isaacs, who [wrote](https://github.com/npm/cli/blame/e340cf64ba31ef329a9049b60c32ffd0342cfb7d/docs/content/commands/npm-ls.md) that blurb can help.

**Comment by punndcoder28** [comment] 2023-09-09 13:36
Got it. Would going through the logical changes on the file `./lib/commands/ls.js` since that commit makes sense?

**Comment by milaninfy** [comment] 2024-12-05 17:44
**Closing:** this looks to be similar if not a duplicate of an existing issue, https://github.com/npm/documentation/issues/1365. If you believe your instance is unique, please provide further clarifying details.

**Closed as not planned by milaninfy** 2024-12-05 17:44 UTC
Labels: Documentation

**Comment by rotu** [comment] 2024-12-05 21:52
@milaninfy The bad docs exist here:

**Comment by rotu** [comment] 2024-12-05 21:56
@milaninfy The bad docs exist in this repo, so it is an issue in this repo:
https://github.com/npm/cli/blob/latest/docs/lib/content/commands/npm-ls.md

I believe this repo is the source of truth and https://github.com/npm/documentation/issues/1365 should be closed, since the npm/documentation repo is derived from here.
