### ISSUE TITLE
[BUG] `npm version` with workspace will not write new data back to `package-lock.json`

### ISSUE THREAD

**Issue by zthxxx** [npm/cli#4193] opened 2021-12-27 07:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

1. run `npm version` for workspaces with `-w <workspace>` args
2. see only changed `package.json` but not change lockfile

### Expected Behavior

run `npm version -w <workspace>` need adjust new version of workspace package in `package-lock.json`

As it said in [npm cli docs](https://docs.npmjs.com/cli/v8/commands/npm-version#description):

> Run this(`npm version`) in a package directory to bump the version and write the new data back to package.json, package-lock.json, and, if present, npm-shrinkwrap.json.

![image](https://user-images.githubusercontent.com/15135943/147444826-88da27d1-fda1-4168-be90-ad12f0ab0641.png)

### Steps To Reproduce

1. run `npm version` for workspaces with `-w <workspace>` args
2. see only changed `package.json` but not change lockfile
3. for verify whether lockfile need update, I have run `npm install`
4. yes, `lockfile` changed

![image](https://user-images.githubusercontent.com/15135943/147444082-36ffdffe-1d39-45fb-97e8-57de6088e163.png)

![image](https://user-images.githubusercontent.com/15135943/147444323-0dc07d79-e838-406b-8d2b-d2c65afa6f23.png)

### Environment

- npm: 8.3.0
- Node: 16.8.0
- OS: macOS 11.15
- platform: Mac
- npm config:

```
audit = false
fund = false
if-present = true
ignore-scripts = false
yes = true
```

**Comment by wraithgar** [comment] 2022-03-16 19:40
Closing as a duplicate of https://github.com/npm/cli/issues/3403

**Closed as completed by wraithgar** 2022-03-16 19:40 UTC
Labels: Release 8.x, Bug, Needs Triage

**Comment by zthxxx** [comment] 2022-03-16 19:44
My solution: move to using pnpm

**Comment by jonthomp** [comment] 2022-06-29 14:35
@wraithgar @fritzy please can this be re-opened? I don't think it is a duplicate of https://github.com/npm/cli/issues/3403.

The bug here is that running `npm version -w=<workspace>` does not update `package-lock.json`

**Comment by wraithgar** [comment] 2022-06-29 15:19
```sh
~/D/n/s/ws (main|✔) $ npm version minor -w workspace-a
workspace-a
v1.1.0

added 2 packages in 469ms
~/D/n/s/ws (main|✚2) $ git diff package-lock.json 
diff --git a/package-lock.json b/package-lock.json
index 119a66b..08a7625 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -32,7 +32,7 @@
       "link": true
     },
     "workspace-a": {
-      "version": "1.0.0",
+      "version": "1.1.0",
```

It does though?

**Comment by jonthomp** [comment] 2022-06-29 15:33
Sorry, I forgot to try it out on the latest npm, it does indeed work. We're currently on 8.5.5 where it does not. We will update. Thanks.

**Comment by surbhirverma** [comment] 2022-07-21 02:49
this doesn't seem to work if my packages are not published to registry. It throws error 404 not in registry. There is already a bug reported for this https://github.com/npm/cli/issues/3940
