### ISSUE TITLE
[BUG] `npm-run` runs in background if it cannot write logs

### ISSUE THREAD

**Issue by blaise-io** [npm/cli#6520] opened 2023-06-02 15:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When I run this command
```sh
$ sudo -u nobody sh -c 'npm run server'
```

I get the following output:

```log
> test@1.0.0 server
> node index.js

Server running at http://127.0.0.1:3000/
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /nonexistent
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/nonexistent'
npm ERR!  [Error: EACCES: permission denied, mkdir '/nonexistent'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/nonexistent'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! Log files were not written due to an error writing to the directory: /nonexistent/.npm/_logs
npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal
```

At this point my server is still running, as a background process. (as if I ran the command with `&`, but I did not.)

```sh
$ curl http://127.0.0.1:3000/
Hello World
```

_I know I can fix the EACCES by making sure the path is writable using `sudo -u nobody sh -c 'npm run server --cache .'`, my problem is that npm does not handle the error in an expected way_.

### Expected Behavior

I would expect that either 

A) The server stops and the process exits with an error code due to the errors being fatal, OR  
B) The process runs in the foreground ignoring non-fatal errors.

### Steps To Reproduce

```js
// index.js
const http = require('http');

const hostname = '127.0.0.1';
const port = 3000;

const server = http.createServer((req, res) => {
  res.statusCode = 200;
  res.setHeader('Content-Type', 'text/plain');
  res.end('Hello World');
});

server.listen(port, hostname, () => {
  console.log(`Server running at http://${hostname}:${port}/`);
});
```

```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "server": "node index.js"
  },
  "author": "Blaise",
  "license": "ISC"
}
```

Now run `sudo -u nobody sh -c 'npm run server'`, where `-u nobody` causes npm not to be able to write logs.

### Environment

- npm: 9.6.6
- Node.js: v20.2.0
- OS Name: Ubuntu 22.04.2 LTS (jammy)
- System Model Name: AWS EC2 / also on MacBook Air 2020 with Docker
- npm config:
```ini
; node bin location = /usr/bin/node
; node version = v20.2.0
; npm local prefix = /app
; npm version = 9.6.6
; cwd = /app
; HOME = /root
; Run `npm config ls -l` to show all defaults.
```

**Comment by myleshk** [comment] 2023-08-29 06:36
+1 and looks duplicate of #6245

**Comment by lukekarrys** [comment] 2024-05-14 02:06
This was fixed by https://github.com/npm/cli/commit/c7a592c9c400e73dd27264c11ad6459616023e4c as part of `npm@10.2.5`.

**Closed as completed by lukekarrys** 2024-05-14 02:06 UTC
Labels: Bug, Release 9.x
