### ISSUE TITLE
[BUG] npm ERR! Cannot destructure property 'name' of 'node' as it is null.

### ISSUE THREAD

**Issue by dmnsgn** [npm/cli#2548] opened 2021-01-26 11:27 UTC
Opening a new issue as requested by @isaacs https://github.com/npm/cli/issues/1832#issuecomment-766953686

### Current Behavior:

Installing a dependency from a GitHub URL fails.

### Expected Behavior:

Dependency is installed without error.

### Steps To Reproduce:

```sh
npm init -y
npm i -D git://github.com/GoogleChromeLabs/critters.git
```

Yields:

```sh
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install --cache=/Users/my-name/.npm/_cacache --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit
npm ERR! npm ERR! code ERESOLVE
npm ERR! npm ERR! Cannot destructure property 'name' of 'node' as it is null.
```

### Environment:
- OS: MacOS 10.15.6
- Node: v15.5.1
- npm: 7.4.0

**Comment by isaacs** [comment] 2021-01-29 01:05
There are two issues here.

As it happens, `critters` has a legit peer dependency issue that we can't unravel (or rather, _won't_, as it would require explosively expensive traversals, in the general case -- there is a solution, but finding it is too hard).

<details>
The general situation is like this:

```
a@1 -> b@>=1
a@2 -> b@>=2
a@3 -> b@>=3
b@1 -> c@>=1
b@2 -> c@>=2
c@1 -> d@>=1
c@2 -> d@>=2
c@3 -> d@>=3
```

Then the package depends on `{a: "1.x", d: "2.x"}`.
npm resolves `a@1.x` to `a@1.0.0`, and looks for `b@>=1`.
This resolves to `b@3.0.0`, and now it looks for `c@>=3`
This resolves to `c@3.0.0`, and now it looks for `d@>=3`, and _whoops_ there's no version available that meets the `d@>=3` requirement without conflicting with the root's dependency on `d@2.x`!

To solve this, we'd have to unwind the stack all the way back.  So, we can't get c@3.0.0, is there any other `c@>=3` that doesn't have the same problem?  No, so we can't use `b@3.0.0`, is there any other `b@>=1` that doesn't depend on a known-bad version of `c`? Yes, let's try `b@2.0.0`, then `c@2.0.0`, then `d@2.0.0`, and we have our answer.

However...

There may be 10 different packages in the stack, across 10 different majors, each with 100 different patch versions to check, and this becomes `O(n!)` in many cases, for a very large `n`.  Even pubgrub gives up eventually.

The solution, of course, is to just specify that you want `b@2` and `c@2` in your package.json, problem solved.
</details>

It would be easy enough for a human brain familiar with the code to see what deps need to be specified to give npm enough to go on.  However, how would you know what's happening with such a useless ERESOLVE error?

First issue is that it wasn't tracking the `dev` dependencies properly when creating the tentative/virtual tree to resolve against.  That's fixed by https://github.com/npm/arborist/pull/214, so we get a proper ERESOLVE with a "current" value.

Second issue, this is happening in a project that isn't even `critters`!  What are you supposed to do about it?  Probably better to just ignore `ERESOLVE` errors that happen among transitive devDependencies at git preparation time, so that's fixed in https://github.com/npm/pacote/pull/63

When those two land, this should work as expected.

**Comment by darcyclarke** [comment] 2021-02-02 08:01
@dmnsgn Closing: As I just tried this out & it seems to be working as of npm v7.5.1 - you can grab the latest via `npm i -g npm@7`.

**Closed as completed by darcyclarke** 2021-02-02 08:01 UTC
Labels: Release 7.x, Bug

**Comment by dmnsgn** [comment] 2021-02-02 21:23
I can confirm, error above doesn't show up anymore in 7.5.1 👍

**Comment by jcuna** [comment] 2021-02-02 21:30
Seeing this pop up for me on npm@7.5.2. 

~~~~
[Container] 2021/02/02 21:17:08 Running command npm install
--
91 | TypeError: Cannot destructure property `stat` of 'undefined' or 'null'.
92 | at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/node-gyp/lib/index.js:2:29)
93 | at Module._compile (module.js:652:30)
94 | at Object.Module._extensions..js (module.js:663:10)
95 | at Module.load (module.js:565:32)
96 | at tryModuleLoad (module.js:505:12)
97 | at Function.Module._load (module.js:497:3)
98 | at Module.require (module.js:596:17)
99 | at require (internal/module.js:11:18)
100 | at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script-pkg.js:4:55)
101 | at Module._compile (module.js:652:30)
102 | /usr/local/lib/node_modules/npm/node_modules/@npmcli/config/lib/index.js:163
103 | throw new Error('call config.load() before reading values')

~~~~

**Comment by jcuna** [comment] 2021-02-02 21:41
Downgrading to 7.5.1 and still getting this error.

~~~

[Container] 2021/02/02 21:37:41 Running command npm install
--
91 | TypeError: Cannot destructure property `stat` of 'undefined' or 'null'.
92 | at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/node-gyp/lib/index.js:2:29)
93 | at Module._compile (module.js:652:30)
94 | at Object.Module._extensions..js (module.js:663:10)
95 | at Module.load (module.js:565:32)
96 | at tryModuleLoad (module.js:505:12)
97 | at Function.Module._load (module.js:497:3)
98 | at Module.require (module.js:596:17)
99 | at require (internal/module.js:11:18)
100 | at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script-pkg.js:4:55)
101 | at Module._compile (module.js:652:30)
102 | /usr/local/lib/node_modules/npm/node_modules/@npmcli/config/lib/index.js:163
103 | throw new Error('call config.load() before reading values')
104 | ^
105 |  
106 | Error: call config.load() before reading values
107 | at Config.get (/usr/local/lib/node_modules/npm/node_modules/@npmcli/config/lib/index.js:163:13)
108 | at process.errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:171:32)
109 | at emitOne (events.js:116:13)
110 | at process.emit (events.js:211:7)
111 | at process._fatalException (bootstrap_node.js:375:26)


~~~

**Comment by jcuna** [comment] 2021-02-02 21:42
I'll open a new issue. Thanks

**Comment by simoncpu** [comment] 2021-03-13 16:03
I am experiencing this on npm v7.6.1 as well: I ran `npm update` on AWS-CDK.

```132 error code ERESOLVE
133 verbose stack TypeError: Cannot destructure property 'name' of 'node' as it is null.
133 verbose stack     at printNode (/Users/simoncpu/.npm-packages/lib/node_modules/npm/lib/utils/explain-dep.js:29:5)
133 verbose stack     at explainNode (/Users/simoncpu/.npm-packages/lib/node_modules/npm/lib/utils/explain-dep.js:13:3)
133 verbose stack     at explainEresolve (/Users/simoncpu/.npm-packages/lib/node_modules/npm/lib/utils/explain-eresolve.js:24:24)
133 verbose stack     at report (/Users/simoncpu/.npm-packages/lib/node_modules/npm/lib/utils/explain-eresolve.js:50:3)
133 verbose stack     at module.exports (/Users/simoncpu/.npm-packages/lib/node_modules/npm/lib/utils/error-message.js:22:24)
133 verbose stack     at errorHandler (/Users/simoncpu/.npm-packages/lib/node_modules/npm/lib/utils/error-handler.js:175:15)
133 verbose stack     at /Users/simoncpu/.npm-packages/lib/node_modules/npm/lib/npm.js:114:9
134 verbose cwd /my/directory/something/something
135 verbose Darwin 20.3.0
136 verbose argv "/Users/simoncpu/.n/bin/node" "/Users/simoncpu/.npm-packages/bin/npm" "update"
137 verbose node v14.16.0
138 verbose npm  v7.6.1
139 error Cannot destructure property 'name' of 'node' as it is null.
140 verbose exit 1
```

**Comment by gnapse** [comment] 2022-02-23 18:58
I still experience this in npm 7.21.0

<img width="782" alt="image" src="https://user-images.githubusercontent.com/15199/155388119-34080ba8-34da-4d77-867a-47614f9b0db3.png">

<details>
<summary>
Here's the log file
</summary>

```
0 verbose cli [
0 verbose cli   '/Users/ernesto/.fnm/node-versions/v16.8.0/installation/bin/node',
0 verbose cli   '/var/folders/tm/svfmwn415yx10pvtrg0c577w0000gp/T/fnm_multishell_48251_1645640939564/bin/npm',
0 verbose cli   'install'
0 verbose cli ]
1 info using npm@7.21.0
2 info using node@v16.8.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/Users/ernesto/.fnm/node-versions/v16.8.0/installation/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/ernesto/code/doist/reactist/.npmrc Completed in 1ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:/Users/ernesto/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/Users/ernesto/.fnm/node-versions/v16.8.0/installation/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 8ms
19 timing npm:load:configload Completed in 8ms
20 timing npm:load:setTitle Completed in 13ms
21 timing npm:load:setupLog Completed in 0ms
22 timing config:load:flatten Completed in 2ms
23 timing npm:load:cleanupLog Completed in 2ms
24 timing npm:load:configScope Completed in 0ms
25 timing npm:load:projectScope Completed in 0ms
26 timing npm:load Completed in 26ms
27 timing arborist:ctor Completed in 1ms
28 timing idealTree:init Completed in 989ms
29 timing idealTree:userRequests Completed in 0ms
30 silly idealTree buildDeps
31 silly fetch manifest @doist/eslint-config@^7.1.0
32 timing arborist:ctor Completed in 0ms
33 http fetch GET 200 https://registry.npmjs.org/@doist%2feslint-config 886ms (cache hit)
34 silly fetch manifest @typescript-eslint/eslint-plugin@^4.33.0
35 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2feslint-plugin 9ms (cache hit)
36 silly fetch manifest @typescript-eslint/parser@^4.33.0
37 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2fparser 10ms (cache hit)
38 silly fetch manifest eslint@^7.32.0
39 http fetch GET 200 https://registry.npmjs.org/eslint 8ms (cache hit)
40 silly fetch manifest eslint-plugin-import@^2.25.3
41 http fetch GET 200 https://registry.npmjs.org/eslint-plugin-import 3ms (cache hit)
42 silly fetch manifest eslint-plugin-prettier@^3.1.4
43 http fetch GET 200 https://registry.npmjs.org/eslint-plugin-prettier 2ms (cache hit)
44 silly fetch manifest prettier@2.5.1
45 http fetch GET 200 https://registry.npmjs.org/prettier 1ms (cache hit)
46 silly fetch manifest eslint-plugin-react@^7.23.2
47 http fetch GET 200 https://registry.npmjs.org/eslint-plugin-react 2ms (cache hit)
48 silly fetch manifest eslint-plugin-react-hooks@^4.3.0
49 http fetch GET 200 https://registry.npmjs.org/eslint-plugin-react-hooks 4ms (cache hit)
50 silly fetch manifest eslint-plugin-simple-import-sort@^7.0.0
51 http fetch GET 200 https://registry.npmjs.org/eslint-plugin-simple-import-sort 4ms (cache hit)
52 silly placeDep ROOT @doist/eslint-config@7.1.0 REPLACE for: @doist/reactist@11.1.0 want: ^7.1.0
53 silly placeDep ROOT @typescript-eslint/eslint-plugin@4.33.0 OK for: @doist/eslint-config@7.1.0 want: ^4.33.0
54 silly placeDep ROOT @typescript-eslint/parser@4.33.0 OK for: @typescript-eslint/eslint-plugin@4.33.0 want: ^4.0.0
55 timing idealTree Completed in 2073ms
56 timing command:install Completed in 2091ms
57 verbose stack Error: could not resolve
57 verbose stack     at PlaceDep.failPeerConflict (/Users/ernesto/.fnm/node-versions/v16.8.0/installation/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:470:25)
57 verbose stack     at PlaceDep.place (/Users/ernesto/.fnm/node-versions/v16.8.0/installation/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:187:21)
57 verbose stack     at new PlaceDep (/Users/ernesto/.fnm/node-versions/v16.8.0/installation/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:68:10)
57 verbose stack     at PlaceDep.placeInTree (/Users/ernesto/.fnm/node-versions/v16.8.0/installation/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:342:26)
57 verbose stack     at PlaceDep.place (/Users/ernesto/.fnm/node-versions/v16.8.0/installation/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:203:10)
57 verbose stack     at new PlaceDep (/Users/ernesto/.fnm/node-versions/v16.8.0/installation/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:68:10)
57 verbose stack     at /Users/ernesto/.fnm/node-versions/v16.8.0/installation/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:890:31
57 verbose stack     at Array.map (<anonymous>)
57 verbose stack     at Arborist.[buildDepStep] (/Users/ernesto/.fnm/node-versions/v16.8.0/installation/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:890:8)
57 verbose stack     at async Arborist.buildIdealTree (/Users/ernesto/.fnm/node-versions/v16.8.0/installation/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:206:7)
58 verbose cwd /Users/ernesto/code/doist/reactist
59 verbose Darwin 21.3.0
60 verbose argv "/Users/ernesto/.fnm/node-versions/v16.8.0/installation/bin/node" "/var/folders/tm/svfmwn415yx10pvtrg0c577w0000gp/T/fnm_multishell_48251_1645640939564/bin/npm" "install"
61 verbose node v16.8.0
62 verbose npm  v7.21.0
63 error code ERESOLVE
64 verbose stack TypeError: Cannot destructure property 'name' of 'node' as it is undefined.
64 verbose stack     at printNode (/Users/ernesto/.fnm/node-versions/v16.8.0/installation/lib/node_modules/npm/lib/utils/explain-dep.js:34:5)
64 verbose stack     at explainNode (/Users/ernesto/.fnm/node-versions/v16.8.0/installation/lib/node_modules/npm/lib/utils/explain-dep.js:16:3)
64 verbose stack     at explain (/Users/ernesto/.fnm/node-versions/v16.8.0/installation/lib/node_modules/npm/lib/utils/explain-eresolve.js:38:16)
64 verbose stack     at report (/Users/ernesto/.fnm/node-versions/v16.8.0/installation/lib/node_modules/npm/lib/utils/explain-eresolve.js:56:3)
64 verbose stack     at module.exports (/Users/ernesto/.fnm/node-versions/v16.8.0/installation/lib/node_modules/npm/lib/utils/error-message.js:21:24)
64 verbose stack     at exitHandler (/Users/ernesto/.fnm/node-versions/v16.8.0/installation/lib/node_modules/npm/lib/utils/exit-handler.js:152:19)
64 verbose stack     at /Users/ernesto/.fnm/node-versions/v16.8.0/installation/lib/node_modules/npm/lib/npm.js:156:9
65 verbose cwd /Users/ernesto/code/doist/reactist
66 verbose Darwin 21.3.0
67 verbose argv "/Users/ernesto/.fnm/node-versions/v16.8.0/installation/bin/node" "/var/folders/tm/svfmwn415yx10pvtrg0c577w0000gp/T/fnm_multishell_48251_1645640939564/bin/npm" "install"
68 verbose node v16.8.0
69 verbose npm  v7.21.0
70 error Cannot destructure property 'name' of 'node' as it is undefined.
71 verbose exit 1
```
</details>

**Comment by vincentbernat** [comment] 2025-06-02 06:41
I am also running in this bug with npm 9.2.0.

```
58 verbose stack TypeError: Cannot destructure property 'name' of 'node' as it is undefined.
58 verbose stack     at printNode (/usr/share/nodejs/npm/lib/utils/explain-dep.js:36:5)
58 verbose stack     at explainNode (/usr/share/nodejs/npm/lib/utils/explain-dep.js:17:3)
58 verbose stack     at explain (/usr/share/nodejs/npm/lib/utils/explain-eresolve.js:39:16)
58 verbose stack     at report (/usr/share/nodejs/npm/lib/utils/explain-eresolve.js:63:21)
58 verbose stack     at module.exports (/usr/share/nodejs/npm/lib/utils/error-message.js:27:37)
58 verbose stack     at exitHandler (/usr/share/nodejs/npm/lib/utils/exit-handler.js:184:47)
58 verbose stack     at module.exports (/usr/share/nodejs/npm/lib/cli.js:144:12)
```

Adding a few `console.log()`, I see that yes, `node` is undefined. It comes from (in `explain-eresolve.js`):

```js
  if (peerConflict) {
    const heading = '\nConflicting peer dependency:'
    const pc = explainNode(peerConflict.peer, depth, color)
    out.push(heading + ' ' + pc)
  }
```

peerConflict object is:

```js
{
  name: '@typescript-eslint/parser',
  version: '8.29.0',
  location: 'node_modules/@typescript-eslint/parser',
  isWorkspace: false,
  dependents: [
    {
      type: 'peer',
      name: '@typescript-eslint/parser',
      spec: '^8.33.0',
      error: 'INVALID',
      from: [Object]
    }
  ]
}
```

So, no `peer` property.

To reproduce:
```
git clone https://github.com/akvorado/akvorado.git
cd akvorado/console/frontend
git checkout dependabot/npm_and_yarn/console/frontend/typescript-eslint/eslint-plugin-8.33.0
npm install --save-dev @typescript-eslint/eslint-plugin@8.33.0 @typescript-eslint/parser@8.33.0
```
