### ISSUE TITLE
npm i changing package-lock.json

### ISSUE THREAD

**Issue by SiddharthaMishra-dev** [npm/cli#7720] opened 2024-08-13 11:45 UTC
When I cloned the repo , delete its package-lock.json file and then use `npm i`, in the package-lock.json it is showing typescript version 5.5.4 and node engine >=14.17

![image](https://github.com/user-attachments/assets/12b8a1c5-957e-4068-a8cc-ca3fcaea69b0)

but I again use `npm i` package-lock changes typescript version to 4.9.5.

![image](https://github.com/user-attachments/assets/51894555-0f10-4689-8b6c-c89c03d9b23f)

 I haven't add any node package nor remove any package but don't know it why it is causing problem. This change is breaking the code in the deployment phase in Amplify.

**Comment by SiddharthaMishra-dev** [comment] 2024-08-13 13:37
I have tried second step. On first install it is working perfect. But if I pushed the code and someone else is using `npm i` , it is updating the typescript version in package-lock

Also I am not using typescript in the project. It is from one of the dependency library.

This is package.json
![image](https://github.com/user-attachments/assets/2d95af6b-ee0e-494a-b396-6f2a8c2587ae)

**Comment by milaninfy** [comment] 2024-08-13 14:50
@SiddharthaMishra-dev. Please update or refile this issue with all the details requested in our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).

**Comment by milaninfy** [comment] 2024-08-19 14:23
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.

**Closed as not planned by milaninfy** 2024-08-19 14:23 UTC
