### ISSUE TITLE
[BUG] Unhelpful error installing from pr if wrong pr number is used

### ISSUE THREAD

**Issue by isaacs** [npm/cli#3179] opened 2021-05-03 00:20 UTC
I am pretty sure this is going to affect _any_ install from a git remote with a ref that's not found in the origin.  But I encountered it trying to install a PR, and haven't investigated further.

Instead of "remote reference not found in git repository", or some other helpful thing, it does this.

### Current Behavior:

Pacote fails with a git folder issue.

```
$ npm i npm/pacote#pull/55
npm ERR! code 128
npm ERR! command failed
npm ERR! command git clone --mirror -q ssh://git@github.com/npm/pacote.git /Users/isaacs/.npm/_cacache/tmp/git-clone-00c3d7a2/.git
npm ERR! fatal: destination path '/Users/isaacs/.npm/_cacache/tmp/git-clone-00c3d7a2/.git' already exists and is not an empty directory.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/isaacs/.npm/_logs/2021-05-03T00_17_29_111Z-debug.log
```

### Expected Behavior:

Report that `pull/55` isn't a thing that exists in the npm/pacote repository.

### Environment:
macOS, npm 7.11.2

My bet is that this is a bug in either `pacote` or `@npmcli/git`, but I haven't dug any further into it as yet.

**Comment by isaacs** [comment] 2021-05-03 00:21
npm debug log

```
0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'i',
0 verbose cli   'npm/pacote#pull/55'
0 verbose cli ]
1 info using npm@7.11.2
2 info using node@v16.0.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/Users/isaacs/dev/npm/cli/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/isaacs/dev/npm/cli/git-commit-spoofing/test/.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/Users/isaacs/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 7ms
19 timing npm:load:configload Completed in 7ms
20 timing npm:load:setTitle Completed in 29ms
21 timing npm:load:setupLog Completed in 1ms
22 timing npm:load:cleanupLog Completed in 2ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 0ms
25 timing npm:load Completed in 40ms
26 timing config:load:flatten Completed in 2ms
27 timing arborist:ctor Completed in 0ms
28 timing idealTree:init Completed in 117ms
29 timing arborist:ctor Completed in 0ms
30 timing idealTree Completed in 14845ms
31 timing command:install Completed in 14854ms
32 verbose stack Error: command failed
32 verbose stack     at ChildProcess.<anonymous> (/Users/isaacs/dev/npm/cli/node_modules/@npmcli/promise-spawn/index.js:64:27)
32 verbose stack     at ChildProcess.emit (node:events:365:28)
32 verbose stack     at maybeClose (node:internal/child_process:1067:16)
32 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
33 verbose cwd /Users/isaacs/dev/npm/cli/git-commit-spoofing/test
34 verbose Darwin 20.3.0
35 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "npm/pacote#pull/55"
36 verbose node v16.0.0
37 verbose npm  v7.11.2
38 error code 128
39 error command failed
40 error command git clone --mirror -q ssh://git@github.com/npm/pacote.git /Users/isaacs/.npm/_cacache/tmp/git-clone-00c3d7a2/.git
41 error fatal: destination path '/Users/isaacs/.npm/_cacache/tmp/git-clone-00c3d7a2/.git' already exists and is not an empty directory.
42 verbose exit 128
```

**Comment by ljharb** [comment] 2021-05-03 00:37
That ref should exist (if the PR does) in every GitHub repo - it just might not be fetched by default.

**Comment by darcyclarke** [comment] 2021-06-11 18:51
Closing as a duplicate of https://github.com/npm/cli/issues/3149 as the fix should be similar (ie. check git refs for existence & throw a more meaningful/helpful error)

**Closed as completed by darcyclarke** 2021-06-11 18:51 UTC
Labels: Release 7.x, Bug, Duplicate
