### ISSUE TITLE
[BUG] npm install crashes

### ISSUE THREAD

**Issue by vindi-r** [npm/cli#905] opened 2020-02-21 10:37 UTC
# What / Why
I cant do npm install on Linux

## When
Today

## Where
Ubuntu 18
[log.txt](https://github.com/npm/cli/files/4235597/log.txt)
vindi@DESKTOP-38F3B70:/mnt/c/Users/vox-vindi/Desktop$ node -v
v13.9.0
vindi@DESKTOP-38F3B70:/mnt/c/Users/vox-vindi/Desktop$ npm -v
6.13.7

### Current Behavior

* n/a

### Steps to Reproduce

* n/a

### Expected Behavior

* n/a

## Who

* n/a

## References

* n/a

**Comment by DanielRuf** [comment] 2020-02-23 00:06
Duplicate of #417

**Comment by vindi-r** [comment] 2020-02-24 14:54
@DanielRuf in my test laptop sometimes install goes correct, sometimes falls.
Will be usefull if I attach another logs (with sucess and fail attempts) ?

**Comment by DanielRuf** [comment] 2020-02-24 15:15
> @DanielRuf in my test laptop sometimes install goes correct, sometimes falls.
> Will be usefull if I attach another logs (with sucess and fail attempts) ?

Did you already try to clear the cache with `npm cache clean --force`.

**Comment by vindi-r** [comment] 2020-02-25 08:50
sure, every install accompanied by cache clean

`
  - npm cache verify
  - npm cache clean --force
  - npm --loglevel verbose --prefer-online install
`

**Comment by DanielRuf** [comment] 2020-02-25 09:22
Can you provide some info about your npm version and node version?
In general the error message is the same and it is the same issue like in #417 which is an umbrella issue to find out what causes this. Is your application working after this?

**Comment by vindi-r** [comment] 2020-02-25 11:16
sure, my app works OK. But I neet run npm i multiple times to complete build.

`
vindi@DESKTOP-38F3B70:~$ node -v
v13.9.0
vindi@DESKTOP-38F3B70:~$ npm -v
6.13.7
vindi@DESKTOP-38F3B70:~$
`

**Comment by vindi-r** [comment] 2020-02-25 11:17
sure, my app works OK. But I neet run npm i multiple times to complete build.

```
vindi@DESKTOP-38F3B70:~$ node -v
v13.9.0 
vindi@DESKTOP-38F3B70:~$ npm -v 
6.13.7
```

**Comment by darcyclarke** [comment] 2021-06-02 21:55
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 21:55 UTC
Labels: Bug
