### ISSUE TITLE
[BUG] code ERR_SOCKET_TIMEOUT with NPM 8.3.1 to NPM 8.5.0

### ISSUE THREAD

**Issue by CodeTroopers** [npm/cli#4414] opened 2022-02-15 14:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I use a private repository on Nexus, **my configuration works with NPM 8.3.0**
From a docker image node:lts, I run the command:
`npm ci --maxsockets=3`
This fails with NPM 8.3.1 to NPM 8.5.0 :
```
npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! errno ERR_SOCKET_TIMEOUT
npm ERR! network request to https://nexus.biosency.com/repository/boraconnect-front/yargs/-/yargs-13.1.0.tgz failed, reason: Socket timeout
```
If I  rollback to NPM 8.3.0, It works
There is no cache since it's a virtual machine with a gitlab runner without cache configration

### Expected Behavior

Modules are installed from my private repository on Nexus

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm: 8.5.0
- Node.js: 16.14.0
- npm config:
```ini
; "user" config from /root/.npmrc

//nexus.biosency.com/repository/boraconnect-front/:_password = (protected) 
//nexus.biosency.com/repository/boraconnect-front/:username = "npm" 
registry = "https://nexus.biosency.com/repository/boraconnect-front/" 

```

**Comment by codan84** [comment] 2022-02-23 16:48
I had the same issue on npm `v8.1.0`, `v8.5.0`. Issue is gone on exactly the same setup with npm `v8.5.1`. This is not my network issue, this is something in npm itself.

**Comment by fritzy** [comment] 2022-02-24 20:30
**Closing:** this looks to be similar if not a duplicate of an existing issue, #3078 . If you believe your instance is unique, please provide further clarifying details.

As an FYI, we're actively working this issue, so thank you for the additional information.

**Closed as completed by fritzy** 2022-02-24 20:30 UTC
Labels: Release 8.x, Bug, Needs Triage
