### ISSUE TITLE
[BUG] npm7 doesn't install packages that are only found on GitHub

### ISSUE THREAD

**Issue by vlilloh** [npm/cli#1879] opened 2020-09-30 06:02 UTC
### Current Behavior:

It doesn't install packages that are only found on GitHub.

### Expected Behavior:

It should install packages that are only found on GitHub.

### Steps To Reproduce:

1. With this config in `package.json`, e.g.: `"dependencies": { "@gastromatic/react-dates": "1.0.7" }`
2. With this config in `.npmrc`, e.g.: `@gastromatic:registry=https://npm.pkg.github.com`
3. Run 'npx npm@7.0.0-rc.0 i'
4. See error:
```
npm ERR! code EINTEGRITY
npm ERR! sha512-BUAcX26JrA+RHhaVkOCWAK95ffzA4uXgkQyl/TD+yYbRvxK9BpXjqKNxTSVzKosxXHdWPSyKUkl6fDEg3RPg4w== integrity checksum failed when using sha512: wanted sha512-BUAcX26JrA+RHhaVkOCWAK95ffzA4uXgkQyl/TD+yYbRvxK9BpXjqKNxTSVzKosxXHdWPSyKUkl6fDEg3RPg4w== but got sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==. (0 bytes)
```

With these steps npm6 does install packages that are only found on GitHub.

### Environment:

- OS: MacOS 10.15.7
- Node: 14.13.0
- npm: 7.0.0-rc.0

**Comment by darcyclarke** [comment] 2020-10-01 21:51
Closing: I believe this is a duplicate of https://github.com/npm/cli/issues/1800

**Closed as completed by darcyclarke** 2020-10-01 21:51 UTC
Labels: Release 7.x, Bug, Duplicate

**Comment by farhansolodev** [comment] 2022-03-18 23:20
Did this ever get fixed for you? I've been trying to run:

`npx piuccio/cowsay hello world` and `npx github:piuccio/cowsay hello world`
and both just quietly exit after a run of the progress bar.

In contrast, `npx cowsay hello world` works fine.

Update:
Downgrading npm to v6 by running `npm install -g npm@6` fixed my issue.
