### ISSUE TITLE
[BUG] Installing certain packages is extremely slow

### ISSUE THREAD

**Issue by bbrk24** [npm/cli#6391] opened 2023-04-22 22:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [ ] I am using the latest npm

### Current Behavior

Currently, my package.json specifies `"typescript": "^5.0.2"`. When I change it to say `"typescript": "^5.0.3"`, npm 9 spins for 4:28 before deciding it doesn't exist. For comparison, npm 8 installs it with no problem in 0:44.

Ironically, I can't upgrade npm to 9.6 due to this issue: npm 9.5.1 times out when I run `npm i -g npm`.

### Expected Behavior

npm 9 should be able to locate and download these versions with similar performance to npm 8.

### Steps To Reproduce

1. Have a project with a v2 lockfile and TypeScript 5.0.2
2. Install node 18.16.0 with npm 9.5.1 
3. Update the package.json to request TypeScript 5.0.3 or newer
4. Run `npm i`

### Environment

- npm: 9.5.1
- Node.js: 18.16.0
- OS Name: Windows 10
- System Model Name: Maingear Vector 2
- npm config:
```ini
; "user" config from C:\Users\bbrk2\.npmrc

//registry.npmjs.org/:_authToken = (protected) 

; node bin location = C:\Users\bbrk2\.nvm\versions\node\v18.16.0\bin\node.exe
; node version = v18.16.0
; npm local prefix = C:\Users\bbrk2\[REDACTED]
; npm version = 9.5.1
; cwd = C:\Users\bbrk2\[REDACTED]
; HOME = C:\Users\bbrk2
; Run `npm config ls -l` to show all defaults.
```

**Comment by bbrk24** [comment] 2023-04-22 22:53
<details>
  <summary>Full log from <code>npm i -g npm</code></summary>
  <pre>0 verbose cli C:\Users\bbrk2\.nvm\versions\node\v18.16.0\bin\node.exe C:\Users\bbrk2\.nvm\versions\node\v18.16.0\bin\node_modules\npm\bin\npm-cli.js
1 info using npm@9.5.1
2 info using node@v18.16.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:C:\Users\bbrk2\.nvm\versions\node\v18.16.0\bin\node_modules\npm\npmrc Completed in 0ms
6 timing config:load:builtin Completed in 0ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:C:\Users\bbrk2\.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:C:\Users\bbrk2\.nvm\versions\node\v18.16.0\bin\etc\npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:setEnvs Completed in 1ms
15 timing config:load Completed in 9ms
16 timing npm:load:configload Completed in 9ms
17 timing npm:load:mkdirpcache Completed in 0ms
18 timing npm:load:mkdirplogs Completed in 1ms
19 verbose title npm i npm
20 verbose argv "i" "--global" "npm"
21 timing npm:load:setTitle Completed in 1ms
22 timing config:load:flatten Completed in 2ms
23 timing npm:load:display Completed in 3ms
24 verbose logfile logs-max:10 dir:C:\Users\bbrk2\AppData\Local\npm-cache\_logs\2023-04-22T22_44_17_394Z-
25 verbose logfile C:\Users\bbrk2\AppData\Local\npm-cache\_logs\2023-04-22T22_44_17_394Z-debug-0.log
26 timing npm:load:logFile Completed in 5ms
27 timing npm:load:timers Completed in 0ms
28 timing npm:load:configScope Completed in 0ms
29 timing npm:load Completed in 20ms
30 timing config:load:flatten Completed in 0ms
31 silly logfile start cleaning logs, removing 5 files
32 silly logfile done cleaning log files
33 http fetch GET 200 https://registry.npmjs.org/npm 133241ms (cache stale)
34 timing arborist:ctor Completed in 0ms
35 timing idealTree:init Completed in 6ms
36 timing idealTree:userRequests Completed in 1ms
37 silly idealTree buildDeps
38 silly fetch manifest npm@*
39 http fetch GET 200 https://registry.npmjs.org/npm 133121ms (cache stale)
40 silly placeDep ROOT npm@9.6.4 OK for:  want: *
41 timing idealTree:#root Completed in 133157ms
42 timing idealTree:node_modules/npm Completed in 0ms
43 timing idealTree:buildDeps Completed in 133159ms
44 timing idealTree:fixDepFlags Completed in 0ms
45 timing idealTree Completed in 133169ms
46 timing reify:loadTrees Completed in 133317ms
47 timing reify:diffTrees Completed in 3ms
48 silly reify mark retired [
48 silly reify   'C:\\Users\\bbrk2\\.nvm\\versions\\node\\v18.16.0\\bin\\node_modules\\npm',
48 silly reify   'C:\\Users\\bbrk2\\.nvm\\versions\\node\\v18.16.0\\bin\\npm',
48 silly reify   'C:\\Users\\bbrk2\\.nvm\\versions\\node\\v18.16.0\\bin\\npm.cmd',
48 silly reify   'C:\\Users\\bbrk2\\.nvm\\versions\\node\\v18.16.0\\bin\\npm.ps1',
48 silly reify   'C:\\Users\\bbrk2\\.nvm\\versions\\node\\v18.16.0\\bin\\npx',
48 silly reify   'C:\\Users\\bbrk2\\.nvm\\versions\\node\\v18.16.0\\bin\\npx.cmd',
48 silly reify   'C:\\Users\\bbrk2\\.nvm\\versions\\node\\v18.16.0\\bin\\npx.ps1'
48 silly reify ]
49 silly reify moves {
49 silly reify   'C:\\Users\\bbrk2\\.nvm\\versions\\node\\v18.16.0\\bin\\node_modules\\npm': 'C:\\Users\\bbrk2\\.nvm\\versions\\node\\v18.16.0\\bin\\node_modules\\.npm-Hd0fT2a4',
49 silly reify   'C:\\Users\\bbrk2\\.nvm\\versions\\node\\v18.16.0\\bin\\npm': 'C:\\Users\\bbrk2\\.nvm\\versions\\node\\v18.16.0\\bin\\.npm-Bkr6bjpw',
49 silly reify   'C:\\Users\\bbrk2\\.nvm\\versions\\node\\v18.16.0\\bin\\npm.cmd': 'C:\\Users\\bbrk2\\.nvm\\versions\\node\\v18.16.0\\bin\\.npm.cmd-Q3GuklLb',
49 silly reify   'C:\\Users\\bbrk2\\.nvm\\versions\\node\\v18.16.0\\bin\\npm.ps1': 'C:\\Users\\bbrk2\\.nvm\\versions\\node\\v18.16.0\\bin\\.npm.ps1-Odga2puQ',
49 silly reify   'C:\\Users\\bbrk2\\.nvm\\versions\\node\\v18.16.0\\bin\\npx': 'C:\\Users\\bbrk2\\.nvm\\versions\\node\\v18.16.0\\bin\\.npx-aCkU9Xy2',
49 silly reify   'C:\\Users\\bbrk2\\.nvm\\versions\\node\\v18.16.0\\bin\\npx.cmd': 'C:\\Users\\bbrk2\\.nvm\\versions\\node\\v18.16.0\\bin\\.npx.cmd-Y8079OUI',
49 silly reify   'C:\\Users\\bbrk2\\.nvm\\versions\\node\\v18.16.0\\bin\\npx.ps1': 'C:\\Users\\bbrk2\\.nvm\\versions\\node\\v18.16.0\\bin\\.npx.ps1-nRStF7EX'
49 silly reify }
50 timing reify:retireShallow Completed in 10ms
51 timing reify:createSparse Completed in 0ms
52 silly tarball no local data for npm@https://registry.npmjs.org/npm/-/npm-9.6.4.tgz. Extracting by manifest.
53 timing reify:rollback:createSparse Completed in 1ms
54 timing reify:rollback:retireShallow Completed in 5ms
55 timing command:i Completed in 399792ms
56 verbose type system
57 verbose stack FetchError: request to https://registry.npmjs.org/npm/-/npm-9.6.4.tgz failed, reason: connect ETIMEDOUT 2606:4700::6810:1a23:443
57 verbose stack     at ClientRequest.<anonymous> (C:\Users\bbrk2\.nvm\versions\node\v18.16.0\bin\node_modules\npm\node_modules\minipass-fetch\lib\index.js:130:14)
57 verbose stack     at ClientRequest.emit (node:events:513:28)
57 verbose stack     at TLSSocket.socketErrorListener (node:_http_client:502:9)
57 verbose stack     at TLSSocket.emit (node:events:525:35)
57 verbose stack     at emitErrorNT (node:internal/streams/destroy:151:8)
57 verbose stack     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
57 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
58 verbose cwd C:\Users\bbrk2\source\repos\conniebot
59 verbose Windows_NT 10.0.19045
60 verbose node v18.16.0
61 verbose npm  v9.5.1
62 error code ETIMEDOUT
63 error syscall connect
64 error errno ETIMEDOUT
65 error network request to https://registry.npmjs.org/npm/-/npm-9.6.4.tgz failed, reason: connect ETIMEDOUT 2606:4700::6810:1a23:443
66 error network This is a problem related to network connectivity.
66 error network In most cases you are behind a proxy or have bad network settings.
66 error network
66 error network If you are behind a proxy, please make sure that the
66 error network 'proxy' config is set properly.  See: 'npm help config'
67 verbose exit 1
68 timing npm Completed in 399838ms
69 verbose unfinished npm timer reify 1682203590704
70 verbose unfinished npm timer reify:loadBundles 1682203724036
71 verbose unfinished npm timer reifyNode:node_modules/npm 1682203724036
72 verbose code 1
73 error A complete log of this run can be found in:
73 error     C:\Users\bbrk2\AppData\Local\npm-cache\_logs\2023-04-22T22_44_17_394Z-debug-0.log</pre>
</details>

**Comment by wraithgar** [comment] 2023-04-24 01:54
Duplicate of https://github.com/npm/cli/issues/4028 and/or https://github.com/npm/cli/issues/3359

**Closed as completed by wraithgar** 2023-04-24 01:54 UTC
Labels: Bug, Needs Triage, Release 9.x
