### ISSUE TITLE
[BUG] `.gitignore` files renamed to `.npmignore` on install

### ISSUE THREAD

**Issue by louis-bompart** [npm/cli#5756] opened 2022-10-26 19:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When installing a package with a bundled `.gitignore` file, the installed copy is instead named  `.npmignore`.

### Expected Behavior

When installing a package with a bundled `.gitignore` file, the installed copy should still be named `.gitignore`.

### Steps To Reproduce

MRC repo: https://github.com/louis-bompart/glowing-telegram
```
git clone https://github.com/louis-bompart/glowing-telegram
cd glowing-telegram
npm pack
npm i glowing-telegram-1.0.0.tgz
```
Check the `node_modules/glowing-telegram/foo` directory: there's no .gitignore but a .npmignore instead

### Environment

- npm: 8.19.2/9.0.0
- Node.js: 16.18.10
- OS Name: Windows10
- System Model Name: N.A
- npm config:
```ini
; "builtin" config from C:\Users\louis\AppData\Roaming\npm\node_modules\npm\npmrc

prefix = "C:\\Users\\louis\\AppData\\Roaming\\npm"

; "user" config from C:\Users\louis\.npmrc

//localhost:4873/:_authToken = (protected)
//registry.npmjs.org/:_authToken = (protected)

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v16.18.0
; npm local prefix = E:\Repos\foobaraa
; npm version = 8.19.2
; cwd = E:\Repos\foobaraa
; HOME = C:\Users\louis
; Run `npm config ls -l` to show all defaults.
```

**Comment by davidecorreu** [comment] 2022-11-03 15:12
I'm having a similar issue were a I have "myPackage" that contains a `resources/projectTemplate/.gitignore`.

I can see that the file is listed as `dist/resources/projectTemplate/.gitignore` when running `npm pack` or `npm publish` but after running `npm install myPackage` what I see installed is `node_modules/myPackage/dist/resources/projectTemplate/.npmignore`.

I would expect to see  `node_modules/myPackage/dist/resources/projectTemplate/.gitignore` after running `npm install myPackage` or `npm install myPackage-1.2.3.tgz`.

I'm using Windows 10, with node version = v16.14.2, and npm version = 8.19.2

**Comment by MondoGao** [comment] 2022-12-06 07:39
reproducible on npm 9.1.2.
subfolders' .gitignore are also affected by this behavior.

this is a severe bug when installing packages include template code.

**Comment by MondoGao** [comment] 2022-12-06 07:45
May caused by this line https://github.com/npm/cli/blob/latest/node_modules/pacote/lib/fetcher.js#L448

**Comment by MondoGao** [comment] 2022-12-06 07:49
**How to fix temporarily:**
It seems if you include a .npmignore file into your pkg's files on the same level of .gitignore, npm will skip this rename behavior.

---
not working.

**Comment by MondoGao** [comment] 2022-12-07 07:43
allow-git-ignore option isn't added to npm cli's definitions
in pacote, the default behavior is false, then cause this issue.

**Comment by siemhesda** [comment] 2023-12-06 18:24
As described above, I assume the steps to reproduce should be as below (missing the `cd glowing-telegram` part):

```
git clone https://github.com/louis-bompart/glowing-telegram
cd glowing-telegram
npm pack
npm i glowing-telegram-1.0.0.tgz
```

Following these steps, this issue is no longer reproducible on the current npm version

I'm therefore closing this issue for now

**Closed as completed by siemhesda** 2023-12-06 18:24 UTC
Labels: Release 8.x, Bug, Priority 1

**Comment by louis-bompart** [comment] 2023-12-06 18:54
@siemhesda, I'd suggest to reopen the issue.
I can't say when, but there seems to have been a change in how the "files" field is handled, which led to the `.gitignore` file being ignored during `npm pack`.

I updated the MRE repo `glowing-telegram` (and corrected the steps in the issue description, indeed I had forgotten the `cd`).

I validated that the issue is still present with npm 10.2.4.

**Comment by qiufeihong2018** [comment] 2024-08-23 01:48
Is this problem solved?
