### ISSUE TITLE
Publishing Pacakge to local verdaccio server fails

### ISSUE THREAD

**Issue by Marty-Byrde** [npm/cli#6354] opened 2023-04-13 10:04 UTC
I am currently working on another package that I would like to publish to my local verdaccio server, so that I can reuse its contents in my other projects. First of all, I would like to specify my setup regarding node and npm. I am working on a Window 10 maschine with a node version 12.18.3. Now as one might notice, this node version is quite old, but required by some of my older projects. Thus, I am using volta, to specify node version independently for projects. Hence, I can have multiple projects with different node versions. 

The project I am currently working on uses ES6. As ES6 is not available in the node version 12.18.3, compiling and running the project on this version fails. Still it is possible to develop such a package (ES6), publish it to my local verdaccio server and use it in other projects that have a higher node version, such as 16.18.1. 

As I am using newer node versions in new projects (16.18.1), compiling and running them works fine. But the problem occours when I try to publish such a package to my local verdaccio server. (As one might notice, I have set the default npm registry to my local verdaccio server.) Running the `npm publish` command returns the following error message:

`PS C:\#Modules\LogUtils\logutils> npm publish`
`npm ERR! code ENOENT      `                                                                    
`npm ERR! syscall open     `                                                                    
`npm ERR! path C:\package.json      `                                                           
`npm ERR! errno -4058   `                                                                       
`npm ERR! enoent ENOENT: no such file or directory, open 'C:\package.json'      `               
`npm ERR! enoent This is related to npm not being able to find a file.         `                
`npm ERR! enoent        `                                                                       
                                                                                              
`npm ERR! A complete log of this run can be found in:    `                                      
`npm ERR!     C:\Users\....\AppData\Local\npm-cache\_logs\2023-04-13T10_00_37_402Z-debug-0.log`

But for some reason when switching the node version back to 12.18.3 by using the `volta pin node@12.18.3` command, publishing the same content works fine. Since I have tried to fix this issue over a longer period now, wihtout success and this behaivour gets quite annoying over time, I hope some of you might have had the same issue or could provide some suggestions on how to solve this.

**Comment by milaninfy** [comment] 2024-09-06 19:33
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce. please use our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).

**Closed as not planned by milaninfy** 2024-09-06 19:33 UTC
