### ISSUE TITLE
[BUG] npm_ variables are lost when using script-shell config parameter

### ISSUE THREAD

**Issue by ThePlenkov** [npm/cli#3084] opened 2021-04-15 12:08 UTC
Hi!

I just noticed that in case of using parameter  [script-shell](https://docs.npmjs.com/cli/v7/commands/npm-run-script#script-shell) we loose all environment variables. 

It's very simple to check for example in Windows (`scripts:{set:"set", env:"env"})`)

Scenario 1 in windows - ok, npm_config_ variables are shown
```
npm run set
```

Scenario 2 in windows WSL,  - also works
```
npm run env
```

Scenario 3 - in windows but with `script-shell=bash`. **Doesn't work**
```
npm run env
```

Could you please check how you inject environment variables. I really hope you can analyze also this variable and provide them also for script-shell scenario.

Thank you!

**Comment by darcyclarke** [comment] 2021-06-04 18:34
**Action:** Needs further review/reproduction

**Comment by nlf** [comment] 2022-04-27 16:53
just a note - i cannot reproduce this in osx or linux, will try on windows when i get a chance

**Comment by nlf** [comment] 2022-05-31 16:12
i'm unable to reproduce this in windows either.

i'm going to close this issue, but if the problem is persisting please open a new issues and give us as much information as you're able to help us reproduce the problem.

**Closed as not planned by nlf** 2022-05-31 16:12 UTC
Labels: Release 7.x, Bug, Needs Triage, platform:windows
