### ISSUE TITLE
[BUG] npm install does not run prepare scripts of workspaces except for root

### ISSUE THREAD

**Issue by trusktr** [npm/cli#3840] opened 2021-10-06 05:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

Related issues that were considered fixed, but the issue seems to persist or have regressed:

- https://github.com/npm/cli/issues/1965
- https://github.com/npm/cli/issues/2900

### Current Behavior

`npm install` does not run `prepare` scripts of workspaces except for the root workspace.

### Expected Behavior

It should run `prepare` of all workspaces.

### Steps To Reproduce

Reproduction repo comparing it with `lerna`: https://github.com/trusktr/npm-workspaces-vs-lerna

Steps:

```
git clone https://github.com/trusktr/npm-workspaces-vs-lerna.git
cd npm-workspaces-vs-lerna
npm install
npx lerna bootstrap
```

Notice that the `npm install` command runs `prepare` only for package `a`, while the `npx lerna bootstrap` command runs it for all three packages a, b, and c.

### Environment

- OS: Linux
- Node: 14.16.1
- npm: 7.24.2

**Comment by trusktr** [comment] 2021-10-06 05:50
Related issues that were fixed as solved, but the issue still seems to persist:

- https://github.com/npm/cli/issues/1965
- https://github.com/npm/cli/issues/2900

**Comment by trusktr** [comment] 2021-10-08 22:39
I was trying to see if I could move from Lerna to npm for multi-package management, but this is currently a blocker.

**Comment by nlf** [comment] 2022-10-03 16:09
i'm unable to reproduce this with the latest npm@8. i think what might be happening here is that the effect of scripts running in the background is that you're unable to see that the scripts are actually running. by running `npm install --foreground-scripts` i'm able to see all of the echo statements

i'm going to close this, but please feel free to reopen if you can still reproduce this in the latest npm@8

**Closed as not planned by nlf** 2022-10-03 16:09 UTC
Labels: Release 7.x, Bug, Needs Triage
