### ISSUE TITLE
[BUG] npm config get prefix super slow

### ISSUE THREAD

**Issue by DullReferenceException** [npm/cli#1243] opened 2020-05-04 17:19 UTC
# What / Why

This is an attempt to resurrect this unresolved bug: https://github.com/npm/npm/issues/14458

For some reason, the command `npm config get prefix` is multi-seconds slow. This normally wouldn't bother me, but for users of `nvm` like me, this is really impacting since it uses this command internally, and nvm is used in shell startup scripts. See https://github.com/nvm-sh/nvm/issues/782 for more details. Therefore, shell startup is super slow, especially for those using WSL.

## When

Always

## Where

NPM CLI

### Current Behavior

Run `time npm config get prefix`, see multi-second response timing.

### Steps to Reproduce

Run `npm config get prefix`

### Expected Behavior

Result should come back quicker.

## Who

?

## References

  * Related to https://github.com/npm/npm/issues/14458, https://github.com/nvm-sh/nvm/issues/1242

**Comment by ljharb** [comment] 2020-05-04 18:22
cc @darcyclarke; this actually would make a *ton* of difference for every nvm user, including every travis-ci run.

**Comment by darcyclarke** [comment] 2020-05-04 19:07
🤔 I'm positive there's some digging to be done here

**Comment by EdwardLuke** [comment] 2020-05-13 16:24
Has any progress been made with this? I would be interested in helping with this issue.

**Comment by IdsTeepe** [comment] 2020-07-04 10:56
Recently, `npm config get prefix` has been very slow on my machine. This seems to be ever since I moved the `/var/` directory from my SSD to my HDD to free up some space.
The first time the command runs (as part of my `.bashrc` script) it is especially slow, taking somewhere between 10-20 seconds. Later runs (by opening new shells) it 'only' takes a few seconds.

**Comment by darcyclarke** [comment] 2021-06-02 21:21
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 21:21 UTC
Labels: Release 6.x, Bug
