### ISSUE TITLE
[BUG] Subdependency that needs to be built from source not found (works with npm 6)

### ISSUE THREAD

**Issue by lognaturel** [npm/cli#3556] opened 2021-07-17 03:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to include a dependency that needs to be built from source ([libxslt](https://github.com/albanm/node-libxslt)) which itself has a dependency that needs to be built from source ([libxmljs](https://github.com/MrMYHuang/libxmljs)), `npm install` fails with:

`npm ERR! clang: error: no such file or directory: '<project path>/node_modules/node1-libxmljsmt-myh/build/Release/xmljs-myh.node'`

There is no `node_modules` directory at that point.

### Expected Behavior

`npm install` succeeds and dependencies and subdependencies are installed

These all work:
- `npm install` with `npm` 6.14.13
- Pulling the dependency locally, building the dependency with `npm install` with `npm` 7.20.0, including it with `"libxslt": "file:../node-libxslt"`, then doing `npm install` with `npm` 7.20.0 in the project
- `yarn`
- `pnpm`

### Steps To Reproduce

1. Set npm to 7.20.0
2. Clone https://github.com/lognaturel/enketo-transformer/tree/upgrade-libxslt
3. `npm install`

### Environment

- OS: macOS 11.4 and Ubuntu 18.04.5 LTS
- Node: 12, 14, 16
- npm: 7.19.1, 7.20.0

**Comment by ljharb** [comment] 2021-07-17 04:16
What about with npm 7.20?

**Comment by lognaturel** [comment] 2021-07-17 05:35
I'm sorry, I wrote 7.2.0 but meant 7.20.0! Updated

**Comment by lognaturel** [comment] 2021-07-20 20:40
Interestingly, this specific issue seems to have come up previously with these two libraries. From https://github.com/albanm/node-libxslt/issues/41, it looks like it worked in `4.6.1` then broke in the upgrade to `5` and was fixed at some point between then and `6.14.13`.

**Comment by nlf** [comment] 2022-03-08 22:05
are you still seeing this issue with npm@8.5.3? i attempted to reproduce it but encountered unrelated build errors about a missing config.h

**Comment by cwirtanen** [comment] 2022-03-08 22:32
I just tried this on a fresh node14 docker image (after installing npm@8.5.3 and python3.9) and got the same, original error that I also see on npm@7.
https://pastebin.com/NtY5Wa9J

**Comment by lognaturel** [comment] 2022-03-08 23:47
@cwirtanen yours looks like a different issue -- the one I described only manifests when building a project that uses `node-libxslt` as a dependency, not when building directly. @nlf unfortunately the project I use this with fails for seemingly other reasons with `npm 8`. See https://github.com/enketo/enketo-express if you want to try it. I'll try to come back to this soon.

**Comment by nlf** [comment] 2022-04-27 18:23
@lognaturel hmm, i get the same error regarding a missing `config.h` file which judging by https://github.com/albanm/node-libxslt/pull/86 looks to be due to missing platform support for my particular laptop. 

what error are you seeing? from my perspective this seems to point to an issue with node-libxslt rather than npm itself, but if what you're getting now makes it look like an npm specific bug then we'll certainly look into it further.

**Comment by nlf** [comment] 2022-05-31 16:17
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.

**Closed as completed by nlf** 2022-05-31 16:17 UTC
Labels: Release 7.x, Bug, Needs Triage

**Comment by lognaturel** [comment] 2022-05-31 16:28
Thanks for following up and I apologize for not coming back. Using NPM 6 has been fine so it's been hard to make this a priority. Will reopen if it is reproducible at some point when we feel pressure to upgrade.
