### ISSUE TITLE
[BUG] npx . launches bin script in shell

### ISSUE THREAD

**Issue by PRR24** [npm/cli#7201] opened 2024-02-05 08:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Launching ```npx .``` within module executes script defined in package.json/bin in shell.

### Expected Behavior

Script is executed with node.
It was executed with node in older versions of the npm.

### Steps To Reproduce

1. npm init
2. index.js: ```console.log("test");```
3. package.json: ```"bin": "./index.js"```
4. npm install
5. npx .
6. shell error about console log is displayed (varies from one platfrom to another)

### Environment

- npm: 10.2.4
- Node.js: 21
- OS Name: Ubuntu 22.04, Windows 10
- npm config: all commented out

**Comment by ljharb** [comment] 2024-02-05 16:06
I’m confused; executing it with node would be up to the shebang in the file referenced by the build script.

**Comment by ljharb** [comment] 2024-02-05 16:07
What does `which node` say?

**Comment by PRR24** [comment] 2024-02-05 16:33
```/usr/bin/node``` on Linux and
```/usr/local/bin/node``` on Mac
The index.js file contains only single line of code (above) and ```node index.js``` works as expected.

**Comment by ljharb** [comment] 2024-02-05 16:36
Ahh. When a package like that is *installed*, npm creates the appropriate infra required to make it runnable directly, but that wouldn’t be present in the current package.

In which version of npm/npx did this work?

**Comment by PRR24** [comment] 2024-02-05 17:06
Works perfectly with npx 6.14.16 / node 14.19.1
Found this issue while upgrading old machine, but couldn't find any notice about the change or a new way to execute node project locally.
Goal is to:
* git clone
* npm install
* [insert command here that is not ```node somedirectory/subdirectory/app.js```, previously ```npx .```]

```npm start -- --argument value``` is the best alternative I have found so far, but it is more error prone for users to write (especially the -- in the middle)

It would be great if npm could detech local usage and support it. I think it would also be reasonable to skip caching the local project.

**Comment by PRR24** [comment] 2024-02-05 17:28
One more thing... The package is being copied to ~/.npm/, as a result of executing ```npx .``` so it is kind'a getting installed, just from local source, not from npm repo.

**Comment by milaninfy** [comment] 2024-09-13 19:11
@PRR24 I think you should have `#!/usr/bin/env node` in your code file as first line if you are expecting it to be run with node.

**Comment by milaninfy** [comment] 2024-09-23 13:07
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.

**Closed as completed by milaninfy** 2024-09-23 13:07 UTC
Labels: Bug, Needs Triage, Release 10.x
