### ISSUE TITLE
[BUG] npm install <package> does nothing when file:<path> has been used

### ISSUE THREAD

**Issue by scamden** [npm/cli#2443] opened 2021-01-06 00:15 UTC
### Current Behavior:
if I have a dep linked via `file:depPath` npm will not overwrite it when I try to install `depName@latest`

### Expected Behavior:
it should install a real version (not a file version) in the lock and in the file system

### Steps To Reproduce:
1. `npm install ../some-package`
2. `npm install some-package@latest`
3. notice that `../some-package` remains as resolved in lock and in node_modules

note: legacy peer deps has been used, not sure if that could be related

### Environment:
node 12
mac os big sur
npm: 7.3

**Comment by scamden** [comment] 2021-01-06 00:38
@ruyadorno this one is really frustrating. i'm not really sure how I can get rid of a `file: depPath` without completely wiping out the lock file.. even running `npm rm depName --no-save` doesn't change the lock file, so it still simply reinstalls the file version of the dep on the next install (without no-save you lose whether its dev, peer or regular)

in fact, this seems like a whole class of odd behavior we've seen where the lock file will often not line up with what's in the file system. and it doesn't fix it on subsequent installs. (not to pile on, i'm happy to open a different bug for this part if it helps). but I really need the lock file to reflect what's actually installed and what's actually installed to follow the lock file, which is frequently not happening since version 7.

**Comment by wraithgar** [comment] 2021-01-06 18:19
I was able to confirm this, but ONLY when the version in the local `file:depPath` matched the `@latest` version in the registry.  When the `@latest` was newer, it updated as intended.

**Comment by scamden** [comment] 2021-01-06 18:43
correct. that's exactly what I see as well. but of course most of the time
@latest will be exactly what I have locally (or older) if i'm trying to install it,
cause otherwise I wouldn't have been able to publish that version :P

**Comment by scamden** [comment] 2021-01-06 18:51
I also just confirmed that it's nothing special about the latest tag. it happens if the semver version you are trying to install is satisfied by the linked dep. aka if i'm file linked to package: `myPackage` and the local package.json is version 1.1.0 and I try to install `npm i myPackage@1.x.x` or `1.1.0` or even `^1.0.0` or seemingly any semver that matches the current version in that package it will not remove the link.

**Comment by scamden** [comment] 2021-01-12 18:02
is there a timeline for this? or a workaround? `file:` is pretty unusable with this bug..

**Comment by scamden** [comment] 2021-02-08 20:20
@ryd

**Comment by scamden** [comment] 2021-02-08 20:22
@ruyadorno @wraithgar guys any word on this? It's been weeks and it's totally blocking us

**Comment by scamden** [comment] 2021-02-19 01:15
@wraithgar you verified yes? needs triage still?

**Comment by scamden** [comment] 2021-02-19 01:17
@wraithgar help??

**Comment by ruyadorno** [comment] 2021-02-19 01:34
hi @scamden sorry about the delay! 
I'll make sure we prioritize this, thank you for reporting it!

**Comment by scamden** [comment] 2021-02-19 01:46
thanks so much!

**Comment by wraithgar** [comment] 2021-03-08 22:58
This bug has been partially fixed as of at least `v7.6.1`. If you do specify the `@latest` in the spec it will install from the registry, even if the latest version matches what's on disk.

There is still a bug with leaving off `@latest` that we are looking at. Will keep this issue open to track that part.

**Comment by scamden** [comment] 2021-03-09 00:07
great! that alone is a huge win and unblocks us, really appreciate it.

**Closed as completed** 2021-03-09 18:10 UTC
Labels: Release 7.x, Bug, Priority 1
