### ISSUE TITLE
[BUG] npm publish succeeds but gives an error output

### ISSUE THREAD

**Issue by moficodes** [npm/cli#4302] opened 2022-01-21 01:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

```bash
npm publish --access public
```

should publish the package. And it does. But after the publishing is done I get a 403.

 

### Expected Behavior

No error output.

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm: 8.3.2
- Node.js: v14.18.2
- OS Name: MacOS Monterey 12
- System Model Name: Macbook Pro
- npm config:
```ini
; "builtin" config from /usr/local/lib/node_modules/npm/npmrc

prefix = "/usr/local" 

; "user" config from /Users/mofirahman2/.npmrc

//registry.npmjs.org/:_authToken = (protected) 

; node bin location = /usr/local/bin/node
; cwd = <CWD>
; HOME = /Users/mofirahman2
; Run `npm config ls -l` to show all defaults.
```

**Comment by moficodes** [comment] 2022-01-21 07:05
```bash
npm run publish

> packagename@0.0.9 publish
> npm publish --access public

npm notice 
npm notice 📦  vve-breakout@0.0.9
npm notice === Tarball Contents === 
npm notice 526B   .editorconfig            
npm notice 1.1kB  LICENSE                  
npm notice 867B   README.md                
npm notice 2.7kB  demo/index.html          
npm notice 52B    index.js                 
npm notice 1.7kB  package.json             
npm notice 14.8kB src/VveBreakout.js       
npm notice 112B   vve-breakout.js          
npm notice 906B   web-dev-server.config.mjs
npm notice === Tarball Details === 
npm notice name:          vve-breakout                            
npm notice version:       0.0.9                                   
npm notice filename:      vve-breakout-0.0.9.tgz                  
npm notice package size:  6.8 kB                                  
npm notice unpacked size: 22.8 kB                                 
npm notice shasum:        c4c8b6b7b74362147b7640fd3d3b1447f5106f94
npm notice integrity:     sha512-cAFUPRDSOeMlb[...]bSZO5dqHvIHZg==
npm notice total files:   9                                       
npm notice 
npm notice Publishing to https://registry.npmjs.org/
⸨⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⸩ ⠇ : notice Publishing to https://registry.npmjs.org/
> packagename@0.0.9 publish
> npm publish --access public

npm notice ⠂⠂⠂⠂⠂⠂⠂⠂⸩ ⠇ : notice Publishing to https://registry.npmjs.org/
npm notice 📦  packagename@0.0.9
npm notice === Tarball Contents === 
npm notice 526B   .editorconfig            
npm notice 1.1kB  LICENSE                  
npm notice 867B   README.md                
npm notice 2.7kB  demo/index.html          
npm notice 52B    index.js                 
npm notice 1.7kB  package.json             
npm notice 14.8kB src/VveBreakout.js       
npm notice 112B   packagename.js          
npm notice 906B   web-dev-server.config.mjs
npm notice === Tarball Details === 
npm notice name:         packagename                            
npm notice version:       0.0.9                                   
npm notice filename:      packagename-0.0.9.tgz                  
npm notice package size:  6.8 kB                                  
npm notice unpacked size: 22.8 kB                                 
npm notice shasum:        c4c8b6b7b74362147b7640fd3d3b1447f5106f94
npm notice integrity:     sha512-cAFUPRDSOeMlb[...]bSZO5dqHvIHZg==
npm notice total files:   9                                       
npm notice 
npm notice Publishing to https://registry.npmjs.org/
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/packagename - You cannot publish over the previously published versions: 0.0.9.
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mofirahman2/.npm/_logs/2022-01-21T07_03_57_691Z-debug-0.log
npm ERR! code 1
npm ERR! path /Users/mofirahman2/Documents/github.com/vonage/ve-education-pre-package-solution-demo/packagename
npm ERR! command failed
npm ERR! command sh -c npm publish --access public

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mofirahman2/.npm/_logs/2022-01-21T07_03_53_634Z-debug-0.log```

**Comment by lukekarrys** [comment] 2022-01-31 19:14
I think this is expected, since you are attempting to publish the same version twice. `npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/packagename - You cannot publish over the previously published versions: 0.0.9.` You can update the version using `npm version` and then try publishing that new version.

**Comment by moficodes** [comment] 2022-02-03 16:05
I am publishing the 0.0.9 version.

It publishes 0.0.9 then gives the error that its already exists. 

Prior to running the command my version was 0.0.8

**Comment by DRigby26** [comment] 2022-02-03 22:02
I am seeing a very similar issue as well, except with a private package. After logging in and using my two factor auth token while publishing, it'll error out but the package will still publish. 
```
npm ERR! code ENEEDAUTH
npm ERR! need auth This command requires you to be logged in to https://registry.yarnpkg.com/
npm ERR! need auth You need to authorize this machine using `npm adduser`
```
I tried running `npm adduser` as well but same issue.

**Comment by lukekarrys** [comment] 2022-02-10 20:50
Thanks for the follow up @moficodes! I think I see what's happening now.

The run script you are using to publish is calling `npm publish` twice: `"publish": "npm publish --access public"`.  I do think this is a bug, as I don't know why this would be happening. I'll keep this open and try to come up with a reason and a fix for this.

For now I'd recommend removing that `publish` script from your `package.json` and running `npm publish` (instead of `npm run publish`).

Two other things to note about this:

- `--access public` only needs to be used the first time you publish a scoped package since those are private by default. From what I can see from your package, it isn't scoped so you shouldn't need to use `--access public` each time.
- If you are working on a scoped package that you plan on publishing publicly, you can create a `.npmrc` file in the root of your project that contains `access=public`. See https://docs.npmjs.com/creating-and-publishing-scoped-public-packages for more info about scoped packages and public access.

**Comment by lukekarrys** [comment] 2022-03-21 18:48
> I do think this is a bug, as I don't know why this would be happening.I didn't

Turns out this is by design and a `publish` run-script will always be run during `npm publish`: https://docs.npmjs.com/cli/v8/using-npm/scripts#npm-publish. So you'll need to rename your run-script to something other than publish.

**Closed by lukekarrys** 2022-03-21 18:48 UTC
Labels: Release 8.x, Bug, Priority 1, cmd:run-script
