### ISSUE TITLE
[BUG] npm install creates files in the past

### ISSUE THREAD

**Issue by mikkorantalainen** [npm/cli#1887] opened 2020-10-01 17:52 UTC
### Current Behavior:
When I run `npm install` many files inside directory `node_modules` have file timestamps in the past.

### Expected Behavior:
Filesystem timestamps should reflect the moment those files were added to the system. Incorrect timestamps may affect backups among other problems.

### Steps To Reproduce:
cat > package.json <<EOF
{
  "name": "minimal-demo",
  "dependencies": {
    "lodash": ">=1"
  }
}
EOF
npm install
find node_modules -mtime +100

### Additional notes

I guess this is caused by reproducible builds which use date in past to not change the resulting binaries due changes in timestamps. However, there's absolutely no reason to *extract* those timestamps to target filesystem because the faked timestamp is required only for the binary package.

### Environment:
Ubuntu 18.04
$ apt policy nodejs
nodejs:
  Installed: 12.18.4-1nodesource1
  Candidate: 12.18.4-1nodesource1
  Version table:
 *** 12.18.4-1nodesource1 500
        500 https://deb.nodesource.com/node_12.x bionic/main amd64 Packages
        100 /var/lib/dpkg/status
...

**Comment by futagoza** [comment] 2020-11-08 14:17
I just had this issue occur to me but thought it weird that all the new timestamps (7 updated packages with over 50 files updated from what I could tell after I ran _npm i_ to update an existing project's installed dependencies) were the same: _26/10/1985 09:15_

Since I never save the node_modules folder in git (when I remember to use it 😅) or interact with this folder directly through any tool or library (not that I'm aware of anyway), this isn't an urgent issue for me, but still feel that this should be fixed because (like mentioned in the expected behavior section above) this issue can affect backup tools (which I used to use before switching to git, and out of habit, somtimes still do use).

I'm using:
Node 15.1.0
NPM 7.0.8
VS Code 1.51.0

**Comment by Flimm** [comment] 2020-11-16 08:08
This issue also affects build tools that look at mtime of a file, which many of them do.

For example, let's say I have a build step in my favourite build tool that looks at `node_modules/example/foobar.js`, minifies it, and creates `foobar.min.js`, but only if the source file has a newer mtime than the destination file. I would expect that every time `foobar.js` is updated, the build tool would run again and overwrite the destination file. However, if I use `npm update`, the file `foobar.js` will still have an `mtime` stuck in the past, and so the build tool will not run the minify step, leaving an out-of-date destination file in the directory.

**Comment by ljharb** [comment] 2020-11-16 08:57
Wouldn't those systems be a lot more robust if they used content-addressing rather than the mtime?

**Comment by Flimm** [comment] 2020-11-16 09:02
> Wouldn't those systems be a lot more robust if they used content-addressing rather than the mtime?

Yes, they would be more robust, but they would also be slower, and they would require additional storage. That is why many build systems use `mtime` instead of content-addressing. It usually works, this is the only case that I can think of where it hasn't worked well for me.

**Comment by darcyclarke** [comment] 2021-06-02 21:08
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 21:08 UTC
Labels: Release 6.x, Bug
