### ISSUE TITLE
[BUG] npm install ends with EEXIST

### ISSUE THREAD

**Issue by pythoulon** [npm/cli#672] opened 2020-01-09 17:49 UTC
# The problem

> I have cloned [Microsoft's VSCode Language server](https://github.com/microsoft/vscode-extension-samples.git). I then change directory to the example I'm interested in (`lsp-samples`) and run `npm install` in that folder.

It quickly dies the the following error message:

npm ERR! code EEXIST
npm ERR! syscall mkdir
npm ERR! path G:\My Drive\Git\vscode-extension-samples\vscode-extension-samples\lsp-sample\node_modules\.staging    
npm ERR! errno -4075
npm ERR! EEXIST: file already exists, mkdir 'G:\My Drive\Git\vscode-extension-samples\vscode-extension-samples\lsp-sample\node_modules\.staging'
npm ERR! File exists: G:\My Drive\Git\vscode-extension-samples\vscode-extension-samples\lsp-sample\node_modules\.staging
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

See attached log file.
[2020-01-09T17_39_35_413Z-debug.log](https://github.com/npm/cli/files/4041728/2020-01-09T17_39_35_413Z-debug.log)

# What's weird
is that it complains that the .staging directory already exists, when it is the install process itself that created the folder (when I start, there is no preexisting node_modules folder).

Any idea what the problem might be ? I've tried reinstalling npm, deleting the node_modules folder and starting over, deleting the intermediate .staging folder, using the --force option, to no avail...

**Comment by aprilmintacpineda** [comment] 2020-01-10 04:30
I got the same error, though probably different case.

I just did `npm update -g` and then after that, npm will no longer work. Here's the screenshot of the whole thing.

![image](https://user-images.githubusercontent.com/21032419/72125808-f669bf80-33a4-11ea-91b2-294bfa6cf5e3.png)

To make npm work again, I have to `brew reinstall node` :((

**Comment by LitoMore** [comment] 2020-01-10 06:08
Duplicate of #611

**Comment by pythoulon** [comment] 2020-01-10 06:45
Sorry, but I don't understand how this is a duplicate of #611 ... (that said, it may be the same internal mechanism that causes both failures, is this the case?)
In my case `npm install -g npm` works fine (first thing I did when it started failing) ; I also performed a `npm install -g typescript@latest` without any problem.
Note that every time I do a `npm install` it dies with the same EEXIST error, but the thing it complains about varies from one case to the next (even when I totally remove the node_modules folder in between tries): in general existing .staging or .bin folder.

**Comment by LitoMore** [comment] 2020-01-10 06:55
@pythoulon My mistake. Please ignore that 😂

**Comment by pythoulon** [comment] 2020-01-10 06:56
No problem...😁

**Comment by playniuniu** [comment] 2020-01-10 08:01
same problem here

**Comment by aprilmintacpineda** [comment] 2020-01-10 13:31
See https://github.com/npm/cli/issues/611#issuecomment-573035688 if that helps.

**Comment by pythoulon** [comment] 2020-01-10 17:27
More on this. I realized that my development folder is on the special drive created by Google Drive File Stream (the sync engine between Windows' file system and Google Drive). 
Out of curiosity, I move the dev folder out of there onto a "real" drive. And voilà, it works!

So the problem seems to be with the way npm interacts with the virtual file system created by Drive File Stream... I'm going to leave my dev folder out of it...

**Comment by AshishShanker** [comment] 2020-05-12 20:55
I have the exact same problem but in a different context. 

I have stepped through `npm cli` code in `debugger` and have identified the proximate cause of the `EEXIST` error, and also appear to have a workaround, but no idea why `npm cli` is behaving that way or why the workaround works :)

DISCLAIMER: I have superficial understanding of `npm cli` code, so it is possible my conclusions are erroneous as well.

**My setup**
Windows 10.0.18363
Node 14.2.0
npm 6.14.5
Verdaccio 4.6.2

I use Verdaccio to enable a local npm registry on `localhost:4873`. I have a simple scoped package called `@myscope/myapp` that has just a `package.json` and a `README.md`. The package has one dependency on `esm`. Verdaccio proxies to `npmjs` so any packages like `esm` published to `npmjs` are downloaded transparently.

My workflow is as follows:
- `npm publish` in the project's root directory --> this publishes the package to `Verdaccio; I already have `.npmrc` setup to point to `localhost:4873` as my registry.
- `npm install -g @myscope/myapp`

When I do `npm publish` I am able to verify the application got published. I am also able to download the `myapp-0.0.1.tgz` file generated by the publish step and confirm that it contains both the `package.json` and `README.md` files.

When I do the global install step, I get the `EEXIST` error
```
$ npm install @myscope/myapp --global
npm ERR! code EEXIST
npm ERR! syscall mkdir
npm ERR! path <%APPDATA%>\npm\node_modules\@myscope\myapp
npm ERR! errno -4075
npm ERR! EEXIST: file already exists, mkdir '<%APPDATA%>\npm\node_modules\@myscope\myapp'
npm ERR! File exists: <%APPDATA%>\npm\node_modules\@myscope\myapp
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.
```
re-running the command with `--force` as recommended *does not* help.

**Insights from Debugger session**
- For every install job, `npm` internally looks up all the packages to be downloaded and creates an `extract` job for each (in this case 2 `extract` jobs are created, one for `@myscope/myapp` and the other for `esm`. 

    During the `extract` for `@myscope/myapp` it was observed that although the correct `.tgz` file was streamed in, only the `README.md` file actually got extracted. This file is written to `.staging` as `myapp-<some_hash>`

    `esm` gets downloaded into `.staging` directory correctly, including all files and directories.

- For every package installed, a `finalize` is run. This is the step where package files are moved from `.staging` to their final destination under `node_modules`. 

    `finalize` for `esm` executes first. I suspect because `myapp-<some_hash>` is not a directory, just a file 

    Since this involves calls to `mkdirp`, `npm` ends up creating the "deeper" path first (since `esm` is installed in `%APPDATA%\npm\node_modules\@myscope\myapp\node_modules`. As a result, when the time comes to `mkdirp` the directory for `myapp` to house the file from that package, the program throws an EEXIST error because `/myapp` directory already exists.

This is the proximate cause of failure. 

I suspect the real issue is that `@myscope/myapp`'s files didn't get extracted properly, because of which the `extract` step did not produce a directory in `.staging` for `@myscope/myapp`. I suspect that had that directory been in place, it's `finalize` would have been called first and the install would have gone through.

`npm` internally uses `chain` from `slide` package, so I don't think the order of execution of `finalize` step is subject to some sort of a race condition.

**Workaround**
Not sure why this works (running this from `gitbash`):
1. remove dependency on `esm` from `@myscope/myapp` source code (take it out of `dependencies` object
2. `npm unpublish @myscope/myapp` --> `myapp` removed from `Verdaccio`
3. `npm publish` --> from project's home dir. `@myscope/myapp` published to `Verdaccio` with no dependency on `esm`
4. `npm install -g @myscope/myapp`
    - this goes through without error. Interestingly, I see both `package.json` and `README.md` in the installed directory. There is no `node_modules` directory because there is no dependency
5. `npm uninstall -g @myscope/myapp --force`
6. `npm unpublish @myscope/myapp --force` --> app removed from `Verdaccio`
7. Reintroduce dependency on `esm` into source code
8. `npm publish` --> from project home dir. `@myscope/myapp` published to `Verdaccio` with dependency on `esm`
9. `npm install -g @myscope/myapp` --> works!!! I can see `package.json`, `README.md`, and `node_modules` with `esm` package in it.

**Comment by nsitu** [comment] 2021-04-07 12:51
@pythoulon I would second your observations about Google Drive. I am experiencing the same issue but it goes away when I move the folder to a "real" local drive. I would be curious to know whether there's a deeper dive possible here. Any idea where one might go next with this problem?

**Comment by pythoulon** [comment] 2021-04-07 19:03
@nsitu No idea... Looks like a problem somewhere deep in npm (or worse in Google Drive's implementation ?)

**Comment by laptevme** [comment] 2021-04-26 21:06
I have the same problem with the npm update.
It worked for me:
1. Run "npm install -g npm"
2. Immediately delete files "npm", "npm.cmd", "npx" and "npx.cmd" from the working directory.

**Closed as completed** 2021-06-02 21:55 UTC
Labels: Bug

**Comment by pf-paul** [comment] 2022-10-18 10:49
Just wondering why this has been closed as completed when none of the comments address the OP's issue?

I am seeing the same error: `npm ERR! EEXIST: file already exists, mkdir 'G:\My Drive\...\myproject\node_modules\.staging'`
Does anyone know how to resolve this?

(I did the same as the OP, deleted `.staging` folder manually and then ran `npm install` again, but this step shouldn't be necessary if there was no `node_modules` folder to begin with.)

**Comment by adenike005** [comment] 2023-11-03 10:39
hi

**Comment by abhijitmaiti** [comment] 2023-11-18 18:14
![Screen Shot 2023-11-18 at 11 43 51 PM](https://github.com/npm/cli/assets/72270611/67c307ef-456f-4b5b-baf7-a2cf197212d9)

same problem

**Comment by kervyntan** [comment] 2023-12-21 02:41
Facing the same issue at the moment
<img width="938" alt="Screenshot 2023-12-21 at 10 41 02 AM" src="https://github.com/npm/cli/assets/73232587/ca57eadc-91e1-4a94-9925-b72c7b07834b">
