### ISSUE TITLE
[BUG] cb() never called! npm file install error

### ISSUE THREAD

**Issue by EmreSoftware** [npm/cli#1748] opened 2020-08-31 14:32 UTC
### Current Behavior:
 cb() never called!

### Expected Behavior:
Download and install file successfully using npm

### Steps To Reproduce:

1. write npm i discord.js (example)
2. Error cb() never called!

### Environment:

npm: 6.14.6

**Comment by pkrasicki** [comment] 2020-08-31 15:17
Related or duplicate of: https://github.com/npm/cli/issues/1720

**Comment by pkrasicki** [comment] 2020-08-31 15:19
There are even more issues like this:
https://github.com/npm/cli/issues/1696
https://github.com/npm/cli/issues/1671
https://github.com/npm/cli/issues/1740
https://github.com/npm/cli/issues/1737
https://github.com/npm/cli/issues/1731
https://github.com/npm/cli/issues/1666
https://github.com/npm/cli/issues/1647
https://github.com/npm/cli/issues/1625
https://github.com/npm/cli/issues/1608
https://github.com/npm/cli/issues/1605
https://github.com/npm/cli/issues/1552
https://github.com/npm/cli/issues/1546
https://github.com/npm/cli/issues/1531
https://github.com/npm/cli/issues/1505
https://github.com/npm/cli/issues/1466
https://github.com/npm/cli/issues/1464

**Comment by darcyclarke** [comment] 2021-06-02 21:16
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Comment by darcyclarke** [comment] 2021-06-02 21:21
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 21:21 UTC
Labels: Release 6.x, Bug
