### ISSUE TITLE
[BUG] Install fails if "bin" script doesn't exist

### ISSUE THREAD

**Issue by t1m0thyj** [npm/cli#2632] opened 2021-02-05 15:35 UTC
### Current Behavior:

In a workspace, `npm install` fails for a package with a "bin" script defined in package.json that doesn't exist. NPM tries to chmod the non-existent "bin" script, resulting in ENOENT error.
```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /home/timothy/dev/npm7-bin-link-issue/node_modules/cli/lib/index.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/timothy/dev/npm7-bin-link-issue/node_modules/cli/lib/index.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

### Expected Behavior:

`npm install` should succeed and NPM should not attempt to chmod "bin" scripts if they don't exist.

### Steps To Reproduce:

The scenario of a non-existent "bin" script is easy to encounter in a TypeScript monorepo using NPM workspaces, where a "bin" script may point to a `.js` file that doesn't exist until the TS is transpiled to JS.

To reproduce the error, clone [this minimal sample repo](https://github.com/t1m0thyj/npm7-bin-link-issue) and run `npm install`. Or follow the steps below:
1. Create an NPM project: `npm init -y`
2. Define the `workspaces` property in top-level package.json:
  `"workspaces": [ "./packages/*" ]`
3. Create the directory structure "packages/cli" and generate a package.json there: `cd packages/cli && npm init -y`
4. Define `bin` property in "packages/cli/package.json" and point to a non-existent script:
  `"bin": { "test-cli": "./nonexistent.js" }`
5. Run `npm install` at top level of project and see ENOENT

### Environment:

- OS: Ubuntu 18.04
- Node: 15.8.0
- npm: 7.5.1

**Comment by chuanqisun** [comment] 2021-05-12 04:04
I ran into the same issue. Seems to have been caused by workspace.
npm 7.11.2
node 16.1.0
Ubuntu 20.04.1 LTS (running as WSL)

**Comment by t1m0thyj** [comment] 2021-05-15 14:37
For others encountering this issue, I've temporarily worked around it by adding a preinstall script to the package that has a "bin" script, which creates an empty "bin" script if none exists yet: https://github.com/zowe/zowe-cli/blob/da013f8b6897a16325343466c73f42de3b434325/packages/cli/scripts/preinstall.js

**Comment by ruyadorno** [comment] 2021-05-21 19:41
Hi @t1m0thyj thank you so much for bringing this to our attention and opening https://github.com/npm/bin-links/pull/23

I'm really curious about this statement:

> The scenario of a non-existent "bin" script is easy to encounter in a TypeScript monorepo using NPM workspaces, where a "bin" script may point to a .js file that doesn't exist until the TS is transpiled to JS.

Is that a common scenario in the wider TypeScript community? I'm interested in understanding better the reasons and problems that particular setup is aiming to solve.

---

Meanwhile, I looked at your [minimal sample repo](https://github.com/t1m0thyj/npm7-bin-link-issue) and from an **npm7** point of view it stands out the fact that the example is not using the `prepare` lifecycle script in order to make sure the `build` script gets run prior to the install / bin-linking, I made an example PR showing the way I would instinctively approach it here: https://github.com/t1m0thyj/npm7-bin-link-issue/pull/1 - but I'm aware that the decision to not use the `prepare` lifecycle script might have been intentional, so I'd like to hear from you.

**Comment by ljharb** [comment] 2021-05-21 19:49
@ruyadorno it's common in any package that uses babel also; the "bin" script would be a `.js` file that doesn't exist prior to the build step running as well.

**Comment by ruyadorno** [comment] 2021-05-21 20:14
right, thanks @ljharb! yeah my first thought is that the installer should def be more reliable anyways but I just want to make sure I fully understand the problem space first.

> it's common in any package that uses babel also

in that case how is the babel ecosystem working around it today? 

> the "bin" script would be a .js file that doesn't exist prior to the build step running as well.

and from your pov is there a particular reason for not hooking the build step with the `prepare` lifecycle script? (assuming we're talking about nested workspaces here)

**Comment by ljharb** [comment] 2021-05-21 20:50
@ruyadorno sure. All of my build steps use `prepublishOnly`, not `prepare`, which seems valid. Build output doesn't need to exist until publish time - or until i want sibling workspace packages to be able to consume it (ie, at runtime) - but certainly does not need to ever exist at install time.

**Comment by chuanqisun** [comment] 2021-05-22 08:09
I might have a chicken-and-egg problem. I can't generate the `.js` file in `prepare` step because I need to `npm install` the build tools first. But I can't `npm install` because the `.js` file doesn't exist. My current workaround is `cd` into the nested package folder, `npm install && npm run build` to generate that `.js` file, then `cd` back to the monorepo root and run `npm install`. Any suggestions or workarounds?

[The problematic package.json line](https://github.com/osmoscraft/osmosfeed/blob/master/packages/cli/package.json#L12)
[My documented workaround](https://github.com/osmoscraft/osmosfeed/blob/master/docs/developer-guide.md#first-time-install)

**Comment by t1m0thyj** [comment] 2021-06-18 19:27
> Hi @t1m0thyj thank you so much for bringing this to our attention and opening [npm/bin-links#23](https://github.com/npm/bin-links/pull/23)
> 
> I'm really curious about this statement:
> 
> > The scenario of a non-existent "bin" script is easy to encounter in a TypeScript monorepo using NPM workspaces, where a "bin" script may point to a .js file that doesn't exist until the TS is transpiled to JS.
> 
> Is that a common scenario in the wider TypeScript community? I'm interested in understanding better the reasons and problems that particular setup is aiming to solve.
> 
> Meanwhile, I looked at your [minimal sample repo](https://github.com/t1m0thyj/npm7-bin-link-issue) and from an **npm7** point of view it stands out the fact that the example is not using the `prepare` lifecycle script in order to make sure the `build` script gets run prior to the install / bin-linking, I made an example PR showing the way I would instinctively approach it here: [t1m0thyj/npm7-bin-link-issue#1](https://github.com/t1m0thyj/npm7-bin-link-issue/pull/1) - but I'm aware that the decision to not use the `prepare` lifecycle script might have been intentional, so I'd like to hear from you.

@ruyadorno Sorry for the delayed response. I don't claim to know how the wider TypeScript community handles this. I also don't immediately see an issue with using the `prepare` lifecycle script as you've suggested, so I'll consult with my team about whether it would work for our use case.

However, requiring to use the `prepare` lifecycle script feels like more of a workaround than the ideal solution to me. It also seems like other folks who've commented on this issue have reasons why they can't use it.

I suppose this comes down to the question of how npm should handle bins that don't exist at the end of the install process:
1. Should npm assume that something is wrong if a bin doesn't exist, and fail with an error as it does now?
1. Should npm issue a warning when a bin doesn't exist, since it may be a problem but doesn't necessarily warrant a fatal error?
1. Should npm assume that it doesn't matter if a bin doesn't exist, and fail silently when this happens?

The current behavior is `#1`, and my PR https://github.com/npm/bin-links/pull/23 implements `#3`. But after further consideration, perhaps `#2` offers a compromise that would be the best option?

**Comment by ljharb** [comment] 2021-06-18 19:59
The only time npm should be validating things like that is at publish time, i think.

**Comment by aladdin-add** [comment] 2021-06-20 05:12
> The only time npm should be validating things like that is at publish time, i think.

agreed!

**Comment by bennypowers** [comment] 2021-07-25 11:10
I encountered this while attempting to [migrate my yarn1/changesets monorepo to npm7](https://github.com/apollo-elements/apollo-elements/runs/3154297647?check_suite_focus=true)

In my case, the missing bin script which causes the failure is from one of the monorepo packages, which is concerning, as I would not expect `npm i` or `npm ci` from the root to reference that file at all 

I'm very much looking forward to finishing this migration and coming back to npm after a long time with yarn. Thanks for the 👀 on this issue.

This was my workaround, in `@apollo-elements/create/package.json` (abridged):
```json
{
  "name": "@apollo-elements/create",
  "bin": {
    "create-app": "index.js"
  },
  "scripts": {
    "🚨__COMMENT__🚨": "echo 'The next two lines are a workaround for https://github.com/npm/cli/issues/2632'",
    "preinstall": "touch index.js",
    "postinstall": "[ -s index.js ] || rm -f index.js",
    "prepublishOnly": "tsc -b ."
  }
}
```  
I'm not certain if this will break on windows machines.

**Comment by JackuB** [comment] 2021-07-29 09:29
You may also create a static bin script. You can then commit this static file, so npm install won't fail anymore.
Update your bin location to a static file like so:

```diff
{
  "name": "mudkipz",
  "version": "1.0.0",
  "bin": {
-    "mudkipz-generator": "dist/index.js
+    "mudkipz-generator": "bin/mudkipz"
  },
  "scripts": {
    "build": "tsc"
  }
}
```

and then create a `bin/mudkipz` that contains

```js
#!/usr/bin/env node
require("../dist/index.js");
```

Don't forget to include the `bin` folder in your release and make the bin file executable.

**Comment by trusktr** [comment] 2021-10-06 05:11
> All of my build steps use `prepublishOnly`, not `prepare`, which seems valid.

Note that in that case the package is not installable from git (`prepare` runs for packages installed from git, but not `prepublishOnly`).

**Comment by ljharb** [comment] 2021-10-06 05:20
That's only the case if I have a build process, which very few of my packages do. I use `prepublishOnly` to make sure i'm not accidentally marking a backport as "latest".

**Comment by wraithgar** [comment] 2021-10-12 19:19
I landed the PR as a bugfix after reviewing the code and seeing all the other comments in that block that indicated that things that are not there should be ignored

cf: https://github.com/npm/bin-links/blob/47e3e535d595efb9cdd110f5e6936b68f34c4f60/lib/link-gently.js#L34-L42
```javascript
  // if the script or manpage isn't there, just ignore it.
  // this arguably *should* be an install error of some sort,
  // or at least a warning, but npm has always behaved this
  // way in the past, so it'd be a breaking change
  return Promise.all([
    lstat(absFrom).catch(throwNonEnoent),
    lstat(to).catch(throwNonEnoent),
  ]).then(([stFrom, stTo]) => {
    // not present in package, skip it
```

I'll hold off on publishing in case someone has a big red flag for why this should behave differently but looking at bin-links this really does look like a bug that is being fixed.

**Comment by wraithgar** [comment] 2021-10-12 19:19
Notably there is a comment here indicating that it should be a warning, and that may still be the case but I think adding that warning is a separate concern.

**Comment by t1m0thyj** [comment] 2022-02-04 18:58
Should this issue be closed? Looks like it was fixed in npm@8.1.0 through arborist@4.0.1 -> bin-links@2.3.0

**Comment by wraithgar** [comment] 2022-02-07 15:07
Thanks @t1m0thyj

**Closed as completed by wraithgar** 2022-02-07 15:07 UTC
Labels: Release 7.x, Bug, Priority 2

**Comment by remcohaszing** [comment] 2022-02-21 09:46
I just ran into this issue trying to move [appsemble](https://gitlab.com/appsemble/appsemble) to npm using npm 8.5.1.

```sh
git clone git@gitlab.com:appsemble/appsemble.git
cd appsemble
rm yarn.lock
npm install
```

**Comment by chuanqisun** [comment] 2022-06-12 16:42
@wraithgar, was this closed by accident? @t1m0thyj 's fix was a workaround in the `zowe-cli` project, not `npm-cli`

**Comment by t1m0thyj** [comment] 2022-06-13 11:52
@chuanqisun It was fixed in npm in https://github.com/npm/bin-links/pull/28 although perhaps there is a regression?

**Comment by chuanqisun** [comment] 2022-06-18 16:58
@t1m0thyj, I can repro the issue in npm `8.0.0`, node `16.11.0`. I'm using workspace to manage multiple packages in a monorrepo, and it actually works when I `npm install` in the inner package, but fails when I `npm install` in the root package.

UPDATE

Updating to latest node and npm fixed my problem! I didn't know how I have missed that step.
