### ISSUE TITLE
npm ERR! 504 Gateway Time-out whenever I use npm 8

### ISSUE THREAD

**Issue by keerthika-priya** [npm/cli#5943] opened 2022-12-09 06:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [ ] I am using the latest npm

### Current Behavior

I have a project which was using npm 6 before, now while trying to use npm 8.11.0 (that comes with node 16.15.1) I always get **'npm ERR! 504 Gateway Time-out'** when I do npm i

I am only able to do npm i successfully after deleting my package-lock.json file or downgrading to npm 6.
I don't want to delete the package-lock.json file so this issue is stopping me from developing.

`npm ERR! code E504
npm ERR! 504 Gateway Time-out - GET http://10.47.6.199/fk-artifactory-526/npm/react-native-scrollable-tab-header/-/react-native-scrollable-tab-header-0.2.9.tgz
npm verb exit 1
npm timing npm Completed in 275963ms
npm verb unfinished npm timer reify 1670562603242
npm verb unfinished npm timer reify:unpack 1670562604174
npm verb unfinished npm timer reifyNode:node_modules/react-native-scrollable-tab-header 1670562604191
npm verb unfinished npm timer reifyNode:node_modules/normalize-package-data/node_modules/resolve 1670562604198
npm verb unfinished npm timer reifyNode:node_modules/fk-react-native-tab-view 1670562604213
npm verb unfinished npm timer reifyNode:node_modules/fk-react-native-sdk 1670562604213
npm verb unfinished npm timer reifyNode:node_modules/babel-plugin-transform-react-jsx 1670562604224
npm verb unfinished npm timer reifyNode:node_modules/babel-plugin-transform-object-rest-spread 1670562604224
npm verb unfinished npm timer reifyNode:node_modules/babel-plugin-syntax-dynamic-import 1670562604226`

### Expected Behavior

Should be able to do npm i without deleting package-lock

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm: 8.11.0
- Node.js: 16.15.1
- OS Name: Mac 12.6.1
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by milaninfy** [comment] 2024-05-16 15:53
@keerthika-priya  can you try replicating this problem on the latest version of `npm`? (ie. `npm i -g npm`). 
Please fill up complete issues template including Steps to Reproduce, logs and `npm config ls` output.

**Comment by milaninfy** [comment] 2024-05-22 13:33
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.

**Closed as completed by milaninfy** 2024-05-22 13:33 UTC
Labels: Release 8.x, Bug, Needs Triage
