### ISSUE TITLE
[QUESTION] How to avoid "nested aliases not supported"

### ISSUE THREAD

**Issue by alecgibson** [npm/cli#1349] opened 2020-05-26 09:57 UTC
# What / Why

```bash
❯ node -v
v10.16.3
❯ npm -v
6.14.5
```

Sometimes when running `npm install`, we get an error:

```
npm ERR! nested aliases not supported
```

Here's the associated log file:
[2020-05-26T09_33_10_215Z-debug.log](https://github.com/npm/cli/files/4681249/2020-05-26T09_33_10_215Z-debug.log)

We're the `@reedsy` org, and I'm assuming this error is related to the fact that we're running libraries that rely on other libraries with aliases (ie a nested alias).

Obviously one "fix" for this is to remove the nested aliases. _However_, that's a non-ideal fix. Our nested dependency uses an alias, because it's a fork, which we're trying to keep as close to upstream as possible. The only reason we've forked is to tweak one of the underlying dependencies.

The other reason just removing aliases isn't a good fix is that we happen to have control over the nested alias in this case, but presumably a 3rd party library would be within their rights to use an alias, and then we'd have no control over that.

Here's one of the relevant parts of the dependency tree:

```
├─┬ @reedsy/reedsy-sharedb@22.1.5
│ ├─┬ rich-text@npm:@reedsy/rich-text@4.1.0-reedsy.1.0.0
│ │ └─┬ quill-delta@npm:@reedsy/quill-delta@4.2.2-reedsy.1.0.0
```

So in the above:

 - our app imports `@reedsy/reedsy-sharedb` (a library we fully control)
 - `@reedsy/reedsy-sharedb` imports `rich-text` as an alias. To be fair, we could change this from an alias, because we control it, but it probably doesn't matter, because...
 - `rich-text` is a forked library, which we'd like to keep as close to upstream as possible, but with a single change to _its_ dependencies, to point to our own forked version of `quill-delta` (which we do through an alias to avoid changing all the `require` statements in the forked version of `rich-text`)

Weirdly, the fact that it has nested aliases doesn't seem to matter if:

 - using `npm ci` (because it's not trying to update the lockfile?)
 - deleting `package-lock.json`, and regenerating from scratch with `npm install`

So my questions are:

 - _Why_ aren't nested aliases supported? Is it particularly bad practice to have a nested alias?
 - Clearly they can be made to work (see above workarounds), so why doesn't the default `npm install` work?
 - Is this a bug with `npm`?

## Where

* `npm/cli`

## Who

* n/a

## References

* n/a

**Comment by isaacs** [comment] 2020-06-05 01:00
The issue isn't that you have an alias dep which itself has alias deps.  It's that you are somehow getting a double-aliased dep like `foo@npm:bar@npm:baz@1.2.3`.  (That would mean "name the package foo, but actually install `bar@npm:baz@1.2.3` there, and the correct incantation would be `foo@npm:baz@1.2.3`.)

**Comment by alecgibson** [comment] 2020-06-05 07:08
I mean, for now I've just removed the nested aliases because I happen to control the packages, but if I didn't, this wouldn't be great. Would be nice to support this.

**Comment by isaacs** [comment] 2020-06-05 23:58
@alecgibson I don't know if you understand what I'm saying.

`quill-delta@npm:@reedsy/quill-delta@4.2.2-reedsy.1.0.0` isn't a "nested alias".  It should be fine.

So, I suspect that this has to do with something else?  Maybe what's being stored to the lockfile is invalid somehow?  What shows up in your package-lock.json when you delete it and do a from-scratch clean install?  Can you share that file?

**Comment by alecgibson** [comment] 2020-06-08 07:24
@isaacs sorry I think I'm confused by what a nested alias is, then. This is what I have in the problematic `package-lock.json`:

```json
      "@reedsy/reedsy-sharedb": {
      "version": "22.1.5",
      "resolved": "https://npm.pkg.github.com/download/@reedsy/reedsy-sharedb/22.1.5/<hash>",
      "integrity": "<hash>",
      "requires": {
        "@reedsy/reedsy-editor-utilities": "^13.2.4",
        "@reedsy/reedsy-logger-js": "^1.11.4",
        "@types/clone": "^0.1.30",
        "@types/common-tags": "^1.8.0",
        "@types/lru-cache": "^5.1.0",
        "bson-objectid": "^1.3.0",
        "clone": "^2.1.2",
        "common-tags": "^1.8.0",
        "eslint": "^6.7.2",
        "fast-deep-equal": "^3.1.1",
        "fp-ts": "^2.6.0",
        "hot-shots": "^7.4.2",
        "io-ts": "^2.2.2",
        "lru-cache": "^5.1.1",
        "ot-json0": "npm:@reedsy/ot-json0@^1.1.0-reedsy.1.0.0",
        "rich-text": "npm:@reedsy/rich-text@4.1.0-reedsy.1.0.0",
        "sharedb": "^1.3.4"
      },
      "dependencies": {
        "quill-delta": {
          "version": "npm:quill-delta@npm:@reedsy/quill-delta@4.2.2-reedsy.1.0.0",
          "resolved": "https://npm.pkg.github.com/download/@reedsy/quill-delta/4.2.2-reedsy.1.0.0/<hash>",
          "integrity": "<hash>",
          "requires": {
            "fast-diff": "1.2.0",
            "lodash.clonedeep": "^4.5.0",
            "lodash.isequal": "^4.5.0"
          }
        }
      }
    }
```

**Comment by sanjay-sridharan** [comment] 2020-10-19 21:53
For my proprietary package I get the same error, however, I have no workaround:
1. npm ci is not an option because I have modified package.json, therefore, it is out-of-sync with npm-shrinkwrap and package-lock
2. npm i produces the error when I have done the following
  a. Removed node_modules dir
  b. Removed npm-shrinkwrap and package-lock files
  c. [2020-10-19T21_38_50_493Z-debug.log](https://github.com/npm/cli/files/5405010/2020-10-19T21_38_50_493Z-debug.log)

**Comment by darcyclarke** [comment] 2021-06-02 21:21
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 21:21 UTC
Labels: Awaiting Information, Release 6.x
