### ISSUE TITLE
[BUG] "cb() never called!"

### ISSUE THREAD

**Issue by ghost** [npm/cli#3723] opened 2021-09-06 16:57 UTC
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

error message * "ERR! cb() never called!"
log:
[2021-09-06T16_28_38_095Z-debug.log](https://github.com/npm/cli/files/7117165/2021-09-06T16_28_38_095Z-debug.log)
ran the npm install command in a files directory to install a software. i am farely new to npm so ive probabley just done something wrong.. 

### Expected Behavior

npm said it was a problem with itself, this being the reason why ive submitted this but i dont know exactly if its saying its a problem with itself meaning that it, (its actual program) has done somthing wrong- or an error has just become because i have simply done a wrong command* or the files in the folder i was installing cannot be installed,
apoligies if you get this alot.

### Environment

- OS: Windows 10 Home, 10.0.19043, 21H1
- Node: 14.17.3
- npm: 6.14.13

**Comment by tmakuch-vizlib** [comment] 2021-09-08 10:41
To bump the issue - it is reproducible by random jobs on CircleCi for the project we're running as well.

I can not provide log, as everytime I try to rerun the job ssh access the job passes, only info I have for now that it's not an windows-only issue. Our CCI is running linux machine:

```
System information:
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: xfs
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Kernel Version: 4.15.0-1106-aws
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
```

**Comment by awebdev** [comment] 2021-09-09 22:54
I'm running into similar issue on my Macbook any solutions?? tried verifying+busting cache 
```
❯ node -v
v12.22.6

❯ npm -v
6.14.15
```
OS: MacOS BigSur 11.5.1 

logs:
```
❯ npm i grunt --loglevel=silly                                                                           18:18:57
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'i',
npm verb cli   'grunt',
npm verb cli   '--loglevel=silly'
npm verb cli ]
npm info using npm@6.13.4
npm info using node@v12.15.0
npm verb npm-session 77aafaf861f6005e
npm sill install loadCurrentTree
npm sill install readLocalPackageData
npm http fetch GET 304 https://npm.xxxxxxxxxx.com/grunt 861ms (from cache)
npm sill pacote tag manifest for grunt@latest fetched in 872ms
npm timing stage:loadCurrentTree Completed in 890ms
npm sill install loadIdealTree
npm sill install cloneCurrentTreeToIdealTree
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
npm sill install loadShrinkwrap
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 0ms
npm sill install loadAllDepsIntoIdealTree
npm sill resolveWithNewModule grunt@1.4.1 checking installable status
npm http fetch GET 304 https://npm.xxxxxxxxxx.com/dateformat 316ms (from cache)
npm sill pacote range manifest for dateformat@~3.0.3 fetched in 319ms
npm sill resolveWithNewModule dateformat@3.0.3 checking installable status
npm http fetch GET 304 https://npm.xxxxxxxxxx.com/js-yaml 276ms (from cache)
npm sill pacote range manifest for js-yaml@~3.14.0 fetched in 278ms
npm sill resolveWithNewModule js-yaml@3.14.1 checking installable status
npm http fetch GET 304 https://npm.xxxxxxxxxx.com/findup-sync 821ms (from cache)
npm http fetch GET 304 https://npm.xxxxxxxxxx.com/exit 873ms (from cache)
npm http fetch GET 304 https://npm.xxxxxxxxxx.com/grunt-known-options 870ms (from cache)
npm http fetch GET 304 https://npm.xxxxxxxxxx.com/grunt-legacy-util 869ms (from cache)
npm http fetch GET 304 https://npm.xxxxxxxxxx.com/grunt-legacy-log 872ms (from cache)
npm http fetch GET 304 https://npm.xxxxxxxxxx.com/iconv-lite 871ms (from cache)
npm http fetch GET 304 https://npm.xxxxxxxxxx.com/eventemitter2 883ms (from cache)
npm http fetch GET 304 https://npm.xxxxxxxxxx.com/grunt-cli 881ms (from cache)
npm sill pacote range manifest for grunt-known-options@~2.0.0 fetched in 882ms
npm sill resolveWithNewModule grunt-known-options@2.0.0 checking installable status
npm sill pacote range manifest for grunt-legacy-util@~2.0.1 fetched in 881ms
npm sill resolveWithNewModule grunt-legacy-util@2.0.1 checking installable status
npm sill pacote range manifest for iconv-lite@~0.4.13 fetched in 884ms
npm sill resolveWithNewModule iconv-lite@0.4.24 checking installable status
npm sill pacote range manifest for grunt-legacy-log@~3.0.0 fetched in 886ms
npm sill resolveWithNewModule grunt-legacy-log@3.0.0 checking installable status
npm sill pacote range manifest for grunt-cli@~1.4.2 fetched in 892ms
npm sill resolveWithNewModule grunt-cli@1.4.3 checking installable status
npm http fetch GET 304 https://npm.xxxxxxxxxx.com/minimatch 302ms (from cache)
npm http fetch GET 304 https://npm.xxxxxxxxxx.com/glob 904ms (from cache)
npm sill pacote range manifest for glob@~7.1.6 fetched in 910ms
npm sill resolveWithNewModule glob@7.1.7 checking installable status
npm http fetch GET 304 https://npm.xxxxxxxxxx.com/nopt 479ms (from cache)
npm http fetch GET 304 https://npm.xxxxxxxxxx.com/mkdirp 481ms (from cache)
npm http fetch GET 304 https://npm.xxxxxxxxxx.com/rimraf 480ms (from cache)
npm sill pacote range manifest for mkdirp@~1.0.4 fetched in 486ms
npm sill resolveWithNewModule mkdirp@1.0.4 checking installable status
npm sill pacote range manifest for rimraf@~3.0.2 fetched in 483ms
npm sill resolveWithNewModule rimraf@3.0.2 checking installable status
npm timing npm Completed in 2706ms
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/apotlapally/.npm/_logs/2021-09-09T23_19_12_781Z-debug.log
```

**Comment by yxlee61** [comment] 2021-09-13 14:28
I'm running into similar issue with pipeline build in Azure Devops. The difference between the failed build and the last successful build is the npm version (upgrade from 6.14.14 to 6.14.15)
```
C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\nodejs\npm.cmd" --version"
6.14.15
C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\nodejs\npm.cmd" config list"
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.14.15 node/v14.17.6 win32 x64"

; environment configs
prefix = "C:\\npm\\prefix"
userconfig = "D:\\a\\1\\npm\\31149.npmrc"

; globalconfig C:\npm\prefix\etc\npmrc
cache = "C:\\npm\\cache"

; builtin config undefined

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = D:\a\1\s\clients\ionleaks
; HOME = C:\Users\VssAdministrator
; "npm config ls -l" to show all defaults.

C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\nodejs\npm.cmd" install"
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>
```

**Comment by ghost** [comment] 2021-09-17 08:17
I  get the issue on jenkins with  E401
```
+ npm install
npm ERR! code E401
npm ERR! Incorrect or missing password.
```
after a research in the internet I add the npm login.
    jenkins pipeline:
```
    stage('NPM Install') {
      steps {
        nodejs(nodeJSInstallationName: 'node_15_11_0') {
          sh 'npm config ls'
          sh 'npm login'
          sh 'npm install'
        }
      }
    }
```
and get following error:
```
; Run `npm config ls -l` to show all defaults.
[Pipeline] sh
+ npm login
npm notice Log in on https://registry.npmjs.org/
Username: npm ERR! cb() never called!
```

**Comment by lukekarrys** [comment] 2021-09-23 00:35
@awebdev can you try replicating this problem on the latest version of `npm`? (ie. `npm i -g npm`)

**Comment by lukekarrys** [comment] 2021-09-23 00:36
@cawena That looks like it is a different issue, please use our [issue template](https://github.com/npm/cli/issues/new/choose) & review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs) to file a new issue.

**Comment by lukekarrys** [comment] 2021-09-23 00:37
**Closing:** In general, this error with `ERR! cb() never called!` can arise for a number of reasons; Please read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) & refile an issue with as much information as possible if you're able to **consistently reproduce** this error.

**Closed as completed by lukekarrys** 2021-09-23 00:37 UTC
Labels: Release 7.x, Bug, Needs Triage
