### ISSUE TITLE
  run `npm fund` for details doesn't work

### ISSUE THREAD

**Issue by pleabargain** [npm/cli#5173] opened 2022-07-15 08:52 UTC
I just updated npm 
in the message I see
  run `npm fund` for details

I ran npm fund and got
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

**Comment by ljharb** [comment] 2022-07-15 16:48
What version of npm did you update to?

**Comment by pleabargain** [comment] 2022-07-16 08:15
latest

**Comment by ljharb** [comment] 2022-07-16 15:17
That changes week to week. 8.14.0?

**Comment by pleabargain** [comment] 2022-07-18 08:06
8.14.0
correct 

see screengrab below

I just updated npm again then ran npm fund and got zero results.

<img width="391" alt="image" src="https://user-images.githubusercontent.com/640846/179469114-f8dd4e60-b06a-40bc-8173-9337818c2355.png">

**Comment by wraithgar** [comment] 2022-07-21 15:38
Duplicate of https://github.com/npm/cli/issues/3112

**Closed as completed by wraithgar** 2022-07-21 15:38 UTC
