### ISSUE TITLE
[QUESTION] <npm-dependency-module-version>

### ISSUE THREAD

**Issue by alanhe421** [npm/cli#831] opened 2020-02-15 16:41 UTC
Just like the dependencies shown in the figure, I want to know, for example, when we package the front end, the package version we packaged in, such as hello, will be 0.1.2 or 0.2.8?

package tool like webpack

![image](https://user-images.githubusercontent.com/9245110/74591694-084e1a80-5055-11ea-8441-866be55abd0a.png)

**Comment by ljharb** [comment] 2020-02-15 16:44
It’d be both - you’ll get two copies of “hello”.

**Comment by alanhe421** [comment] 2020-02-15 16:49
> It’d be both - you’ll get two copies of “hello”.

I understand that in physical space, there are actually two versions. My question is, which version of vendor.js will be in the front end, such as packaging, or will both exist.

**Comment by ljharb** [comment] 2020-02-15 17:42
Both will be present, because `bar` requires `hello@0.2.8` and `foo` requires `hello@0.1.2`, and those aren't compatible, so foo and bar can't share a `hello` instance.

**Comment by alanhe421** [comment] 2020-02-15 17:52
> Both will be present, because `bar` requires `hello@0.2.8` and `foo` requires `hello@0.1.2`, and those aren't compatible, so foo and bar can't share a `hello` instance.

I also have a question. If you directly and indirectly depend on different versions of the same package, I tested and found that only the directly dependent version will be installed in the node  modules . Is this correct?

This scenario is different from indirectly relying on multiple versions.

![image](https://user-images.githubusercontent.com/9245110/74592692-ccb84e00-505e-11ea-9c0b-1161b270ab69.png)

**Comment by ljharb** [comment] 2020-02-15 17:54
you can't directly rely on multiple versions, only transitively.

**Comment by alanhe421** [comment] 2020-02-15 17:57
You do n’t understand the meaning, please see the picture clearly, I want to express that this project directly depends on hello, and indirectly depends on hello, and the version is different.

**Comment by ljharb** [comment] 2020-02-15 17:58
In that case you'll still get two copies, same as in the first scenario.

**Comment by alanhe421** [comment] 2020-02-16 01:54
> first

I got it,I directly checked the packaged file of vendor.js and found out that as you said, in fact both will exist. At this time, I still have a question, that is, `in the second scenario, in our code, the function hello is imported. In Webpack's logic, do we import 0.1.2 or 0.2.8?`

I understand that the default is directly dependency, which is 0.1.2.

`in the first scenario, in our code, the function hello is imported. In Webpack's logic, do we import 0.1.2 or 0.2.8?`

In addition, `what you call incompatible means that as long as the version numbers are different, are they incompatible, or do we need to consider semver?`

I think the information is incomplete

**Comment by ljharb** [comment] 2020-02-16 03:58
The package.json and npm consider semver; once they’re installed, any duplication of non identical versions imo should be treated as an important one - meaning, semver is considered only at install time, not at build time or run time.

**Comment by darcyclarke** [comment] 2021-06-02 21:55
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 21:55 UTC
Labels: Awaiting Information
