### ISSUE TITLE
npm v10 does not install .tgz dependencies into other .tgz pedencencies 

### ISSUE THREAD

**Issue by jpsandovaln** [npm/cli#7630] opened 2024-07-08 03:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

- npm does not install .tgz dependencies within .tgz dependencies

**Description:**
The issue occurred when upgrading from node 14.21.3 (npm 6.14.18) to node 20.12.2 (npm 10.5.0)
only the dependencies added in the package.json were installed into node_modules the linked dependencies are lost

### Expected Behavior

- All dependencies must be installed, the main ones and the linked ones

### Steps To Reproduce

Currently we have 2 projects, the first (project A) which is made up of several packages that each generate a different .tgz file which depends on itself and the second (project B) is the main one that consumes these generated tgz.
Below I illustrate with an example

![image](https://github.com/npm/cli/assets/35410949/0e139513-8b9d-4880-b203-91e318ac0bcf)

The second project B consumes the dependencies generated in project A

![image](https://github.com/npm/cli/assets/35410949/1239847a-f407-47f0-afbf-a90b13d9a981)

When the `npm install ` instruction is run in project B, only the dependencies added in the package.json file, that is, ServerCore.tgz and generalCore.tgz, are installed.
but they should all be installed and appear in node_modules

- serverCore.tgz
- generalCore.tgz
- cache.tgz
- database.tgz
- apikey.tgz
- logger.tgz
- email.tgz

**package.json file from project B**

```
{
  "name": "app",
  "dependencies": {
        "@babel/runtime": "7.18.x",
        "@myproject/server-core": "file:./serverCore.tgz",
        "@myproject/general-core": "file:./generalCore.tgz"
  }
}
```

### Environment

- npm: 10.5.0
- Node.js: 14.21.3

**Comment by dhei** [comment] 2024-07-09 00:35
👋 Hi @jpsandovaln, do you mind provide a minimal version of repro?

Based on your description, I have tried a minimal setup like this myself:

1. package `myapp` depends on package `dep1` 
>"dependencies": {"dep1": "file:../dep1/dep1-1.0.0.tgz"}
2. package `dep1` depends on package `dep2` and `dep3`
>"dependencies": {"dep2": "file:../dep2/dep2-1.0.0.tgz", "dep3": "file:../dep3/dep3-1.0.0.tgz"}
3. package `dep2` and `dep3` has no dependencies
4. with node 20.12.2 (npm 10.5.0), I tried `npm install` from `myapp` folder, it gets `dep1`, `dep2` and `dep3` all installed as expected.

**Comment by jpsandovaln** [comment] 2024-07-09 19:43
Hi @dhei thanks for response,
Taking your example, the problem would be if `dep2 and dep3` have dependencies on other .tgz, I will prepare a simple example with the issue reproduced and post it to this chat when I finish, thanks again

**Comment by jpsandovaln** [comment] 2024-07-11 12:24
Hi @dhei I created a repository on github with a simple project, please could you review it? https://github.com/jpsandovaln/ReproduceIssue/

**Comment by dhei** [comment] 2024-07-12 22:12
@jpsandovaln Thanks for sharing the repro.

The error seems to be the relative file path of the nested .tgz dependency isn't being resolved correctly. Specifically, `"@projecta/logger": "file:./../logger/projecta-logger-1.0.0.tgz"`
(https://github.com/jpsandovaln/ReproduceIssue/blob/master/ProjectA/packages/general-core/package.json#L10) isn't getting resolved as a tgz in `vendor` directory when installing from ProjectB.

One way to overcome this is to [`overrides`](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#overrides) the nested .tgz dependencies in your ProjectB's package.json with the a relative file path. Here is what I tried https://github.com/dhei/ReproduceIssue/commit/5e3637f6405bb2b9a307308b64c41b8192ec5ee1 and it works.

**Comment by jpsandovaln** [comment] 2024-07-17 16:18
Thanks @dhei I will try it, I will let's you know if it is working for me, thanks again

**Comment by jpsandovaln** [comment] 2024-07-18 14:02
@dhei , Yes it worked, thank you very much.

**Comment by dhei** [comment] 2024-07-18 16:12
Glad it works for you. Closing this issue.

**Closed as completed by dhei** 2024-07-18 16:12 UTC
Labels: Bug, Needs Triage
