### ISSUE TITLE
[BUG] Updating NPM causes Command Not Found

### ISSUE THREAD

**Issue by sumanthratna** [npm/cli#700] opened 2020-01-16 23:08 UTC
# What / Why
If the user makes a mistake and tries to update NPM without Internet, they will be unable to use NPM. 

## When
Updating NPM via `npm install -g npm` results in:
```
npm WARN registry Using stale data from https://registry.npmjs.org/ because the host is inaccessible -- are you offline?
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
npm ERR! code EEXIST
npm ERR! syscall symlink
npm ERR! path ../../../lib/node_modules/npm/man/man1/npm-adduser.1
npm ERR! dest /usr/local/share/man/man1/npm-adduser.1
npm ERR! errno -17
npm ERR! EEXIST: file already exists, symlink '../../../lib/node_modules/npm/man/man1/npm-adduser.1' -> '/usr/local/share/man/man1/npm-adduser.1'
npm ERR! File exists: /usr/local/share/man/man1/npm-adduser.1
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2020-01-16T16_30_31_460Z-debug.log
```

Running `npm run [SCRIPT]` results in `zsh: command not found: npm`. 

### Steps to Reproduce
Disconnect from Internet and run `npm install -g npm` on v6.13.4. 

### Expected Behavior
Shouldn't uninstall npm.

**Comment by garretthyder** [comment] 2020-01-17 18:22
Hello, I'm also experiencing this issue trying to upgrade from v6.13.4 to v6.13.6 using `npm install -g npm`. In my case I have full internet access so don't believe that's the cause. It seems the failed install removes npm from my system and I have to reinstall node to restore it `brew reinstall node`.

I'm using macOS Catalina 10.15.2

**Comment by jorisgeer** [comment] 2020-02-14 07:23
Same issue here updating from 6.13.4 → 6.13.7 

As npm recommends this upgrade on each commandline invocation, I vote for raising the severity of this issue.

**Comment by darcyclarke** [comment] 2021-06-02 21:45
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 21:45 UTC
Labels: Bug
