### ISSUE TITLE
[QUESTION] Problems with the Cloudflare caching layer?

### ISSUE THREAD

**Issue by michaelsbradleyjr** [npm/cli#482] opened 2019-11-14 17:17 UTC
# What / Why

Earlier today a new version of a package I use was published: `web3@1.2.3`. It has various `web3-[pkg]` dependencies, and all of them were likewise published earlier today at version `1.2.3`.

What I'm finding is that `npm i web3@1.2.3` is not succeeding consistently. npm reports that `web3-[pkg]` doesn't have a version matching `1.2.3`, where `[pkg]` could be `eth`, `core`, `core-helpers`, etc.

```
$ npm i web3@1.2.3
npm WARN deprecated @types/bignumber.js@5.0.0: This is a stub types definition for bignumber.js (https://github.com/MikeMcl/bignumber.js/). bignumber.js provides its own type definitions, so you don't need @types/bignumber.js installed!
npm ERR! code ETARGET
npm ERR! notarget No matching version found for web3-eth@1.2.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'web3'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/michael/.npm/_logs/2019-11-14T16_52_47_357Z-debug.log

$ npm i web3@1.2.3
npm WARN deprecated @types/bignumber.js@5.0.0: This is a stub types definition for bignumber.js (https://github.com/MikeMcl/bignumber.js/). bignumber.js provides its own type definitions, so you don't need @types/bignumber.js installed!
npm ERR! code ETARGET
npm ERR! notarget No matching version found for web3-core-helpers@1.2.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'web3-core'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/michael/.npm/_logs/2019-11-14T16_52_54_636Z-debug.log
```

However, `npm show web3-[pkg] version` mostly reports `1.2.3`, occasionally still `1.2.2`.

Trying, for example:

```
curl https://registry.npmjs.org/web3-core/?foo=blahblah | grep "1\.2\.3"
```

I get the hoped for result, i.e. the JSON response does have version `1.2.3`.

But, without the query param:

```
curl https://registry.npmjs.org/web3-core/ | grep "1\.2\.3"
```

It often doesn't have `1.2.3`. Looking at the response headers with `curl -I` I see Cloudflare stuff. So I'm wondering if something's going wrong with Cloudflare and/or with communication between Cloudflare and the registry servers.

I realize it probably does take a bit of time for the Cloudflare layer to catch up, but I haven't previously experienced a long delay like this.

Also, my apologies if this isn't the best place to file this issue. With the discussion forum archived, I wasn't sure what's the best place.

## Where

* npm public registry

## Who

* n/a

## References

* n/a

**Comment by Jolg42** [comment] 2021-04-12 14:21
We're having many issues since a few days, we have to wait and retry multiple times after publishing a new version for our packages.

It fails with `No matching version found for <packageName#previousVersion>` and goes away sometimes after waiting more than 10 minutes. Which is a bit too long, it was working fine before (2 weeks ago for example.)

**Comment by darcyclarke** [comment] 2021-06-02 21:45
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 21:45 UTC
Labels: Awaiting Information
