### ISSUE TITLE
[BUG] <stuck in (⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠇ idealTree:lib: sill idealTree buildDeps>

### ISSUE THREAD

**Issue by baebae-dev** [npm/cli#5331] opened 2022-08-21 14:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

now i using 
node -v : v18.7.0
npm -v : v8.15.0

i installed node and npm
and now i trying to install vue-cli to using vue.js

but i stuck in (⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠇ idealTree:lib: sill idealTree buildDeps
when i did ```npm install -g @vue/cli```

ㅠㅠ

i did remove all and install n times...
and  npm set registry http://registry.npmjs.org/
and npm set strict-ssl false

but all things not help to resolve
plz help me 

i'm very thank u for all the advices

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm: 8.15.0
- Node.js: v18.7.0
- OS Name: Mac M1

**Comment by furstenheim** [comment] 2023-10-03 21:17
I'm seeing the same issue with npm v9. Using npm v10 or npm v6 fixes the issue. 

In my case I can see that traceroute for npmjs is not very good:

```
traceroute npmjs.org
traceroute to npmjs.org (104.16.28.34), 64 hops max
  1   192.168.0.1  5,641ms  2,491ms  106,954ms 
  2   *  *  * 
  3   *  *  * 
  4   *  *  * 
  5   *  *  * 
  6   181.89.51.39  59,006ms  18,690ms  * 
  7   181.13.127.246  59,856ms  11,706ms  11,498ms 
  8   104.16.28.34  11,546ms  12,759ms  10,935ms
```

**Comment by milaninfy** [comment] 2024-05-24 18:55
@baebae-dev. `npm install -g @vue/cli` in latest npm(10.8.0) is getting executed without any error. 
Can you try replicating this problem on the latest version of `npm`? (ie. `npm i -g npm`)

**Comment by milaninfy** [comment] 2024-05-30 12:53
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.

**Closed as not planned by milaninfy** 2024-05-30 12:54 UTC
Labels: Release 8.x, Bug, Needs Triage
