### ISSUE TITLE
[BUG] NPM install seems to scope down os/arch of images in `package-lock.js` to only what exists in `node_modules`

### ISSUE THREAD

**Issue by ThomasShih** [npm/cli#7493] opened 2024-05-09 14:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

For some reason, when regenerating `package-lock.js`, it seems like NPM takes only the images from what exist in node_modules (ie your os and arch type) and puts that into the `package-lock.js`. This means that the `package-lock.js` is now only valid for your machines like yours and not a different Os or Arch.

### Expected Behavior

Package-lock ignores the packages what exist in node_module and regenerates only based off whats in package.json. And that not specifying a `--os` or `--cpu` means images for all os and archs are stored in package-lock.

### Steps To Reproduce

In a brand new directory
1. git init (to see changes) and gitignore the node_modules
2. npm init
3. npm install a package that has more than one image for various os and cpu, such as `npm install @angular-devkit/build-angular`
4. git commit 
5. `rm package-lock.json`
6. npm install
7. observe the change detection showing that non-local os/cpu images are deleted:

![image](https://github.com/npm/cli/assets/55861476/0a6014f1-159c-4e20-ab90-dc550ceea9fc)

### Environment

- npm: v10.7.0
- Node.js: v20.11.0
- OS Name: darwin arm64
- System Model Name: Macbook M series
- npm config:
```ini
; node bin location = /Users/<name>/.nvm/versions/node/v20.11.0/bin/node
; node version = v20.11.0
; npm local prefix = /Users/<name>/Documents/GitHub/npm-cli-test
; npm version = 10.7.0
; cwd = /Users/<name>/Documents/GitHub/npm-cli-test
; HOME = /Users/<name>
; Run `npm config ls -l` to show all defaults.
```

**Comment by wraithgar** [comment] 2024-05-09 20:17
This is the same root cause as https://github.com/npm/cli/issues/6301. Closing as duplicate of that.

**Closed as not planned by wraithgar** 2024-05-09 20:17 UTC
Labels: Bug, Needs Triage, Release 10.x
