### ISSUE TITLE
[BUG] Publishing with npmlibpublish returns status 429

### ISSUE THREAD

**Issue by eTech-Source** [npm/cli#7784] opened 2024-09-18 00:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When I send a request with npmlibpublish I get a 429 error:

```lang-none
: 429 Too Many Requests - PUT https://registry.npmjs.org/universal-fs
    at /Users/ekrich/projects/universal-fs/node_modules/.pnpm/npm-registry-fetch@17.1.0/node_modules/npm-registry-fetch/lib/check-response.js:95:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async publish (/Users/ekrich/projects/universal-fs/node_modules/.pnpm/libnpmpublish@9.0.9/node_modules/libnpmpublish/lib/publish.js:53:15)
    at async publishPkg (file:///Users/ekrich/projects/universal-fs/build/publish.mjs:45:5) {
  headers: [Object: null prototype] {
    date: [ 'Wed, 18 Sep 2024 00:19:58 GMT' ],
    'content-type': [ 'text/html; charset=UTF-8' ],
    'content-length': [ '5399' ],
    connection: [ 'keep-alive' ],
    'retry-after': [ '1934' ],
    'x-frame-options': [ 'SAMEORIGIN' ],
    'referrer-policy': [ 'same-origin' ],
    'cache-control': [
      'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0'
    ],
    expires: [ 'Thu, 01 Jan 1970 00:00:01 GMT' ],
    vary: [ 'Accept-Encoding' ],
    server: [ 'cloudflare' ],
    'cf-ray': [ '8c4d2ae27e202efe-LAX' ],
    'x-fetch-attempts': [ '1' ]
  },
  statusCode: 429,
  code: 'E429',
  method: 'PUT',
  uri: 'https://registry.npmjs.org/universal-fs',
  body: Buffer(5399) [Uint8Array] [
     60,  33,  68,  79,  67,  84,  89,  80,  69,  32, 104, 116,
    109, 108,  62,  10,  60,  33,  45,  45,  91, 105, 102,  32,
    108, 116,  32,  73,  69,  32,  55,  93,  62,  32,  60, 104,
    116, 109, 108,  32,  99, 108,  97, 115, 115,  61,  34, 110,
    111,  45, 106, 115,  32, 105, 101,  54,  32, 111, 108, 100,
    105, 101,  34,  32, 108,  97, 110, 103,  61,  34, 101, 110,
     45,  85,  83,  34,  62,  32,  60,  33,  91, 101, 110, 100,
    105, 102,  93,  45,  45,  62,  10,  60,  33,  45,  45,  91,
    105, 102,  32,  73,
    ... 5299 more items
  ],
  pkgid: 'universal-fs@2.0.0-canary-2'
}
```

Here is my code:
```lang-js
 const manifest = await pacote.manifest(".");
    const tarData = await pacote.tarball("dist");

    // @ts-ignore
    await publish(manifest, tarData, {
      npmVersion: `universal-fs@${currentVersion}`,
      token: process.env.NPM_TOKEN,
      defaultTag: baseBranch === "main" ? "latest" : "canary"
    });
```

I have confirmed all directories exist.

### Expected Behavior

It should publish a new version `2.0.0-canary-2` to npm.

### Steps To Reproduce

1. In this environment...
```

  System:
    OS: macOS 15.0
    CPU: (12) arm64 Apple M2 Max
    Memory: 533.08 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.5.1 - ~/.nvm/versions/node/v22.5.1/bin/node
    npm: 10.8.3 - ~/.nvm/versions/node/v22.5.1/bin/npm
    pnpm: 9.10.0 - ~/Library/pnpm/pnpm
    bun: 1.1.26 - ~/.bun/bin/bun
  Managers:
    Cargo: 1.78.0 - ~/.cargo/bin/cargo
    Homebrew: 4.3.19 - /opt/homebrew/bin/brew
    pip3: 24.0 - /opt/homebrew/bin/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 16.0.0 - /usr/bin/gcc
    Git: 2.39.5 - /usr/bin/git
    Clang: 16.0.0 - /usr/bin/clang
    FFmpeg: 7.0.1 - /opt/homebrew/bin/ffmpeg
    Curl: 8.7.1 - /usr/bin/curl
    OpenSSL: 3.3.1 - /opt/homebrew/bin/openssl
  Servers:
    Apache: 2.4.59 - /usr/sbin/apachectl
  Virtualization:
    Docker: 27.0.3 - /usr/local/bin/docker
  SDKs:
    iOS SDK:
      Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
  IDEs:
    VSCode: 1.93.1 - /usr/local/bin/code
    Vim: 9.0 - /usr/bin/vim
    Xcode: 16.0/16A242d - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 21.0.2 - /usr/bin/javac
    Perl: 5.34.1 - /usr/bin/perl
    Python3: 3.12.4 - /opt/homebrew/bin/python3
    Ruby: 2.6.10 - /usr/bin/ruby
    Rust: 1.78.0 - /Users/ekrich/.cargo/bin/rustc
  Databases:
    SQLite: 3.43.2 - /usr/bin/sqlite3
  Browsers:
    Safari: 18.0
```
3. With this config...
No special config. Code is added above.
5. Run '...'
```lang-js
 const manifest = await pacote.manifest(".");
    const tarData = await pacote.tarball("dist");

    // @ts-ignore
    await publish(manifest, tarData, {
      npmVersion: `universal-fs@${currentVersion}`,
      token: process.env.NPM_TOKEN,
      defaultTag: baseBranch === "main" ? "latest" : "canary"
    });
```
7. See error...

```lang-none
: 429 Too Many Requests - PUT https://registry.npmjs.org/universal-fs
    at /Users/ekrich/projects/universal-fs/node_modules/.pnpm/npm-registry-fetch@17.1.0/node_modules/npm-registry-fetch/lib/check-response.js:95:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async publish (/Users/ekrich/projects/universal-fs/node_modules/.pnpm/libnpmpublish@9.0.9/node_modules/libnpmpublish/lib/publish.js:53:15)
    at async publishPkg (file:///Users/ekrich/projects/universal-fs/build/publish.mjs:45:5) {
  headers: [Object: null prototype] {
    date: [ 'Wed, 18 Sep 2024 00:19:58 GMT' ],
    'content-type': [ 'text/html; charset=UTF-8' ],
    'content-length': [ '5399' ],
    connection: [ 'keep-alive' ],
    'retry-after': [ '1934' ],
    'x-frame-options': [ 'SAMEORIGIN' ],
    'referrer-policy': [ 'same-origin' ],
    'cache-control': [
      'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0'
    ],
    expires: [ 'Thu, 01 Jan 1970 00:00:01 GMT' ],
    vary: [ 'Accept-Encoding' ],
    server: [ 'cloudflare' ],
    'cf-ray': [ '8c4d2ae27e202efe-LAX' ],
    'x-fetch-attempts': [ '1' ]
  },
  statusCode: 429,
  code: 'E429',
  method: 'PUT',
  uri: 'https://registry.npmjs.org/universal-fs',
  body: Buffer(5399) [Uint8Array] [
     60,  33,  68,  79,  67,  84,  89,  80,  69,  32, 104, 116,
    109, 108,  62,  10,  60,  33,  45,  45,  91, 105, 102,  32,
    108, 116,  32,  73,  69,  32,  55,  93,  62,  32,  60, 104,
    116, 109, 108,  32,  99, 108,  97, 115, 115,  61,  34, 110,
    111,  45, 106, 115,  32, 105, 101,  54,  32, 111, 108, 100,
    105, 101,  34,  32, 108,  97, 110, 103,  61,  34, 101, 110,
     45,  85,  83,  34,  62,  32,  60,  33,  91, 101, 110, 100,
    105, 102,  93,  45,  45,  62,  10,  60,  33,  45,  45,  91,
    105, 102,  32,  73,
    ... 5299 more items
  ],
  pkgid: 'universal-fs@2.0.0-canary-2'
}
```

### Environment

- npm: `10.8.3`
- Node.js: `v22.5.1`
- OS Name: `macOS sequoia`
- System Model Name: Macbook Pro M2 Max (32gb ram, 1tb storage) on external studio display
- npm config: none
```ini
; "user" config from /Users/ekrich/.npmrc

//registry.npmjs.org/:_authToken = (protected)

; node bin location = /Users/ekrich/.nvm/versions/node/v22.5.1/bin/node
; node version = v22.5.1
; npm local prefix = /Users/ekrich/projects/universal-fs
; npm version = 10.8.3
; cwd = /Users/ekrich/projects/universal-fs
; HOME = /Users/ekrich
; Run `npm config ls -l` to show all defaults.
```

**Comment by milaninfy** [comment] 2024-09-23 13:22
Checkout these issues and see if the solutions there fixes your issue.  https://github.com/npm/cli/issues/4250 https://github.com/npm/cli/issues/7091

Closing this one as duplicate of these, feel free to reopen if this issue persist.

**Closed as not planned by milaninfy** 2024-09-23 13:22 UTC
Labels: Bug, Needs Triage
