### ISSUE TITLE
Unable to connect to internet for npm installation from application (from VSCode)

### ISSUE THREAD

**Issue by bhagavs** [npm/cli#5020] opened 2022-06-15 07:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I am installing the npm packages using npm install from VS Code for my project solution. I am setting up the solution in a VM running in private network. Therefore, I need to set proxies for the same using npm commands before that. I should be able to install the packages from the internet. 

### Expected Behavior

The npm packages does not get installed even after using npm install --force.  I am getting '!!tunneling socket could not be established, cause=write EPROTO 18100:error:1408F10B: SSL routines: ssl3_get_record:wrong version number:' error. 

### Steps To Reproduce

npm set strict-ssl false 

npm config set registry https://registry.npmjs.org/

npm config set proxy http://kumaraz:xxxxxxxx@host:port/

npm config set https-proxy http://kumaraz:xxx@host:port/

npm config set http-proxy http://kumaraz:xxx@host:port/

npm install --force
![VSCode Error and proxy config with and without certicates](https://user-images.githubusercontent.com/107538805/173772486-b696e130-8ec3-4628-ac71-7fd0d0337205.PNG)

### Environment

- npm: 8.1.2
- 
- Node.js: 16.13.2
- OS Name: Windows 10
- System Model Name: VM
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by milaninfy** [comment] 2024-05-24 19:13
@bhagavs Not enough information to reproduce the issue. I was not able to reproduce this with latest npm@10.8.0. 
If this is still an issue for you, can you try replicating this problem on the latest version of `npm`? (ie. `npm i -g npm`)  
Provide the logs and configs.

**Comment by milaninfy** [comment] 2024-05-30 12:52
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.

**Closed as not planned** 2024-05-30 12:54 UTC
Labels: Release 8.x, Bug, Needs Triage
