### ISSUE TITLE
Not able to use all commands of npm in Version 7.20.6

### ISSUE THREAD

**Issue by AkashJeedigunta** [npm/cli#3662] opened 2021-08-18 18:18 UTC
Hi,

I am trying to migrate from npm 6.x to npm 7.x, which was successful after so many trials

Currently, I have

NPM: 7.20.6
NODE: 14.16.1

However, every time I want to use commands like `npm audit`, `npm outdated`, `npm update` on my packages I see these errors

`npm verb stack HttpErrorAuthUnknown: Unable to authenticate, need: BASIC realm="Sonatype Nexus Repository Manager"
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:84:17
npm verb stack     at processTicksAndRejections (internal/process/task_queues.js:93:5)
npm verb stack     at async Arborist.[nodeFromEdge] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:987:19)
npm verb stack     at async Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:867:11)
npm verb stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:203:7)
npm verb stack     at async Promise.all (index 1)
npm verb stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:141:5)
npm verb stack     at async Install.install (/usr/local/lib/node_modules/npm/lib/install.js:150:5)`

BASIC realm="Sonatype Nexus Repository Manager" being so painful and not able to resolve how much ever I tried 

AND 

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree`

even when I run `rm -rf node_modules` & `rm -rf package-lock.json` the results are not helpful

I need some assistance. Please let me know if you need anything else from my error stack

Thank you all!

**Comment by darcyclarke** [comment] 2021-12-01 05:21
1. Please use our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).
2. If you're having trouble with a third party registry configuration (ex. Sonatype) you may want to double check your `.npmrc` & other config values are set properly (ex. run `npm config ls` to see all your settings & ensure they are correct, especially any related to authentication... which you may need to provide some kind of basic auth creds in the `registry` config for something like Nexus, afaicr)
3. If you're having issues with `ERESOLVE` errors because of conflicting peer dependencies you have three options:
  1. Fix the conflicts yourself (pretty tough)
  2. Run `npm install` with `--force` (which may have unintended consequences of upgrading/downgrading certain peer deps to resolve the conflicts
  3. Run `npm install` (or other commands) with `--legacy-peer-deps` (which should resolve most of your issues by ignoring peer dependencies like historical versions of npm did)
4. Try upgrading to the latest version of `npm` (ie. `npm i -g npm`) & reproducing your issues

I'm going to close this for now but will reopen if you find that you're still having issues & can provide a reproduction case of the problem (also, please update the issue/thread following the issue template referenced above)

**Closed as completed by darcyclarke** 2021-12-01 05:21 UTC
