### ISSUE TITLE
[BUG] Exit handler never called!

### ISSUE THREAD

**Issue by benosmond** [npm/cli#7665] opened 2024-07-18 19:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`npm install` fails with error:
> Exit handler never called!

This also happens when running `npm ci` and `npm i --no-package-lock`.

Only happens on one machine, works fine in CI pipeline as well as on other machines.

### Expected Behavior

`npm install` succeeds and installs dependencies.

### Steps To Reproduce

It's happening any time I run `npm i` on my machine, and not on any others with the same project. I've tried:

- Reinstalling Node
- Deleting and re-cloning the repository
- Using `npm ci` and `npm i --no-package-lock`
- Cleaning the NPM cache with `npm cache clean --force`
- Changing NPM version back to v6
  This gave a different error to before, but still didn't work.
- Deleting node_modules and trying again
- Checking if there were any proxy settings (there arent')
- Removing the private package feed and using NPM as the registry
- Setting progress=false in NPM config
- Turning the loglevel to info. It all looks fine until it gives the error.
- Deleting .npmrc in the project and in my user directory.

### Environment

- using npm@10.8.2
- using node@v22.5.0
- Windows 11
- System Model Name: Lenovo
- npm config:
```ini
; "user" config from C:\Users\Ben.Osmond\.npmrc

//pkgs.dev.azure.com/bentleycs/Seequent/_packaging/Seequent-libraries/npm/registry/:_password = (protected)
//pkgs.dev.azure.com/bentleycs/Seequent/_packaging/Seequent-libraries/npm/registry/:username = (protected)
email = (protected)
loglevel = "info"
progress = false
strict-ssl = false

; "project" config from C:\Code\react-portal\.npmrc

always-auth = true
registry = "https://pkgs.dev.azure.com/bentleycs/Seequent/_packaging/Seequent-libraries/npm/registry/"

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v22.5.0
; npm local prefix = C:\Code\react-portal
; npm version = 10.8.2
; cwd = C:\Code\react-portal
; HOME = C:\Users\Ben.Osmond
; Run `npm config ls -l` to show all defaults.
```

**Comment by tbcshifter** [comment] 2024-07-18 19:44
I tried rolling back to `10.8.1` and still see this issue with node `22.5.0`. It just showed up today and all my builds are broken. 

I tried node `22.4.1` with npm `10.8.1`, which was the latest yesterday and it works. So it seems to be a node issue more than an npm issue.

**Comment by dewbjorn** [comment] 2024-07-18 19:57
Having the same exact issue.

**Comment by milaninfy** [comment] 2024-07-18 19:57
**Closing** Seems similer if not duplicate of https://github.com/npm/cli/issues/7657. 
Try node 22.4.1 with npm 10.8.2.

**Closed as not planned** 2024-07-18 19:57 UTC
Labels: Bug, Needs Triage

**Comment by benosmond** [comment] 2024-07-18 20:03
Version 22.4.1 gives me the same issue.

**Comment by milaninfy** [comment] 2024-07-18 20:08
@benosmond Strange, usually `npm install` or `npm ci` issues we have seen today are mostly in node 22.5.0, if it's happening for you with node 22.4.1 and latest npm, could you please provide reproduction steps ( including package.json or repository if possible ) with your configuration ?

**Comment by tbcshifter** [comment] 2024-07-19 15:48
> if it's happening for you with node 22.4.1 and latest npm

I have no issues with 22.4.1 and 10.8.2.

**Comment by milaninfy** [comment] 2024-07-19 15:49
Fixed in Node.js v22.5.1 https://github.com/nodejs/node/issues/53902#issuecomment-2239263377
