### ISSUE TITLE
npm install returns an error 403, cloudflare captcha page is returned instead of package json

### ISSUE THREAD

**Issue by spankandex** [npm/cli#1566] opened 2020-07-26 18:27 UTC
# What / Why
I have a ubuntu server 18.04 in north america and installed nodejs / npm from official repositories. On this specific server, which has no specific network configuration, no vpn, nothing unsual, when trying to run "npm install" commands, it return a 403 error, cause the request is getting a cloudflare page asking for a captcha. I also don't have any specific configuration on npm cli. Everything is brand as new, virgin as it is.

### Steps to Reproduce
root@ns105270:~# npm install npm -g
npm ERR! registry error parsing json
npm ERR! Linux 4.15.0-112-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "npm" "-g"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2

npm ERR! Unexpected token < in JSON at position 0
npm ERR! <!DOCTYPE html>
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR!  <html class="no-js" lang="en-US"> 
npm ERR! <head>
npm ERR! <title>Attention Required! | Cloudflare</title>
npm ERR! <meta name="captcha-bypass" id="captcha-bypass" />
npm ERR! <meta charset="UTF-8" />
npm ERR! <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
npm ERR! <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
npm ERR! <meta name="robots" content="noindex, nofollow" />
npm ERR! <meta name="viewport" content="width=device-width,initial-scale=1" />
npm ERR! <link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />
npm ERR! 
npm ERR! <style type="text/css">body{margin:0;padding:0}</style>
npm ERR!
npm ERR!
npm ERR! <script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script>
npm ERR! <script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script>
npm ERR!
npm ERR!
npm ERR!
npm ERR!
npm ERR!
npm ERR! <style type="text/css">
npm ERR!   #cf-wrapper #spinner {width:69px; margin:  auto;}
npm ERR!   #cf-wrapper #cf-please-wait{text-align:center}
npm ERR!   .attribution {margin-top: 32px;}
npm ERR!   .bubbles { background-color: #f58220; width:20px; height: 20px; margin:2px; border-radius:100%; display:inline-block; }
npm ERR!   #cf-wrapper #challenge-form { padding-top:25px; padding-bottom:25px; }
npm ERR!   #cf-hcaptcha-container { text-align:center;}
npm ERR!   #cf-hcaptcha-container iframe { display: inline-block;}
npm ERR!   @keyframes fader     { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
npm ERR!   #cf-wrapper #cf-bubbles { width:69px; }
npm ERR!   @-webkit-keyframes fader { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
npm ERR!   #cf-bubbles > .bubbles { animation: fader 1.6s infinite;}
npm ERR!   #cf-bubbles > .bubbles:nth-child(2) { animation-delay: .2s;}
npm ERR!   #cf-bubbles > .bubbles:nth-child(3) { animation-delay: .4s;}
npm ERR! </style>
npm ERR! </head>
npm ERR! <body>
npm ERR!   <div id="cf-wrapper">
npm ERR!     <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
npm ERR!     <div id="cf-error-details" class="cf-error-details-wrapper">
npm ERR!       <div class="cf-wrapper cf-header cf-error-overview">
npm ERR!         <h1 data-translate="challenge_headline">One more step</h1>
npm ERR!         <h2 class="cf-subheadline"><span data-translate="complete_sec_check">Please complete the security check to access</span> registry.npmjs.org</h2>
npm ERR!       </div>
npm ERR!
npm ERR!       <div class="cf-section cf-highlight cf-captcha-container">
npm ERR!         <div class="cf-wrapper">
npm ERR!           <div class="cf-columns two">
npm ERR!             <div class="cf-column">
npm ERR!
npm ERR!               <div class="cf-highlight-inverse cf-form-stacked">
npm ERR!                 <form class="challenge-form" id="challenge-form" action="/npm?__cf_chl_captcha_tk__=f3a3859badbbefc65a8beeb5a4bdb4d3050a5824-1595787585-0-AZs-xML0mPeK0eG6WR-7PZYL6-FBM15WoFyPwr97JJi5x3AEQmAv7t9PaqZRqXc-jYFrq5DsnyMc_vRYXgfO8uDURPrAXUd7g5sEI7K8ma9h8jTZBYzIEhJV8qSwIKWQahm6lPlEqzxxCJNxvaH_T73rovz2P-7KhR4zpQsszMoGJdutT5lA5hsKnIXgMAz8SlW-PBnZLyqPxXTjnRCI2yFPa6AF2tg6AEwjwM6NmuNxAAhRkIZYJZE9gypS-0FQ3QUTzLzuBNbvAgwXdjzyHgrW3ucHGnwxvQe4KfJR2u12vBRZbahME62sYGDGYRUbi6IoBzvP5PB46FnsQkgjWdX4-qXziwUt9F-axzM4-eEyd3ygKIO5Tt6L7n6rLlcdkxqQdQM9ora6vgqj7jxb5n2Uf0st3wm6RGbBkNm08v9I7-j266mHsTMsow9JAr_u7KW8D_l3Qwx4DnEGZ2WfogCb1PfuQDwVq_N0-X8GtmRMA3a9SX0-GMnvNEpGTZZkJlg6Z6NUSJzYpzmcEvScltk3LTWqmg8iVyVGhDHoHIwm" method="POST" enctype="application/x-www-form-urlencoded">
npm ERR!
npm ERR!   <input type="hidden" name="r" value="32518c00cb66aa1812419fc8d14c7d59aea2c2e3-1595787585-0-AWpvCLgFiu+N7lQ+2HUaHql/HDFh0XLWNZso4nKyYtXuM3XospDeYQVCav8/qasYNOyc+88xOG7dnVAfqgU2WT0iH3J/BpxrPtNO6PsWsT6zohV7wzkZahC30rJfLfm1TaiyolHk+oN+/OJBRCqV5aMRzjEJsU0AhPJbsfqSGqtYMfxP7UBns9WN3esih1ZWtVSIX/+I33h4R2NhQRwUHr4ZB/afdQXDO2rQPzZWHZXpVPNTyhu56rseGj2NjOvD15tQxAy7NDGMEsQ6Ee1L22VN0JyGVuBxv4wEhjQCSZczr4PBPAbfgQOismNi2o7EFR8bCSvz7WSxEjKgEVjGsKiF/zWUGuLGfleLCtP7wgAxQDFdgXQ1NRJIKP+pWGxjIB/oek3iAkZ2QZ1t1eVcxrTc1ewM4kL9p06+7G7J40enWcfMp4R2TvoUWdWp2lr5e+fgGotlBnKzyfsvG9qLkWZrVkCmJ5HaNoyp6U3bqT7WQ/lGdE+0sPKh8K02Gqmh9T+6Q73Clo0LatG3wEZBp5tqzF17dYU4X0UxZEHkR0BjqK439FqbEicTzoM1XMRZpvzYbr31+8OyiMOSClpBVmKc08Mm+q4kDrSY3HNbTfbsvKgFmGrafBJPo3h9P9zeO+lUPqiIfBDVNKF2rt3gDmfjCPt6oRA+m2Y+36nKuARBo0dx03y6UfP4XoNtSn658Mlw4qUdOuPAaciKA3DarGOZzkM6mvv3yZml/rfEpobhjHwVmA14EhDOQZBmGWsyzdj7cxkfrtY/AqZdf+U4hBvaj120hoqRz5CO6yD4cuFKRKUoCuz//LlkP/axUVq08F2N9rPJVtN8EWNTpL4y0pWt1D452dRyS3Nh3vJKaRRRBgOLn/LknCOqTLO752rieZmPygxy9b/vAJTMN5O+ShszSR9O4d9bwh8W/gwWTcslSQXgt4f+18MoIBr4Tnrnt15P5MWcwGadQPdtl0ZkPiWuCWSGX9YvYmdRQKsYoCyIOIkwhERi6jfLHmj8XHkDliuvBucmbl76xCEBprkk8o6UdG/VkqKoMwSQQ0/waPTaag8Db4PwguAKt62ytANA7wmXAhbbPscII6etaiwkB4AOaWqQfo0NwFtOwLSmW+3GXC8MJEPAgOOOq76XjEYDhiJzNWw0d+7UWZOB6T0DZmspe2dMmIrrNqtNdHZV+c9ViapEJ+WXJaqEHSdb84aLlsq15h+HAr+U930vSppZQboVlBO3qBFtPkOMXqG6tBr6v2QCmSDlVKH3iL6B3paY0SnjQyBzWBuHaD+Ox8PZETY5RclvUY+Q5VfVqVtt7uXZ9n/nLncOlXSRN/INXm6liw==">
npm ERR!   <input type="hidden" name="cf_captcha_kind" value="h">
npm ERR!   <input type="hidden" name="vc" value="">
npm ERR!
npm ERR!   <script type="text/javascript" src="/cdn-cgi/scripts/hcaptcha.challenge.js" data-type="normal"  data-ray="5b902178d97cec2e" async data-sitekey="33f96e6a-38cd-421b-bb68-7806e1764460"></script>
npm ERR!
npm ERR!   <noscript id="cf-captcha-bookmark" class="cf-captcha-info">
npm ERR!   <h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1>
npm ERR!   </noscript>
npm ERR!   <div id="no-cookie-warning" data-translate="turn_on_cookies" style="display:none">
npm ERR!     <h1 data-translate="turn_on_cookies" style="color:#bd2426;">Please enable Cookies.</h1>
npm ERR!   </div>
npm ERR!   <script type="text/javascript">
npm ERR!   //<![CDATA[
npm ERR!     var a = function() {try{return !!window.addEventListener} catch(e) {return !1} },
npm ERR!       b = function(b, c) {a() ? document.addEventListener("DOMContentLoaded", b, c) : document.attachEvent("onreadystatechange", b)};
npm ERR!       b(function(){
npm ERR!         var cookiesEnabled=(navigator.cookieEnabled)? true : false;
npm ERR!         if(!cookiesEnabled){
npm ERR!           var q = document.getElementById('no-cookie-warning');q.style.display = 'block';
npm ERR!         }
npm ERR!       });
npm ERR!   //]]>
npm ERR!   </script>
npm ERR!   <div id="trk_captcha_js" style="background-image:url('/cdn-cgi/images/trace/captcha/nojs/h/transparent.gif?ray=5b902178d97cec2e')"></div>
npm ERR! </form>
npm ERR!
npm ERR!               </div>
npm ERR!             </div>
npm ERR!
npm ERR!             <div class="cf-column">
npm ERR!               <div class="cf-screenshot-container">
npm ERR!
npm ERR!                 <span class="cf-no-screenshot"></span>
npm ERR!
npm ERR!               </div>
npm ERR!             </div>
npm ERR!           </div>
npm ERR!         </div>
npm ERR!       </div>
npm ERR!
npm ERR!       <div class="cf-section cf-wrapper">
npm ERR!         <div class="cf-columns two">
npm ERR!           <div class="cf-column">
npm ERR!             <h2 data-translate="why_captcha_headline">Why do I have to complete a CAPTCHA?</h2>
npm ERR!
npm ERR!             <p data-translate="why_captcha_detail">Completing the CAPTCHA proves you are a human and gives you temporary access to the web property.</p>
npm ERR!           </div>
npm ERR!
npm ERR!           <div class="cf-column">
npm ERR!             <h2 data-translate="resolve_captcha_headline">What can I do to prevent this in the future?</h2>
npm ERR!
npm ERR!
npm ERR!             <p data-translate="resolve_captcha_antivirus">If you are on a personal connection, like at home, you can run an anti-virus scan on your device to make sure it is not infected with malware.</p>
npm ERR!
npm ERR!             <p data-translate="resolve_captcha_network">If you are at an office or shared network, you can ask the network administrator to run a scan across the network looking for misconfigured or infected devices.</p>
npm ERR!
npm ERR!
npm ERR!
npm ERR!           </div>
npm ERR!         </div>
npm ERR!       </div>
npm ERR!
npm ERR!
npm ERR!       <div class="cf-error-footer cf-wrapper">
npm ERR!   <p>
npm ERR!     <span class="cf-footer-item">Cloudflare Ray ID: <strong>5b902178d97cec2e</strong></span>
npm ERR!     <span class="cf-footer-separator">&bull;</span>
npm ERR!     <span class="cf-footer-item"><span>Your IP</span>: 147.135.68.36</span>
npm ERR!     <span class="cf-footer-separator">&bull;</span>
npm ERR!     <span class="cf-footer-item"><span>Performance &amp; security by</span> <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>
npm ERR!
npm ERR!   </p>
npm ERR! </div>
npm ERR!
npm ERR!
npm ERR!     </div>
npm ERR!   </div>
npm ERR!
npm ERR!   <script type="text/javascript">
npm ERR!   window._cf_translation = {};
npm ERR!
npm ERR!
npm ERR! </script>
npm ERR!
npm ERR!
npm ERR! </body>
npm ERR! </html>
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

### Expected Behavior
As I have configured on other servers, the package should be installed instead of appearing that html cloudflare asking for a captcha response.

I could use a VPN service to surround the problem, however... this could happen on other servers and to anyone else. 
I already tried to change the registry to HTTP instead of HTTPS. 

Thank you

**Comment by jf-marino** [comment] 2020-08-01 23:52
Also having this same issue, looks like my ISP set up some aggressive caching through Cloudflare and downloads to private packages stop working when they turn that on (they seem to turn it on on Fridays and off on Mondays 🙄 ). Is there a way to bypass that without the ISP changing their config?

As a workaround I just connect from my mobile network whenever I'm about to do an install, but it's very annoying.

Thanks!

**Comment by noahcooper** [comment] 2020-10-22 02:54
I just started running into this problem after using npm for years. None of the reasons described on the Cloudflare CAPTCHA page apply to me -- they seem to suggest this has something to do with malware, but I don't think that's actually the case.

**Comment by darcyclarke** [comment] 2021-06-02 21:16
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 21:16 UTC
Labels: Release 6.x
