### ISSUE TITLE
npm is very slow when used install command then used cache revalidated!!!

### ISSUE THREAD

**Issue by nerdy-panda** [npm/cli#4671] opened 2022-04-04 12:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

hello 
i create laravel project then using 
npm install command 
but when running this command i should wait around 2 hours for install packages !!! 
i not have unlimited life !!!! 

### Expected Behavior

this is my log  when ran npm install command !!!
[2022-04-04T10_56_21_817Z-debug-0.log](https://github.com/npm/cli/files/8409576/2022-04-04T10_56_21_817Z-debug-0.log)

### Environment

- npm: 8.6.0
- Node.js: 16.14.2
- OS Name: ubuntu xfce => xubuntu
- System Model Name:

**Comment by nlf** [comment] 2022-04-07 23:11
looks like you had a lot of requests failing and retrying.. unfortunately when this happens there isn't really much we can do. you could try running `npm install --fetch-retries=0` which will prevent requests from being attempted more than once, but is far more likely to just fail and exit with an error on a flaky network, which may lead you to having to run the command more than once.

if you can reproduce this on more than just your own computer and your own network, we'd be happy to look at it, but we can't really do much to help you with failed requests unfortunately so i'm going to close this issue.

if you do manage to reproduce it, feel free to reopen this issue and include the steps you took to produce the problem.

**Closed as completed by nlf** 2022-04-07 23:11 UTC
Labels: Release 8.x, Bug, Needs Triage
