### ISSUE TITLE
NVM for Windows cannot install npm 6.14.17

### ISSUE THREAD

**Issue by robi-wan** [npm/cli#4890] opened 2022-05-12 15:03 UTC
See issue [Error installing NodeJS 14.19.2 with npm version 6.14.17](https://github.com/coreybutler/nvm-windows/issues/799).

NVM uses the URL https://github.com/npm/cli/archive/v6.14.17.zip to download npm.
This URL typed into a browser returns the same "error" as mentioned in the issue:
`the given path has multiple possibilities: #<Git::Ref:0x00007f49a98a1f98>, #<Git::Ref:0x00007f49a9891dc8>`

Is there something you can do about this?

**Comment by mrtawil** [comment] 2022-05-12 15:43
Same issue

**Comment by ljharb** [comment] 2022-05-12 16:11
I believe this is a duplicate of another issue. Make sure you're on latest nvm-windows - 1.18 iirc?

**Comment by mrtawil** [comment] 2022-05-12 17:08
> I believe this is a duplicate of another issue. Make sure you're on latest nvm-windows - 1.18 iirc?

I am using nvm version 1.1.9, it seems that the download link of this version of npm is broken

**Comment by douglasg14b** [comment] 2022-05-12 18:19
@ljharb

Please refer to the link in the OP.

Note that when you go to the link you recieve:

>  the given path has multiple possibilities: #<Git::Ref:0x00007f49a98a1f98>, #<Git::Ref:0x00007f49a9891dc8>

Instead of a zip file download.

Related: https://github.com/coreybutler/nvm-windows/issues/766

**Comment by darcyclarke** [comment] 2022-05-16 21:36
I'm not sure what the root cause of this problem is but I see that others have found a way around this: https://github.com/coreybutler/nvm-windows/issues/373#issuecomment-529991743 `npm@6` is essentially in maintenance mode & only gets security patches when we can/are able to. You should try updating to the latest stable version of node & npm whenever possible (ie. `node@18` & `npm@8.1.0`).

**Comment by darcyclarke** [comment] 2022-05-16 21:38
@ruyadorno when you get a second, can you look into this? (ref. https://github.com/npm/cli/archive/v6.14.17.zip)

**Comment by coreybutler** [comment] 2022-05-28 16:08
I have temporarily hacked a patch into NVM4W 1.1.10 (to be released soon), but the root cause is in this repo. See https://github.com/coreybutler/nvm-windows/issues/766.

This repo has a [branch](https://github.com/npm/cli/tree/v6.14.17) and a [tag](https://github.com/npm/cli/releases/tag/v6.14.17) with the same name (v6.14.17). Github's redirect URL doesn't know which one to resolve to, so it sends a `300` response instead of a redirect (as @robi-wan described). Removing or renaming one of these will likely resolve the issue.

**Comment by ruyadorno** [comment] 2022-05-31 01:22
thanks @coreybutler I deleted that unexpected branch from the repo, that seems to have fixed it! 😊

**Closed as completed by ruyadorno** 2022-05-31 01:22 UTC
Labels: Release 6.x, Bug, platform:windows, Priority 1
