### ISSUE TITLE
[QUESTION] <403 forbidden>

### ISSUE THREAD

**Issue by anchal0997** [npm/cli#805] opened 2020-02-13 12:32 UTC
npm ERR! code E403
npm ERR! 403 403 Forbidden - GET https://registry.npmjs.intuit.com/neo4j-driver
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/agarg5/.npm/_logs/2020-02-13T12_29_42_032Z-debug.log

**Comment by imposeren** [comment] 2020-02-17 11:41
The same can happen for default registry url sometimes (randomly), for example when installing from docker container using AWS codebuild:

```
Step 1/6 : FROM node:10-slim
...
```
```
Step 4/6 : RUN npm install grunt -g
--
514 | ---> Running in XXXXXXX
515 | npm ERR! code E403
516 | npm ERR! 403 403 Forbidden - GET https://registry.npmjs.org/grunt
517 | npm ERR! 403 In most cases, you or one of your dependencies are requesting
518 | npm ERR! 403 a package version that is forbidden by your security policy.

```

Somewhat related to #622

**Comment by hsmusz** [comment] 2020-02-17 11:48
getting the same error on heroku build

Step 16/20 : RUN npm ci && npm run production
 ---> Running in XXXXXXX
npm ERR! code E403
npm ERR! 403 Forbidden: jquery@3.4.1
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-17T11_17_32_964Z-debug.log

When doing npm install locally i get E429 on random packages

**Comment by chee** [comment] 2020-02-17 12:00
@anchal0997 it seems your registry is set to `registry.npmjs.intuit.com`, which could be set in the project's `package.json`(in the registry field) or in your `~/.npmrc`. you might need to login to that using `npm login` (is it a private registry?) or remove the line about it from your `~/.npmrc`.

(though right now the official registry is also giving some people 403s)

**Comment by chee** [comment] 2020-02-17 13:05
@anton-bot this is not a duplicate. this user is not using the npm registry. note this line in their initial report:

> npm ERR! 403 403 Forbidden - GET https://registry.npmjs.intuit.com/neo4j-driver

(this issue is also older, 4 days ago.)

**Comment by DanielRuf** [comment] 2020-02-18 06:10
@chee he referred to the last sentence at https://github.com/npm/cli/issues/805#issuecomment-586957436

**Comment by DanielRuf** [comment] 2020-02-18 06:11
Generally this issue is not a bug in npm but a problem with the authentication with this intuit registry.

**Comment by prozanne** [comment] 2020-03-17 07:17
I've got exactly same error message. 
And I tried a lot of things but finally after I had removed specific folder in my project,
it could be published.
In my case, the folder might be banned for uploading...
And still I can't figure out the exact reason.

**Comment by DanielRuf** [comment] 2020-03-17 08:07
> In my case, the folder might be banned for uploading

What was the name of it?

**Comment by prozanne** [comment] 2020-03-17 08:15
> > In my case, the folder might be banned for uploading
> 
> What was the name of it?

The folder contains tizen tv web application.
config.xml, index.html... etc
When I had removed tizen web application, I managed to publish.

**Comment by DanielRuf** [comment] 2020-03-17 08:48
@prozanne I'm unsure if it is ok that you shared the code with us. This might be a different issue and requires some testing on your side (which file may be problematic?).

**Comment by prozanne** [comment] 2020-03-17 23:16
> @prozanne I'm unsure if it is ok that you shared the code with us. This might be a different issue and requires some testing on your side (which file may be problematic?).

Oh.... that's ture, I think I shouldn't have uploaded the code.
I'd better to remove it.
Anyway....
Having dug a lot, finally we've got a clue.
If bootstrap.css, socket.io libraries, tizen package file(.wgt) and image resource file(.png) are contained, I couldn't publish at all.
But when we removed all of them, it worked.

**Comment by DanielRuf** [comment] 2020-03-17 23:52
<img width="315" alt="Bildschirmfoto 2020-03-18 um 00 52 12" src="https://user-images.githubusercontent.com/827205/76912040-c4983c00-68b2-11ea-95e4-a468f4afa58f.png">

You might want to remove the first version of your comment too.

**Comment by avimehenwal** [comment] 2020-07-29 00:12
I have the same issue, how can I debug it? I am collecting and packaging only `.vue` files, no images. Any help is appretiated

**Comment by AmitMirgal** [comment] 2020-10-13 15:30
what's the package name in package.json? @avimehenwal

**Comment by gempain** [comment] 2020-10-14 09:38
Had the same issue. I was trying to publish to a scope which was not in my organization. I had a typo in the scope of my package name in my `package.json`.

**Comment by haaarshsingh** [comment] 2020-10-23 02:10
I was having this bug too, this (probably) won't work for everyone but my problem was just that I was using an already existing pacakge.

Probably not what'll fix your problem, but it fixed mines.

**Comment by jsdev-mario** [comment] 2020-11-02 19:41
same issue

**Comment by jlorenzoC** [comment] 2020-12-09 01:13
Hi. The same over here when i try to: `npm i @angular/material-moment-adapter `  
```
npm ERR! code E403
npm ERR! 403 403 Forbidden - GET http://my.nexus.ip/repository/npm-proxy/@angular%2fmaterial-moment-adapter
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\***\***\AppData\Roaming\npm-cache\_logs\2020-12-09T00_53_23_966Z-debug.log
```

**Comment by TechQuery** [comment] 2020-12-15 20:44
Even `npm whoami` & `npm login` throw the same `403` error...

**Comment by aminya** [comment] 2020-12-16 18:20
For me, I was trying to publish a package under my personal name, while I was logged in as the organization I own. It was fixed by relogging by `npm login`.

**Comment by saltukalakus** [comment] 2020-12-31 22:06
I had the same error when publishing a package. It turned out that my email wasn't verified in my NPM account. Verifying it helped to resolve the issue.

**Comment by JoseAtencio** [comment] 2021-01-08 21:17
@saltukalakus thanks it worked for me

**Comment by azhaubassar** [comment] 2021-01-14 03:38
@saltukalakus thank you, you saved my hours

**Comment by fayismahmood** [comment] 2021-01-22 03:16
> I had the same error when publishing a package. It turned out that my email wasn't verified in my NPM account. Verifying it helped to resolve the issue.

yah it worked for me too

**Comment by lzj723** [comment] 2021-02-24 07:56
i've got the same error when i run "npm install" with company's private npm registry, even when npm login.

**Comment by khurramlashari** [comment] 2021-02-28 14:40
i've got the same error and in my case package name was duplicate

**Comment by Sataa-Yu** [comment] 2021-03-24 20:10
I've also got the same error when I run "npm install" after npm login with 2 factor auth.

**Comment by Dharmendra205111014** [comment] 2021-04-01 11:26
> > @prozanne I'm unsure if it is ok that you shared the code with us. This might be a different issue and requires some testing on your side (which file may be problematic?).
> 
> Oh.... that's ture, I think I shouldn't have uploaded the code.
> I'd better to remove it.
> Anyway....
> Having dug a lot, finally we've got a clue.
> If bootstrap.css, socket.io libraries, tizen package file(.wgt) and image resource file(.png) are contained, I couldn't publish at all.
> But when we removed all of them, it worked.

Very similer thing happening to me, if i remove my README.md file it works fine. @prozanne could you find anything there ?

**Comment by himharsh1997** [comment] 2021-04-22 13:34
Hi guys! 2 things to do:
1.  Verify your account first.
2.  create file .npmrc file and set  //registry.npmjs.org/:_authToken=<access_token> in it. You will get access_token from your account with publishing access.

**Comment by kenchon** [comment] 2021-05-04 10:22
I tried following but didn't work:

- [x] Confirm no duplicate package names on npm
- [x] Verify email
- [x] Enable 2FA (also tried w/o 2FA)
- [x] Do `npm login` 
- [x] Set access token on `~/.npmrc` (as @himharsh1997 mentioned)

**Comment by moamlrh** [comment] 2021-05-16 17:44
I solved by :
- go to [npmjs.org](https://www.npmjs.com)
- create a new **access_token** by : 
      - Click on your image in the right corner 
      - Access tokens
      - Generate new token
      - Select type : **Publish**
- After that copy the token
- got to your project
- Create **.npmrc**  file
- Set `//registry.npmjs.org/:_authToken=<access_token>`  in it

**Comment by darcyclarke** [comment] 2021-06-02 21:55
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 21:55 UTC
Labels: Awaiting Information

**Comment by ghost** [comment] 2021-12-06 07:32
> Hi guys! 2 things to do:
> 
> 1. Verify your account first.
> 2. create file .npmrc file and set  //registry.npmjs.org/:_authToken=<access_token> in it. You will get access_token from your account with publishing access.

verifying email is not enough..2. step solves the problem

**Comment by real-jiakai** [comment] 2022-09-28 05:06
In my case. Before I ran the command `npm login`, I didn't change the registry to `npm`.  If you are using `nrm` . You should change the registry to `npm` first. `nrm ls` + `nrm use npm` solves my problem.

**Comment by AndreaPontrandolfo** [comment] 2022-10-01 21:05
> I was having this bug too, this (probably) won't work for everyone but my problem was just that I was using an already existing pacakge.
> 
> Probably not what'll fix your problem, but it fixed mines.

THANK YOU. I was going crazy, couldn't figure out why npm was telling me that i was publishing a package not owned by me. Read your comment, and yeah, turn out another package with the same name got published 10 years ago, lol. Had to change the name but finally got my package published! 🎉

**Comment by juliaivi** [comment] 2023-05-20 07:40
В моем случае была проблема из-за файла .npmrc . Может кому-то поможет
