### ISSUE TITLE
[BUG] npm run is broken

### ISSUE THREAD

**Issue by ahuglajbclajep** [npm/cli#1704] opened 2020-08-23 00:22 UTC
### Current Behavior:

```sh
$ npx -qp npm@7.0.0-beta.5 -c 'npm run'
start:webpack-dev-server --open
build:NODE_ENV=production webpack -p

$ npx -qp npm@7.0.0-beta.6 -c 'npm run'
npm timing config:load:defaults Completed in 1ms
...
npm timing npm:load Completed in 25ms
npm run-script <command> [-- <args>]

aliases: run, rum, urn
npm timing npm Completed in 155ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ahu/.npm/_logs/2020-08-23T00_18_04_815Z-debug.log
```

### Expected Behavior:

```sh
$ npx -qp npm@7.0.0-beta.6 -c 'npm run'
start:webpack-dev-server --open
build:NODE_ENV=production webpack -p
```

### Steps To Reproduce:

1. `npx -qp npm@7.0.0-beta.6 -c 'npm run'`

### Environment:

- OS: macOS Catalina 10.15.6
- Node: 12.18.3
- npm: 6.14.6
- npx: 6.14.6

**Comment by isaacs** [comment] 2020-08-25 18:27
Root cause: https://github.com/npm/config/issues/2

We should be skipping env values of `''` rather than putting them in the configuration object.

**Comment by ljharb** [comment] 2020-08-25 20:50
Isn’t the empty string distinct from unset?

**Comment by isaacs** [comment] 2020-09-18 18:16
It is, but unfortunately npm 6 did not respect this distinction appropriately.

Fixed in latest beta.

**Closed as completed by isaacs** 2020-09-18 18:16 UTC
Labels: Release 7.x, Bug, Needs Triage
