### ISSUE TITLE
[BUG] Unable to install anything from a scoped private registry: registry gets ignored

### ISSUE THREAD

**Issue by OnkelTem** [npm/cli#3554] opened 2021-07-16 14:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I find no way to install anything from a private registry.
I associated our scope with a registry, but then it gets completely ignored by NPM.

### Expected Behavior

NPM should install the package from a registry associated with the scope. 

### Steps To Reproduce

First I associate a scope with a registry (https://docs.npmjs.com/cli/v7/using-npm/scope#associating-a-scope-with-a-registry)

```
$ npm config set @ourscope:registry http://gitlab.our.domain/api/v4/packages/npm/
```

It updates `~/.npmrc` file and `npm config ls` confirms that the changes is accepted.

But afterwards there's no way to install anything for that repo. Specifically:

```
$ npm i @ourscope/a-package --verbose
```
shows that the first request goes to npmjs.com which returns 404:

```
$ npm i @ourscope/a-package --verbose                                                         
npm verb cli [
npm verb cli   '/home/user/.nvm/versions/node/v14.16.1/bin/node',
npm verb cli   '/home/user/.nvm/versions/node/v14.16.1/bin/npm',
npm verb cli   'i',
npm verb cli   '@ourscope/a-package',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@7.20.0
npm info using node@v14.16.1
npm timing npm:load:whichnode Completed in 0ms
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:/home/user/.nvm/versions/node/v14.16.1/lib/node_modules/npm/npmrc Completed in 2ms
npm timing config:load:builtin Completed in 2ms
npm timing config:load:cli Completed in 3ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:/projects/ourscope/lib/a-package-2/.npmrc Completed in 2ms
npm timing config:load:project Completed in 3ms
npm timing config:load:file:/home/user/.npmrc Completed in 0ms
npm timing config:load:user Completed in 0ms
npm timing config:load:file:/home/user/.nvm/versions/node/v14.16.1/etc/npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:validate Completed in 1ms
npm timing config:load:credentials Completed in 1ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 12ms
npm timing npm:load:configload Completed in 12ms
npm timing npm:load:setTitle Completed in 0ms
npm timing npm:load:setupLog Completed in 1ms
npm timing npm:load:cleanupLog Completed in 2ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load:projectScope Completed in 0ms
npm timing npm:load Completed in 18ms
npm timing config:load:flatten Completed in 2ms
npm timing arborist:ctor Completed in 0ms
npm timing arborist:ctor Completed in 1ms
npm timing idealTree:init Completed in 10ms
npm timing idealTree:userRequests Completed in 2ms
npm http fetch GET 404 https://registry.npmjs.org/@ourscope/a-package 1492ms (cache skip)
npm http fetch GET 404 https://registry.npmjs.org/@ourscope/a-package 933ms (cache skip)
npm timing idealTree:#root Completed in 2448ms
npm timing idealTree:node_modules/@ourscope/a-package Completed in 0ms
npm timing idealTree:buildDeps Completed in 2452ms
npm timing idealTree:fixDepFlags Completed in 2ms
npm timing idealTree Completed in 2471ms
npm timing command:install Completed in 2489ms
npm verb stack HttpErrorGeneral: 404 Not Found - GET https://registry.npmjs.org/@ourscope/a-package - Not found
npm verb stack     at /home/user/.nvm/versions/node/v14.16.1/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:95:15
npm verb stack     at processTicksAndRejections (internal/process/task_queues.js:93:5)
npm verb stack     at async Arborist.[nodeFromEdge] (/home/user/.nvm/versions/node/v14.16.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:940:19)
npm verb stack     at async Arborist.[buildDepStep] (/home/user/.nvm/versions/node/v14.16.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:886:11)
npm verb stack     at async Arborist.buildIdealTree (/home/user/.nvm/versions/node/v14.16.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:218:7)
npm verb stack     at async Promise.all (index 1)
npm verb stack     at async Arborist.reify (/home/user/.nvm/versions/node/v14.16.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:134:5)
npm verb stack     at async Install.install (/home/user/.nvm/versions/node/v14.16.1/lib/node_modules/npm/lib/install.js:150:5)
npm verb statusCode 404
npm verb pkgid @ourscope/a-package@*
npm verb cwd /projects/ourscope/lib/a-package-2
npm verb Linux 5.4.0-77-generic
npm verb argv "/home/user/.nvm/versions/node/v14.16.1/bin/node" "/home/user/.nvm/versions/node/v14.16.1/bin/npm" "i" "@ourscope/a-package" "--verbose"
npm verb node v14.16.1
npm verb npm  v7.20.0
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@ourscope/a-package - Not found
npm ERR! 404 
npm ERR! 404  '@ourscope/a-package@*' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm verb exit 1
npm timing npm Completed in 2694ms
```

Even if I pass `--registry` param via command line, it doesn't make any difference and NPM sends request to npmjs.com instead. 

### Environment

- OS: Ubuntu 20.04
- Node: 14.x
- npm: 7.20.0

**Comment by JBBianchi** [comment] 2021-07-16 15:08
I don't think it's a bug. I faced the same kind of behavior when I started to work with GitLab.

If I recall well, the problem was that I thought the package was published but it was not. In the end it was a mixup between project level and instance level urls usage.

Double check that you are actually publishing at the project level and consuming at the instance (or project) level. Publishing at instance level don't raise an error as far as I remember, thus making the process a little tedious.

**Comment by OnkelTem** [comment] 2021-07-19 08:08
Thank you @JBBianchi 

Yeah, I admit that the problem could be at the GitLab side but I don't get how/when am I assumed to know that?
Even in the verbose mode NPM doesn't show any activity against the GitLab registry. 
How one would even know that something goes wrong if NPN doesn't tell anything?

**Comment by JBBianchi** [comment] 2021-07-19 09:41
It's not the fault of NPM if the registry says "ok, you published the package" but actually didn't, it's GitLab fault.

The only thing that points out that you need to use the project level endpoint and not the instance level endpoint is the [GitLab documentation](https://docs.gitlab.com/ee/user/packages/npm_registry/#publish-an-npm-package):
```
Publish an npm package

Prerequisites:

    Authenticate to the Package Registry.
    Set a project-level npm endpoint. <--
```

I must admit I lost a lot of time on that one.

**Comment by OnkelTem** [comment] 2021-07-19 09:56
> The only thing that points out that you need to use the project level endpoint and not the instance level endpoint is the [GitLab documentation](https://docs.gitlab.com/ee/user/packages/npm_registry/#publish-an-npm-package):

I've successfully published the npm package using project-level endpoint. I would have done it with instance-level endpoint and that was my initial idea, but according to [the docs](https://docs.gitlab.com/ee/user/packages/npm_registry/#use-the-gitlab-endpoint-for-npm-packages) it's not possible:

> Some features such as **publishing** a package is only available on the **project-level endpoint**.

But as for the installation from the instance-level endpoint, I believe it should be possible. Otherwise, i.e. - without publishing and installation - what would be a use case for instance-level endpoint at all, huh?

So yeah, I want to use project-level endpoint for publishing and instance-level for installations.

**Comment by JBBianchi** [comment] 2021-07-19 09:58
> So yeah, I want to use project-level endpoint for publishing and instance-level for installations.

That's the way to go, once published at project level, the package is available at instance level.

**Comment by OnkelTem** [comment] 2021-07-19 10:40
> > So yeah, I want to use project-level endpoint for publishing and instance-level for installations.
> 
> That's the way to go, once published at project level, the package is available at instance level.

And that's exactly why I did. 

I published the package using the following configuration:

1) Token in the `~/.npmrc`:
```
$ cat ~/.npmrc
//gitlab.our.domain/api/v4/projects/2/packages/npm/:_authToken=MfX...Q3
```

2) `publishConfig` in the `package.json`:

```
  "publishConfig": {
    "@streamlabs:registry": "http://gitlab.our.domain/api/v4/projects/2/packages/npm/"
  }
```

I published it using just regular `npm publish` and it showed up in the corresponding section:

![image](https://user-images.githubusercontent.com/114060/126146524-03e56300-cc12-438a-8633-5e80a2b70dc7.png)


To install it I added the next line to the `~/.npmrc`:

```
@streamlabs:registry=http://gitlab.our.domain/api/v4/packages/npm/
```

and then... it doesn't work.

**Comment by JBBianchi** [comment] 2021-07-19 10:48
At first glance, I think it should. Are you authenticated to use `http://gitlab.our.domain/api/v4/packages/npm/` ? 
if so, you might wanna check your npm logs and your GitLab logs and maybe open an issue on GitLab.

**Comment by OnkelTem** [comment] 2021-07-19 11:27
> Are you authenticated to use `http://gitlab.our.domain/api/v4/packages/npm/`

How can I tell that?
I have this line in the `~/.npmrc`:

```
//gitlab.our.domain/api/v4/packages/npm/:_authToken=Mf...Q3
```

(btw, seems like I used incorrect URL before - with "/projects" part, now I removed it)

**Comment by JBBianchi** [comment] 2021-07-19 11:40
> 
> 
> > Are you authenticated to use `http://gitlab.our.domain/api/v4/packages/npm/`
> 
> How can I tell that?
> I have this line in the `~/.npmrc`:
> 
> ```
> //gitlab.our.domain/api/v4/packages/npm/:_authToken=Mf...Q3
> ```
> 
> (btw, seems like I used incorrect URL before - with "/projects" part, now I removed it)

I think you can run something along the line of `npm whoami --registry=http://gitlab.our.domain/api/v4/packages/npm/` 

Another thing to check maybe is the autorizations you gave to each token, double check they have the rights to access the registry?

**Comment by rwky** [comment] 2022-01-04 18:43
I had the same issue, turns out the personal access token I was using didn't have the `api` scope permissions. 

What's weird is that without the correct scope npm reports as connecting to registry.npmjs.org instead of the gitlab instance, with the correct scope it lists the gitlab instance, this threw me since I assumed npm was connecting to the default registry even though it wasn't.

**Comment by nlf** [comment] 2022-03-08 21:59
@OnkelTem is this still an issue? we did make some changes to how scoped registries are handled in the last several months. can you try updating to npm@8.5.3 and see if things are working as you expect?

**Comment by wraithgar** [comment] 2022-03-15 21:35
Closing due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.

**Closed as completed by wraithgar** 2022-03-15 21:35 UTC
Labels: Release 7.x, Bug, Needs Triage

**Comment by MatTheCat** [comment] 2022-10-06 08:28
I’m late to the party but I experienced the same issue as https://github.com/npm/cli/issues/3554#issuecomment-882442924

In my case the trick was the instance level registry only finds packages whose scope match the hosting project group namespace: eg. if your group page is https://gitlab.com/streamlabs then your packages must be `@streamlabs/something` (from https://docs.gitlab.com/ee/user/packages/npm_registry/#package-naming-convention).

You can workaround this by creating an empty project and using its registry to publish all your package. Then you can configure npm to use its project-level endpoint for `@streamlabs`.

**Comment by jonybekov** [comment] 2022-11-18 13:26
I also faced the same problem today. As per [this comment](https://stackoverflow.com/a/53162803/9710130) my encoding was UTF-16 BE. Converting .npmrc config file into UTF-8 resolved the issue.

When I ran ```npm config ls``` the result was something like this:
```
"project" config from C:\Users\LEGION\Projects\myorg-apps\disputes\.npmrc

��@myorg:registry = "\u0000h\u0000t\u0000t\u0000p\u0000s\u0000:\u0000/\u0000/\u0000g\u0000i\u0000t\u0000l\u0000a\u0000b\u0000.\u0000c\u0000o\u0000m\u0000/\u0000a\u0000p\u0000i\u0000/\u0000v\u00004\u0000/\u0000p\u0000a\u0000c\u0000k\u0000a\u0000g\u0000e\u0000s\u0000/\u0000n\u0000p\u0000m\u0000/\u0000" 
```

After converting to UTF-8, it was like this:
```
"project" config from C:\Users\LEGION\Projects\myorg-apps\disputes\.npmrc
@myorg:registry = "https://gitlab.com/api/v4/packages/npm/"
```

**Comment by thw0rted** [comment] 2023-01-25 19:06
@wraithgar Not sure if it makes sense reopen this, or file a new issue.  I am facing a similar problem to the OP but the cause is not exactly the same.

In my project level `.npmrc` I have `@myscope:registry=https://our.gitlab.domain/etc/etc/`.  In my user profile `.npmrc` I have `//our.gitlab.domain/etc/etc/:_authToken "myAuthToken"`.  With this config, I can ask for a nonexistent package in our scope (`npm install @myscope/not-a-real-package`) and get a `SELF_SIGNED_CERT_IN_CHAIN` error, pointing to `https://our.gitlab.domain/etc/etc/@myscope%2fnot-a-real-package`.  This is expected, because `our.gitlab.domain` is signed by our own CA.

I tried to fix this by setting `NODE_EXTRA_CA_CERTS=my-ca.pem`.  I expected this to give me a 404 from `our.gitlab.domain`, but instead I get `404 Not Found - GET https://registry.npmjs.org/@myscope/not-a-real-package - Not found`.  I also tried fixing it by setting `cafile=my-ca.pem` in `.npmrc` but that still tries to reach public NPM, this time failing with

```
npm ERR! errno UNABLE_TO_GET_ISSUER_CERT_LOCALLY
npm ERR! request to https://registry.npmjs.org/@myscope/not-a-real-package failed, reason: unable to get local issuer certificate
```

This suggests that it's actually making the request it claims to be making, to `registry.npmjs.org`, which is of course not signed by our CA cert.  (I assume specifying `cafile` means the built-in CAs are ignored.)  In this case, the debug log makes no mention at all of `our.gitlab.domain`.

My question is, if I declare an explicit (private) registry for a scoped package, should NPM ever actually request that package from `npmjs.org`?  If the answer is "no", in the above example NPM is misbehaving.  If the answer is "yes", 1) why???, 2) is that documented somewhere?, 3) can I stop it? and 4) how can I tell from the logs that this is happening intentionally?

**Comment by wraithgar** [comment] 2023-01-25 19:09
The answer is no, npm should not be doing that.

**Comment by thw0rted** [comment] 2023-01-25 20:01
Ok so, do you want to reopen this or should I make a new issue? I think the underlying issue is probably the same.

**Comment by wraithgar** [comment] 2023-01-25 20:48
It's never wise to assume the root causes are the same.  The issue template is designed to bring out an exact duplication scenario so we aren't trying to potentially solve two different bugs in one issue.

**Comment by thw0rted** [comment] 2023-01-25 20:57
Sorry, what I meant to say was, while our initial intentions may have differed, I believe the actual configuration I wound up with is in fact identical to the OP.

I was deliberately trying to request a package that doesn't exist, while the OP thought they were requesting a real package, but realized later that they were mistaken.  In both cases, we were configuring our `npmrc` to point to a Gitlab package registry for a specific scope, requesting a package that doesn't exist on that private registry, and the client wound up making a request to the public registry instead.  The names of the scope and private server might differ, but otherwise it sounds like our configurations were identical.
