### ISSUE TITLE
[BUG] ci and install run preinstall lifecycle script at different times

### ISSUE THREAD

**Issue by Kuinox** [npm/cli#289] opened 2019-11-07 08:44 UTC
# What / Why
NPM run preinstall script at different times in the lifecycle, if a package is installed via `npm ci` or `npm install`
This issue is the same than this one: https://npm.community/t/ci-and-install-run-preinstall-lifecycle-script-at-different-times/7317   
Issue that got closed while being acknowledged as a bug.

### Current Behavior
When running `npm i` the `preinstall` script is ran before downloading a package.
When running `npm ci` the `preinstall` script is ran after downloading the package, before it is installed.

### Steps to Reproduce
npm install/npm ci any project.

### Expected Behavior
The script `preinstall` should be run before downloading the package for `npm ci`.

### Use Case
While running `npm install`, we start a proxy, and packages are resolved trough this proxy.   
When running `npm ci`, the proxy doesn't start, and npm cannot resolve the package.

**Comment by Kuinox** [comment] 2020-03-16 00:07
Now some package cannot even be installed using npm ci because the library author does not use npm ci and this bug break the package install.
We cannot use npm ci on some of our project because of this.

**Comment by Kuinox** [comment] 2020-03-16 00:11
I believe these issues are the same bug: #454 & #452 .

**Comment by robertaistleitner** [comment] 2020-04-15 14:14
Same here, I do some clean-up (including node_modules) on `preinstall` in development with `npm install`. In our CI pipeline this is done via `npm ci` which installs the dependencies, after that `preinstall` is deleting the node_modules folder because of the wrong execution order.

**Comment by maboesanman** [comment] 2020-04-30 15:44
I'm also having this issue. I'm using `npm install <folder>` to use my package in my integration tests, and that folder needs to be built before I run install. for now I'm just manually building it but I would like preinstall to handle this, or at least for there to be a "predownload" script or something

**Comment by trevor-scheer** [comment] 2020-09-18 20:45
We have a similar use case. We're building a package from rust to create a wasm/js package, which we'd like to then install via a file reference. With `npm ci`, this build step doesn't happen until the error of a missing package has already failed the install.

**Comment by Kuinox** [comment] 2020-09-18 20:57
@trevor-scheer due to this bug we switched to yarn and it works without any issue. 
They also answered the issues I opened, in less than one week :D.

**Comment by trevor-scheer** [comment] 2020-09-18 22:22
Sadly not an option for us but thanks for the quick response @Kuinox! Glad you found a way around it 🙂

**Comment by darcyclarke** [comment] 2021-06-02 21:45
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 21:45 UTC
Labels: Bug

**Comment by Kuinox** [comment] 2021-06-07 15:07
🎉this bug got automatically closed for the second time.

**Comment by ljharb** [comment] 2021-06-07 15:50
@Kuinox can you confirm that this is still an issue in npm 7?

**Comment by Kuinox** [comment] 2021-06-07 17:10
I can't, because I don't remember which conditions caused this issue.

**Comment by trevor-scheer** [comment] 2021-06-08 18:37
Can confirm the two are consistent now, at least in our case where a dependency is missing. The `preinstall` script doesn't run in either case now if the installation of `node_modules` fails. Totally unnecessary to clone and run this repo, but if you choose to, you can note the `preinstall.js` script never runs (logging "hello") in either case of `npm i` or `npm ci`. This is not the case in `npm@6`.
https://github.com/trevor-scheer/npm-preinstall-reproduction

This is documented clearly under [`npm ci`](https://docs.npmjs.com/cli/v7/using-npm/scripts#npm-ci), but not under [`npm install`](https://docs.npmjs.com/cli/v7/commands/npm-install).

**Comment by hyrumwhite** [comment] 2021-09-08 15:07
> These all run after the actual installation of modules into node_modules, in order, with no internal actions happening in between

What's the point of any of the lifecycle hooks, besides postinstall, if they all run after install without doing anything in between?

**Comment by OZZlE** [comment] 2024-09-02 10:43
Seems like a dumb feature but I added my script to our Dockerfile instead before "npm ci/install" instead...

Will cause headaches locally though because Dependabot always sets the wrong Artifactory, we use a mirror of registry.npm.js and Dependabot doesn't support mirrors either..
