### ISSUE TITLE
[BUG] `file:` dependency is locked without package name when install is run for the 1st time

### ISSUE THREAD

**Issue by mvorisek** [npm/cli#6430] opened 2023-05-07 07:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Please run the repro steps below. Currently when a `file:` dependency is required, it is added to the lock file without a name when the npm install is run for the 1st time. Even if there is no dependency change, when the npm install is rerun, the lock file is changed.

### Expected Behavior

no lock file change

### Steps To Reproduce

1. `git clone https://github.com/atk4/ui.git`
2. `cd js`
3. `rm package-lock.json`
4. `npm i --package-lock-only`
5. `cp package-lock.json package-lock2.json`
6. `npm i --package-lock-only`
7. notice `packages` -> `.eslint` -> `name` key is added to the lock file (`diff package-lock2.json package-lock.json`)

![image](https://user-images.githubusercontent.com/2228672/236663506-7f77a1ee-94ea-439c-b05e-9f7101cf08c8.png)

### Environment

- npm: 9.6.4
- Node.js: v19.8.1
- OS Name: Windows 10 x64

**Comment by mvorisek** [comment] 2023-10-08 18:30
Can someone, please, look into this lock file instability issue?

**Comment by mvorisek** [comment] 2024-02-01 09:33
Hi all, this issue is still present, can someone please confirm/reproduce it and fix it? Thank you in advance!

**Comment by sonallux** [comment] 2024-02-18 15:14
I am also experiencing this issue and have looked into it a bit. The issue is only present when the folder name of the `file:` dependency is different from the package name. 

I have created a reproduction test for this issue in this branch: https://github.com/sonallux/npm/tree/chore/6430-add-reproduction-test-case and opened PR #7228

**Comment by milaninfy** [comment] 2024-07-02 18:11
Fixed by https://github.com/npm/cli/pull/7602

**Closed as completed by milaninfy** 2024-07-02 18:11 UTC
Labels: Bug, Needs Triage, Release 9.x
