### ISSUE TITLE
[BUG] Cursor spinner during password entry

### ISSUE THREAD

**Issue by mcandre** [npm/cli#7635] opened 2024-07-09 15:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When entering a password with the `--auth-type legacy` option, then npm often shows an animated spinning cursor where the password is supposed to be typed in. This is incredibly confusing, as it is no longer clear whether the user is expected to wait for some internal processing to complete, or go ahead and supply the password.

### Expected Behavior

No spinner displays during password entry.

### Steps To Reproduce

1. Use `--auth-type legacy` when authenticating to private NPM registries.

### Environment

(enterprise)

**Comment by milaninfy** [comment] 2024-07-09 15:44
**Closing:** this looks to be similar if not a duplicate of an existing issue, [7583](https://github.com/npm/cli/issues/7583). If you believe your instance is unique, please provide further clarifying details.

**Closed as not planned by milaninfy** 2024-07-09 15:44 UTC
Labels: Bug, Needs Triage
