### ISSUE TITLE
[BUG] cb() never called!

### ISSUE THREAD

**Issue by bobKasbi** [npm/cli#767] opened 2020-02-04 15:21 UTC
# What / Why
 error:

`npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/userName/.npm/_logs/2020-02-04T14_47_01_098Z-debug.log`

## When

When I run `npm install`. I get following
  Happened first time today

### Current Behavior
See error mentioned before

### Steps to Reproduce
run `npm install`

### Expected Behavior
Should install what is defined in `package.json`

**Comment by na-ringtail** [comment] 2020-02-04 20:11
The same issue. Trying to install dependencies on clean project https://github.com/caiobiodere/cordova-template-framework7-vue-webpack
node 13.5.0
npm 6.13.7
Windows 8.1

**Comment by bobKasbi** [comment] 2020-02-05 06:56
I think issue occurs with/after installing the nodejs version 13.x When I did downgrade to 12.14.1 it works fine. So, it would be great if the issue is fixed for version: 13.x

**Comment by na-ringtail** [comment] 2020-02-05 18:41
Used `framework7 create` instead. There were no error, so my problem isn't actual anymore.

**Comment by DanielRuf** [comment] 2020-02-18 06:39
Duplicate of https://github.com/npm/cli/issues/417

**Comment by darcyclarke** [comment] 2021-06-02 21:45
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Comment by DanielRuf** [comment] 2021-06-02 21:51
Seems to be still open.

**Comment by darcyclarke** [comment] 2021-06-02 21:55
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 21:55 UTC
Labels: Bug
