### ISSUE TITLE
[BUG] <title> report 'no matching version found' error during second npm install

### ISSUE THREAD

**Issue by zhangchen97** [npm/cli#7138] opened 2024-01-15 12:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

the package.json content of my project:
```
"dependencies": {
"A": "file:./deps/A1@4.9.5-r3.tgz'
"B": "file:./deps/B1@1.1.3.tgz'
}
```

the package.json content of package "B":
```
"dependencies":{
    "commander": "^9.3.0",
    "fs-extra": "^10.1.0",
    "json5": "^2.2.3",
    "source-map": "0.7.4",
    "A":"npm:A1@4.9.5-r6"
}
```
However, A1@4.9.5-r6 is non-existent and I accidentally added it.

The package-lock.json file in my project does not contain information about A@4.9.5-r6.
Information about other packages exists, that is "A": "file:./deps/A1@4.9.5-r3.tgz'、"commander": "^9.3.0"、"fs-extra": "^10.1.0"、"json5": "^2.2.3"、"source-map": "0.7.4".

Operation commands and symptoms:
When I run the npm install command for the first time, no error is reported. A1@4.9.5-r3.tgz is successfully installed, but A1@4.9.5-r6 is not successfully installed.

When I run the npm install command for the second time, the following error information is displayed: error notarget No matching version found for A1@4.9.5-r6.

### Expected Behavior

When I run npm install for the first time, the error message "error notarget No match version found'A1@4.9.5-r6'" is displayed.

More importantly, I want to know why no error is reported when npm install is executed for the first time, and the error is reported for the second time.

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm: 6.14.17
- Node.js:14.12.1
- OS Name: linux
- System Model Name:
- npm config:
'
 strict-ssl=false
 package-lock=true
'
```ini
; copy and paste output from `npm config ls` here
```

**Comment by milaninfy** [comment] 2024-05-08 16:14
@zhangchen97 Not reproducible for me. I tried replicating similer setup as you describe in the issue. On the first time install I am getting "No matching version found" 
```sh
~/workarea/7138 $ npm install
npm error code ETARGET
npm error notarget No matching version found for peerpkg@9.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.
```
can you try replicating this problem on the latest version of `npm`? (ie. `npm i -g npm`)

**Comment by milaninfy** [comment] 2024-05-16 12:48
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.

**Closed as not planned by milaninfy** 2024-05-16 12:48 UTC
Labels: Bug, Needs Triage, Release 9.x
