### ISSUE TITLE
[BUG] git+https package resolves to git+ssh

### ISSUE THREAD

**Issue by ilanolkies** [npm/cli#4548] opened 2022-03-10 19:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`ethereumjs-abi` is set as `git+https://` dependency but it is resolver as `git+ssh://`. This makes, for example, Github Actions fail

package.json in npm registry:

<img width="771" alt="Screen Shot 2022-03-10 at 16 52 36" src="https://user-images.githubusercontent.com/36084092/157743765-26986112-ffa1-4c30-9925-a811d0daf1ca.png">

> Source: https://unpkg.com/browse/eth-sig-util@1.4.2/package.json

My package-lock after installing

https://github.com/rsksmart/rLogin-providers/blob/624e76413a3e84e256b254f5b7bfb8f3126f8f6d/packages/rlogin-dcent-provider/package-lock.json#L1261

https://github.com/rsksmart/rLogin-providers/blob/624e76413a3e84e256b254f5b7bfb8f3126f8f6d/packages/rlogin-dcent-provider/package-lock.json#L1294

An isolation of the problem, take a look at _steps to reproduce_

![Screen Shot 2022-03-10 at 16 53 16](https://user-images.githubusercontent.com/36084092/157743959-bfe56092-0c03-4c12-a254-974b059c352b.png)

![Screen Shot 2022-03-10 at 16 53 42](https://user-images.githubusercontent.com/36084092/157744025-25174a9e-e9e1-4461-abb3-6e3d59fac291.png)

### Expected Behavior

Packages using `git+https` must use HTTPS to resolve

### Steps To Reproduce

1. Create a new folder
2. Do `npm init`
3. Do `npm i eth-sig-util@1.4.2`
4. Check package-lock

### Environment

- npm: 8.5.4
- Node.js: 16.14.0
- OS Name: Mac OS
- System Model Name: Macbook Pro
- npm config: (nothing changed from default config)
```ini
```

This also happens in Github Actions environment. See https://github.com/rsksmart/rLogin-essentials/runs/5498619013?check_suite_focus=true

**Comment by XhmikosR** [comment] 2022-03-11 07:18
Agreed, I've been seeing this too for some time and forgot to make an issue.

Happens with `github:repo/owner#branch` too (with npm v8.3.1 that ships with Node.js 16.14.0), unsure if it's 100% the same issue, but the result is the same. (https://github.com/fenneclab/hugo-bin/commit/6f3764855fc87e37134726c0de45cc908d36af0d)

This breaks CI with older npm versions since they don't seem to support `git+ssh`.

**Comment by wraithgar** [comment] 2022-03-14 14:03
Duplicate of https://github.com/npm/cli/issues/2610

**Closed as completed by wraithgar** 2022-03-14 14:03 UTC
Labels: Release 8.x, Bug, Needs Triage
