### ISSUE TITLE
npm install with --legacy-peer-deps modifies shrinkwraps in some cases despite no changes to node_modules/ or package.json

### ISSUE THREAD

**Issue by dgoldstein0** [npm/cli#4006] opened 2021-11-06 20:42 UTC
reproduction with npm 7.13.0 (haven't tried a newer version yet)
```
npm init
npm install --legacy-peer-deps react-use@17.2.4
npm shrinkwrap
cp npm-shrinkwrap.json first
npm install --legacy-peer-deps
diff npm-shrinkwrap.json first
```

I expected the final diff to be empty, but instead I'm getting

```
$ diff npm-shrinkwrap.json first
414c414,415
<       "integrity": "sha512-dg8yXdcQmvgR13RIlZbTRQOoUrDciFVoSBZILwjE2LFISxZZ8loVJKAkuzswl5js8BHda79bIb2b84ehU8IjXw=="
---
>       "integrity": "sha512-dg8yXdcQmvgR13RIlZbTRQOoUrDciFVoSBZILwjE2LFISxZZ8loVJKAkuzswl5js8BHda79bIb2b84ehU8IjXw==",
>       "requires": {}
```

while functionally equivalent, this poses a problem I'm having to work around right now because I'm integrating npm with another tool, and it's assuming that the shrinkwrap will be byte equivalent unless something important changed.

**Comment by madandrija** [comment] 2021-11-09 13:37
I have the same issue in my `package-lock.json`, regardless if I'm using `legacy-peer-deps`, on the latest npm version (8.1.0) - some of us get one version, some get the other. 

The difference turns out to be 

```
-      "devOptional": true
+      "dev": true
```

and

```
-      "integrity": "sha512-15Ft8p1vVEvBQDjZV6XSQULHIbRTetygyGyaF953pq/ukW0AnnHD3Kra7NasJxryWfbBrD18i11uors0CvnOwg==",
-      "requires": {}
+      "integrity": "sha512-15Ft8p1vVEvBQDjZV6XSQULHIbRTetygyGyaF953pq/ukW0AnnHD3Kra7NasJxryWfbBrD18i11uors0CvnOwg=="
```

**Comment by vdhpieter** [comment] 2021-11-22 10:53
Also happening for us regardless of `--legacy-peer-deps`. It's super annoying! Hope this get's fixed soon!

EDIT: It also doesn't happen when using npm ci (that's lucky so it doesn't break our CI caching)

**Comment by darcyclarke** [comment] 2021-12-01 06:07
In the future, please use our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs)

Notably...

1. You should use `npm ci` for consistency (ref. https://docs.npmjs.com/cli/v8/commands/npm-ci)
2. You can pass `--package-lock-only` to `install` to also only read from that/shrinkwrap files for more consistency

Let me know if either of the above still results in mutated lock or shrinkwrap files.

**Comment by vdhpieter** [comment] 2021-12-01 22:44
@darcyclarke Using `npm ci` indeed doesn't have the bug, and we use it what is there for: in our CI. It takes notably longer to run (given it cleans out the `node_modules` folder). It can't be that that is the solution for this problem. We can't ask our developers to constantly run `npm ci` instead of `npm install` .

The second solution only seems to work for the shrinkwrap files which we don't use

Is there something I can do to help? Try to create a reproduction or so

**Comment by dgoldstein0** [comment] 2021-12-04 10:14
oh, I didn't know about npm ci! that seems to be what I need, at least for this particular case of npm install misbehavior.  I still don't think it's ideal for npm install to be non-idempotent like this but for my particular use case, `npm ci` is better than my workaround of always installing twice. (within a tool that's using npm under the hood - so it's not requiring double installation from the user, but instead just is extra slow due to the extra work)

... I'm not really sure why I didn't use the issue template, I'm pretty sure I just didn't see it.  It's been long enough I don't recall.

**Comment by wraithgar** [comment] 2022-05-04 16:20
Closing as `npm ci` worked for the original author of the issue.

**Closed as completed by wraithgar** 2022-05-04 16:20 UTC
Labels: Needs Triage
