### ISSUE TITLE
npm [QUESTION] <title>

### ISSUE THREAD

**Issue by zeki0775** [npm/cli#552] opened 2019-12-04 12:37 UTC
hi, when I say install npm install package, it gives error. not loaded.

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:

what should I do?

**Comment by DanielRuf** [comment] 2019-12-25 19:18
Duplicate of https://github.com/npm/cli/issues/553

**Comment by mikemimik** [comment] 2020-01-20 17:15
Duplicate issue; aggregating into https://github.com/npm/cli/issues/417.

**Closed as completed by mikemimik** 2020-01-20 17:15 UTC
Labels: Bug
