### ISSUE TITLE
Remove link to bug forum from the readme

### ISSUE THREAD

**Issue by rooby** [npm/cli#1529] opened 2020-07-17 04:21 UTC
# What / Why

The project readme says to use https://npm.community/c/bugs/6 to report bugs, however that forum doesn't seem to be as good of a bug tracker as this one.

I've only looked at it briefly but I've already noticed a few issues with it:

- It seems to close issues after a certain time period, regardless of whether a bug was fixed or not. Aside from losing track of what's been fixed or not, this will fragment conversations as new issues will be opened for the same thing once the old one is closed.
- The forum doesn't really seem to be active at all, considering how many people use npm and how many issues get posted in the github issue queue.
- The sorting of the bug list by clicking the headers doesn't seem to work.
- It's separating the repository from its related issues, which makes it more difficult to track what's happening.

Why are you pointing people to go there instead of here?

**Comment by rooby** [comment] 2020-07-17 04:35
I just noticed that the forum is archived: https://npm.community/t/these-forums-have-being-archived/10924/2

However there is no mention of that if you hit that site via other pages, like via the link from the project page here.

It would be useful to change the message in the banner that appears on all the pages of that forum (the one that says "This is the official npm forum.") to say that it's archived.

**Comment by darcyclarke** [comment] 2021-06-02 21:16
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 21:16 UTC
Labels: Release 6.x, Bug

**Comment by rooby** [comment] 2021-06-02 22:09
Looks like these links have been fixed anyway

**Comment by thw0rted** [comment] 2021-09-17 08:21
@darcyclarke it looks like the OP is right about the actual readme, but https://github.com/npm/npm is still the top Google search result for "npm github", and still points to the now-archived Discourse site.  Would it be possible for somebody on the team to update the `npm/npm` front page one more time to point to the best new-new community resources?  Maybe just a link to https://blog.npmjs.org/post/188841555980/updates-to-community-docs-more, which seems to be the latest update on how NPM community works....
