### ISSUE TITLE
[BUG] npm ERR! code ECONNRESET in jenkins pipeline with Node 16.13.1 and NPM 8.1.2

### ISSUE THREAD

**Issue by sandeepdussa** [npm/cli#4221] opened 2022-01-07 16:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

We are facing below issue in our pipeline during npm install. But it works fine in our local machine.

00:45:05  npm timing reify:loadTrees Completed in 165792ms
00:45:05  npm timing reify:diffTrees Completed in 38ms
00:45:05  npm timing reify:retireShallow Completed in 1ms
00:45:06  npm timing reify:createSparse Completed in 428ms
00:45:06  npm timing reify:trashOmits Completed in 5ms
00:45:06  npm timing reify:loadBundles Completed in 0ms
00:45:53  npm verb stack Error: aborted
00:45:53  npm verb stack     at connResetException (node:internal/errors:691:14)
00:45:53  npm verb stack     at TLSSocket.socketCloseListener (node:_http_client:407:19)
00:45:53  npm verb stack     at TLSSocket.emit (node:events:402:35)
00:45:53  npm verb stack     at node:net:687:12
00:45:53  npm verb stack     at Socket.done (node:_tls_wrap:580:7)
00:45:53  npm verb stack     at Object.onceWrapper (node:events:510:26)
00:45:53  npm verb stack     at Socket.emit (node:events:402:35)
00:45:53  npm verb stack     at TCP.<anonymous> (node:net:687:12)
00:45:53  npm verb cwd /bld/workspace/er-pipeline_feature_node-upgrade
00:45:53  npm verb Linux 5.4.0-91-generic
00:45:53  npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--no-audit" "--no-optional" "--no-shrinkwrap" "--no-package-lock" "--loglevel" "verbose"
00:45:53  npm verb node v16.13.1
00:45:53  npm verb npm  v8.1.2
00:45:53  npm ERR! code ECONNRESET
00:45:53  npm ERR! network aborted
00:45:53  npm ERR! network This is a problem related to network connectivity.
00:45:53  npm ERR! network In most cases you are behind a proxy or have bad network settings.
00:45:53  npm ERR! network 
00:45:53  npm ERR! network If you are behind a proxy, please make sure that the
00:45:53  npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
00:45:53  npm verb exit 1
00:45:53  npm timing npm Completed in 206825ms

### Expected Behavior

Smooth npm install is expected.

### Steps To Reproduce

1. In this environment... Jenkins
2. With this config... Using internal artifactory
3. Run '...'  npm install "--no-audit" "--no-optional" "--no-shrinkwrap" "--no-package-lock" "--loglevel" "verbose"
4. See error... error added in current behaviour

### Environment

- npm: 8.1.2
- Node.js: 16.13.1
- OS Name: Linux
- System Model Name: Jenkins Pipeline

**Comment by vrej-abramian** [comment] 2023-04-27 13:56
After resolving the `npm verb stack Error: Socket timeout` error by increasing the npm timeouts to
* `fetch-timeout 500000`, `fetch-retry-maxtimeout 12000000`, and `fetch-retry-mintimeout 2000000`

**Now we have the same issue (error)** - thanks to @sandeepdussa who reported.
Jenkins pipeline for the npm multi-architecture builds (amd64, arm64) using `buildkitd`.  
* npm  v8.19.3
* node v16.19.1
* Linux x86_64
* buildkitd ver: github.com/moby/buildkit v0.11.5 252ae63bcf2a9b62777add4838df5a257b86e991


> [2023-04-27T12:13:00.881Z] #22 656.8 npm timing reifyNode:node_modules/ms Completed in 403286ms
[2023-04-27T12:13:02.092Z] #22 657.9 npm verb stack Error: aborted
[2023-04-27T12:13:02.092Z] #22 657.9 npm verb stack     at connResetException (node:internal/errors:705:14)
[2023-04-27T12:13:02.092Z] #22 657.9 npm verb stack     at TLSSocket.socketCloseListener (node:_http_client:454:19)
[2023-04-27T12:13:02.092Z] #22 657.9 npm verb stack     at TLSSocket.emit (node:events:525:35)
[2023-04-27T12:13:02.092Z] #22 657.9 npm verb stack     at node:net:301:12
[2023-04-27T12:13:02.092Z] #22 657.9 npm verb stack     at TCP.done (node:_tls_wrap:588:7)
[2023-04-27T12:13:02.092Z] #22 657.9 npm verb cwd /home/node/app
[2023-04-27T12:13:02.092Z] #22 657.9 npm verb Linux 5.10.167-147.601.amzn2.x86_64
[2023-04-27T12:13:02.092Z] #22 657.9 npm verb node v16.19.1
[2023-04-27T12:13:02.092Z] #22 657.9 npm verb npm  v8.19.3
[2023-04-27T12:13:02.092Z] #22 658.0 npm ERR! code ECONNRESET
[2023-04-27T12:13:02.359Z] #22 658.3 npm ERR! network aborted
[2023-04-27T12:13:02.359Z] #22 658.3 npm ERR! network This is a problem related to network connectivity.
[2023-04-27T12:13:02.359Z] #22 658.3 npm ERR! network In most cases you are behind a proxy or have bad network settings.
[2023-04-27T12:13:02.359Z] #22 658.3 npm ERR! network 
[2023-04-27T12:13:02.359Z] #22 658.3 npm ERR! network If you are behind a proxy, please make sure that the
[2023-04-27T12:13:02.359Z] #22 658.3 npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
[2023-04-27T12:13:02.359Z] #22 658.3 npm verb exit 1

**Comment by vrej-abramian** [comment] 2023-04-28 13:41
@sandeepdussa, Implementing the following configurations solved my headache on `npm verb stack Error: Socket timeout` & `npm verb stack Error: aborted` for a similar scenario.
* Although I believe that decreasing the `maxsockets` (default 15) did the trick, but also sharing the rest of the parameters that may be helpful:
>maxsockets=10
fetch-retries=5
fetch-retry-factor=20
fetch-timeout=3600000
fetch-retry-mintimeout=3000000
fetch-retry-maxtimeout=3500000

**Comment by milaninfy** [comment] 2024-06-27 14:31
@sandeepdussa  can you try replicating this problem on the latest version of `npm`? (ie. `npm i -g npm`)

**Comment by milaninfy** [comment] 2024-07-04 14:38
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.

**Closed as not planned by milaninfy** 2024-07-04 14:38 UTC
Labels: Release 8.x, Bug, Needs Triage
