### ISSUE TITLE
[BUG] Frequent CloudFlare 502/503 responses from audit endpoints

### ISSUE THREAD

**Issue by DanielThomas** [npm/cli#1154] opened 2020-04-14 17:24 UTC
# What / Why
We're seeing fairly regular timeouts for audit requests. It's not terminal for `npm install` but surfaces in metrics and contract tests we have for our registry caches.

## When
Looks pretty frequent:
<img width="1050" alt="Screen Shot 2020-04-14 at 10 19 25 AM" src="https://user-images.githubusercontent.com/1479220/79254702-f8c33600-7e39-11ea-8e89-cd0a3ac532ca.png">

## Where
Can reproduce with this dummy audit request. Failed several times this morning:
```
curl -v https://registry.npmjs.org/-/npm/v1/security/audits -d '{"requires":{"test":"^0.6.0"},"dependencies":{"ansi-font":{"version":"0.0.2","integrity":"sha1-iQMBvVhBRi/TnAt3Ca/R9SUUMzE="},"test":{"version":"0.6.0","integrity":"sha1-WYasRF7Bd1QyJRLRBLoyyKY+k44=","requires":{"ansi-font":"0.0.2"}}},"install":["test@0.6.0"],"remove":[],"metadata":{"npm_version":"6.4.1","node_version":"v10.11.0","platform":"darwin"}}'
```

Surfaces as both 502 Bad Gateway:
```
< HTTP/2 502
< date: Tue, 14 Apr 2020 17:12:58 GMT
< content-type: text/html; charset=UTF-8
< set-cookie: __cfduid=d97a97fe40a5a0a5abc6751edde4be22c1586884370; expires=Thu, 14-May-20 17:12:50 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax
< cf-ray: 583f0dd4cccced0f-SJC
< cache-control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< set-cookie: cf_ob_info=502:583f0dd4d47aed0f:SJC; path=/; expires=Tue, 14-Apr-20 17:13:28 GMT
< pragma: no-cache
< set-cookie: cf_use_ob=443; path=/; expires=Tue, 14-Apr-20 17:13:28 GMT
< x-frame-options: SAMEORIGIN
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< server: cloudflare
<
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<meta http-equiv="refresh" content="0">

<title>prod-frontdoor-lb-west.internal.npmjs.com | 502: Bad gateway</title>
```

And 503 Service Unavailable:
```
< HTTP/2 503
< date: Tue, 14 Apr 2020 17:11:02 GMT
< content-type: application/json
< content-length: 31
< set-cookie: __cfduid=db6f229e7af08f92201069197b93a66c61586884249; expires=Thu, 14-May-20 17:10:49 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< server: cloudflare
< cf-ray: 583f0adcdfbe6bea-SJC
<
* Connection #0 to host registry.npmjs.org left intact
{"error":"Service Unavailable"}* Closing connection 0
```

**Comment by MM-at-work** [comment] 2020-04-14 22:21
Also seeing this error:

`npm audit --registry=https://registry.npmjs.org -verbose`

502:
[2020-04-14T22_15_27_544Z-debug.log](https://github.com/npm/cli/files/4478048/2020-04-14T22_15_27_544Z-debug.log)

**Comment by cdbkr** [comment] 2020-04-15 14:43
experiencing same issues.
Frequent 500s and 503s between 200s.

**Comment by FBNitro** [comment] 2020-04-15 16:16
Same, 500's etc.
Blocking all my CI/Pull Request runs.

**Comment by trisgerra** [comment] 2020-04-15 16:21
Same issues here. 
500, 503 etc.

**Comment by MM-at-work** [comment] 2020-04-15 20:34
Opened a ticket via community support referencing this issue.
Looks like it may be resolved now.

**Comment by FBNitro** [comment] 2020-04-16 15:27
Looks like it's failing again today:

npm http fetch POST 500 https://registry.npmjs.org/-/npm/v1/security/audits 395ms
npm verb stack Error: Your configured registry (https://registry.npmjs.org/) may not support audit requests, or the audit endpoint may be temporarily unavailable.

It was working for a little while yesterday.

**Comment by MM-at-work** [comment] 2020-04-16 15:28
Failing again today for me too
Here's today's updated error log from
npm audit --registry=https://registry.npmjs.org -verbose

[2020-04-16T15_26_51_839Z-debug.log](https://github.com/npm/cli/files/4488188/2020-04-16T15_26_51_839Z-debug.log)

**Comment by cdbkr** [comment] 2020-04-16 15:39
earlier today was fine but now it's happening the same. experiencing this in Southern US.

**Comment by darcyclarke** [comment] 2021-06-02 22:07
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 22:07 UTC
Labels: Bug
