### ISSUE TITLE
[BUG] error cb() never called!

### ISSUE THREAD

**Issue by sevku** [npm/cli#1207] opened 2020-04-24 20:01 UTC
`$npm install electron`

produces the following:

```
[...]
17013 silly extract core-js@2.6.5 extracted to /home/user/tmp/whatsdesk/node_modules/.staging/core-js-5571b1e3 (3013ms)
17014 http fetch GET 200 https://registry.npmjs.org/app-builder-bin/-/app-builder-bin-2.6.4.tgz 40701ms
17015 silly extract app-builder-bin@2.6.4 extracted to /home/user/tmp/whatsdesk/node_modules/.staging/app-builder-bin-9b742321 (40789ms)
17016 error cb() never called!
17017 error This is an error with npm itself. Please report this error at:
17018 error <https://github.com/npm/npm/issues>

```

**Comment by lolo2mars** [comment] 2020-04-25 22:34
pi@raspberrypi:~/leon $ npm install
> leon@1.0.0-beta.2 preinstall /home/pi/leon
> node scripts/setup/preinstall.js
➡ Running Leon's installation...
npm ERR! cb() never called!
npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-04-25T21_28_49_307Z-debug.log
[...]
20360 silly extract googleapis@25.0.0 extracted to /home/pi/leon/node_modules/.staging/googleapis-666923a3 (2382972ms)
20361 silly extract @ffprobe-installer/win32-x64@4.0.2 extracted to /home/pi/leon/node_modules/.staging/@ffprobe-installer/win32-x64-474ab219 (2394899ms)
20362 silly extract rxjs@6.4.0 extracted to /home/pi/leon/node_modules/.staging/rxjs-6c41163b (1543321ms)
20363 silly extract rxjs@5.5.12 extracted to /home/pi/leon/node_modules/.staging/rxjs-4ee73ddb (1331147ms)
20364 silly extract @ffprobe-installer/darwin-x64@4.0.3 extracted to /home/pi/leon/node_modules/.staging/@ffprobe-installer/darwin-x64-ef4812f7 (2506690ms)
20365 silly extract grpc@1.18.0 extracted to /home/pi/leon/node_modules/.staging/grpc-c88e0105 (669043ms)
20366 timing npm Completed in 2570513ms
20367 error cb() never called!
20368 error This is an error with npm itself. Please report this error at:
20369 error <https://npm.community>

**Comment by SagarKapasi099** [comment] 2020-04-26 16:32
Got this same error.

$ `npm i -g mdlt`
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/<USER>/.npm/_logs/2020-04-26T16_19_16_819Z-debug.log


**Log Contains This.**
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/13.13.0_1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   '-g',
1 verbose cli   'mdlt'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v13.13.0
4 verbose npm-session 408a68c4e061fa82
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/mdlt 4862ms
8 timing npm Completed in 96810ms
9 error cb() never called!
10 error This is an error with npm itself. Please report this error at:
11 error <https://npm.community>
```

But `npm i -g mdlt` worked the second time.

**Comment by SagarKapasi099** [comment] 2020-04-27 12:37
Getting this same error again. Now inside docker.
While deploying an angular frontend.

```
$ sudo docker-compose build

Building myapp
Step 1/11 : FROM node AS build
 ---> a5a6a9c32877
Step 2/11 : WORKDIR /usr/src/app
 ---> Using cache
 ---> a09e007c0606
Step 3/11 : COPY package.json ./
 ---> Using cache
 ---> e6a7acd14931
Step 4/11 : RUN npm install
 ---> Running in 6a9fc478f42a
npm WARN deprecated tslint@6.1.2: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.12: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-27T12_27_56_282Z-debug.log
ERROR: Service 'myapp' failed to build: The command '/bin/sh -c npm install' returned a non-zero code: 1

```
Sorry. i don't know how to get log file from a container that failed to build and is not running.

docker-compose.yaml
```
version: '2'
services:
  myapp:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - VIRTUAL_HOST=www.example.com,example.com
      - LETSENCRYPT_HOST=www.example.com,example.com
    network_mode: example_default
```

Dockerfile
```
### STAGE 1: Build ###
FROM node AS build
WORKDIR /usr/src/app
COPY package.json ./
RUN npm install
COPY . .
RUN rm -rf /usr/src/app/dist/Frontend/*
RUN node_modules/@angular/cli/bin/ng build --prod
### STAGE 2: Run ###
FROM nginx
COPY --from=build /usr/src/app/dist/Frontend /usr/share/nginx/html
COPY ./nginx/default.conf /etc/nginx/conf.d
EXPOSE 80
```

**Comment by calebdwilliams** [comment] 2020-04-27 14:10
Getting the same issue on an install.

**Comment by lolo2mars** [comment] 2020-04-29 18:06
I'd first running npm install  ( and get all packages depencies linked to leon project ) 
with : npm ERR! cb() never called!
So when I run now "npm install --only=dev" don't need to do extracts steps because pkg was allready got before on previous running ... so it running  postinstall .. 
I hope this help you to use this version 14 :)

**Comment by darcyclarke** [comment] 2021-06-02 21:21
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 21:21 UTC
Labels: Release 6.x, Bug
