### ISSUE TITLE
[BUG] Cannot update npm v7 to latest version.

### ISSUE THREAD

**Issue by Ayfri** [npm/cli#2630] opened 2021-02-05 12:11 UTC
### Current Behavior:
When I execute `npm i -g npm@7`, I get this error every times:
```js
npm ERR! code EPERM
npm ERR! syscall rename
npm ERR! path C:\Users\Pierre\AppData\Roaming\npm\node_modules\npm\node_modules\encoding\lib
npm ERR! dest C:\Users\Pierre\AppData\Roaming\npm\node_modules\.npm-71ox59pH\node_modules\encoding\lib
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\Pierre\AppData\Roaming\npm\node_modules\npm\node_modules\encoding\lib' -> 'C:\Users\Pierre\AppData\Roaming\npm\node_modules\.npm-71ox59pH\node_modules\encoding\lib'
npm ERR!  [Error: EPERM: operation not permitted, rename 'C:\Users\Pierre\AppData\Roaming\npm\node_modules\npm\node_modules\encoding\lib' -> 'C:\Users\Pierre\AppData\Roaming\npm\node_modules\.npm-71ox59pH\node_modules\encoding\lib'] {
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\Users\\Pierre\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\encoding\\lib',
npm ERR!   dest: 'C:\\Users\\Pierre\\AppData\\Roaming\\npm\\node_modules\\.npm-71ox59pH\\node_modules\\encoding\\lib'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Pierre\AppData\Local\npm-cache\_logs\2021-02-05T12_06_42_557Z-debug.log
```

### Expected Behavior:
Get the latest version installed globally.

### Environment:
- OS: Window 20h2
- Node: 15.7.0
- npm: 7.5.0

**Comment by dhtzs** [comment] 2021-02-05 12:14
I've been facing the same problem for a while now. I've tried checking folder/file permissions but everything seems normal as I have full control permissions. There should obviously be a solution to the problem.

**Comment by dhtzs** [comment] 2021-02-05 13:54
I've been facing the same problem for a while now. I've tried checking folder/file permissions but everything seems normal as I have full control permissions. There should obviously be a solution to the problem.

Environment:
OS: Windows 10 20H2
Node: 15.8.0
npm: 7.5.0 / 7.5.1

**Comment by SBRK** [comment] 2021-02-05 14:34
Haven't had the issue by updating, but I have a similar issue when linking my libs... So far NPM7 has been a trainwreck for me...

**Comment by apasov** [comment] 2021-02-05 16:32
I get this error also when running `npm update -g` as well as when trying to re-install or update any already existing global package.  Installing a global package not installed previously works properly.

**Comment by Ayfri** [comment] 2021-02-05 17:23
I also get this error in administrator mode.

**Comment by dhtzs** [comment] 2021-02-05 19:27
> I also get this error in administrator mode.

Even worse, when I'm trying to run `npm i npm -g` with administrator rights, npm installation completely breaks.

**Comment by DeeDeeG** [comment] 2021-02-11 04:43
Edit: Actually, I tested again, and this comment doesn't seem to be accurate for me anymore. I can properly do `npm install -g npm`. Working for me with npm v6 and v7. Sorry for the noise.

Hi folks. I think `npm install -g npm` doesn't work very well on Windows. (It hasn't worked well for me even with npm v6.)

There is a utility meant to make this easier: https://github.com/felixrieseberg/npm-windows-upgrade#readme

If you are reluctant to install that or need a technically minimal fix, I also know of a manual workaround, but it's not very fun to do and can break your npm install if you don't do it right... (Tested only with NodeJS extracted from a .zip. Not tested with Node from the `.msi` installer.)

<details><summary>Advanced manual workaround. Follow the steps carefully or it may break your npm install! (Click to expand):</summary>

- Navigate to where your npm is installed, using the file browser
- Rename the `npx.cmd` batch script to `npx-old.cmd`
- Rename the plain `npm` and `npx` files with no file extension to `npm-old` and `npx-old` (or delete them! These are not used on Windows, as far as I know, unless you are on Windows Subsystem for Linux or something.)
- If you have them, rename `npm.ps1` and `npx.ps1` to `npm-old.ps1` and `npx-old.ps1`
- Get ready to do these next things really fast:
  - In a terminal window (`cmd.exe`), run `npm install -g npm`
  - Once you see npm is running, IMMEDIATELY rename the `npm.cmd` file to `npm-old.cmd`

All this allows npm to install the new files without having a file permission error regarding the existing files.

</details>

It would be great if `npm install -g npm` "just worked" though. I'd be thankful for any effort from the npm team to make that possible. Best regards.

**Comment by nlf** [comment] 2021-02-11 16:46
a patch for the original issue reported here will be landing soon and part of the next release!

**Comment by nlf** [comment] 2021-02-16 16:29
this is resolved in 7.5.4, unfortunately if you already have the broken 7.5.3 getting it installed is either going to mean:

1) reinstall nodejs entirely, then `npm i -g npm` which should get you the fixed 7.5.4
2) if you have bash, try running `curl -q https://www.npmjs.com/install.sh | sh`

I'm going to close this issue as we do have outside confirmation that 7.5.4 works correctly, but do let us know in a new issue if you continue to see this problem after updating!

**Closed as completed by nlf** 2021-02-16 16:29 UTC
Labels: Release 7.x, Bug, platform:windows, Priority 1

**Comment by vaaski** [comment] 2021-02-17 08:29
I can confirm that global installs are fixed in 7.5.4, however simply using the repair option of the 14.15.5 LTS Node.js installer didn't work on windows.

And because I had to uninstall anyway I replaced the default installation method with [nvs](https://github.com/jasongin/nvs) which makes switching Node.js versions a breeze.

**Comment by SBRK** [comment] 2021-02-23 15:47
NPM is still stuck to 7.5.3 with `nvm`, even when installing the latest version. Is there a way to install manually ?

**Comment by nlf** [comment] 2021-02-23 15:49
i'm not sure i follow, you mean after uninstalling and reinstalling you're still on 7.5.3?

you can try to clone this repo and install npm from it directly

```sh
git clone git@github.com:npm/cli
cd cli
node . install -g npm
```

**Comment by SBRK** [comment] 2021-02-23 16:02
> i'm not sure i follow, you mean after uninstalling and reinstalling you're still on 7.5.3?

yes. I was able to get it working, I just cloned and copied by hand to the node_modules folder of my node installation. I can confirm that the problems I had (global install, link) all seem gone!

**Comment by nlf** [comment] 2021-02-23 16:02
glad to hear!

**Comment by hades42** [comment] 2022-02-28 13:10
I have been trying to follow every single approach here. And it's still not working for me.
Mine is still showing:
```
❯ npm -v
7.3.0
```
## Environment: 
OS: macOS 11.4
Shell: fish 3.3.1
Node: v17.6.0
