### ISSUE TITLE
[BUG] Install of certain package errors out 'cb() never called' 

### ISSUE THREAD

**Issue by Anan5a** [npm/cli#1135] opened 2020-04-10 08:06 UTC
# What / Why

> NPM failed to install some package dependencies 
It failed during installation of ```fsevents``` package

## When

* today?

## Where

* n/a

### Current Behavior

* Fails in middle of ```npm install```

### Steps to Reproduce

* try installing a package that depends on fsevents

### Expected Behavior

* should install just fine

## Who

* n/a

## References

* n/a

## Logs

```
ananta@debian:~/PROJECTS/unit3d-test$ npm install --verbose --no-optional
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/home/ananta/.nvm/versions/node/v13.11.0/bin/node',
npm verb cli   '/home/ananta/.nvm/versions/node/v13.11.0/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   '--no-optional'
npm verb cli ]
npm info using npm@6.13.7
npm info using node@v13.11.0
npm verb npm-session 98f4aa45dbec2486
npm info lifecycle @~preinstall: @
npm timing stage:loadCurrentTree Completed in 16ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 1061ms
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 1609ms
npm timing stage:loadIdealTree Completed in 3122ms
npm timing stage:generateActionsToTake Completed in 846ms
npm verb correctMkdir /home/ananta/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /home/ananta/.npm/_locks/staging-f8b184b98acc8f8d.lock for /home/ananta/PROJECTS/unit3d-test/node_modules/.staging
npm http fetch GET 304 http://registry.npmjs.org/emojione-assets 1976ms (from cache)
npm timing npm Completed in 562914ms
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ananta/.npm/_logs/2020-04-10T08_01_52_782Z-debug.log
ananta@debian:~/PROJECTS/unit3d-test$ 
```

### Last few lines of debug.log

```
16995 silly extract es-abstract@1.17.5 extracted to /home/ananta/PROJECTS/unit3d-test/node_modules/.staging/es-abstract-fadff1e1 (5857ms)
16996 silly extract collect.js@4.20.3 extracted to /home/ananta/PROJECTS/unit3d-test/node_modules/.staging/collect.js-584c6c61 (1565ms)
16997 silly extract es5-ext@0.10.52 extracted to /home/ananta/PROJECTS/unit3d-test/node_modules/.staging/es5-ext-7071914d (7239ms)
16998 silly extract lodash@4.17.15 extracted to /home/ananta/PROJECTS/unit3d-test/node_modules/.staging/lodash-f9e1c64d (3434ms)
16999 silly extract caniuse-lite@1.0.30001038 extracted to /home/ananta/PROJECTS/unit3d-test/node_modules/.staging/caniuse-lite-5af91014 (1916ms)
17000 silly extract fsevents@1.2.11 extracted to /home/ananta/PROJECTS/unit3d-test/node_modules/.staging/fsevents-c428c5f0 (2638ms)
17001 timing npm Completed in 562914ms
17002 error cb() never called!
17003 error This is an error with npm itself. Please report this error at:
17004 error <https://npm.community>
```

**Comment by DanielRuf** [comment] 2020-04-12 16:54
Duplicate of #417

Please also try to upgrade npm to the latest available release.

**Comment by Anan5a** [comment] 2020-04-12 18:03
@DanielRuf  ``` npm 6.14.4``` via ```nvm```

**Comment by darcyclarke** [comment] 2021-06-02 21:25
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 21:25 UTC
Labels: Release 6.x, Bug
