### ISSUE TITLE
[BUG] <npm ERR! ERESOLVE unable to resolve dependency tree>

### ISSUE THREAD

**Issue by thigur** [npm/cli#5780] opened 2022-10-31 20:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

$ sudo npm i dotenv
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: consensys.demos@0.1.0
npm ERR! Found: next@undefined
npm ERR! node_modules/next
npm ERR!   next@"12.1.4" from the root project
npm ERR! 
npm ERR! peer next@">=10.2.0" from eslint-config-next@12.1.4
npm ERR! node_modules/eslint-config-next
npm ERR!   dev eslint-config-next@"12.1.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-10-31T19_23_00_439Z-debug-0.log

$ sudo npm i dotenv --force
npm WARN using --force Recommended protections disabled.
npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-10-31T19_33_07_712Z-debug-0.log

### Expected Behavior

Not sure

### Steps To Reproduce

1. In this environment... See below
2. With this config... See below
3. Run '...' Run
4. See error... See above

### Environment

- npm: 8.19.2
- Node.js: v14.20.0
- OS Name: ubuntu 18
- System Model Name:NA
- npm config:NA
```ini; copy and paste output from `npm config ls` here
```
; node bin location = /usr/bin/node
; node version = v14.20.0
; npm local prefix = /home/lnnnnn/Getting-Started-With-Infura
; npm version = 8.19.2
; cwd = /home/nnnnn/Getting-Started-With-Infura
; HOME = /home/nnnnn
; Run `npm config ls -l` to show all defaults.

**Comment by lukekarrys** [comment] 2022-11-02 02:55
Can you post your `package.json` and/or `package-lock.json`, and also the full contents of the debug log file? It looks like there are some conflicting peer dependency versions in your tree. You can also try installing with `--force` or `--legacy-peer-deps`.

**Comment by lukekarrys** [comment] 2022-12-07 02:22
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.

**Closed as completed by lukekarrys** 2022-12-07 02:22 UTC
Labels: Awaiting Information, Release 8.x

**Comment by MuhammadsolihGofurov** [comment] 2023-01-05 16:51
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: portfolio@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0 || ^16.0.0 || ^17.0.0" from react-lazyload@3.2.0
npm ERR! node_modules/react-lazyload
npm ERR!   react-lazyload@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\BEST\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\BEST\AppData\Local\npm-cache\_logs\2023-01-05T16_50_04_769Z-debug-0.log

**Comment by MuhammadsolihGofurov** [comment] 2023-01-05 16:51
i mean , i have problem that is releated it

**Comment by MuhammadsolihGofurov** [comment] 2023-01-05 16:52
please , who can help me ?

**Comment by suleigolden** [comment] 2023-03-06 16:45
@lukekarrys  I also have almost the same problem. Here are my error logs.  Running Git Action on react application

Run npm ci
  
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @material-ui/core@[4](https://github.com/suleigolden/codebender-frontend/actions/runs/4345476760/jobs/7590240489#step:4:4).12.[4](https://github.com/suleigolden/codebender-frontend/actions/runs/4345476760/jobs/7590240489#step:4:5)
npm ERR! Found: @types/react@18.0.28
npm ERR! node_modules/@types/react
npm ERR!   @types/react@"^18.0.14" from the root project
npm ERR!   peerOptional @types/react@"*" from @material-ui/types@[5](https://github.com/suleigolden/codebender-frontend/actions/runs/4345476760/jobs/7590240489#step:4:6).1.0
npm ERR!   node_modules/@material-ui/types
npm ERR!     @material-ui/types@"5.1.0" from @material-ui/core@4.12.4
npm ERR!     node_modules/@material-ui/core
npm ERR!       @material-ui/core@"^4.12.4" from the root project
npm ERR!       1 more (@material-ui/icons)
npm ERR!     @material-ui/types@"5.1.0" from @material-ui/styles@4.11.5
npm ERR!     node_modules/@material-ui/styles
npm ERR!       @material-ui/styles@"^4.11.5" from @material-ui/core@4.12.4
npm ERR!       node_modules/@material-ui/core
npm ERR!         @material-ui/core@"^4.12.4" from the root project
npm ERR!         1 more (@material-ui/icons)
npm ERR!   7 more (@types/hoist-non-react-statics, @types/react-dom, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional @types/react@"^1[6](https://github.com/suleigolden/codebender-frontend/actions/runs/4345476760/jobs/7590240489#step:4:7).8.6 || ^17.0.0" from @material-ui/core@4.12.4
npm ERR! node_modules/@material-ui/core
npm ERR!   @material-ui/core@"^4.12.4" from the root project
npm ERR!   peer @material-ui/core@"^4.0.0" from @material-ui/icons@4.11.3
npm ERR!   node_modules/@material-ui/icons
npm ERR!     @material-ui/icons@"^4.11.3" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @types/react@1[7](https://github.com/suleigolden/codebender-frontend/actions/runs/4345476760/jobs/7590240489#step:4:8).0.53
npm ERR! node_modules/@types/react
npm ERR!   peerOptional @types/react@"^16.[8](https://github.com/suleigolden/codebender-frontend/actions/runs/4345476760/jobs/7590240489#step:4:9).6 || ^17.0.0" from @material-ui/core@4.12.4
npm ERR!   node_modules/@material-ui/core
npm ERR!     @material-ui/core@"^4.12.4" from the root project
npm ERR!     peer @material-ui/core@"^4.0.0" from @material-ui/icons@4.11.3
npm ERR!     node_modules/@material-ui/icons
npm ERR!       @material-ui/icons@"^4.11.3" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /home/ubuntu/.npm/_logs/2023-03-06T16_0[9](https://github.com/suleigolden/codebender-frontend/actions/runs/4345476760/jobs/7590240489#step:4:10)_19_680Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2023-03-06T[16](https://github.com/suleigolden/codebender-frontend/actions/runs/4345476760/jobs/7590240489#step:4:17)_09_[19](https://github.com/suleigolden/codebender-frontend/actions/runs/4345476760/jobs/7590240489#step:4:20)_680Z-debug-0.log
Error: Process completed with exit code 1.
