### ISSUE TITLE
[BUG] @ffmpeg-installer/ffmpeg - npm ERR! "cb() never called"

### ISSUE THREAD

**Issue by JeremieRousseau** [npm/cli#799] opened 2020-02-12 10:51 UTC
Hello 

I tried to install ffmpeg by :
> sudo npm install --save @ffmpeg-installer/ffmpeg
return npm ERR! "cb() never called"

> npm -v
6.13.7
> node -v
v13.7.0 

OS : Linux Mint 19.3 Tricia base ubuntu bionic

I can install express without a problem.
Ask : Is it a chmod problem? A graphic card problem or an npm problem?

**Comment by DanielRuf** [comment] 2020-02-18 06:24
Duplicate of https://github.com/npm/cli/issues/417

**Comment by darcyclarke** [comment] 2021-06-02 21:55
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 21:55 UTC
Labels: Bug
