### ISSUE TITLE
[BUG] Add `"max-len": ["error", 80]` to .eslintrc.json and make it work

### ISSUE THREAD

**Issue by isaacs** [npm/cli#2029] opened 2020-10-23 18:22 UTC
We have a lot of long lines, let's shorten them.

Be smart about making the choices to split lines, no fake internet points for cutting strings and making them unreadable!

**Comment by ljharb** [comment] 2020-10-23 19:05
You can configure max-len to ignore lines with long strings or regexes or urls; i suggest doing so. Example: https://github.com/airbnb/javascript/blob/2c5c88d0487db3024e8a20bb20f46933a03dd8aa/packages/eslint-config-airbnb-base/rules/style.js#L205

**Comment by dominguetigs** [comment] 2020-11-14 03:24
@isaacs 
Is anyone doing this issue?

**Comment by Gurinderp** [comment] 2020-11-25 07:58
Could I take on this issue if no one is currently working on it? @isaacs 
Not sure if @dominguetigs still wants it.

**Comment by dominguetigs** [comment] 2020-11-25 09:14
You can do it @Gurinderp

**Comment by tutur0001** [comment] 2020-12-03 10:54
Me I can if you want

**Comment by codexofc** [comment] 2020-12-03 14:05
Can you assign me on this issue ? @isaacs

**Comment by Edu93Jer** [comment] 2020-12-06 22:45
Hi @isaacs is anyone still working on the case? If no, could you please explain to me a little more about the project, I'm a newbie and would like to contribute, or is the issue is closed?

**Comment by Edu93Jer** [comment] 2020-12-15 21:42
@darcyclarke - @isaacs, so I just added the "max-len" to the .eslintrc.json, but what do you mean with make it work?
It should be working right, just adding this rules...
`"max-len": ["error", 80, {
      "ignoreUrls": true,
      "ignoreComments": false,
      "ignoreRegExpLiterals": true,
      "ignoreStrings": true,
      "ignoreTemplateLiterals": true
    }]`

**Comment by isaacs** [comment] 2020-12-16 00:52
Well, there are quite a few places (iirc?) that are longer than 80 chars.  So `npm run lint` should not raise any errors with that option.

**Comment by a2br** [comment] 2020-12-29 15:51
Looks like https://github.com/npm/cli/pull/2361 has been merged. Shouldn't this issue be closed too?

**Closed as completed** 2020-12-29 15:53 UTC
Labels: Priority Backlog, Enhancement, Good First Issue, Release 7.x, Bug, :gem: Free Internet Points :gem:
