### ISSUE TITLE
[BUG] npm v7.10+ incompatible with git v2.22

### ISSUE THREAD

**Issue by acshef** [npm/cli#3578] opened 2021-07-26 18:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

From npm v7.10 and onward, installing a package from a git repository fails because npm is internally passing some bad arguments to git. Manual execution of git commands (e.g. `git clone` or `git ls-remote`) works as expected. I suspect this is a result of the following commit, appearing in npm 7.10:

3b476a24cf0b2823fdf92505b84bddde4fcc8b14 `@npmcl/git@2.0.8`
fix(git): do not use shell when calling git

### Expected Behavior

Installing a package of the form `git+ssh://git@server/path/to/repo.git` should install as expected (assuming permissions, SSH, etc. are all correct)

### Steps To Reproduce

1. On linux, with git 2.22.x (assuming setup that yields correct behavior of git and ssh)
2. Run `npm i --no-save git+ssh://git@bitbucket.COMPANYNAME.com/PATH/TO/REPO.git`\*
3. See error:
```
npm ERR! code 128
npm ERR! command failed
npm ERR! command git ls-remote ssh://git@bitbucket.COMPANYNAME.com/PATH/TO/REPO.git
npm ERR! command-line line 0: Bad yes/no/ask argument.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
```

\* Obviously, I've used a git server internal to my company. But this error should present itself even if using GitHub's `git+ssh://git@github.com:user_name/node_project.git` syntax.

### Environment

- OS: Linux (any x86/x64)
- Node: Tested on 11+
- npm: 7.10+
- git 2.22.x

**Comment by nlf** [comment] 2022-03-08 22:18
we've made a few changes to how git dependencies are handled since this issue was opened, can you try updating to npm@8.5.3 and see if you still have this problem?

**Comment by wraithgar** [comment] 2022-03-16 14:24
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.


I think this was likely fixed by https://github.com/npm/git/pull/7

**Closed as completed by wraithgar** 2022-03-16 14:24 UTC
Labels: Release 7.x, Bug, Needs Triage
