### ISSUE TITLE
[BUG] npm exec failed at launch `yarn-deduplicate`

### ISSUE THREAD

**Issue by SkReD** [npm/cli#1668] opened 2020-08-13 07:30 UTC
### Current Behavior:
Failing with error
```
Error: Cannot find module 'C:\test-package\node_modules\yarn-deduplicate\cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

### Expected Behavior:
Runs without errors 

### Steps To Reproduce:
1. Run `npm exec yarn-deduplicate` in any directory with yarn.lock

### Environment:
- OS: Windows 10 x64
- Node: 12.14.1
- NPM: 7.0.0-beta.4

**Comment by ruyadorno** [comment] 2020-09-23 21:04
hi @SkReD I tried but could not reproduce it on macos:

```sh
$ mkdir test-yarn-deduplicate && cd test-yarn-deduplicate
$ yarn init
$ yarn add simple-output
$ npm exec yarn-deduplicate
### no output (I assume it worked fine?)
$ echo $?
### 0
```

Please let us know if you can get the latest beta version (currently `v7.0.0-beta.12`) and still see the problem, if that's the case a minimal reproduction example (feel free to push to a git repo) would be super helpful. 😊 Thanks!

**Comment by darcyclarke** [comment] 2020-11-02 18:46
Closing. Please feel free to reopen if you're still experiencing this issue.

**Closed as completed by darcyclarke** 2020-11-02 18:46 UTC
Labels: Release 7.x, Bug, platform:windows
