### ISSUE TITLE
[BUG] npm error Exit handler never called!

### ISSUE THREAD

**Issue by Vikybad** [npm/cli#7669] opened 2024-07-19 10:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by Sebastian-Webster** [comment] 2024-07-19 10:19
I'm having this issue as well. I've noticed it only happens only on Node.js 22.5.0. I had a GitHub Actions workflow with the following matrix:
os: [ ubuntu-20.04, ubuntu-22.04, windows-2019, windows-2022, macOS-12, macOS-13, macOS-14 ]
node-version: [18.x, 19.x, 20.x, 21.x, 22.4.0, 22.4.1, 22.5.0 ]
All workflows worked except for the ones running node 22.5.0

**Comment by AleksaRistic216** [comment] 2024-07-19 10:38
I have same issue and it started today. I have workflow runs which build my docker images and I run them multiple times a day.
Last time it worked was yesterday (18.07.2024)

![image](https://github.com/user-attachments/assets/3969cc93-5604-4b03-8430-01e7b0f549c6)

Jobs are running on:
```
  Ubuntu
  22.04.4
  LTS
  Image: ubuntu-22.04
  Version: 20240714.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240714.1/images/ubuntu/Ubuntu2204-Readme.md

  ```

**Comment by marvingbh** [comment] 2024-07-19 10:56
same issue

**Comment by matteobe** [comment] 2024-07-19 11:08
Same issue
Also yesterday working, no changes and today not working

**Comment by alex-weber** [comment] 2024-07-19 11:14
same issue on Heroku. Build fails using 22.5.0
22.4.1 works fine

**Comment by Sebastian-Webster** [comment] 2024-07-19 11:15
An example GitHub Actions workflow with this issue can be found here: https://github.com/Sebastian-Webster/npm-reproducible-example/actions/runs/10007074269. It's only failing on Node 22.5.0. Both npm ci and npm install

**Comment by actualben** [comment] 2024-07-19 11:17
This `npm install` error is happening on the `node:22@sha256:b44cbfafe84144217b7502cde5d21958500781fb9b13eed74a47486db2277cd5` docker tag. It's notable that npm exits 0 after it fails. I have a [filtered error log excerpt](https://pastebin.com/wqfnrbL2).

* npm -v: 10.8.2
* node -v: v22.5.0
* OS Name: Debian 12
* System Model Name: N/A - happening on both ARM64 and AMD64
* npm config ls: 
```
node bin location = /usr/local/bin/node
node version = v22.5.0
npm local prefix = /build
npm version = 10.8.2
cwd = /build
HOME = /root
```

**Comment by gopivr** [comment] 2024-07-19 11:20
Any work around for this issue.. Still facing this issue

**Comment by alex-weber** [comment] 2024-07-19 11:23
> Any work around for this issue.. Still facing this issue

use node 22.4

**Comment by milaninfy** [comment] 2024-07-19 12:23
Closing Seems similer if not duplicate of https://github.com/npm/cli/issues/7657.
Try node 22.4.1 with npm 10.8.2.

**Closed as completed by milaninfy** 2024-07-19 12:23 UTC
Labels: Bug, Needs Triage

**Comment by milaninfy** [comment] 2024-07-19 14:36
Fixed in Node.js v22.5.1 https://github.com/nodejs/node/issues/53902#issuecomment-2239263377
