### ISSUE TITLE
cb() never called![BUG] <title>

### ISSUE THREAD

**Issue by bhargav2204** [npm/cli#828] opened 2020-02-15 07:21 UTC
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bhagu\AppData\Roaming\npm-cache\_logs\2020-02-15T07_06_40_844Z-debug.log
PS E:\instaprops\ipros-website>

**Comment by MuhammadAyaz33** [comment] 2020-02-15 17:38
getting same error when running 'npm install'  :(
node => v13.8.0
npm => 6.13.6
Ubuntu 18.04 LTS

**Comment by antonioastorino** [comment] 2020-02-15 20:25
Same here.
Console output:
```Antonios-MacBook-Pro:template antonio$ npm i @types/jquery
Unhandled rejection Error: EACCES: permission denied, open '/Users/antonio/.npm/_cacache/index-v5/d3/e5/07764666b5b3c75ba85c4299f9f79c6b6cb6394880f6c5ebc93c03ca2434'

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/antonio/.npm/_logs/2020-02-15T20_16_22_762Z-debug.log
```
Log file content:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   '@types/jquery' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose npm-session 85a736fb6c62f2ea
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 timing npm Completed in 512ms
8 error cb() never called!
9 error This is an error with npm itself. Please report this error at:
10 error <https://npm.community>

```

**Comment by antonioastorino** [comment] 2020-02-15 20:31
Workaround googled:
sudo chown -R $(whoami) ~/.npm

**Comment by DanielRuf** [comment] 2020-02-18 05:59
Duplicate of https://github.com/npm/cli/issues/417

**Closed as completed** 2020-10-30 20:57 UTC
