### ISSUE TITLE
[BUG] Can't create a new project using either angular or ionic cli

### ISSUE THREAD

**Issue by donhmorris** [npm/cli#2667] opened 2021-02-10 19:58 UTC
### Current Behavior:
Get an error when creating an ionic app using angular.

Get this error while creating the project:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: test3@0.0.1
npm ERR! Found: @angular/compiler@11.0.9
npm ERR! node_modules/@angular/compiler
npm ERR!   dev @angular/compiler@"~11.0.5" from the root project
npm ERR!   peer @angular/compiler@"11.0.9" from @angular/compiler-cli@11.0.9
npm ERR!   node_modules/@angular/compiler-cli
npm ERR!     dev @angular/compiler-cli@"~11.0.5" from the root project
npm ERR!     peer @angular/compiler-cli@"^11.0.0" from @angular-devkit/build-angular@0.1100.7
npm ERR!     node_modules/@angular-devkit/build-angular
npm ERR!       dev @angular-devkit/build-angular@"~0.1100.5" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/compiler@"11.1.2" from @angular/localize@11.1.2
npm ERR! node_modules/@angular/localize
npm ERR!   peerOptional @angular/localize@"^11.0.0" from @angular-devkit/build-angular@0.1100.7
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"~0.1100.5" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/don/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/don/.npm/_logs/2021-02-10T19_52_20_549Z-debug.log
[ERROR] An error occurred while running subprocess npm.
```

### Expected Behavior:
Successfully create ionic project and install dependencies

### Steps To Reproduce:
ionic command: ionic start test3
choose angular and then sidemenu

### Environment:
- os Mac Big Sur
- Apple silicon (M1)
- Node 15.8.0
- NPM 7.5.3

If I install NPM 6.14.11 and keep everything else the same, ionic works fine.

**Comment by isaacs** [comment] 2021-02-11 01:12
Can you please share the file `/Users/don/.npm/eresolve-report.txt` and `/Users/don/.npm/_logs/2021-02-10T19_52_20_549Z-debug.log`?  That will be helpful in resolving this.

**Comment by isaacs** [comment] 2021-02-11 01:13
I believe that the root cause of this is likely https://github.com/npm/arborist/issues/223

**Closed as completed** 2021-02-12 16:50 UTC
Labels: Release 7.x, Bug, Needs Triage

**Comment by donhmorris** [comment] 2021-02-12 20:21
Was there a code change implemented for this problem?
