### ISSUE TITLE
[BUG] npm does not setup child workspace’s bin or use parent’s bin

### ISSUE THREAD

**Issue by jlarmstrongiv** [npm/cli#4591] opened 2022-03-20 09:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I cannot run unpublished npx package scripts in child workspaces

### Expected Behavior

When using npm, whether from:
- npm install
- npm rebuild
- npx

I expect to find the `node_modules/.bin` folder for my `package.json` scripts in the child workspaces, not just parent.  I expect npm to link the bin folder in my child package.  

Or, I expect npm to fallback to/include the parent’s bin, so that unpublished npx commands can still be found.

### Steps To Reproduce

1. Create an npm workspace with multiple packages
2. Have one package set the bin property in the package.json
```json
{
  "name": "@clis/port",
  "version": "1.0.0",
  "private": true,
  "type": "module",
  "exports": {
    "require": "./dist/index.cjs",
    "default": "./dist/index.js"
  },
  "main": "dist/index.cjs",
  "module": "dist/index.js",
  "source": "src/index.ts",
  "types": "dist/index.d.ts",
  "bin": "./dist/cli.js",
  },
}
```
4. Have another package depend on that first package
```json
{
  "name": "@keystonejs/example",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "port": "npx @clis/port",
  },
  "devDependencies": {
    "@clis/port": "file:../../../clis/port",
  },
}
```
5. Be sure you have installed all dependencies with `npm install`
6. Attempt to run the script `npm run port`
7. Watch npm crash as it tries to find the private package published in npm, rather than find the private package locally

### Other notes:
These script work fine in the parent package.json, as the `node_modules/.bin` folder exists.  However, it will crash in all child workspaces by trying to find a published version on npm.

### Other notes:
Related issues:
- https://github.com/npm/cli/issues/2826
- https://github.com/npm/cli/issues/3520

### Environment

- npm:  8.1.0
- Node.js:  v14.18.1
- OS Name:  MacOS 10.15.7
- System Model Name:  MacBook Pro
- npm config:
```ini
; "user" config from /Users/username/.npmrc

//registry.npmjs.org/:_authToken = (protected)
init-author-name = (protected)
scripts-prepend-node-path = "auto"

; "env" config from environment

prefix = "/Users/username/.asdf/installs/nodejs/14.18.1/.npm"

; node bin location = /Users/username/.asdf/installs/nodejs/14.18.1/bin/node
; cwd = /Users/username/Desktop/monorepos/turbo-monorepo
; HOME = /Users/username
; Run `npm config ls -l` to show all defaults.
```

**Comment by ShusenLiu** [comment] 2022-04-27 22:57
I encounter the same issue. as a workaround, i need to:
```
npm i
npm run build -ws `package-with-binary`
npm i
npm run `package-with-binary`
```

and I observe that in the second `npm i`, it actually produce these logs:
```
44 silly reify mark retired [
44 silly reify   'path/node_modules/cli',
44 silly reify ]
45 silly reify moves {
45 silly reify   'path/node_modules/cli': 'path/node_modules/cli-FzlzzC2M',
45 silly reify }
```

this is really annoying for us, hope this could be prioritize and fixed soon.

**Comment by cackerman-qumulo** [comment] 2023-01-20 23:30
Ran into this as well. Running the following caused an error.

```sh
npm ci
npx lerna run build
npx <workspace-name>
```

The solution I found was to add an `npm update` after building.

```sh
npm ci
npx lerna run build
npm update <workspace-name>
npx <workspace-name>
```

That seems to work for me, without having to run a full "install" again.

**Comment by romanlex** [comment] 2023-03-28 20:04
Can confirm this issues with npm 9

**Comment by apples** [comment] 2023-05-15 22:12
I believe I'm running into a related issue here.

I've got two git repos: `monorepo-1` and `monorepo-2`. Both are using npm workspaces.

Inside of `monorepo-1` is a package `A`, and inside of `monorepo-2` are packages `B` and `C`.

`A` depends on `B` via a `git+ssh` url.
`B` depends on `C` via local workspace.
`C` has `bin` script which `B` requires in its `prepare`/`build` script.

When I try to install within `monorepo-2` by itself, it fails because the `bin` scripts from `C` are apparently not properly installed. Workarounds are easy, however, and I'm able to get `monorepo-2` installing correctly with some convincing.

But when installing `monorepo-1`, it git clones `monorepo-2` to some temp dir, fails the install because of missing `bin` scripts, and then cleans up the git clone directory. So there's no chance of a workaround here.

**Comment by carecki** [comment] 2024-02-23 22:08
What I've done was instead `npm install` or `npm update` I've used more dedicated command for it - `npm rebuild`. And put it in the `postinstall` script after building my package containing binary (named code-gen). So whole `postinstall` looks like this:
```
"postinstall": "npm run build -w packages/code-gen && npm rebuild --ignore-scripts @my-product/code-gen"
```
This way, straight after installing modules, my `code-gen` package is:

1. compiled from typescript and builds its binary,
2. and then `npm rebuild` step correctly sees that there is a binary this time in it and adds missing symlink to it in the `node_modules/.bin`. I've added `--ignore-scripts` to avoid running scrips unrelated to binary registration.

This way after whole `npm install` the binary from `@my-product/code-gen` package is ready to be used by other packages in the workspaces.

**Comment by milaninfy** [comment] 2024-07-12 20:27
@jlarmstrongiv can you try replicating this problem on the latest version of `npm`? (ie. `npm i -g npm`) . Looks like this issue is fixed. 

```sh 
~/workarea/rep $ npm ls
rep@1.0.0 /Users/milaninfy/workarea/rep
├─┬ w1@1.0.0 -> ./w1
│ └── w2@1.0.0 deduped -> ./w2
└── w2@1.0.0 -> ./w2

# my setup for workspaces 
~/workarea/rep $ npm pkg get workspaces
[
  "w1",
  "w2"
]

# w2 has bin specified
~/workarea/rep $ npm pkg get bin -w w2
{
  "w2": "index.js"
}

# w1 has script using w2 bin
~/workarea/rep $ npm pkg get scripts -w w1
{
  "w1": {
    "test": "npx w2"
  }
}

# running script in w1 
~/workarea/rep/w1 $ npm run test

> w1@1.0.0 test
> npx w2

Hello, world!

# running script in root with workspace flag
~/workarea/rep $ npm run test -w w1

> w1@1.0.0 test
> npx w2

Hello, world!
```

**Comment by milaninfy** [comment] 2024-07-19 17:11
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.

**Closed as completed by milaninfy** 2024-07-19 17:11 UTC
Labels: Release 8.x, Bug, Needs Triage
