### ISSUE TITLE
[BUG] npm cli doesn't allow login with username that contains capitol letters.

### ISSUE THREAD

**Issue by stoneRdev** [npm/cli#1225] opened 2020-04-30 18:55 UTC
I am unable to login to my github packages, because apparently NPM has a personal issue with capitol letters. 

Here's a copy paste of my terminal:
[werlious@boulder-a420]$ npm login --registry=https://npm.pkg.github.com
Username: stoneRdev
npm WARN Name must be lowercase 
Username: (stoneRdev) 
npm WARN Name must be lowercase 
Username: (stoneRdev) npmnpm ERR! canceled
                                              ^ ctrl+c here   

It should not matter that my username has capitols, nor that its working on a separate registry. 
NPM can enforce PACKAGE names all it wants, it's a PACKAGE manager after all. But, NPM has no business telling me what my username can and can't be as its not a login manager.

So please, fix this obvious bug

**Comment by stoneRdev** [comment] 2020-04-30 19:02
Added info: 
  I can log into the regular cli fine, as my npm username is werlious, so no capitols, but I'm sure if it did, I would be excluded from publishing packages based on name alone from this. and who knows how many others have had this issue.

**Comment by ettud** [comment] 2020-07-06 06:18
I guess, since npmjs.com doesn't allow upper cases in usernames, the same logic is used in the client. However, some private npm registries (e. g. Proget) allow such usernames. In order not to break existing begavior, maybe new flag should be introduced? For example:
`npm login --registry=https://npm.pkg.github.com --allow-capital-letters`
It would be a very small change that doesn't break anything.

**Comment by stoneRdev** [comment] 2020-09-03 09:20
@ettud I agree, and fully support that. Maybe I'll do a pull for it

**Comment by darcyclarke** [comment] 2021-06-02 22:10
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is reproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 22:10 UTC
Labels: Bug
