### ISSUE TITLE
[BUG] Infinite loop running script with --workspaces option

### ISSUE THREAD

**Issue by mdesousa** [npm/cli#4713] opened 2022-04-08 20:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

We have a workspace configured 2 levels deep as follows:
```
.
+-- package.json
   +-- a
   |   `-- package.json
   `-- b
       `-- package.json
       +-- b1
       |   `-- package.json
       `-- b2
           `-- package.json
```
The root package.json has a script `npm run build --workspaces` to build all workspaces.
The package.json under `b` also has a script `npm run build --workspaces` to build b1 and b2.
When we run the root script, npm goes into a infinite loop of running the scripts.

### Expected Behavior

npm should not hang. it should run the scripts as expected: a, b1, b2

### Steps To Reproduce

Create a configuration with a workspace hierarchy that has multiple levels.
For parent workspaces, define a script runs the children scripts with the --workspace option.

### Environment

- npm: 8.6.0
- Node.js: v14.18.1
- OS Name: MacOS
- System Model Name: Macbook Pro

**Comment by lukekarrys** [comment] 2022-04-10 07:32
Closing as a duplicate of #4518.

**Closed as completed by lukekarrys** 2022-04-10 07:32 UTC
Labels: Release 8.x, Bug, Needs Triage
