### ISSUE TITLE
[BUG] npm install rises correctly a Conflicting peer dependency error but the reported module version is wrong

### ISSUE THREAD

**Issue by dacsystemsw** [npm/cli#5133] opened 2022-07-07 14:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When I run `npm install` I get the following error

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: angular-resize-event@2.0.1
npm ERR! Found: @angular/common@11.1.2
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"11.1.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^10.0.14" from angular-resize-event@2.0.1
npm ERR! node_modules/angular-resize-event
npm ERR!   angular-resize-event@"^2.0.1" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @angular/common@10.2.5
npm ERR! node_modules/@angular/common
npm ERR!   peer @angular/common@"^10.0.14" from angular-resize-event@2.0.1
npm ERR!   node_modules/angular-resize-event
npm ERR!     angular-resize-event@"^2.0.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/luca/.npm/eresolve-report.txt for a full report.
```

The dependecies in the root module are the following

``` 
"dependencies": {
    "@angular/common": "11.1.2",
    "angular-resize-event": "^2.0.1"
  }
```
While the peer deps of  `"angular-resize-event":@"^2.0.1"`

```
"peerDependencies": {
    "@angular/common": "^10.0.14",
    "@angular/core": "^10.0.14"
  },
```

### Expected Behavior

The peer dependency conflict should occur between the root module dependency `@angular/common": "11.1.2` and `@angular/common": "^10.0.14` peer dep from `angular-resize-event":@"^2.0.1` while in the error it's mentioned 
`npm ERR! Conflicting peer dependency: @angular/common@10.2.5
`
So, I would expect something like this:
```
[...]

npm ERR! Conflicting peer dependency: @angular/common@10.0.14
npm ERR! node_modules/@angular/common
npm ERR!   peer @angular/common@"^10.0.14" from angular-resize-event@2.0.1
npm ERR!   node_modules/angular-resize-event
npm ERR!     angular-resize-event@"^2.0.1" from the root project


```

I've never installed `angular/common@10.2.5` neither it's referenced in any way in the project.

I also tried to use these per deps, but I got the same outcome:
```
"peerDependencies": {
    "@angular/common": "10.0.14",
    "@angular/core": "^10.0.14"
  },
```

### Steps To Reproduce

1. create a folder, cd into it
2. `npm init -y`
3. `npm install @angular/common@11.1.2 -E `
4. `npm install --legacy-peer-deps angular-resize-event@2.0.1` (`--legacy-peer-deps` needed otherwise the installation fails correctly. Yes, i'm using npm version ~~8.13.1~~ 8.13.2)
5. `npm install`
6. ERROR

### Environment

- npm: 8.13.2
- Node.js: 16.3.0
- OS Name: Fedora Linux 36

**Comment by ljharb** [comment] 2022-07-07 14:56
The strong implication here is that you have something in your graph that depends on angular 11, and something else that depends on angular 10. These things are incompatible, so you have to downgrade everything to things that work with v10, or upgrade everything to work with v11, and drop whatever remains incompatible.

**Comment by nlf** [comment] 2022-07-13 21:32
exactly what @ljharb said, although it looks like your upgrade path may be a bit simpler than it appears at a glance.

first, to explain what's going on. as you mentioned, the package `angular-resize-event@2.0.1` has a peer dependency on `@angular/common@^10.0.14`. you're seeing `@angular/common@10.2.5` being mentioned in the logs because the original requirement of `^10.0.14` is a range. the newest version that matches that range is `10.2.5` so that's what npm tries to install, and where the error comes from.

now, as for fixing it, it looks like updating `angular-resize-event` to `2.1.0` (which is actually the newest version that matches your requirement range of `^2.0.1`, so if you were to delete your `node_modules` and `package-lock.json` that's what you would get) changes its peer dependency on `@angular/common` to the range `^11.2.2`. if you can then update your root dependency to the same version, you shouldn't have any more conflicts.

since everything else here is working as intended (despite not being super readable), i'm going to go ahead and close this issue. you're welcome to reopen it if you continue to have problems.

**Closed as completed by nlf** 2022-07-13 21:32 UTC
Labels: Release 8.x, Bug, Needs Triage
