### ISSUE TITLE
[BUG] TAR_BAD_ARCHIVE : Unrecognized archive format

### ISSUE THREAD

**Issue by VishalMishraTss** [npm/cli#7988] opened 2024-12-17 06:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

while running RUN npm install pm2 -g   in docker creation of my node app
I am getting:
npm error code TAR_BAD_ARCHIVE
npm error TAR_BAD_ARCHIVE: Unrecognized archive format

Dockerfile: 
FROM node:18-slim
 
WORKDIR /usr/src/app
 
COPY package*.json ./
 
RUN npm i --only=production
 
COPY . .
 
RUN npm install pm2 -g
# tried below also still same
# RUN npm cache clean --force && npm install pm2 -g 

 
EXPOSE 1337
 
CMD ["pm2-runtime", "dist/server.js"]

### Expected Behavior

It should install pm2 properly in the docker container

### Steps To Reproduce

1. Docker base image tested on: node:18-slim, node:18,node:16,node:16-slim,node:alpine,node:latest,node:18-slim,node:18,node:22,node:20

2.Manually test the PM2 installation:
Run a temporary container for debugging:
docker run -it --rm node:18-slim bash
Inside the container, run:
npm cache clean --force && npm install -g pm2

error encountered: 
npm error code TAR_BAD_ARCHIVE
npm error TAR_BAD_ARCHIVE: Unrecognized archive format

### Environment

- npm: 11.0.0
- Node.js: v22.12.0
- OS Name: Microsoft Windows [Version 10.0.22621.2861]

**Comment by atharva-unde** [comment] 2024-12-17 07:32
Duplicate of https://github.com/npm/cli/issues/7986

**Comment by BRAVO68WEB** [comment] 2024-12-17 12:40
Same, its again an India specific error. Ahh

**Comment by BRAVO68WEB** [comment] 2024-12-17 12:40
Our AWS server in Mumbai are failing.
But, Singapore ones are up!

**Comment by Ganesh1991** [comment] 2024-12-17 13:07
Facing same issue
 
70.30 npm error code TAR_BAD_ARCHIVE
70.30 npm error TAR_BAD_ARCHIVE: Unrecognized archive format
70.30 npm error A complete log of this run can be found in: /root/.npm/_logs/2024-12-17T13_05_42_763Z-debug-0.log

**Comment by Ganesh1991** [comment] 2024-12-17 13:10
Issue with NPM site. you can track status from here https://status.npmjs.org/

**Comment by milaninfy** [comment] 2024-12-17 13:28
Closing as duplicate of https://github.com/npm/cli/issues/7986.

**Closed as not planned by milaninfy** 2024-12-17 13:28 UTC
Labels: Registry, Bug, Duplicate
