### ISSUE TITLE
[BUG] the readability of the notice about upgrading NPM is very poor on a white background

### ISSUE THREAD

**Issue by jcollum** [npm/cli#3585] opened 2021-07-27 17:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I was told to report this as a bug https://github.com/npm/feedback/discussions/504 

![2021-07-23_11-49-09](https://user-images.githubusercontent.com/704514/126828115-3427ede6-2a5a-4b69-80d0-ef2593fa7366.png)

YSK that black backgrounds are harder to read for people with astigmatism

> Dark mode can also affect people who have astigmatism, a common condition where vision becomes blurred because of the curvature of the eye. A study published in Ergonomics in 2013 found that for people with standard vision in the daytime, white text on a black background is often better for proofreading and clear vision. **A person with astigmatism in one or both eyes, though, might experience problems reading in dark mode.** People with astigmatism may find that white letters begin to bleed into the black background during dark mode, making them harder to read. It's a phenomenon known as halation. If you can't really focus when your phone's on dark mode, you may need to get an eye test.

 https://www.bustle.com/p/what-happens-to-your-body-when-you-use-dark-mode-on-your-phone-according-to-experts-23619973 

### Expected Behavior

The text is readable on a white background. 

### Steps To Reproduce

1. have a terminal with a white background
2. have an npm version that is slightly out of date

### Environment

Node v14.16.0
NPM 7.18.1
OS:
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H15

**Comment by wraithgar** [comment] 2021-07-27 18:55
Duplicate of https://github.com/npm/cli/issues/3091

**Closed as completed by wraithgar** 2021-07-27 18:55 UTC
Labels: Release 7.x, Bug, Needs Triage
