### ISSUE TITLE
[NPM does not installing anything ] <title>

### ISSUE THREAD

**Issue by DrackoDrain** [npm/cli#7617] opened 2024-06-27 17:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

![Screenshot 2024-06-27 224951](https://github.com/npm/cli/assets/93030539/36fed6de-c375-4c1b-80e5-e31649344e76)
![Screenshot 2024-06-27 225256](https://github.com/npm/cli/assets/93030539/0537c5f3-9dd2-4ed1-8ee8-0b8cb24ed789)

### Expected Behavior

I installed latest version of node.js and it is not installing anything for example mongoose, react, express.js etc... ****

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by milaninfy** [comment] 2024-06-27 19:03
@DrackoDrain 
Please provide all the information mentioned in issues template like steps to reproduce, logs, configs etc. 
Also It would be useful if you can please provide output of your install command with logs like `npm install -D parcel -ddd` ?

**Comment by milaninfy** [comment] 2024-07-04 14:37
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.

**Closed as not planned by milaninfy** 2024-07-04 14:37 UTC
Labels: Bug, Needs Triage
