### ISSUE TITLE
NPM can not install updates

### ISSUE THREAD

**Issue by Fcscanf** [npm/cli#2697] opened 2021-02-14 05:18 UTC
### Steps To Reproduce:

NPM can not install updates
![image](https://user-images.githubusercontent.com/27654200/107869231-ce615f80-6ec6-11eb-968e-e5e07d82f1a1.png)

### Environment:

OS：Window10
Node：v14.15.4

**Comment by nlf** [comment] 2021-02-16 19:26
this issue is resolved in npm@7.5.4, unfortunately as you've noticed it can be difficult to get back to a working npm that allows you to install the updated version. a couple of approaches are:

1) if you have bash available, `curl -q https://www.npmjs.com/install.sh | sh`
2) if you do not have bash available, you'll need to uninstall nodejs and reinstall. this should get you an older, working, version of npm. from there you can update to 7.5.4 with `npm i -g npm`

closing as a duplicate of #2663

**Closed as completed by nlf** 2021-02-16 19:26 UTC
Labels: Release 7.x, Bug, Needs Triage
