### ISSUE TITLE
[BUG] "npm link ../my-package --only=prod" deletes my-package

### ISSUE THREAD

**Issue by charbugs** [npm/cli#3155] opened 2021-04-27 09:42 UTC
### Current Behavior:
The command `npm link ../my-package --only=prod` deletes `my-package` if it's listed in `devDependencies`

### Expected Behavior:
It should not delete my-package.

### Steps To Reproduce:
```
$ mkdir my-package
$ cd my-package
$ npm init -y
$ cd ..
$ mkdir my-app
$ cd my-app
$ npm init -y

$ vi package.json
```

Manually add my-package to devDependencies:

```
{
  "name": "my-app",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "my-package": "latest"
  }
}
```

In ./my-app

```
$ ls ..
my-app my-package
$ npm link ../my-package --only=prod
$ ls ..
my-app
```

my-package has been deleted :astonished:

### Environment:
- OS: Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux
- Node: 14.6.1
- npm: 7.11.1

**Comment by wraithgar** [comment] 2021-05-06 23:09
Looks like this was related to https://github.com/npm/cli/issues/2889, which was fixed in `v7.12.0`

Can reproduce this w/ an npm earlier than that, and confirm that the directory isn't deleted w/ `v7.12.0`

**Closed as completed by wraithgar** 2021-05-06 23:09 UTC
Labels: Release 7.x, Bug, Priority 1
