### ISSUE TITLE
[QUESTION] <cb() never called while installing Gulp-sass packages>

### ISSUE THREAD

**Issue by priuet** [npm/cli#743] opened 2020-01-30 05:27 UTC
Hello! Can you please help me with the following problem: I cannot install SASS packages for my project. I created a folder for my sass project. There’s a package son file inside. Now I need to download node modules for it: gulp-sourcemap, autoprefixer, gulp-if, gulp-concat, gulp-clean-css and browser-sync. 
I’m doing everything with MacOS Terminal. 
I type in $ npm install --save-dev gulp-sass. 
The reply I get is the following:
MacBook-Pro-Anastasia:SASS anastasia$ npm install --save-dev gulp-sass
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/anastasia/.npm/_logs/2020-01-30T05_00_30_646Z-debug.log

It repeats with all the packages which I’m trying to install. 
I’ve tried to update Gulp itself. Then But I failed and got the same reply "cb() never called!"
gulp -v
CLI version: 2.2.0
Local version: Unknown

Please can you help me? How can I fix this problem?

My node and npm version details are--
node -- **13.3.0**
npm -- **6.13.1**

System Information --
Operating System: MacOS High Sierra 10.13.6

**Comment by DanielRuf** [comment] 2020-02-18 06:40
Duplicate of https://github.com/npm/cli/issues/417

**Comment by darcyclarke** [comment] 2021-06-02 21:55
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 21:55 UTC
Labels: Awaiting Information
