### ISSUE TITLE
[BUG] Lost support submodules

### ISSUE THREAD

**Issue by trofim24** [npm/cli#2774] opened 2021-02-25 07:41 UTC
### Current Behavior:
npm version 7 (I tried both 7.0.0 and the last 7.5.6) does not download submodules.

### Expected Behavior:
npm version 6.14.11 has [support submodules](https://github.com/npm/cli/blob/e09bdc142a4d9fe247927eb82a49720d5370b293/changelogs/CHANGELOG-3.md#new-feature-git-submodule-support).

### Steps To Reproduce:
I created 3 repos to reproduce the problem. [The first](https://github.com/trofim24/npm) contains package.json with dependencies to install. [The second](https://github.com/trofim24/npm-bug) contains submodule. [The third](https://github.com/trofim24/npm-bug-submodule) contains only Readme.md
1. `git clone https://github.com/trofim24/npm.git`
2. `npm install`
If you do this on version 6.14.11 then the `node_modules/npm-bug/npm-bug-submodule` folder will exist.
If you do this on version 7.5.6 then the `node_modules/npm-bug/npm-bug-submodule` folder will not exist.

### Environment:
- OS: Windows 10 2004 or Debian GNU/Linux 9.13
- npm: 6.14.11 and npm: 7.5.6

**Comment by trofim24** [comment] 2021-03-17 08:33
Any updates?

**Comment by zpv** [comment] 2021-03-26 22:00
Also experiencing this issue and breaks my workflow. I reverted back to 6 in the meantime.
Related (old) issue: https://github.com/npm/npm/issues/6700

**Comment by trofim24** [comment] 2023-02-13 07:47
Any updates?

**Comment by domq** [comment] 2023-02-28 21:56
Curiously enough, using the latest version of npm, (e.g.) `npm i -g https://github.com/Level/rocksdb` does what we want i.e. pull the [`deps/rocksdb/rocksdb` submodule](https://github.com/Level/rocksdb/tree/master/deps/rocksdb) out of Facebook. But not when `"github.com/Level/rocksdb"` is in a `package.json` as a dependency.

**Comment by ljharb** [comment] 2023-02-28 22:10
@domq presumably `npm install https://github.com/Level/rocksdb` would match package.json (global installs are different than local ones)

**Comment by domq** [comment] 2023-02-28 22:13
@ljharb I'm not sure what you mean with “match `package.json`”, in my experiments it's the git behavior (i.e. whether the clone is recursive or not), that differs between the two situations.

**Comment by ljharb** [comment] 2023-02-28 22:18
@domq sorry, what i mean is, you said `npm install -g` does what you want, but `npm install` (when it's in package.json) does not. I was asking about what `npm install https://github.com/Level/rocksdb` does, which is a third, potentially different thing.

**Comment by domq** [comment] 2023-02-28 22:37
@ljharb oh, I get it now, sorry. The behavior of `npm install https://github.com/Level/rocksdb` is indeed the same as when the dependency is in a `package.json` as you guessed, i.e. a nonrecursive clone is used for the build.

**Comment by cjbj** [comment] 2023-05-25 03:40
Still not fixed in npm 9.6.7

**Comment by DeeDeeG** [comment] 2023-10-24 16:39
**This is both a bug and a documentation issue.** I can confirm this bug (the loss of submodule/recursive cloning in dependencies) is still true in npm 10.

The documentation claims submodules will be cloned, but submodules are actually not cloned anymore. 

> If the repository makes use of submodules, those submodules will be cloned as well.

\- From: https://docs.npmjs.com/cli/v10/commands/npm-install


**Test Results:**
- Submodules _are_ cloned (as in, it works as described in the `npm install` documentation) if you use npm 6 (npm v6.14.18). ✅ 
- Submodule cloning doesn't happen for (as in, docs are inaccurate for) npm 7 (v7.24.2), npm 8 (v8.19.4), npm 9 (v9.9.0), and npm latest/10 (v10.2.1). ❌

**Implications of the bug:**
This loss of submodule/recursive cloning breaks some packages when used as git dependencies. For example, Atom's `superstring` library doesn't build properly on Windows with npm 7.x or newer, as a git dependency, due to a missing vendored `win-iconv` build-time dependency, which is vendored in as a submodule under the `superstring` repo. This was working as of npm 6.

**What to do about it?:**
**I'd love for submodule/recursive cloning for git dependencies to come back in npm latest. It would un-break some dependencies we still rely on.** But if this support is not coming back any time soon, I feel like the docs should be updated in the mean-time to not claim submodules will be cloned when they actually won't. Thanks for considering.

**Comment by ljharb** [comment] 2024-01-18 20:00
fwiw, I suddenly have this need as well on two different repos - i'm using a submodule to pull in test fixtures, and having `npm install` ensure the submodules are available would be very helpful.

**Comment by reggi** [comment] 2024-09-16 16:25
I added to the docs that this is just a limitation of using git packages directly here in this https://github.com/npm/documentation/pull/1279 available here https://docs.npmjs.com/about-packages-and-modules

**Closed as completed by reggi** 2024-09-16 16:25 UTC
Labels: Release 7.x, Release 8.x, Bug, Priority 1, Release 9.x, Release 10.x

**Comment by ljharb** [comment] 2024-09-16 21:09
@reggi is there no plan to add this support? (even by some kind of dev-only postinstall hook)

**Comment by reggi** [comment] 2024-09-17 14:39
@ljharb there is no plan to add this support. If someone in userland wants to make a postinstall hook that's perfectly fine! 😸

**Comment by ljharb** [comment] 2024-09-17 15:25
How would I do such a thing in userland, such that it won't affect my package's consumers?

**Comment by reggi** [comment] 2024-09-17 17:52
idk @ljharb nevermind, idk what you meant by dev-only postinstall hook

**Comment by ljharb** [comment] 2024-09-17 18:00
@reggi i mean that i'd need a hook that runs when i run `npm install` in a `foo` project, but doesn't run when someone does `npm install foo`. I'm not aware of any such hook, which means this can't be done in userland, but I could be wrong.

**Comment by reggi** [comment] 2024-09-17 18:25
@ljharb gotcha thanks for the clarification I'm not aware of such a hook either.

**Comment by ljharb** [comment] 2024-09-17 18:28
then can this be reopened, since the use case isn't currently achievable?

**Comment by threema-danilo** [comment] 2024-10-21 09:49
@reggi the documentation at https://docs.npmjs.com/cli/v10/commands/npm-install still claims that submodules are cloned:

![screenshot-20241021-114613](https://github.com/user-attachments/assets/46b6e2f7-893c-4a8d-9325-647f5a513a60)

Unfortunately the missing support for submodules makes it impossible to install certain libraries through git, for example [node-argon2](https://github.com/ranisalt/node-argon2) which includes the argon2 library from upstream as a submodule.

Please reconsider adding support for submodules. If you decide against it, please update the documentation to remove any claims of such support.

**Comment by tux2nicolae** [comment] 2024-11-10 20:12
Please reconsider, I'm having the same problem
