### ISSUE TITLE
error cb() never called!

### ISSUE THREAD

**Issue by sandeepkallat** [npm/cli#988] opened 2020-03-06 15:04 UTC
# What / Why
I get  error cb() never called! error when trying to install typescript of angular
> n/a

## When
npm install -g typescript

## Where
Windows cmd

### Current Behavior
npm install -g @angular/cli
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:

### Steps to Reproduce
run npm install -g @angular/cli

### Expected Behavior
should install angular/typescript

## Who
[2020-03-06T14_50_38_986Z-debug.log](https://github.com/npm/cli/files/4298928/2020-03-06T14_50_38_986Z-debug.log)
[2020-03-06T14_53_22_051Z-debug.log](https://github.com/npm/cli/files/4298929/2020-03-06T14_53_22_051Z-debug.log)

* n/a

## References

* n/a

**Comment by carlripleylocke** [comment] 2020-03-06 23:05
I get the same error with `npm install -g npm`: 

```
>>> $ npm install -g npm
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2020-03-06T22_57_03_969Z-debug.log
>>> $ cat /home/user/.npm/_logs/2020-03-06T22_57_03_969Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', '-g', 'npm' ]
2 info using npm@6.11.3
3 info using node@v10.1.0
4 verbose npm-session f758b5b91bc948a8
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/npm 367ms
8 timing npm Completed in 1894ms
9 error cb() never called!
10 error This is an error with npm itself. Please report this error at:
11 error <https://npm.community>
>>>(master) $
```

**Comment by DanielRuf** [comment] 2020-03-09 08:57
Duplicate of #417

**Closed as completed** 2021-03-26 04:32 UTC
