### ISSUE TITLE
[BUG] ENOENT: no such file or directory

### ISSUE THREAD

**Issue by kubilaysargin** [npm/cli#964] opened 2020-02-29 13:21 UTC
I have a problem while installing react-native-cli. When i type npm install -g react-native-cli it gives me so much no such file or directory errors.  One example is  ENOENT: no such file or directory, open 'C:\Users\KUBİLAY\AppData\Roaming\npm\node_modules\.staging\winston-6bc268e1\test\transports\webhook-test.js'. When look this winston-6bc268e1 folder's inside, first name of folders are deleted(like est for test, ib for lib).
![cmdererror](https://user-images.githubusercontent.com/61623674/75608299-611aba00-5b0f-11ea-947b-d43a957bfded.png)
![fileerror](https://user-images.githubusercontent.com/61623674/75608306-77c11100-5b0f-11ea-9d2f-93f0206a1b05.png)

**Comment by rushilsrivastava** [comment] 2020-03-07 06:32
Facing this on the latest version as well.

**Comment by DanielRuf** [comment] 2020-03-09 08:56
This is probably an issue with your username (special characters and spaces).

Duplicate of #417

**Comment by rushilsrivastava** [comment] 2020-03-09 09:03
It's an issue with `package-lock.json`. Deleting it and clearing npm cache will fix the issue.

**Comment by DanielRuf** [comment] 2020-03-09 09:26
> It's an issue with `package-lock.json`. Deleting it and clearing npm cache will fix the issue.

Not in all cases. This can help as it refetches packages and updates the dependencies so a fresh cache is used.

You can also use `npm i --force`.

**Comment by rushilsrivastava** [comment] 2020-03-09 09:33
> You can also use npm i --force .

I can confirm that `npm i --force` does not work in this situation. The only work around seems to be deleting the package lock.

**Comment by olavfosse** [comment] 2021-04-29 11:56
bump. can you please fix this, it has persisted for soon 4 years and been reported numerous times. It has surely affected a lot of people through the years.

https://github.com/zkat/npx/search?o=asc&q=space+windows&s=created&type=issues
https://github.com/npm/npx/search?q=space+windows&type=issues
https://github.com/npm/cli/search?q=space+windows&type=issues

Thanks

**Comment by darcyclarke** [comment] 2021-06-02 21:55
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Comment by olavfosse** [comment] 2021-06-02 22:07
This bug has been discarded maybe 100 times now. Please re-open.

**Comment by olavfosse** [comment] 2021-06-21 09:07
@isaacs @iarna @zkat

Please reopen this.

**Comment by ljharb** [comment] 2021-06-21 17:27
@fossegrim does it still occur on npm 7?

**Comment by olavfosse** [comment] 2021-06-21 17:47
yes

**Comment by darcyclarke** [comment] 2021-06-25 19:43
@ljharb we're closing this as the codebase changed significantly between 6-7 - @fossegrim can you please create a new issue w/ more information about the specific problem you're seeing in v7

**Closed as completed by darcyclarke** 2021-06-25 19:43 UTC
Labels: Release 7.x, Bug, Needs Triage

**Comment by ljharb** [comment] 2021-06-25 19:45
@darcyclarke i'm not sure why the codebase changes would have any bearing on the reported problem, which the OP claims still occurs in npm 7.

**Comment by olavfosse** [comment] 2021-06-25 19:55
Steps to reproduce from what I remember is:
1. Create user with username containing space, for example "Olav Fosse". (by default the installer infers username from email. To make the installer prompt for a username string you have to tell it that you cannot connect to internet).
2. Install npm
3. Try doing something with npm. I think I tried running cra `npx create-react-app appname` or something like that. Everything I ran failed.

**Comment by olavfosse** [comment] 2021-06-25 20:02
I cannot be bothered to install Win10 and make a proper detailed bug report, because every time this has been reported previously the issue has been closed prematurely.
