### ISSUE TITLE
Online install script currently broken

### ISSUE THREAD

**Issue by mjramtech** [npm/cli#6589] opened 2023-06-22 10:27 UTC
curl -qL https://www.npmjs.com/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   281    0   281    0     0     47      0 --:--:--  0:00:05 --:--:--    66
sh: 2: Syntax error: newline unexpected

No variations I tried, e.g. specifying versions, resulted in a valid script download.

**Comment by Magnetize** [comment] 2023-06-22 12:35
Having the same issue.

**Comment by kangadrewie** [comment] 2023-06-22 12:58
Seems to be throwing a 404

```
curl -I -X GET -L https://npmjs.org/install.sh                                                                                                                                                                            Thu 22 Jun 2023 12:56:40 UTC
HTTP/2 301
date: Thu, 22 Jun 2023 12:56:45 GMT
location: https://www.npmjs.com/install.sh
cache-control: max-age=3600
expires: Thu, 22 Jun 2023 13:56:45 GMT
server: cloudflare
cf-ray: 7db4a7355bac957f-DUB

HTTP/2 404
date: Thu, 22 Jun 2023 12:56:46 GMT
content-type: application/xml
cf-ray: 7db4a7358e8760e6-DUB
cf-cache-status: EXPIRED
cache-control: public, max-age=14400
vary: Accept-Encoding
set-cookie: __cf_bm=L6bCdTMvEBuvuOzEkX9W8ZU_TJPW5HQ5r_X5jVbcbyo-1687438606-0-AS6kXjzezgl8Ek3G9qbSlDldccUhJoLWY9EfQaLBGrf40tbEAYcTEkJgoPrfMd9b1kWx0L/tZxP1k1o9Olml1zE=; path=/; expires=Thu, 22-Jun-23 13:26:46 GMT; domain=.npmjs.com; HttpOnly; Secure; SameSite=None
server: cloudflare

**Comment by kivinm** [comment] 2023-06-23 10:55
For us it became unavailable around 9 PM GMT June 21.
Our AWS build pipeline totally depends on presence of this script, so we can't build our frontend for more than 36 hours at the moment of writing.
We downloaded a copy of this script using Wayback Machine and uploaded to our own public S3 bucket, but it doesn't work either (error is different - "failed to download script" and this is an unrelated issue).

Looks like some permissions for this file were removed - because if I try to load any similar URL like https://www.npmjs.com/install.sh2 - it will redirect to https://www.npmjs.com/package/install.sh2 and show NPM's 404 page.

UPDATE 1:
I just looked inside downloaded "install.sh" script and noticed that this error "failed to download script" is actually produced by the code inside the script:
...
curl -f -L -s https://www.npmjs.org/install.sh > npm-install-$$.sh
  ret=$?
  if [ $ret -eq 0 ]; then
    (exit 0)
  else
    rm npm-install-$$.sh
    echo "failed to download script" >&2
    exit $ret 
...

So essentially in our case script is downloaded from S3 bucket but then it runs and tries to download itself from npmjs.com again!

UPDATE 2:
I changed URL inside "install.sh" script (uploaded to our S3 bucket) so that it points to itself at our S3 bucket and not at https://www.npmjs.com/install.sh. And it worked!

**Comment by kzg001** [comment] 2023-06-26 10:03
The problem is still not solved

**Comment by kelvinwendel** [comment] 2023-06-26 21:52
I've tried using -O parameter for save in local file instead stdout and apparently works

curl -qL -O https://www.npmjs.com/install.sh | sh

![image](https://github.com/npm/cli/assets/53923665/bfd38bbc-784d-47ec-a607-bba01e45101c)

**Comment by roibWix** [comment] 2023-06-27 09:22
Any ETA for resolving the issue?

**Comment by japboy** [comment] 2023-06-27 09:55
Our team uses a workaround for now, by referring `install.sh` from [@npm/npm-install-script](https://github.com/npm/npm-install-script/) repository;

```sh
# In place of: curl https://www.npmjs.com/install.sh | sudo bash
curl https://raw.githubusercontent.com/npm/npm-install-script/main/install.sh | sudo bash
```

**Comment by Magnetize** [comment] 2023-06-27 14:47
I was actually able to solve this by using this part of the downloaded script (with some adjustments for variables and NPM version).
```
echo "fetching: $url" >&2

cd "$TMP" \
  && curl -SsL -o npm.tgz "$url" \
  && $tar -xzf npm.tgz \
  && cd "$TMP"/package \
  && echo "removing existing npm" \
  && "$node" bin/npm-cli.js rm npm -gf --loglevel=silent \
  && echo "installing npm@$t" \
  && "$node" bin/npm-cli.js install -gf ../npm.tgz \
  && cd "$BACK" \
  && rm -rf "$TMP" \
  && echo "successfully installed npm@$t"
```

**Comment by dogeow** [comment] 2023-06-29 03:33
Why not put this solution in README?

**Comment by dzikoysk** [comment] 2023-07-01 17:56
It also breaks Docker images that installs npm through build script. It's kinda strange that this issue didn't receive any official response while it's still listed in the readme as the official way to do it.

**Comment by lukekarrys** [comment] 2024-05-10 03:08
There was a misconfiguration that resulted in this script no longer being accessible. This has since been fixed and the instructions in the readme now work again.

**Closed as completed by lukekarrys** 2024-05-10 03:08 UTC
