### ISSUE TITLE
[FEATURE] docs

### ISSUE THREAD

**Issue by stexandev** [npm/cli#759] opened 2020-02-03 11:46 UTC
# What / Why

Update/resolve duplicate in documentation about packaging: 

- https://docs.npmjs.com/using-npm/developers.html#the-packagejson-file

- https://docs.npmjs.com/files/package.json#files

Information in these parts diverge

## When

* n/a

## Where

* n/a

### Current Behavior

* n/a

### Expected Behavior

* n/a

## Who

* n/a

## References

* n/a

**Comment by DanielRuf** [comment] 2020-02-20 21:30
Oh and there is still https://npm.community/c/support/docs-needed linked at the bottom.

**Comment by DanielRuf** [comment] 2020-02-20 21:32
>     * https://docs.npmjs.com/files/package.json#files

I don't think this is duplicate because https://docs.npmjs.com/files is an overview of files and these are two different contexts.

**Comment by DanielRuf** [comment] 2020-02-20 21:34
I think these are two different ones because the /files link is for https://docs.npmjs.com/cli-documentation/files

**Comment by DanielRuf** [comment] 2020-02-20 21:39
> https://docs.npmjs.com/using-npm/developers.html#the-packagejson-file
https://github.com/npm/cli/blob/latest/docs/content/using-npm/developers.md

> https://docs.npmjs.com/files/package.json#files
https://github.com/npm/cli/blob/latest/docs/content/configuring-npm/package-json.md

**Comment by darcyclarke** [comment] 2021-06-02 21:55
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 21:55 UTC
Labels: Enhancement
