### ISSUE TITLE
[BUG] npm cache: should not cache if request timed out

### ISSUE THREAD

**Issue by bbarry** [npm/cli#1052] opened 2020-03-23 14:29 UTC
npm 6.14.3  
node 12.4.0  
windows 10  

Trying to clone and work on an existing application on a new machine and I am getting response timeouts for various packages from the npm registry.

```
> npm install
```

and the debug line contains varouls timeouts (different ones each time I use a different cache):

```
46 silly fetchPackageMetaData error for @angular/cli@~9.0.6 Response timeout while trying to fetch https://registry.npmjs.org/@angular%2fcli (over 30000ms)
54 silly fetchPackageMetaData error for @types/node@^13.9.1 Response timeout while trying to fetch https://registry.npmjs.org/@types%2fnode (over 30000ms)
55 silly fetchPackageMetaData error for @ngxs/devtools-plugin@^3.6.2 Response timeout while trying to fetch https://registry.npmjs.org/@ngxs%2fdevtools-plugin (over 30000ms)
75 silly fetchPackageMetaData error for prettier@^1.19.1 Response timeout while trying to fetch https://registry.npmjs.org/prettier (over 30000ms)
76 silly fetchPackageMetaData error for typescript@~3.8.3 Response timeout while trying to fetch https://registry.npmjs.org/typescript (over 30000ms)
83 silly fetchPackageMetaData error for @angular/common@~9.0.6 Response timeout while trying to fetch https://registry.npmjs.org/@angular%2fcommon (over 30000ms)
85 silly fetchPackageMetaData error for @angular/compiler@~9.0.6 Response timeout while trying to fetch https://registry.npmjs.org/@angular%2fcompiler (over 30000ms)
88 silly fetchPackageMetaData error for @angular/forms@~9.0.6 Response timeout while trying to fetch https://registry.npmjs.org/@angular%2fforms (over 30000ms)
94 silly fetchPackageMetaData error for @angular/platform-browser-dynamic@~9.0.6 Response timeout while trying to fetch https://registry.npmjs.org/@angular%2fplatform-browser-dynamic (over 30000ms)
100 silly fetchPackageMetaData error for @ngxs/logger-plugin@^3.6.2 Response timeout while trying to fetch https://registry.npmjs.org/@ngxs%2flogger-plugin (over 30000ms)
105 silly fetchPackageMetaData error for @ngxs/storage-plugin@^3.6.2 Response timeout while trying to fetch https://registry.npmjs.org/@ngxs%2fstorage-plugin (over 30000ms)
110 silly fetchPackageMetaData error for @ngxs/store@^3.6.2 Response timeout while trying to fetch https://registry.npmjs.org/@ngxs%2fstore (over 30000ms)
354 silly fetchPackageMetaData error for webpack@4.41.2 Response timeout while trying to fetch https://registry.npmjs.org/webpack (over 30000ms)
```

so I figure ok, all of these are fairly common packages and many people would be complaining if they were unavailable and I can load all of those urls in a browser just fine, try it again?

```
> npm install
```

this time (and every time after) I get these errors in my log for the above timeouts:

```
2808 http fetch GET 304 https://registry.npmjs.org/@angular%2fcompiler 441ms (from cache)
2809 silly fetchPackageMetaData error for @angular/compiler@~9.0.6 Unexpected end of JSON input while parsing near '...2RWhiGSZE/SJGhZxyaj4J'
2810 http fetch GET 304 https://registry.npmjs.org/@angular%2fcommon 454ms (from cache)
2811 silly fetchPackageMetaData error for @angular/common@~9.0.6 Unexpected end of JSON input while parsing near '...iI6UDb/cxTGIw2YQDpSe6'
```

`npm cache clean` says it is unnecessary as of npm@5;

`npm cache verify` says

```
> npm cache verify
Cache verified and compressed (~\AppData\Roaming\npm-cache\_cacache):
Content verified: 2433 (162806314 bytes)
Content garbage-collected: 65 (25929551 bytes)
Index entries: 3716
Finished in 36.168s
```

running install with a different cache gives different timeouts and then followup installs from those caches give unexpected end of json for those files...

**Comment by bbarry** [comment] 2020-03-23 19:50
also happens in node 12.16.1 (I updated to latest thinking that might help because of the patch note about http events not firing errors correctly)

I was able to work around my timeouts by writing a script that walked the dependency tree from the outermost edges in and generated a package.json in a new folder and ran `npm install` on each folder (my response times for registry.npmjs.org continued to grow as more packages were requested concurrently, so by doing them all individually I was able to get them all in cache to finish the install).

Still, it would be nice if I had an alternative to `npm cache clear --force` when one of these arrived in the cache.

**Comment by tkesgar** [comment] 2020-03-24 10:31
I encountered this issue as well, probably because my internet connection is not very good.

I downgrade to `v6.9.0` (previously installed npm in my computer) and somehow managed to `npm install` successfully.

Update: Encountering the issue again today. Upgrading `node` to latest `v13` solved the issue.

**Comment by bbarry** [comment] 2020-04-06 14:07
I am able to trigger consistently with `npm outdated`

first: 

```
> npm outdated --cache C:\temp\tempnpmcache
npm ERR! Response timeout while trying to fetch https://registry.npmjs.org/@angular-devkit%2fbuild-angular (over 30000ms)
```

every time after:

```
> npm outdated --cache C:\temp\tempnpmcache
npm ERR! Unexpected end of JSON input while parsing near '...r-devkit/core":"^0.7.'
```

**Comment by kamilchm** [comment] 2020-06-25 10:37
This makes `npm install` unusable on slow networks.
I need to make many cycles with `npm install` and `npm cache clean --force` until the `npm install` succeeds in one go. If it encounters a network error and write corrupted package to the cache, the cache as a whole is broken without any way to clean it only from the corrupted packages.
The workaround I use in projects using `npm`:
```
yarn import
yarn install
m package-lock.json
npx synp -s yarn.lock
```

**Comment by bbarry** [comment] 2020-06-25 13:54
I am able to work around this to a limited extent with [verdaccio](https://verdaccio.org/en/). Occasionally corrupted downloads still fail to install but so far none have happened in a way that they remain in the npm cache.

**Comment by kamilchm** [comment] 2020-06-25 14:19
I thought about `verdaccio` too. What stopped me are the package urls in `package-lock.json`. Isn't that something that will change the urls to the local verdaccio registry?

**Comment by bbarry** [comment] 2020-06-25 14:33
Yes it does change them. It seems they change when new versions get installed? I am unsure about exactly what impact it has other than it does let me have the same versions. In all cases thus far I have been able to revert the changes after as all it did was change a few urls and the package.lock file was already up to date with the necessary version details (my working copy not though).

It certainly is not a very good workaround but better than my previous one of dynamically generating a script of folders of package.json files from repeatedly failing `npm install` and downloading the package json for that failing package and producing a single dependency project for each of its dependencies. Then force cleaning and running npm install on each of the thousands of folders. Your idea of yarn seems to work alright as well but will possibly change the hashes to the old format wouldn't it?

**Comment by kamilchm** [comment] 2020-06-25 14:49
Oh, I forgot one final step, `npm install`:
```
yarn import
yarn install
m package-lock.json
npx synp -s yarn.lock
npm install
```

Everything works, and the `hashes` are `sha1` after that. I'm not sure if it's old or new. Projects I work with are using the same format. But this needs to be checked to be sure, though.

**Comment by darcyclarke** [comment] 2021-06-02 21:21
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 21:21 UTC
Labels: Release 6.x, Bug
