### ISSUE TITLE
[BUG] Npx executes wrong version of dependency present in several workspaces

### ISSUE THREAD

**Issue by bertrandE** [npm/cli#6276] opened 2023-03-21 08:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Suppose that you need a dependency (eg. `eslint`) in different versions in two workspaces (eg. `childA` and `childB`):

```
$ npm ls eslint
├─┬ childa@1.0.0 -> ./packages/childA
│ └── eslint@8.36.0
└─┬ childb@1.0.0 -> ./packages/childB
  └── eslint@7.32.0
```

* execute `npx -w packages/childA` and in the interactive subshell execute `eslint -v`. It returns `v8.36.0` as expected
* execute `npx -w packages/childB` and in the interactive subshell execute `eslint -v`. It returns `v7.32.0` as expected
* execute `npx -w packages/childB eslint -v`. It returns `v8.36.0` (expected `v7.32.0`)

Is this intended behaviour? Am I missing something when using `npx` in the context of workspaces?

### Expected Behavior

I expected `npx -w packages/childB eslint -v` to return the `eslint` version relative to the `childB` workspace (_ie._ `v7.32.0`).

### Steps To Reproduce

Using the following repo https://github.com/bertrandE/npm-repro-bin-child-workspace
Execute the commands specified in "Current Behavior".

Somewhat related issue: #2826

### Environment

Tested on both NPM 8 and NPM 9.

**Comment by tnorling** [comment] 2023-06-20 17:12
I am also experiencing this, but only on Windows. It appears to be working as expected on Linux.

**Comment by wertlex** [comment] 2023-06-27 11:41
The same here, however, when pulling [referenced repo](https://github.com/bertrandE/npm-repro-bin-child-workspace) and performing `npm i` in root folder (`npm ci` not works because `js-yaml-3.14.1` could not be resolved) everything seems to work in a right way.

However, if installing `eslint` step by step in each package, the issue will be reproduced.
Summarizing to one command: 
```
rm -rf ./package-lock.json && \
cd ./packages/childA && \
npm rm eslint && \
cd ../../packages/childB && \
npm rm eslint && \
npm i -D -E eslint@7.32.0 && \
cd ../../packages/childA && \
npm i -D -E eslint@8.36.0 && \
cd ../../
```

An interersting thing here that it looks like that `npx` uses only eslint which was hoisted to repo root. So, in this case if one will change of order of `npm i -D -E eslint...`, result will be different.

Tested with `node:18.16.1` [docker image](https://hub.docker.com/layers/library/node/18.16.1/images/sha256-35b6b9bf7880fa8a333820d5c296076a35207c477baf0b359e307927ea2a43e3?context=explore)

**Comment by milaninfy** [comment] 2024-06-21 20:47
@bertrandE This could be fixed on latest version of npm. PR: https://github.com/npm/cli/issues/7379
Running on 10.8.1 it's working as expected. 
 
```sh
~/workarea/rep/test $ npm ls
test@1.0.0 /Users/milaninfy/workarea/rep/test
├─┬ a@1.0.0 -> ./a
│ └── @bintest/pkg1@1.0.0
└─┬ b@1.0.0 -> ./b
  └── @bintest/pkg1@3.0.0

~/workarea/rep/test $ npx -w a @bintest/pkg1
Current time: 6/21/2024, 4:41:56 PM
Package name: @bintest/pkg1
version: 1.0.0
~/workarea/rep/test $ npx -w b @bintest/pkg1
Current time: 6/21/2024, 4:42:02 PM
Package name: @bintest/pkg1
version: 3.0.0
```

**Closed as completed by milaninfy** 2024-06-21 20:47 UTC
Labels: Release 8.x, Bug, Needs Triage
