### ISSUE TITLE
[BUG] npm ci wipes out the scripts in the .bin folder and does not replace them

### ISSUE THREAD

**Issue by wandyezj** [npm/cli#4035] opened 2021-11-10 20:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

npm ci wipes out scripts in the .bin folder instead of reinstalling them.

### Expected Behavior

npm ci reinstalls .bin scripts for each package

### Steps To Reproduce

Use the npm version that comes with Node LTS this is NPM 8.1

1. npm install --save-dev prettier typescript
2. npm ci
3. npm ci
4. observe that tsc and prettier are not present in the `node_modules\.bin`
5. shake fist in confusion as previous scripts that pointed to tsc and prettier in the .bin folder fail

### Environment

- npm: 8.1
- Node: 16.13.0
- OS: Windows 10
- platform: Surface Laptop
- npm config:
```ini
; "builtin" config from C:\Program Files\nodejs\node_modules\npm\npmrc

prefix = "C:\\Users\\<REDACTED>\\AppData\\Roaming\\npm"

; "user" config from C:\Users\<REDACTED>\.npmrc

email = "not-used@example.com"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = <REDACTED>
; HOME = <REDACTED>
; Run `npm config ls -l` to show all defaults.
```

note: should be an option to remove customer information in the npm config ls

**Comment by ruyadorno** [comment] 2022-01-25 20:21
**Closing:** this looks to be similar if not a duplicate of an existing issue, #4308. If you believe your instance is unique, please provide further clarifying details.

**Closed as completed by ruyadorno** 2022-01-25 20:21 UTC
Labels: Release 8.x, Bug, Needs Triage
