### ISSUE TITLE
`npm ls <pkgname>` always exits in error (even when there are no ls problems)

### ISSUE THREAD

**Issue by isaacs** [npm/cli#1979] opened 2020-10-16 23:26 UTC
This is weird...

```
$ node . ls eslint
npm@7.0.2 /Users/isaacs/dev/npm/cli
├─┬ eslint-plugin-import@2.22.1
│ └── eslint@7.11.0 deduped
├─┬ eslint-plugin-node@11.1.0
│ ├─┬ eslint-plugin-es@3.0.1
│ │ └── eslint@7.11.0 deduped
│ └── eslint@7.11.0 deduped
├─┬ eslint-plugin-standard@4.0.1
│ └── eslint@7.11.0 deduped
└── eslint@7.11.0

$ echo $?
1
```

**Comment by ljharb** [comment] 2020-10-17 05:16
I'm surprised that if `npm ls` exits nonzero, that some kind of warning wouldn't automatically be generated on `npm install`?

**Comment by nlf** [comment] 2020-10-27 14:13
is this still an issue? i'm not able to reproduce it from `latest` on my end

**Comment by nlf** [comment] 2020-11-30 18:00
this was fixed in `7.0.3`

**Closed as completed by nlf** 2020-11-30 18:00 UTC
Labels: Release 7.x, Bug
