### ISSUE TITLE
[ERR] npm ERR! cb() never called!

### ISSUE THREAD

**Issue by mhadysydney** [npm/cli#1505] opened 2020-07-09 01:30 UTC
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mhady/.npm/_logs/2020-07-09T01_24_15_710Z-debug.log

Environements:
Ubuntu 20.04
Node 13.14.0
npm 6.4.14

**Comment by zorjo** [comment] 2020-07-09 07:16
➜  npm install
^[[B[        ..........] / extract:global-modules: sill extract globanpm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2020-07-09T07_09_15_901Z-debug.log
The error log is : http://0x0.st/it-h.txt
EDIT: Updating node to 14.5.0 has fixed the problem for me

**Comment by stgoogle** [comment] 2020-07-09 13:16
==> **npm install**

17551 timing npm Completed in 228122ms
17552 error cb() never called!
17553 error This is an error with npm itself. Please report this error at:
17554 error <https://npm.community>

**environment:**
Windows_NT 10.0.18363
npm@6.13.4
node@v12.16.1

2 machines, one run without error, one reported this error.
if I copy over the installed node_module from the other machine, compile and run will be successful.

**Comment by Bow2Jesus** [comment] 2020-07-09 16:27
Similar to above:

![image](https://user-images.githubusercontent.com/4163928/87065475-b0b47500-c1d6-11ea-93d6-87877e3c431e.png)

Here is the contents of the log:

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\i338909\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'bootstrap@3'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.2
4 verbose npm-session dcfad6e8810dc086
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 407 https://registry.npmjs.org/bootstrap 321ms
8 timing npm Completed in 3199ms
9 error cb() never called!
10 error This is an error with npm itself. Please report this error at:
11 error <https://npm.community>

Update1: Tried updating to npm 14.50 as Sourjyo0 suggested.  Was not able to install due to still being on Windows 7.  Updated to 13.14 instead.  This did NOT fix the issue.

Update2: Found that it is not an issue with npm itself, despite the message saying so.  It was a network issue caused by our proxy.  Run "npm config list" to see what your proxy settings are.  They may need to be set to something else or nothing.

**Comment by matepek** [comment] 2020-07-11 03:52
```
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/matepek/.npm/_logs/2020-07-11T03_49_28_699Z-debug.log
```
[2020-07-11T03_49_28_699Z-debug.log](https://github.com/npm/cli/files/4906238/2020-07-11T03_49_28_699Z-debug.log)

**Comment by inzy007** [comment] 2020-07-11 06:47
I've been trying to update lodash dependencies in order to address https://npmjs.com/advisories/1523; however whenever I do so, I run into this error. Attached is the log. I tried increasing the ulimit (ulimit -s 20000), however got the same result.

Environment:
- macOS Catalina v10.15.5
- node v14.4.0
- npm v6.14.6

The package lodash is primarily included as a dependency of react-scripts of which I am using v3.3.0.

MacintoMacBook2:xxxxx$ npm update lodash --depth 20
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxxxx/.npm/_logs/2020-07-11T06_30_37_797Z-debug.log

[2020-07-11T06_30_37_797Z-debug.log](https://github.com/npm/cli/files/4906401/2020-07-11T06_30_37_797Z-debug.log)

**Comment by shaoran** [comment] 2020-07-13 10:05
I have a similar issue when trying to execute `npm update lodash --depth 19` which is what `npm audit` suggests because of lodash. The process take a long time and eventually fails.

My env:

- gentoo linux
- node v12.16.2
- npm 6.14.5

[2020-07-13T09_58_22_112Z-debug.log](https://github.com/npm/cli/files/4911726/2020-07-13T09_58_22_112Z-debug.log)

**Comment by taofeeq-deru** [comment] 2020-07-17 12:25
had similar issue when i ran `npx create-react-app myapp`.

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USER\AppData\Roaming\npm-cache\_logs\2020-07-17T11_56_40_885Z-debug.log

complete log of the error:
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   '--save-exact',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   'react',
1 verbose cli   'react-dom',
1 verbose cli   'react-scripts',
1 verbose cli   'cra-template'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v14.5.0
4 verbose npm-session f6013927937a3518
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/cra-template 5703ms
8 http fetch GET 200 https://registry.npmjs.org/cra-template/-/cra-template-1.0.3.tgz 901ms
9 silly pacote tag manifest for cra-template@latest fetched in 6640ms
10 http fetch GET 200 https://registry.npmjs.org/react 10068ms
11 http fetch GET 200 https://registry.npmjs.org/react-dom 10102ms
12 http fetch GET 200 https://registry.npmjs.org/react-scripts 10192ms
13 http fetch GET 200 https://registry.npmjs.org/react/-/react-16.13.1.tgz 1060ms
14 silly pacote tag manifest for react@latest fetched in 11209ms
15 http fetch GET 200 https://registry.npmjs.org/react-scripts/-/react-scripts-3.4.1.tgz 6264ms
16 silly pacote tag manifest for react-scripts@latest fetched in 16501ms
17 http fetch GET 200 https://registry.npmjs.org/react-dom/-/react-dom-16.13.1.tgz 34805ms
18 silly pacote tag manifest for react-dom@latest fetched in 44948ms
19 timing stage:loadCurrentTree Completed in 45152ms
20 silly install loadIdealTree
21 silly install cloneCurrentTreeToIdealTree
22 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
23 silly install loadShrinkwrap
24 timing stage:loadIdealTree:loadShrinkwrap Completed in 2ms
25 silly install loadAllDepsIntoIdealTree
26 silly resolveWithNewModule cra-template@1.0.3 checking installable status
27 silly resolveWithNewModule react@16.13.1 checking installable status
28 silly resolveWithNewModule react-scripts@3.4.1 checking installable status
29 silly resolveWithNewModule react-dom@16.13.1 checking installable status
30 http fetch GET 200 https://registry.npmjs.org/loose-envify 803ms
31 http fetch GET 200 https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz 286ms
32 silly pacote range manifest for loose-envify@^1.1.0 fetched in 1116ms
33 silly resolveWithNewModule loose-envify@1.4.0 checking installable status
34 http fetch GET 200 https://registry.npmjs.org/prop-types 2554ms
35 http fetch GET 200 https://registry.npmjs.org/object-assign 2571ms
36 http fetch GET 200 https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz 1106ms
37 silly pacote range manifest for object-assign@^4.1.1 fetched in 3704ms
38 silly resolveWithNewModule object-assign@4.1.1 checking installable status
39 http fetch GET 200 https://registry.npmjs.org/prop-types/-/prop-types-15.7.2.tgz 7609ms
40 silly pacote range manifest for prop-types@^15.6.2 fetched in 10197ms
41 silly resolveWithNewModule prop-types@15.7.2 checking installable status
42 http fetch GET 200 https://registry.npmjs.org/js-tokens 3429ms
43 http fetch GET 200 https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz 282ms
44 silly pacote range manifest for js-tokens@^3.0.0 || ^4.0.0 fetched in 3736ms
45 silly resolveWithNewModule js-tokens@4.0.0 checking installable status
46 http fetch GET 200 https://registry.npmjs.org/react-is 24963ms
47 http fetch GET 200 https://registry.npmjs.org/react-is/-/react-is-16.13.1.tgz 5855ms
48 silly pacote range manifest for react-is@^16.8.1 fetched in 30844ms
49 silly resolveWithNewModule react-is@16.13.1 checking installable status
50 http fetch GET 200 https://registry.npmjs.org/scheduler 31305ms
51 http fetch GET 200 https://registry.npmjs.org/scheduler/-/scheduler-0.19.1.tgz 10307ms
52 silly pacote range manifest for scheduler@^0.19.1 fetched in 41641ms
53 silly resolveWithNewModule scheduler@0.19.1 checking installable status
54 http fetch GET 200 https://registry.npmjs.org/@svgr%2fwebpack 14160ms
55 http fetch GET 200 https://registry.npmjs.org/babel-plugin-named-asset-import 14361ms
56 http fetch GET 200 https://registry.npmjs.org/babel-loader 14401ms
57 http fetch GET 200 https://registry.npmjs.org/camelcase 16656ms
58 http fetch GET 200 https://registry.npmjs.org/@svgr/webpack/-/webpack-4.3.3.tgz 3258ms
59 silly pacote version manifest for @svgr/webpack@4.3.3 fetched in 17445ms
60 silly resolveWithNewModule @svgr/webpack@4.3.3 checking installable status
61 http fetch GET 200 https://registry.npmjs.org/babel-eslint 17494ms
62 http fetch GET 200 https://registry.npmjs.org/babel-preset-react-app 18174ms
63 http fetch GET 200 https://registry.npmjs.org/babel-plugin-named-asset-import/-/babel-plugin-named-asset-import-0.3.6.tgz 4031ms
64 silly pacote range manifest for babel-plugin-named-asset-import@^0.3.6 fetched in 18424ms
65 silly resolveWithNewModule babel-plugin-named-asset-import@0.3.6 checking installable status
66 http fetch GET 200 https://registry.npmjs.org/babel-loader/-/babel-loader-8.1.0.tgz 4036ms
67 silly pacote version manifest for babel-loader@8.1.0 fetched in 18472ms
68 silly resolveWithNewModule babel-loader@8.1.0 checking installable status
69 http fetch GET 200 https://registry.npmjs.org/camelcase/-/camelcase-5.3.1.tgz 2454ms
70 silly pacote range manifest for camelcase@^5.3.1 fetched in 19133ms
71 silly resolveWithNewModule camelcase@5.3.1 checking installable status
72 http fetch GET 200 https://registry.npmjs.org/babel-jest 37376ms
73 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2fparser 98469ms
74 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint/parser/-/parser-2.34.0.tgz 1455ms
75 silly pacote range manifest for @typescript-eslint/parser@^2.10.0 fetched in 100058ms
76 silly resolveWithNewModule @typescript-eslint/parser@2.34.0 checking installable status
77 http fetch GET 200 https://registry.npmjs.org/eslint 5941ms
78 http fetch GET 200 https://registry.npmjs.org/eslint/-/eslint-6.8.0.tgz 19196ms
79 silly pacote range manifest for eslint@^6.6.0 fetched in 25202ms
80 silly resolveWithNewModule eslint@6.8.0 checking installable status
81 http fetch GET 200 https://registry.npmjs.org/dotenv-expand 106210ms attempt #3
82 http fetch GET 200 https://registry.npmjs.org/babel-eslint/-/babel-eslint-10.1.0.tgz 108097ms attempt #3
83 silly pacote version manifest for babel-eslint@10.1.0 fetched in 125628ms
84 silly resolveWithNewModule babel-eslint@10.1.0 checking installable status
85 http fetch GET 200 https://registry.npmjs.org/dotenv 107342ms attempt #3
86 http fetch GET 200 https://registry.npmjs.org/case-sensitive-paths-webpack-plugin 108460ms attempt #3
87 http fetch GET 200 https://registry.npmjs.org/babel-preset-react-app/-/babel-preset-react-app-9.1.2.tgz 107703ms attempt #3
88 silly pacote range manifest for babel-preset-react-app@^9.1.2 fetched in 125921ms
89 silly resolveWithNewModule babel-preset-react-app@9.1.2 checking installable status
90 http fetch GET 200 https://registry.npmjs.org/eslint-config-react-app 822ms
91 http fetch GET 200 https://registry.npmjs.org/dotenv-expand/-/dotenv-expand-5.1.0.tgz 839ms
92 silly pacote version manifest for dotenv-expand@5.1.0 fetched in 107072ms
93 silly resolveWithNewModule dotenv-expand@5.1.0 checking installable status
94 http fetch GET 200 https://registry.npmjs.org/eslint-loader 865ms
95 http fetch GET 200 https://registry.npmjs.org/dotenv/-/dotenv-8.2.0.tgz 717ms
96 silly pacote version manifest for dotenv@8.2.0 fetched in 108092ms
97 silly resolveWithNewModule dotenv@8.2.0 checking installable status
98 http fetch GET 200 https://registry.npmjs.org/case-sensitive-paths-webpack-plugin/-/case-sensitive-paths-webpack-plugin-2.3.0.tgz 680ms
99 silly pacote version manifest for case-sensitive-paths-webpack-plugin@2.3.0 fetched in 109158ms
100 silly resolveWithNewModule case-sensitive-paths-webpack-plugin@2.3.0 checking installable status
101 http fetch GET 200 https://registry.npmjs.org/eslint-config-react-app/-/eslint-config-react-app-5.2.1.tgz 1154ms
102 silly pacote range manifest for eslint-config-react-app@^5.2.1 fetched in 2011ms
103 silly resolveWithNewModule eslint-config-react-app@5.2.1 checking installable status
104 http fetch GET 200 https://registry.npmjs.org/css-loader 108861ms attempt #3
105 http fetch GET 200 https://registry.npmjs.org/eslint-loader/-/eslint-loader-3.0.3.tgz 1508ms
106 silly pacote version manifest for eslint-loader@3.0.3 fetched in 2396ms
107 silly resolveWithNewModule eslint-loader@3.0.3 checking installable status
108 http fetch GET 200 https://registry.npmjs.org/eslint-plugin-jsx-a11y 1683ms
109 http fetch GET 200 https://registry.npmjs.org/css-loader/-/css-loader-3.4.2.tgz 1692ms
110 silly pacote version manifest for css-loader@3.4.2 fetched in 110575ms
111 silly resolveWithNewModule css-loader@3.4.2 checking installable status
112 http fetch GET 200 https://registry.npmjs.org/eslint-plugin-react-hooks 2187ms
113 http fetch GET 200 https://registry.npmjs.org/file-loader 1447ms
114 http fetch GET 200 https://registry.npmjs.org/eslint-plugin-import 3268ms
115 http fetch GET 200 https://registry.npmjs.org/eslint-plugin-react 3264ms
116 http fetch GET 200 https://registry.npmjs.org/eslint-plugin-flowtype 4075ms
117 http fetch GET 304 https://registry.npmjs.org/fs-extra 1075ms (from cache)
118 http fetch GET 200 https://registry.npmjs.org/fs-extra/-/fs-extra-8.1.0.tgz 20ms (from cache)
119 http fetch GET 200 https://registry.npmjs.org/babel-jest/-/babel-jest-24.9.0.tgz 92731ms attempt #3
120 silly pacote range manifest for fs-extra@^8.1.0 fetched in 1122ms
121 silly resolveWithNewModule fs-extra@8.1.0 checking installable status
122 silly pacote range manifest for babel-jest@^24.9.0 fetched in 130148ms
123 silly resolveWithNewModule babel-jest@24.9.0 checking installable status
124 http fetch GET 200 https://registry.npmjs.org/eslint-plugin-react-hooks/-/eslint-plugin-react-hooks-1.7.0.tgz 730ms
125 http fetch GET 200 https://registry.npmjs.org/file-loader/-/file-loader-4.3.0.tgz 729ms
126 silly pacote range manifest for eslint-plugin-react-hooks@^1.6.1 fetched in 2956ms
127 silly resolveWithNewModule eslint-plugin-react-hooks@1.7.0 checking installable status
128 silly pacote version manifest for file-loader@4.3.0 fetched in 2213ms
129 silly resolveWithNewModule file-loader@4.3.0 checking installable status
130 http fetch GET 200 https://registry.npmjs.org/eslint-plugin-jsx-a11y/-/eslint-plugin-jsx-a11y-6.2.3.tgz 2093ms
131 silly pacote version manifest for eslint-plugin-jsx-a11y@6.2.3 fetched in 3810ms
132 silly resolveWithNewModule eslint-plugin-jsx-a11y@6.2.3 checking installable status
133 http fetch GET 200 https://registry.npmjs.org/eslint-plugin-flowtype/-/eslint-plugin-flowtype-4.6.0.tgz 799ms
134 silly pacote version manifest for eslint-plugin-flowtype@4.6.0 fetched in 4907ms
135 silly resolveWithNewModule eslint-plugin-flowtype@4.6.0 checking installable status
136 http fetch GET 200 https://registry.npmjs.org/identity-obj-proxy 801ms
137 http fetch GET 200 https://registry.npmjs.org/jest-watch-typeahead 604ms
138 http fetch GET 200 https://registry.npmjs.org/html-webpack-plugin 1307ms
139 http fetch GET 200 https://registry.npmjs.org/identity-obj-proxy/-/identity-obj-proxy-3.0.0.tgz 586ms
140 silly pacote version manifest for identity-obj-proxy@3.0.0 fetched in 1410ms
141 silly resolveWithNewModule identity-obj-proxy@3.0.0 checking installable status
142 http fetch GET 200 https://registry.npmjs.org/html-webpack-plugin/-/html-webpack-plugin-4.0.0-beta.11.tgz 1069ms
143 silly pacote version manifest for html-webpack-plugin@4.0.0-beta.11 fetched in 2424ms
144 silly resolveWithNewModule html-webpack-plugin@4.0.0-beta.11 checking installable status
145 http fetch GET 200 https://registry.npmjs.org/jest-watch-typeahead/-/jest-watch-typeahead-0.4.2.tgz 1114ms
146 silly pacote version manifest for jest-watch-typeahead@0.4.2 fetched in 1756ms
147 silly resolveWithNewModule jest-watch-typeahead@0.4.2 checking installable status
148 http fetch GET 200 https://registry.npmjs.org/optimize-css-assets-webpack-plugin 784ms
149 http fetch GET 200 https://registry.npmjs.org/pnp-webpack-plugin 931ms
150 http fetch GET 200 https://registry.npmjs.org/jest 3301ms
151 http fetch GET 200 https://registry.npmjs.org/eslint-plugin-react/-/eslint-plugin-react-7.19.0.tgz 3676ms
152 silly pacote version manifest for eslint-plugin-react@7.19.0 fetched in 6976ms
153 silly resolveWithNewModule eslint-plugin-react@7.19.0 checking installable status
154 http fetch GET 200 https://registry.npmjs.org/jest-resolve 3214ms
155 http fetch GET 200 https://registry.npmjs.org/mini-css-extract-plugin 2072ms
156 http fetch GET 200 https://registry.npmjs.org/postcss-flexbugs-fixes 145ms
157 http fetch GET 200 https://registry.npmjs.org/optimize-css-assets-webpack-plugin/-/optimize-css-assets-webpack-plugin-5.0.3.tgz 375ms
158 http fetch GET 200 https://registry.npmjs.org/pnp-webpack-plugin/-/pnp-webpack-plugin-1.6.4.tgz 201ms
159 http fetch GET 200 https://registry.npmjs.org/jest/-/jest-24.9.0.tgz 185ms
160 http fetch GET 200 https://registry.npmjs.org/eslint-plugin-import/-/eslint-plugin-import-2.20.1.tgz 4237ms
161 silly pacote version manifest for optimize-css-assets-webpack-plugin@5.0.3 fetched in 1245ms
162 silly resolveWithNewModule optimize-css-assets-webpack-plugin@5.0.3 checking installable status
163 silly pacote version manifest for jest@24.9.0 fetched in 3577ms
164 silly resolveWithNewModule jest@24.9.0 checking installable status
165 silly pacote version manifest for pnp-webpack-plugin@1.6.4 fetched in 1225ms
166 silly resolveWithNewModule pnp-webpack-plugin@1.6.4 checking installable status
167 silly pacote version manifest for eslint-plugin-import@2.20.1 fetched in 7621ms
168 silly resolveWithNewModule eslint-plugin-import@2.20.1 checking installable status
169 http fetch GET 200 https://registry.npmjs.org/jest-resolve/-/jest-resolve-24.9.0.tgz 275ms
170 http fetch GET 200 https://registry.npmjs.org/mini-css-extract-plugin/-/mini-css-extract-plugin-0.9.0.tgz 262ms
171 silly pacote version manifest for jest-resolve@24.9.0 fetched in 3530ms
172 silly resolveWithNewModule jest-resolve@24.9.0 checking installable status
173 http fetch GET 200 https://registry.npmjs.org/postcss-flexbugs-fixes/-/postcss-flexbugs-fixes-4.1.0.tgz 190ms
174 silly pacote version manifest for mini-css-extract-plugin@0.9.0 fetched in 2372ms
175 silly resolveWithNewModule mini-css-extract-plugin@0.9.0 checking installable status
176 silly pacote version manifest for postcss-flexbugs-fixes@4.1.0 fetched in 367ms
177 silly resolveWithNewModule postcss-flexbugs-fixes@4.1.0 checking installable status
178 http fetch GET 200 https://registry.npmjs.org/postcss-normalize 173ms
179 http fetch GET 200 https://registry.npmjs.org/postcss-safe-parser 177ms
180 http fetch GET 200 https://registry.npmjs.org/postcss-preset-env 607ms
181 http fetch GET 200 https://registry.npmjs.org/react-app-polyfill 743ms
182 http fetch GET 200 https://registry.npmjs.org/resolve 975ms
183 http fetch GET 200 https://registry.npmjs.org/postcss-preset-env/-/postcss-preset-env-6.7.0.tgz 892ms
184 http fetch GET 200 https://registry.npmjs.org/postcss-safe-parser/-/postcss-safe-parser-4.0.1.tgz 1307ms
185 silly pacote version manifest for postcss-preset-env@6.7.0 fetched in 1533ms
186 silly resolveWithNewModule postcss-preset-env@6.7.0 checking installable status
187 silly pacote version manifest for postcss-safe-parser@4.0.1 fetched in 1523ms
188 silly resolveWithNewModule postcss-safe-parser@4.0.1 checking installable status
189 http fetch GET 200 https://registry.npmjs.org/react-app-polyfill/-/react-app-polyfill-1.0.6.tgz 711ms
190 silly pacote range manifest for react-app-polyfill@^1.0.6 fetched in 1555ms
191 silly resolveWithNewModule react-app-polyfill@1.0.6 checking installable status
192 http fetch GET 200 https://registry.npmjs.org/postcss-normalize/-/postcss-normalize-8.0.1.tgz 1526ms
193 http fetch GET 200 https://registry.npmjs.org/resolve/-/resolve-1.15.0.tgz 596ms
194 silly pacote version manifest for postcss-normalize@8.0.1 fetched in 1729ms
195 silly resolveWithNewModule postcss-normalize@8.0.1 checking installable status
196 silly pacote version manifest for resolve@1.15.0 fetched in 1604ms
197 silly resolveWithNewModule resolve@1.15.0 checking installable status
198 http fetch GET 200 https://registry.npmjs.org/resolve-url-loader 1318ms
199 http fetch GET 200 https://registry.npmjs.org/sass-loader 1609ms
200 http fetch GET 200 https://registry.npmjs.org/postcss-loader 3185ms
201 http fetch GET 200 https://registry.npmjs.org/react-dev-utils 3115ms
202 http fetch GET 304 https://registry.npmjs.org/semver 1621ms (from cache)
203 silly pacote version manifest for semver@6.3.0 fetched in 1627ms
204 silly resolveWithNewModule semver@6.3.0 checking installable status
205 http fetch GET 200 https://registry.npmjs.org/style-loader 1589ms
206 http fetch GET 200 https://registry.npmjs.org/resolve-url-loader/-/resolve-url-loader-3.1.1.tgz 769ms
207 silly pacote version manifest for resolve-url-loader@3.1.1 fetched in 2124ms
208 silly resolveWithNewModule resolve-url-loader@3.1.1 checking installable status
209 http fetch GET 200 https://registry.npmjs.org/sass-loader/-/sass-loader-8.0.2.tgz 510ms
210 silly pacote version manifest for sass-loader@8.0.2 fetched in 2160ms
211 silly resolveWithNewModule sass-loader@8.0.2 checking installable status
212 http fetch GET 200 https://registry.npmjs.org/postcss-loader/-/postcss-loader-3.0.0.tgz 532ms
213 silly pacote version manifest for postcss-loader@3.0.0 fetched in 3749ms
214 silly resolveWithNewModule postcss-loader@3.0.0 checking installable status
215 http fetch GET 200 https://registry.npmjs.org/react-dev-utils/-/react-dev-utils-10.2.1.tgz 558ms
216 silly pacote range manifest for react-dev-utils@^10.2.1 fetched in 3700ms
217 silly resolveWithNewModule react-dev-utils@10.2.1 checking installable status
218 http fetch GET 200 https://registry.npmjs.org/ts-pnp 581ms
219 http fetch GET 200 https://registry.npmjs.org/style-loader/-/style-loader-0.23.1.tgz 883ms
220 http fetch GET 200 https://registry.npmjs.org/terser-webpack-plugin 2472ms
221 silly pacote version manifest for style-loader@0.23.1 fetched in 2503ms
222 silly resolveWithNewModule style-loader@0.23.1 checking installable status
223 http fetch GET 200 https://registry.npmjs.org/url-loader 1006ms
224 http fetch GET 200 https://registry.npmjs.org/jest-environment-jsdom-fourteen 8809ms
225 http fetch GET 200 https://registry.npmjs.org/webpack-manifest-plugin 1445ms
226 http fetch GET 200 https://registry.npmjs.org/ts-pnp/-/ts-pnp-1.1.6.tgz 1414ms
227 silly pacote version manifest for ts-pnp@1.1.6 fetched in 3710ms
228 silly resolveWithNewModule ts-pnp@1.1.6 checking installable status
229 http fetch GET 200 https://registry.npmjs.org/url-loader/-/url-loader-2.3.0.tgz 2346ms
230 http fetch GET 200 https://registry.npmjs.org/jest-environment-jsdom-fourteen/-/jest-environment-jsdom-fourteen-1.0.1.tgz 1794ms
231 http fetch GET 200 https://registry.npmjs.org/webpack-manifest-plugin/-/webpack-manifest-plugin-2.2.0.tgz 1760ms
232 http fetch GET 200 https://registry.npmjs.org/terser-webpack-plugin/-/terser-webpack-plugin-2.3.5.tgz 2821ms
233 http fetch GET 200 https://registry.npmjs.org/workbox-webpack-plugin 2809ms
234 silly pacote version manifest for url-loader@2.3.0 fetched in 3402ms
235 silly resolveWithNewModule url-loader@2.3.0 checking installable status
236 silly pacote version manifest for webpack-manifest-plugin@2.2.0 fetched in 3258ms
237 silly resolveWithNewModule webpack-manifest-plugin@2.2.0 checking installable status
238 silly pacote version manifest for jest-environment-jsdom-fourteen@1.0.1 fetched in 10661ms
239 silly resolveWithNewModule jest-environment-jsdom-fourteen@1.0.1 checking installable status
240 silly pacote version manifest for terser-webpack-plugin@2.3.5 fetched in 5350ms
241 silly resolveWithNewModule terser-webpack-plugin@2.3.5 checking installable status
242 http fetch GET 200 https://registry.npmjs.org/fsevents 1556ms
243 http fetch GET 200 https://registry.npmjs.org/workbox-webpack-plugin/-/workbox-webpack-plugin-4.3.1.tgz 1575ms
244 silly pacote version manifest for workbox-webpack-plugin@4.3.1 fetched in 4404ms
245 silly resolveWithNewModule workbox-webpack-plugin@4.3.1 checking installable status
246 http fetch GET 200 https://registry.npmjs.org/fsevents/-/fsevents-2.1.2.tgz 2706ms
247 silly pacote version manifest for fsevents@2.1.2 fetched in 4283ms
248 silly resolveWithNewModule fsevents@2.1.2 checking installable status
249 http fetch GET 200 https://registry.npmjs.org/webpack 7685ms
250 http fetch GET 200 https://registry.npmjs.org/webpack-dev-server 7803ms
251 http fetch GET 200 https://registry.npmjs.org/webpack/-/webpack-4.42.0.tgz 3123ms
252 silly pacote version manifest for webpack@4.42.0 fetched in 10869ms
253 silly resolveWithNewModule webpack@4.42.0 checking installable status
254 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2feslint-plugin 148773ms
255 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint/eslint-plugin/-/eslint-plugin-2.34.0.tgz 1022ms
256 silly pacote range manifest for @typescript-eslint/eslint-plugin@^2.10.0 fetched in 149875ms
257 silly resolveWithNewModule @typescript-eslint/eslint-plugin@2.34.0 checking installable status
258 http fetch GET 200 https://registry.npmjs.org/webpack-dev-server/-/webpack-dev-server-3.10.3.tgz 4538ms
259 silly pacote version manifest for webpack-dev-server@3.10.3 fetched in 12370ms
260 silly resolveWithNewModule webpack-dev-server@3.10.3 checking installable status
261 timing npm Completed in 284035ms
262 error cb() never called!
263 error This is an error with npm itself. Please report this error at:
264 error <https://npm.community>

windows 10
node v14.5.0
npm 6.14.5

**Comment by aubelsb2** [comment] 2020-12-04 02:00
Just a guess: I think this is caused when you have 2 file: pathed libraries, one which depends on the other and you have included them in a 3rd project.. I guess it's a version conflict resolution issue during "staging" ?

**Comment by aubelsb2** [comment] 2020-12-04 03:15
I tried to recreate this in a sample project. I did manage to get an error but not quite the same thing:
https://github.com/aubelsb2/npm-fail1

Probably way more complicated that necessary.

Ran:
```npm run installall```
Result:
```
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\arran_w\WebstormProjects\untitled3\ls\l3\node_modules\.staging\caniuse-lite-8269b937\data\regions\SR.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\arran_w\WebstormProjects\untitled3\ls\l3\node_modules\.staging\caniuse-lite-8269b937\data\features\srcset.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\arran_w\WebstormProjects\untitled3\ls\l3\node_modules\.staging\caniuse-lite-8269b937\data\regions\ST.js'
npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\arran_w\AppData\Roaming\npm-cache\_logs\2020-12-04T03_10_11_289Z-debug.log
child_process.js:650
    throw err;
    ^

Error: Command failed: npm install
```

C:\Users\arran_w\AppData\Roaming\npm-cache\_logs\2020-12-04T03_10_11_289Z-debug.log
```
40898 silly saveTree   |   `-- source-map@0.7.3
40898 silly saveTree   +-- watchpack@2.0.1
40898 silly saveTree   `-- webpack-sources@2.2.0
40898 silly saveTree     +-- source-list-map@2.0.1
40898 silly saveTree     `-- source-map@0.6.1
40899 verbose stack RangeError: Maximum call stack size exceeded
40899 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:453:9)
40899 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:453:9)
40899 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:453:9)
40899 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:453:9)
40899 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:453:9)
40899 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:453:9)
40899 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:453:9)
40899 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:453:9)
40899 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:453:9)
40899 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:453:9)
40899 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:453:9)
40899 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:453:9)
40899 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:453:9)
40899 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:453:9)
40899 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:453:9)
40899 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:453:9)
40900 verbose cwd C:\Users\arran_w\WebstormProjects\untitled3\ls\l3

```

**Comment by darcyclarke** [comment] 2021-06-02 21:16
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 21:16 UTC
Labels: Release 6.x
