### ISSUE TITLE
[BUG] `npm publish` runs prepare script silently

### ISSUE THREAD

**Issue by everett1992** [npm/cli#5112] opened 2022-06-30 20:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`npm publish` runs the `prepare` script silently. Unlike `prepublishOnly` it does not print the command that will be run or the commands output.

The order of `prepublishOnly` and `prepare` changed between npm 6 and npm 8 causing some packages I own to compile (prepublishOnly) then clean (prepare) and the silent output made it harder to debug.

### Expected Behavior

`prepare` should be run like other lifecycle hooks, with output to the console.

### Steps To Reproduce

1. Create a package with prepare and prepbulish scripts. These example scripts print to stdout and create a file.
```
{
  "name": "publish-example",
  "version": "1.0.0",
  "scripts": {
    "prepublishOnly": "echo prepublishOnly | tee prepublishOnly",
    "prepare": "echo prepare | tee prepare"
  }
}
```

```
$ npx npm@8.13.2 publish --dry-run

> publish-example@1.0.0 prepublishOnly
> echo prepublishOnly | tee prepublishOnly

prepublishOnly
npm notice 184B package.json
npm notice 8B   prepare
npm notice 15B  prepublishOnly
```

npm outputs the `prepublishOnly` command that will be executed and the commands output.
but npm also ran `prepare` without printing the command or it's output. See that the `prepare` file was created.

If we run again with foregroundScripts npm will print both scripts
```
$ npx npm@8 publish --dry-run --foreground-scripts

> publish-example@1.0.0 prepublishOnly
> echo prepublishOnly | tee prepublishOnly

prepublishOnly

> publish-example@1.0.0 prepare
> echo prepare | tee prepare

prepare
```

Notice that npm 8 runs prepublishOnly then prepare. If we switch to npm 6 that order is flipped

```
npx npm@6 publish --dry-run --foreground-scripts

> publish-example@1.0.0 prepare .
> echo prepare | tee prepare

prepare

> publish-example@1.0.0 prepublishOnly .
> echo prepublishOnly | tee prepublishOnly

prepublishOnly
```

### Environment

- npm: 8.13.2
- Node.js: 16.15.1
- OS Name: Ubuntu

**Comment by wraithgar** [comment] 2022-06-30 23:11
This was an intentional change in npm 7 to run `prepare` scripts in the background by default. If you require them to be in the foreground you can run npm with `--foreground-scripts`

See https://docs.npmjs.com/cli/v8/using-npm/scripts#life-cycle-scripts for more info.

**Comment by wraithgar** [comment] 2022-06-30 23:12
Closing this as 'working as intended'  If you feel the behavior of npm should change in future versions please submit an [rrfc or rfc](https://github.com/npm/rfcs)

**Closed as completed by wraithgar** 2022-06-30 23:12 UTC
Labels: Release 8.x, Bug, Needs Triage

**Comment by fingerartur** [comment] 2023-03-22 16:53
The docs https://docs.npmjs.com/cli/v8/using-npm/scripts#life-cycle-scripts do not say anything about the fact that it runs silently and I think that is the root cause of why this issue was opened.

Please consider reopening.
