### ISSUE TITLE
package 404 not found

### ISSUE THREAD

**Issue by es5es5** [npm/cli#1626] opened 2020-08-06 09:33 UTC
# What / Why
Your package manager couldn't get any packages. (404 not found)

## When
Now

## Where
  * npm public registry

## How
* n/a

### Current Behavior
404 not found

![image](https://user-images.githubusercontent.com/24954436/89516184-16fed880-d813-11ea-9535-9a20ae76b151.png)

**Comment by Abjuk** [comment] 2020-08-06 09:35
The same

**Comment by ckimy** [comment] 2020-08-06 09:37
It seems it cannot find all the scoped packages.

**Comment by iTaybb** [comment] 2020-08-06 09:38
Same here.

**Comment by shane-deveire** [comment] 2020-08-06 09:40
Same here, all vue cli packages for example are 404ing

**Comment by jarreskng** [comment] 2020-08-06 09:40
I'm have this problem too

**Comment by eraldoforgoli** [comment] 2020-08-06 09:43
I'm having this problem too

**Comment by aster-17** [comment] 2020-08-06 09:44
same here

**Comment by TryingOutSomething** [comment] 2020-08-06 09:45
I believe there's another issue that is similar 

Duplicate of #1624

**Comment by Naveen604** [comment] 2020-08-06 09:46
Facing the same. even using npm install getting the same error

**Comment by wtlin1228** [comment] 2020-08-06 09:47
same here

**Comment by averkij** [comment] 2020-08-06 09:48
Confirm.

**Comment by MrTomek** [comment] 2020-08-06 09:49
https://status.npmjs.org/

**Comment by ripkens** [comment] 2020-08-06 09:50
Even if it states its resolved partly, here you get another hint to follow:

Not Found - GET https://registry.npmjs.org/@protobufjs%2fbase64 - Not found

**Comment by BankNatthapon** [comment] 2020-08-06 09:52
+1 we're waiting for your resolved npm team! hang in there✌️

**Comment by zszoubair** [comment] 2020-08-06 09:52
same

**Comment by AlexAndBear** [comment] 2020-08-06 09:55
same.
Holidays incoming!

**Comment by gotoinc** [comment] 2020-08-06 09:56
we can only wait for resolve issues

**Comment by Ademking** [comment] 2020-08-06 09:58
same

**Comment by phanvungoc** [comment] 2020-08-06 10:00
An unexpected error occurred: "https://registry.yarnpkg.com/@react-navigation/stack/-/stack-5.2.10.tgz: Request failed \"404 Not Found\"".

**Comment by lebowvsky** [comment] 2020-08-06 10:02
Same! Unable to init a new Angular project...

**Comment by rbdhack** [comment] 2020-08-06 10:05
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@material-ui%2fcore - Not found

**Comment by dakairus** [comment] 2020-08-06 10:05
any solution time? screwed in the middle of a production deployment. Any scoped npm package is failing

**Comment by H-Haynes** [comment] 2020-08-06 10:08
now ,its fixed

**Comment by rushhourmedia** [comment] 2020-08-06 10:09
Still not fixed for me!

**Comment by markb-trustifi** [comment] 2020-08-06 10:09
This is critical error. No scoped packages can be downloaded.
For example, packages like:
"@kenjiuno/decompressrtf": "^0.1.2",
"@kenjiuno/msgreader": "^1.2.5",
"@peculiar/webcrypto": "^1.0.8",

**Comment by Ademking** [comment] 2020-08-06 10:13
> now ,its fixed

No it's not

**Comment by shi-rudo** [comment] 2020-08-06 10:14
same here, 404 on everything scoped

**Comment by kuperchal** [comment] 2020-08-06 10:17
Same here, almost for an hour for now.
Any updates on solving time?

**Comment by markb-trustifi** [comment] 2020-08-06 10:17
For example:
'@protobufjs/eventemitter@latest' is not in the npm registry.

**Comment by tsunejui** [comment] 2020-08-06 10:17
still not work

**Comment by Serrvosky** [comment] 2020-08-06 10:18
Same problem here

**Comment by sgatana** [comment] 2020-08-06 10:21
Experiencing similar issue @sentry/browser.` error An unexpected error occurred: "https://registry.yarnpkg.com/@sentry%2fbrowser: Not found".`

**Comment by hungvu193** [comment] 2020-08-06 10:22
Well, After few hours I found this 's npm issues :/

**Comment by kiehnek** [comment] 2020-08-06 10:23
Seems like it's partially working. [@material-ui/core](https://registry.npmjs.org/@material-ui%2fcore) is working but for example [@styled-system/background](https://registry.npmjs.org/@styled-system%2fbackground) not.

**Comment by jarreskng** [comment] 2020-08-06 10:23
error before: `npm ERR! 404 Not Found - GET https://registry.npmjs.org/@mdi%2fangular-material - Not found`
error now:     `npm ERR! Maximum call stack size exceeded`

still not work

**Comment by pruttned** [comment] 2020-08-06 10:25
Also all of our scoped packages are not working and just returns 404
e.g. https://registry.npmjs.org/@steinringer/angular-ts-decorators

**Comment by finnkauski** [comment] 2020-08-06 10:27
Just to confirm - fresh install through nvm.

> Not Found - GET https://registry.npmjs.org/@typescript-eslint%2fparser - Not found

**Comment by kiehnek** [comment] 2020-08-06 10:27
News from https://status.npmjs.org/

>  Update - Errors are decreasing while we re-populate a faulty cache. We are working to speed up that process to fully resolve the remaining issues quickly.

**Comment by IanMoroney** [comment] 2020-08-06 10:28
https://imgflip.com/i/4alb6a

**Comment by NeilCresswell** [comment] 2020-08-06 10:29
Getting this on many dozens of unrelated packages, many of which are dependencies of some major projects. In case there is some region CDN issue, I tried using a VPN to appear to be in a different continent but that didn't make any difference. Sometimes a package is present but is not the latest released but one from a long time ago. Sometimes a package is not present. Tried various tricks like changing NPM version, npm config set registry http://registry.npmjs.org, etc. but no luck. Does appear to be a registry issue.

Am dead in the water on all my projects right now and no longer able to install packages like Cordova for example.

**Comment by kiehnek** [comment] 2020-08-06 10:31
@NeilCresswell it's an issue in the registry. See here: https://status.npmjs.org/

**Comment by NeilCresswell** [comment] 2020-08-06 10:32
> @NeilCresswell it's an issue in the registry. See here: https://status.npmjs.org/

@korki43 Thanks. I saw your post above right after I submitted mine and have added status.npmjs.org to my bookmarks.

**Comment by nicoWeb31** [comment] 2020-08-06 10:33
ok i'm not alone....

**Comment by VAlgazin** [comment] 2020-08-06 10:34
The big day when deploy is not available)

**Comment by akacanet87** [comment] 2020-08-06 10:35
This reminds me last year.. Maybe it was almost this season, wasn't it??

**Comment by arham09** [comment] 2020-08-06 10:48
same here,

**Comment by wahyualfarisi** [comment] 2020-08-06 10:50
Yes, I Have same issue

**Comment by gilberto1991** [comment] 2020-08-06 10:52
Same problem here

**Comment by arpalmares** [comment] 2020-08-06 10:53
Same here. Cannot globally install serverless.

**npm install serverless -g**

![image](https://user-images.githubusercontent.com/546819/89523803-13b91c00-d816-11ea-9708-4a6a378d699d.png)

**Comment by BankNatthapon** [comment] 2020-08-06 11:02
Latest update! they're continuing to work on a fix for this issue: https://status.npmjs.org/incidents/cksjqc1w11v5

**Comment by TiagoPortfolio** [comment] 2020-08-06 11:04
I didn't find many NPM registry alternatives but while this is not fixed I am using this one:
```
npm install --registry http://registry.npm.taobao.org
yarn install --registry http://registry.npm.taobao.org
```

**Comment by dandelio** [comment] 2020-08-06 11:05
Same problem here

**Comment by grygoryz** [comment] 2020-08-06 11:33
Same problem. Can't install creat-react-app and create-next-app because of it

**Comment by pavazmo** [comment] 2020-08-06 11:37
I think it's fixed ( at least in my case)

**Comment by jpdewing** [comment] 2020-08-06 11:39
fixed for me too

**Comment by korki43** [comment] 2020-08-06 11:47
👏 👏  for the npm team! Thanks for the quick fix!

**Comment by arpalmares** [comment] 2020-08-06 12:12
Already working! THANK YOU!

**Comment by oxowl** [comment] 2020-08-06 12:51
Yes, working! tks!

**Comment by wildmichael** [comment] 2020-08-06 13:07
I still have the issue:
```
$ npm i @tuxc/long
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@tuxc%2flong - Not found
npm ERR! 404
npm ERR! 404  '@tuxc/long@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by coolbeans47** [comment] 2020-08-06 14:09
I still have the issue with AWS amplify builds.

**Comment by 1000i100** [comment] 2020-08-06 22:22
same here : https://framagit.org/1000i100/g1lien/-/jobs/1071777

**Comment by darcyclarke** [comment] 2020-11-05 16:21
Of note, a 404 response is not uncommon to experience when there is a misconfiguration in your env & you're making requests to private/scoped packages; That said, this issue seemed to occur during a [partial outage back in August](https://status.npmjs.org/incidents/cksjqc1w11v5), so I'm going to assume this has been resolved for the bulk of folks since that incident, & close accordingly. 

If you continue to experience any issues with the npm **registry**, **website** or any other **service** in the future, please... 

* check the status of those services (ie. `npm ping` or https://status.npmjs.org/ or https://twitter.com/npm_support)
* check your environment config (ie. `npm config ls` or `cat ~/.npmrc` etc.)
* check to see if you're logged in - *only, if you're trying to access private/scoped packages* (ie. `npm whoami`)

If everything looks right & you've still got issues/errors, you can file a ticket here: https://www.npmjs.com/support

This repo's **issues** are meant to capture bugs within the `npm` client itself. If you think you've found a bug, please open an issue using one of our templates here: https://github.com/npm/cli/issues/new/choose For any other support, you can head over to https://npm.community to find the links I noted above along with references to documentation, our public events calendar, legacy/archived forums etc..

**Closed as completed by darcyclarke** 2020-11-05 16:21 UTC
