### ISSUE TITLE
[feat] Add option to override infer of folder gid and uid

### ISSUE THREAD

**Issue by robertsLando** [npm/cli#4811] opened 2022-04-27 06:24 UTC
I have found many and many issues related to [this](https://docs.npmjs.com/cli/v7/using-npm/scripts#user) breaking change:

#4589 
https://github.com/npm/cli/issues/4095
https://github.com/npm/cli/issues/3773
https://github.com/npm/cli/issues/3110

Giving that there is no workaround to this except changing the directory permissions before running a command (that looks awful) could someone consider adding a flag to npm command or/and npm config that allows to override this?

The change is explained [here](https://github.com/npm/cli/issues/3110#issuecomment-826979929)

cc @wraithgar @ruyadorno @lukekarrys @fritzy 

I can consider creating a PR if you agree with this

**Comment by nlf** [comment] 2022-05-03 21:46
we're aware of these issues, and we've started some discussion towards how we can improve the file ownership story here: https://github.com/npm/rfcs/issues/546

this also applies to child processes, which i think should have their own rules and settings.

anyway, please do feel free to raise any comments, questions or concerns in the link above. i'm going to close this issue as a duplicate of the RFC

**Closed as not planned by nlf** 2022-05-03 21:46 UTC
