### ISSUE TITLE
[BUG] Exit handler never called on npm ci

### ISSUE THREAD

**Issue by TobiasBabin** [npm/cli#7666] opened 2024-07-19 06:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I'm seeing this output in our Docker build in the step `RUN npm ci`:

```
#12 [base-build 4/5] RUN npm ci
#12 7.165 npm error Exit handler never called!
#12 7.165 npm error This is an error with npm itself. Please report this error at:
#12 7.165 npm error   <https://github.com/npm/cli/issues>
#12 7.166 npm error A complete log of this run can be found in: /root/.npm/_logs/2024-07-19T06_11_36_243Z-debug-0.log
```

### Expected Behavior

`RUN npm ci` completes successfully and Docker build continues

### Steps To Reproduce

Our Dockerfile up to this point:

```
FROM node:slim as base-build

COPY package.json package-lock.json /site/

WORKDIR /site

RUN npm ci
```

Extract of `package.json`:

```json
{
  ..
  "engines": {
    "node": ">=16.16.0"
  },
  ..
```

Then run `docker build -t some-tag .`

### Environment

- OS Name: Ubuntu 22.04.4 (GitHub runner)

Output of `npm config ls`:

```
#10 0.500 ; node bin location = /usr/local/bin/node
#10 0.500 ; node version = v22.5.0
#10 0.500 ; npm local prefix = /site
#10 0.500 ; npm version = 10.8.2
#10 0.500 ; cwd = /site
#10 0.500 ; HOME = /root
```

**Comment by Bramw2003** [comment] 2024-07-19 07:03
This also happens when running `npm install` with the latest version

**Comment by SquirrelDeveloper** [comment] 2024-07-19 07:11
Got the same issue suddenly in github actions

**Comment by poldixd** [comment] 2024-07-19 07:15
Same issue here:

```
$ npm ci
npm error Exit handler never called!
npm error This is an error with npm itself. Please report this error at:
npm error   <https://github.com/npm/cli/issues>
npm error A complete log of this run can be found in: /root/.npm/_logs/2024-07-19T07_12_14_[34](https://XXXXXXXXX)7Z-debug-0.log
$ npm run build
> build
> vite build
sh: 1: vite: not found
```

Using Gitlab Runner 17.2.0 on a self hosted instance with docker image `node:22`.

**Comment by pietrykovsky** [comment] 2024-07-19 07:19
same here

workflow config
```yml
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint
```

package.json
```json
{
  "name": "portfolio",
  "version": "1.3.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@tsparticles/react": "^3.0.0",
    "@tsparticles/slim": "^3.4.0",
    "bootstrap": "^5.3.3",
    "next": "14.2.4",
    "next-intl": "^3.15.3",
    "nodemailer": "^6.9.14",
    "react": "^18",
    "react-bootstrap": "^2.10.3",
    "react-dom": "^18",
    "react-google-recaptcha": "^3.1.0",
    "react-icons": "^5.2.1",
    "react-pdf": "^9.1.0",
    "typewriter-effect": "^2.21.0"
  },
  "devDependencies": {
    "eslint": "^8",
    "eslint-config-next": "14.2.4"
  }
}
```

Install dependencies step:
```sh
Run npm ci
  
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v[4](https://github.com/pietrykovsky/portfolio/actions/runs/10004105702/job/27652183338?pr=14#step:4:4) are no longer supported
npm warn deprecated npmlog@5.0.1: This package is no longer supported.
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated gauge@3.0.2: This package is no longer supported.
npm warn deprecated are-we-there-yet@2.0.0: This package is no longer supported.
npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm warn deprecated @humanwhocodes/config-array@0.11.1[4](https://github.com/pietrykovsky/portfolio/actions/runs/10004105702/job/27652183338?pr=14#step:4:5): Use @eslint/config-array instead
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm error Exit handler never called!
npm error This is an error with npm itself. Please report this error at:
npm error   <https://github.com/npm/cli/issues>
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2024-07-19T07_12_1[5](https://github.com/pietrykovsky/portfolio/actions/runs/10004105702/job/27652183338?pr=14#step:4:6)_242Z-debug-0.log
```

Run linter step:
```sh
Run npm run lint
  npm run lint
  shell: /usr/bin/bash -e {0}
  
> portfolio@1.3.0 lint
> next lint
sh: 1: next: not found
Error: Process completed with exit code 1[2](https://github.com/pietrykovsky/portfolio/actions/runs/10004105702/job/27652183338?pr=14#step:5:2)7.
```

**Comment by tanusharma10** [comment] 2024-07-19 07:22
Same issue we are facing, any work around?

**Comment by IgorOhrimenko** [comment] 2024-07-19 07:31
Yes, just replace from node:22 to node:22.4.

**Comment by pietrykovsky** [comment] 2024-07-19 07:31
actually this issue has been reported earlier - https://github.com/npm/cli/issues/7657

the workaround for this is to change the `node-version` to older version. in my case it was to change from `node-version: '22.x'` to `node-version: '22.3.x'`

**Comment by tanusharma10** [comment] 2024-07-19 07:35
hey, I am using  node:bookworm-slim

**Comment by pietrykovsky** [comment] 2024-07-19 07:36
just use the image with older node version <= 22.4.x

**Comment by tanusharma10** [comment] 2024-07-19 07:37
this will affect build size right?

**Comment by pietrykovsky** [comment] 2024-07-19 07:40
there might be few mb of difference, try node:22.3.0-bookworm-slim

**Comment by tanusharma10** [comment] 2024-07-19 07:54
thanks  all that worked.

**Comment by mohammedshine17** [comment] 2024-07-19 08:15
> ```yaml
>  name: Use Node.js
>       uses: actions/setup-node@v4
>       with:
>         node-version: '22.x'
> ```

how to do that ? please help?

**Comment by nandeshwarshubh** [comment] 2024-07-19 08:43
Coming for our organization too on GCP!

**Comment by melroy89** [comment] 2024-07-19 09:28
Duplicate of: https://github.com/npm/cli/issues/7657?

**Comment by joydeep-php-developer** [comment] 2024-07-19 09:55
I am using node:22-alpine in Dockerfile and facing pm error Exit handler never called. Which version is to use

**Comment by akienz** [comment] 2024-07-19 09:57
> I am using node:22-alpine in Dockerfile and facing pm error Exit handler never called. Which version is to use

node:22.4-alpine3.19 seems to work at the moment

**Comment by joydeep-php-developer** [comment] 2024-07-19 10:31
> > I am using node:22-alpine in Dockerfile and facing pm error Exit handler never called. Which version is to use
> 
> node:22.4-alpine3.19 seems to work at the moment

thanks ...its working

**Comment by HagegeR** [comment] 2024-07-19 10:37
I restricted the max version in my package.json to fix it:
```
"engines": {
    "node": ">=22.2.0 <22.5.0"
  },
```

**Comment by AleksaRistic216** [comment] 2024-07-19 10:50
Looks like new node image 22.5 have bug in it. Work around would be changing `FROM node:22-alpine` to `FROM node:22.4-alpine` in all places in `Dockerfile`

**Comment by milaninfy** [comment] 2024-07-19 12:22
Closing Seems similer if not duplicate of https://github.com/npm/cli/issues/7657.
Try with node 22.4.1 with npm 10.8.2.

**Closed as completed by milaninfy** 2024-07-19 12:22 UTC
Labels: Bug, Needs Triage

**Comment by avijit-shihaan** [comment] 2024-07-19 20:06
I have changed the node version to 20, issue resolved
FROM node:20-alpine AS builder

**Comment by vinniespina** [comment] 2024-07-22 18:18
[](url)
