### ISSUE TITLE
[BUG] Modules run via npx interpret strings that look like environment variables

### ISSUE THREAD

**Issue by YodaDaCoda** [npm/cli#3600] opened 2021-08-03 04:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`npm exec` is interpreting argv strings that look like environment variables. Passing, for example, `test$param` results in `test` being passed to the module (because `param` is not defined in the environment).

### Expected Behavior

Strings passed should not be interpreted.

### Steps To Reproduce

1. Issue occurs with this environment:
`npm` >=v7.1.0.
Earlier versions are unaffected.
Installed `node` version doesn't appear to matter (tested with various v14/v15/v16 releases)

2. With this config
a file in `node_modules/.bin/testington` with this content:
```javascript
#!/usr/bin/env node
console.log(process.argv[2]);
```

3. Run '...'

Note proper quotes used to avoid bash interpreting the string.
```shell
$ npm exec testington 'test$param'
test
```
```shell
$ export param=asdf
$ npm exec testington 'test$param'
testasdf
```

4. See error...

Note that npx intereprets environment variables within the string before they reach the module.

### Environment

- OS: Ubuntu 20.04
- Node: v16.6.0
- npm: 7.1.0

**Comment by ljharb** [comment] 2021-08-03 04:50
Are you sure that’s not your shell doing it?

**Comment by YodaDaCoda** [comment] 2021-08-03 06:20
Positive. This snippet from my console demonstrates the behaviour change. I'm using volta for convenience bisecting, but I am able to replicate this on systems without volta.

```shell
$ volta install npm@7.1.0
success: installed and set npm@7.1.0 as default
$ npx --version
7.1.0
$ npx testington 'test$param'
test
$ volta install npm@7.0.15
success: installed and set npm@7.0.15 as default
$ npx --version
7.0.15
$ npx testington 'test$param'
test$param
```

EDIT: or, if it is the shell interpreting it, it's because npm/npx is passing around the params in an unsafe way.

**Comment by egorkel-da14** [comment] 2021-08-04 11:31
I have similar problem with setting firebase functions config.
When I execute `npx firebase functions:config:set settings.var='abc$123'` then `settings.var='abc'`
If I use `firebase functions:config:set settings.var='abc$123'` (without npx) then `settings.var='abc$123'`
My npx version 7.20.3

**Comment by wraithgar** [comment] 2022-03-16 14:43
**Closing:** this looks to be similar if not a duplicate of an existing issue, #3600. If you believe your instance is unique, please provide further clarifying details.

**Closed as completed** 2022-06-21 18:38 UTC
Labels: Release 7.x, Bug, Priority 2
