### ISSUE TITLE
[BUG] npm install can potentially delete .git directory

### ISSUE THREAD

**Issue by MylesBorins** [npm/cli#1641] opened 2020-08-07 20:33 UTC
This behavior is only reproducible with a specific version of `resolve`, but it is only reproducible on npm 7. I'm pretty sure the deletion of the .git folder is an unfortunate side effect of a missing dependency causing unexpected behavior in `safe-publish-latest`. This behavior is happening independent of `--legacy-peer-deps`

### Current Behavior:
npm install fails with the error `Error: Cannot find module 'camelcase'`, bails, and the .git folder is deleted

### Expected Behavior:
Modules to be installed and .git folder to not be affected.

### Steps To Reproduce:

This will permanently damage the repo so please do it in a fresh install

```bash
$ git clone https://github.com/browserify/resolve.git
$ cd resolve
$ git checkout v1.17.0
$ npm install
```

### Environment:
OSX 10.15.6
Node.js v14.6.0
npm v7.0.0-beta.2

**Comment by ljharb** [comment] 2020-08-07 20:54
for the record, safe-publish-latest has a dep on yargs 7, which depends on camelcase.

**Comment by MylesBorins** [comment] 2020-08-07 22:46
A couple notes before I vanish for the weekend. This bug is unrelated to any of the scripts being run by the package and with a bit of poking I've managed to find even stranger behavior... npm seems to be bringing folder back FROM THE DEAD

```bash
$ git clone https://github.com/browserify/resolve.git
$ cd resolve
$ git checkout v1.17.0
$ rm -rf .git
$ rm -rf test/
$ rm -rf examples/
$ git init
$ git add .
$ git commit -m "Seriously wat"
$ npm install
```

You will notice that not only is the .git folder blown away, but test/ and examples/ is restored... something I can't for the life of me figure out how or why is happening.

**Comment by isaacs** [comment] 2020-08-09 21:49
Ooh, this is a fun one.  Note that it only happens if the folder is named `resolve`.

For some reason, it's trying to reify the published `resolve` version over the root node of the project.  That's not supposed to happen :)

**Comment by isaacs** [comment] 2020-08-10 01:04
Root cause: https://github.com/npm/arborist/commit/909651d042f3f7912f7a1a9f2b47d3676249de6f

**Comment by isaacs** [comment] 2020-08-10 01:06
Fixed in beta branch. 5fb217701c060e37a3fb4a2e985f80fb015157b9

**Closed as completed by isaacs** 2020-08-10 01:06 UTC
Labels: Release 7.x, Bug, Needs Triage

**Comment by hthetiot** [comment] 2022-07-07 17:36
It occurred to one of my developer on node 16.14.2 and npm 8.5.0.
We are investigating to reproduce.

**Comment by RobinAegerter** [comment] 2024-04-09 08:31
This is still an issue with node v20.10.0 and npm 10.5.0.
