### ISSUE TITLE
[BUG] NPM doesn't install peer dependencies

### ISSUE THREAD

**Issue by boojum** [npm/cli#3702] opened 2021-08-31 12:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm working on abstracting my linting configs into shareable ones. The repo can be found [here](https://gitlab.com/b00jum/playground-linting-configs/-/tree/beta). The Gitlab CI takes care of publishing packages to the NPM Registry (for example [@scheisse/stylelint-config-base](https://www.npmjs.com/package/@scheisse/stylelint-config-base)) just fine but when I try to install the configs in another project the `peerDependencies` are not being installed.

For example, here's the `packages/stylelint-config-base/package.json`:
```
{
  "name": "@scheisse/stylelint-config-base",
  "version": "1.0.0",
  "description": "Personal Stylelint configuration.",
  "keywords": [
    "stylelint",
    "css",
    "config"
  ],
  "homepage": "https://gitlab.com/b00jum/playground-linting-configs/-/blob/master/packages/stylelint-config-base#readme",
  "bugs": {
    "url": "https://gitlab.com/b00jum/playground-linting-configs/issues"
  },
  "repository": {
    "type": "git",
    "url": "https://gitlab.com/b00jum/playground-linting-configs.git",
    "directory": "packages/stylelint-config-base"
  },
  "license": "MIT",
  "author": "Tomasz Moskal <boojum@stercus-accidit.com> (https://stercus-accidit.com/)",
  "main": "index.js",
  "devDependencies": {
    "stylelint": "13.13.x",
    "stylelint-a11y": "1.2.x",
    "stylelint-color-format": "1.1.x",
    "stylelint-config-prettier": "8.0.x",
    "stylelint-config-standard": "22.0.x",
    "stylelint-order": "4.1.x",
    "stylelint-semantic-groups": "1.1.x",
    "stylelint-use-logical-spec": "3.2.x"
  },
  "peerDependencies": {
    "stylelint": "13.13.x",
    "stylelint-a11y": "1.2.x",
    "stylelint-color-format": "1.1.x",
    "stylelint-config-prettier": "8.0.x",
    "stylelint-config-standard": "22.0.x",
    "stylelint-order": "4.1.x",
    "stylelint-semantic-groups": "1.1.x",
    "stylelint-use-logical-spec": "3.2.x"
  },
  "publishConfig": {
    "access": "public"
  }
}
```

The `stylelint` and it's plugins are listed as both `peer-`, and `dev-` dependencies. Yet `npm` fails to install them and only `@scheisse/stylelint-config-base` is installed when I run `npm i`.

I'm using `npm v7.20.3`, and I was under the impression that it does install `peerDependencies` automatically?

### Expected Behavior

I  expect `peerDependencies` to be installed when I run `npm i -D @scheisse/stylelint-config-base`.

### Steps To Reproduce

0. Repo responsible for publishing packages to `npm` can be found [here](https://gitlab.com/b00jum/playground-linting-configs/-/tree/beta).
1. `mkdir -p foobar && cd $_`
2. `npm init -y`
3. `npm i -D @scheisse/stylelint-config-base`
4. Inspect `node_modules`: only `@scheisse/stylelint-config-base` is installed, and not its peer dependencies.

### Environment

- OS: Ubuntu 21.04
- Node: 16.7.0
- npm: 7.20.3

**Comment by ljharb** [comment] 2021-08-31 13:48
I’m not sure ^ and x can be used together. `13.13.x` is a range, and `^13.13.0` is a range.

**Comment by boojum** [comment] 2021-08-31 15:23
> I’m not sure ^ and x can be used together. `13.13.x` is a range, and `^13.13.0` is a range.

Thanks for the suggestion! I tried sticking to `13.13.x` range definition in all the packages (and amended the original issue to reflect this).  NPM still doesn't want install the `peerDependencies` :-(

**Comment by ljharb** [comment] 2021-08-31 15:32
Since it's gitlab, is there any chance that the gitlab registry's returned packument lacks the peer dep field?

**Comment by boojum** [comment] 2021-08-31 15:42
> Since it's gitlab, is there any chance that the gitlab registry's returned packument lacks the peer dep field?

I'm only hosting the monorepo on Gitlab, packages are published to the NPM Registy. Sorry for confusion, I clarified it in the original issue.

**Comment by kamarel** [comment] 2021-09-01 15:56
You can try out npm i @scheisse/stylelint-config-base --save. that worked for me

**Comment by billyjanitsch** [comment] 2021-09-02 20:33
>Inspect package.json: only stylelint is installed, and not its peer dependencies.

@boojum This is your issue. npm 7 does automatically install peer dependencies but, in doing so, it doesn't explicitly add them to package.json, so you shouldn't expect to see them there. This is consistent with the behavior for transitive dependencies in general. (If you `npm install foo` and `foo` depends on `bar`, both are installed but only `foo` is added to package.json.) You can confirm that the peer dependencies are installed by inspecting package-lock.json and/or node_modules.

**Comment by boojum** [comment] 2021-09-03 08:35
> You can try out npm i @scheisse/stylelint-config-base --save. that worked for me

@kamarel Hey, thanks for the tip! I just tried it, sadly peer deps are still not being installed.

**Comment by boojum** [comment] 2021-09-03 08:42
> > Inspect package.json: only stylelint is installed, and not its peer dependencies.
> 
> @boojum This is your issue. npm 7 does automatically install peer dependencies but, in doing so, it doesn't explicitly add them to package.json, so you shouldn't expect to see them there. This is consistent with the behavior for transitive dependencies in general. (If you `npm install foo` and `foo` depends on `bar`, both are installed but only `foo` is added to package.json.) You can confirm that the peer dependencies are installed by inspecting package-lock.json and/or node_modules.

@billyjanitsch Of course, you're absolutely right! The mistake is mine, not explaining the issue clearly enough. I agree that `npm i -D @scheisse/stylelint-config-base` shouldn't add `peerDependencies` to the `package.json`. Alas, it _should_ install them into `node_modules`. This is not happening in my case:
```sh
mkdir foobar && cd $_
npm init -y
npm i -D @scheisse/stylelint-config-base

# relevant part
tree node_modules

# output:
#node_modules
#└── @scheisse
#    └── stylelint-config-base
#        ├── CHANGELOG.md
#        ├── index.js
#        ├── LICENSE
#        ├── package.json
#        └── README.md
```

Please notice that there's not peer deps in `node_modules`. I amended the original issue to reflect this.

**Comment by lukekarrys** [comment] 2021-10-07 21:02
@boojum I wasn't able to reproduce this on `7.20.3` or `7.24.2`, except with the `--legacy-peer-deps` flag. Can you check if you have that set anywhere in your config? `npm config get legacy-peer-deps` should tell you if it's true or false.

**Comment by lukekarrys** [comment] 2021-10-20 20:21
I'm going to close this as I wasn't able to reproduce it and I suspect it is due to a `legacy-peer-deps` config value being set via `.npmrc` or a flag. If you can still reproduce this on the latest npm without that value, please reopen this!

**Closed as completed by lukekarrys** 2021-10-20 20:21 UTC
Labels: Awaiting Information, Release 7.x
