### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Lands-1203** [npm/cli#6486] opened 2023-05-22 09:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I use npm to execute any startup command or publish command related to the project, there will be stutters, but not on another computer. I have tried to reinstall node, use a different version, and initialize the .npmrc file. I turned off the git hook.
But once I have successfully executed a command for one project, any command for all other projects can be executed quickly.

### Expected Behavior

I hope npm can work properly.

### Steps To Reproduce

None

### Environment

windows os
```
; "user" config from C:\Users\Lenovo\.npmrc

@huize/:registry = "http://123.xx.xx.xx:4873/" 
//123.xx.xx.xx:4873/:_authToken = (protected) 
cache = "F:\\nodejs\\node_cache" 
prefix = "F:\\nodejs\\node_global" 
registry = "https://registry.npm.taobao.org/" 

; node bin location = F:\nodejs\node.exe
; node version = v16.20.0
; npm local prefix = C:\Users\Lenovo\Desktop\项目\npm\huize_react-components
; npm version = 9.6.7
; cwd = C:\Users\Lenovo\Desktop\项目\npm\huize_react-components
; HOME = C:\Users\Lenovo
; Run `npm config ls -l` to show all defaults.

; "publishConfig" from C:\Users\Lenovo\Desktop\项目\npm\huize_react-components\package.json
; This set of config values will be used at publish-time.

access = "public"
```

**Comment by Lands-1203** [comment] 2023-05-22 09:43
# npm -v
9.6.7

**Comment by Lands-1203** [comment] 2023-05-22 09:48
.npmrc

```
@huize/:registry= http://123.xxxx.xx.xx:4873/
//123.xxxx.xx.xx:4873/:_authToken="xxxxxxxx"
prefix=F:\nodejs\node_global
cache=F: \nodejs\node_cache
registry= https://registry.npm.taobao.org/
```

**Comment by ITZMEHIMANSHUKING** [comment] 2023-05-23 19:45
sha512-4LQrO8XIPkwgx2wanFZU5bCNmzB1dzTbDtgozDs2uqGLj0x1De97lOP3BFEtlsZDFOquwrJt0IHsjEFfgfDyVA==

**Comment by milaninfy** [comment] 2024-06-14 20:47
Information provided is not enough to reproduce the issue correctly, if I were to guess from the write up it would be like first time you are installing or running something has a network calls and data to fetch and it takes time, from second time it works faster, again this is just a guess without all the information and reproduction steps it's hard to tell what is an actual issue here. 
@Lands-1203  can you try replicating this problem on the latest version of `npm`? (ie. `npm i -g npm`)

**Comment by milaninfy** [comment] 2024-06-20 13:28
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.

**Closed as not planned by milaninfy** 2024-06-20 13:28 UTC
Labels: Bug
