### ISSUE TITLE
Error Response timeout while trying to fetch http://registry.npmjs.org/@angular%2fcli (over 30000ms)

### ISSUE THREAD

**Issue by HolySpirit777** [npm/cli#1185] opened 2020-04-21 04:09 UTC
I want to install the angular cli using **npm install @angular/cli** but a got an error saying that it could not fetch the data.

I have tried using both node js version 12 and 13 and also differents npm versions

- I dont use a proxy server.

- I dont use a vpn.

- My internet connection does not have any problem.

- I tried to uninstall node js, also erased the npm directory from Appdata and any other related directory to Node js

this is the log file:

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@angular/cli'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.2
4 verbose npm-session b1b30f92d1295fda
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for @angular/cli@latest Response timeout while trying to fetch http://registry.npmjs.org/@angular%2fcli (over 30000ms)
8 timing stage:rollbackFailedOptional Completed in 1ms
9 timing stage:runTopLevelLifecycles Completed in 30453ms
10 verbose type body-timeout
11 verbose stack FetchError: Response timeout while trying to fetch http://registry.npmjs.org/@angular%2fcli (over 30000ms)
11 verbose stack     at Timeout._onTimeout (C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\body.js:189:16)
11 verbose stack     at listOnTimeout (internal/timers.js:549:17)
11 verbose stack     at processTimers (internal/timers.js:492:7)
12 verbose cwd C:\repositorio
13 verbose Windows_NT 10.0.17763
14 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
15 verbose node v12.16.2
16 verbose npm  v6.14.4
17 error Response timeout while trying to fetch http://registry.npmjs.org/@angular%2fcli (over 30000ms)
18 verbose exit [ 1, true ]

**Comment by RiZKiT** [comment] 2020-04-22 13:43
Related to https://github.com/npm/cli/issues/1151, seems to be an issue with npm 6.14.*.

**Comment by HolySpirit777** [comment] 2020-04-22 13:53
@RiZKiT Thanks for the answer

**Comment by RiZKiT** [comment] 2020-04-22 14:06
Downgrading to 6.13.7 solved it for us.

**Comment by HolySpirit777** [comment] 2020-04-22 14:11
Downgrading to 6.13.7 also solved it for me.

**Comment by KhaledSamir** [comment] 2020-05-08 16:37
Same issue but this /npm/registry/typescript and downgrading to 6.13.7 solved the problem!

No need to increase the timeout in .npmrc or anything like that.

**Comment by AbuAbeer** [comment] 2020-05-10 03:36
same problem here

**Comment by AbuAbeer** [comment] 2020-05-10 23:20
how can i downgrade this?

**Comment by KhaledSamir** [comment] 2020-05-11 04:24
@AbuAbeer You just need to run " npm i npm@6.13.7 " or " npm I -g npm@6.13.7 " if you wanna this to be global version.

After that, just to make sure, run " npm -version " to see what version you are using.

Hope this helps!

**Comment by AbuAbeer** [comment] 2020-05-12 00:05
@KhaledSamir i tried this but getting same error..  Every time there is a new error whenever i try to install expo-cli... 
![Untitled-1 copy](https://user-images.githubusercontent.com/65098236/81623855-4bc8e280-9412-11ea-9259-1b7b81e01cd4.jpg)

**Comment by KhaledSamir** [comment] 2020-05-12 15:14
@AbuAbeer This error you're showing is different than what this thread is talking about. I would say check this issue: https://github.com/expo/expo/issues/1992 and see if it fixes that error.

**Comment by drwatsno** [comment] 2020-05-13 14:38
Faced the same issue while installing dependencies from a private registry.

npm ERR! Response timeout while trying to fetch https://nexus-new.tcsbank.ru/repository/npm-all/@typescript-eslint%2fparser (over 30000ms)

Endpoint is accessible. npm version is 6.14.4

**Comment by KhaledSamir** [comment] 2020-05-13 16:53
@drwatsno Please read the entire thread and suggestions before you report an issue. The solution is within the replies above.

**Comment by drwatsno** [comment] 2020-05-13 16:57
> @drwatsno Please read the entire thread and suggestions before you report an issue. The solution is within the replies above.

Solved it by downgrading npm to 6.13.4.

**Comment by AbuAbeer** [comment] 2020-05-13 23:11
> @AbuAbeer You just need to run " npm i npm@6.13.7 " or " npm I -g npm@6.13.7 " if you wanna this to be global version.
> 
> After that, just to make sure, run " npm -version " to see what version you are using.
> 
> Hope this helps!

Solved this by downgrading. Thanks a lot ..

**Comment by KhaledSamir** [comment] 2020-05-14 01:38
@drwatsno @AbuAbeer Glad to hear the problem is resolved! ;)

**Comment by WalterGaldamezWeb** [comment] 2020-05-22 16:39
Ese mismo problema tenia en la version 6.14.4 actualice a 6.14.5 y el problema se soluciono
npm install npm@latest -g

I had the same problem in version 6.14.4 updated to 6.14.5 and the problem was solved
npm install npm @ latest -g

**Comment by theodor85** [comment] 2020-05-26 08:55
Same problem while installing @vue/cli in docker node:12.16.3. The problem was solved by using node:14.3.0 container.

**Comment by brunopardim** [comment] 2020-06-02 11:35
Hello !
I have same problem, I don´t use proxy ou vpn and my connection is good. I trying the solutions on comments but doesn´t work.

node -v v12.17.0
npm -v 6.14.5

My angular instalation freezes on:

C:\Users\bruno>npm install -g @angular/cli
[ .................] / fetchMetadata: sill resolveWithNewModule which@1.3.1 checking installable status

**Comment by brunopardim** [comment] 2020-06-03 10:47
Tks team, I did install the angular an create a project, everything looks good !

**Comment by serkon** [comment] 2020-06-10 13:00
I have the same problem, but just getting this error at 2.5mb `@logo-software/theme` file sized package. Others (less sized packages) published without problem ...

npm -v
6.14.2


**NOTE:**
When updated to `npm install -g npm@latest` version then published successfully

npm -v
6.14.5

node -v
v13.11.0

**Comment by CollapsedMetal** [comment] 2020-06-15 22:32
Same here... Upgraded npm to **v6.14.5**. Problem fixed

**Comment by ayush0x00** [comment] 2020-08-06 10:38
You may need to check whether npm is up or not. Sometimes, npm is down and hence will result in ERROR 404. You can check the status of npm [here](https://status.npmjs.org/).

**Comment by Dinesh9418** [comment] 2020-08-08 07:27
i have a problem
npm ERR! Response timeout while trying to fetch https://registry.npmjs.org/typescript (over 30000ms)

**Comment by nirajkheria** [comment] 2020-08-27 19:22
I had the same error for npm version 6.14.4 and updating it to the latest version fixed the issue

**Comment by OskarUno** [comment] 2020-11-14 01:31
Hola, a mi pe paso um problema similar al instalar firebase y se soluciono con:

 npm install -g npm@latest

Graciassss

**Comment by darcyclarke** [comment] 2021-06-02 21:21
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 21:21 UTC
Labels: Release 6.x

**Comment by arhamabeer** [comment] 2021-07-29 12:43
Downgrading to npm version 6.13.7 worked for me.
