### ISSUE TITLE
 Installing packages (npm)...npm ERR! code ERR_SOCKET_TIMEOUT npm ERR! errno ERR_SOCKET_TIMEOUT

### ISSUE THREAD

**Issue by mbunix** [npm/cli#4553] opened 2022-03-11 09:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

npm ERR! network Invalid response body while trying to fetch https://registry.npmjs.org/postcss-import: Socket timeout
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bentex/.npm/_logs/2022-03-11T08_41_06_921Z-debug-0.log
✖ Package install failed, see above.
The Schematic workflow failed. See above.

### Expected Behavior

I expect to  create a new angular project  using the command ng new but seems theres a socket timeout each time i try 

### Steps To Reproduce

1. In this environment... linux distro parrotOs
2. With this config...
3. Run '...' ng new ..
4. See error...

### Environment

npm -v
8.3.1

$node -v
v17.4.0

 "user" config from /home/bentex/.npmrc

legacy-peer-deps = true 

; node bin location = /home/bentex/.nvm/versions/node/v17.4.0/bin/node

**Comment by oonsamyi** [comment] 2022-03-15 14:31
Same issue with npm 8.5.4

**Comment by mbunix** [comment] 2022-03-16 12:39
There's a problem with ng schematics npm parsing for v 8 > i dont't get it .

**Comment by donato95** [comment] 2022-03-16 15:20
Having the same issue with react no solution seems to work...

**Comment by nlf** [comment] 2022-03-17 18:25
closing as a duplicate of #3078

**Closed as completed by nlf** 2022-03-17 18:25 UTC
Labels: Release 8.x, Bug, Needs Triage

**Comment by ArmishMunir** [comment] 2022-04-28 06:56
I just had this issue and it helped changing timeouts:

npm config set fetch-retry-mintimeout 20000
npm config set fetch-retry-maxtimeout 120000

**Comment by shahdhairya51** [comment] 2022-06-24 19:29
> I just had this issue and it helped changing timeouts:
> 
> npm config set fetch-retry-mintimeout 20000 npm config set fetch-retry-maxtimeout 120000

This works .thankyou

**Comment by mod7ex** [comment] 2022-06-28 21:34
none of the above worked for me is there any other way ? i have tried eveyrthing in stackoverflow also
is it an issue related to ubuntu ?

**Comment by mihir1739** [comment] 2022-07-05 17:39
> is it an issue related to ubuntu ?

No..I am facing same issue in arch linux.

**Comment by mihir1739** [comment] 2022-07-05 17:40
> is it an issue related to ubuntu ?

No..I am facing same issue in arch linux.

**Comment by mod7ex** [comment] 2022-07-06 08:50
guys try [this](https://stackoverflow.com/questions/72442682/npm-err-code-err-socket-timeout-npm-err-network-socket-timeout/72793541#72793541) it helped many others

**Comment by mustafiz-rahman** [comment] 2022-07-26 10:55
> npm config set fetch-retry-maxtimeout 120000 npm config set fetch-retry-mintimeout 20000 

This worked for me

**Comment by mrdcvlsc** [comment] 2022-07-27 08:58
I have also encountered this error today with:

- **npm - 8.15.0**
- **node - v18.6.0**

I was trying out `npx create-react-app` for the first time, and this error keeps on occurring.

> I just had this issue and it helped changing timeouts:
> 
> npm config set fetch-retry-mintimeout 20000 npm config set fetch-retry-maxtimeout 120000

This one helped me... though I need to add commands and modify the values.

This is what I did:
```
npm config set fetch-retries 5
npm config set fetch-retry-mintimeout 600000
npm config set fetch-retry-maxtimeout 1200000
npm config set fetch-timeout 1800000
```
Seems overkill but It worked for me.

**Comment by hijal** [comment] 2022-07-28 16:44
I just had this issue solved by upgrading the npm package 8.13.2 -> 8.15.1

**Comment by svdilshan** [comment] 2022-07-31 14:16
My npm version is 8.15.1 but this error not fix .

**Comment by eyo25** [comment] 2022-08-04 03:06
> 

thanks man it worked for me too

**Comment by mahbub75** [comment] 2022-09-04 21:23
> I just had this issue and it helped changing timeouts:
> 
> npm config set fetch-retry-mintimeout 20000 npm config set fetch-retry-maxtimeout 120000

it work for me. thanks

**Comment by ranaPhero** [comment] 2022-09-08 07:22
v-8.5.0
Same issue with npm

**Comment by Noema-Zhao** [comment] 2022-09-30 10:46
> I have also encountered this error today with:
> 
> * **npm - 8.15.0**
> * **node - v18.6.0**
> 
> I was trying out `npx create-react-app` for the first time, and this error keeps on occurring.
> 
> > I just had this issue and it helped changing timeouts:
> > npm config set fetch-retry-mintimeout 20000 npm config set fetch-retry-maxtimeout 120000
> 
> This one helped me... though I need to add commands and modify the values.
> 
> This is what I did:
> 
> ```
> npm config set fetch-retries 5
> npm config set fetch-retry-mintimeout 600000
> npm config set fetch-retry-maxtimeout 1200000
> npm config set fetch-timeout 1800000
> ```
> 
> Seems overkill but It worked for me.

It worked for me when I'm installing firebase, only set maxtimeout and timeout 10 times longer.

**Comment by alikhaleghifar** [comment] 2023-01-09 06:59
it work for me. thanks

**Comment by LiuLiujie** [comment] 2023-01-09 16:36
Meet this problem today in a [job](https://github.com/ActionsTools/DockerImageBuilder/actions/runs/3869862949/jobs/6596431408) using Github Actions.

**Comment by HarshDeswal** [comment] 2023-02-17 03:37
> 

It worked for me. Thank you

**Comment by cverma61** [comment] 2023-03-20 05:03
Had the same issue.
This command worked for me.
`npm config set fetch-retry-maxtimeout 120000`

**Comment by tohagan** [comment] 2023-03-23 00:40
Same issue ... Turned out to be an issue with my local network connection that was slow.
I needed ... 

    $ npm config set fetch-retries 20

**Comment by reorx** [comment] 2023-03-29 09:32
What works for me is to set the wait time between retries to a smaller value:

```
npm config set fetch-retry-mintimeout 2000
```

by default its 20s, I think 2s is enough for me

**Comment by bzsky1** [comment] 2023-04-18 21:08
> > I have also encountered this error today with:
> > 
> > * **npm - 8.15.0**
> > * **node - v18.6.0**
> > 
> > I was trying out `npx create-react-app` for the first time, and this error keeps on occurring.
> > > I just had this issue and it helped changing timeouts:
> > > npm config set fetch-retry-mintimeout 20000 npm config set fetch-retry-maxtimeout 120000
> > 
> > 
> > This one helped me... though I need to add commands and modify the values.
> > This is what I did:
> > ```
> > npm config set fetch-retries 5
> > npm config set fetch-retry-mintimeout 600000
> > npm config set fetch-retry-maxtimeout 1200000
> > npm config set fetch-timeout 1800000
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Seems overkill but It worked for me.
> 
> It worked for me when I'm installing firebase, only set maxtimeout and timeout 10 times longer.

ouuuuuuuuugh thanks, for me too works only this

**Comment by Mopro007** [comment] 2023-05-01 11:46
> Having the same issue with react no solution seems to work...

same here

**Comment by Mopro007** [comment] 2023-05-01 12:36
I've been having this issue for  14 days !!!!!!!!
I tried every single solution I found  here !
I tried every single solution I found on  stackoverflow !!
I tried every single solution I found on  google !!!
I tried every single solution I got from chatGPT !!!!






AND
NON
OF
THEM
F*CKING
WORKED !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by bzsky1** [comment] 2023-05-01 22:09
> I've been having this issue for 14 days !!!!!!!! I tried every single solution I found here ! I tried every single solution I found on stackoverflow !! I tried every single solution I found on google !!! I tried every single solution I got from chatGPT !!!!
> 
> AND NON OF THEM F*CKING WORKED !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

mmm try to add one or two more 0  for :


npm config set fetch-retry-maxtimeout 1200000
npm config set fetch-timeout 1800000


in my case it was bc slow internet i think, this problem appeared when i move in new apt with slow internet so was needed to made fetch timeout bigger

**Comment by dopatraman** [comment] 2023-05-03 23:32
NB for 2023: None of these solutions work. I dont see how changing the max timeout will stop the timeout from happening. This seems to be an issue with the NPM registry.

**Comment by Ali-Aref** [comment] 2023-05-10 17:04
> I just had this issue and it helped changing timeouts:
> 
> npm config set fetch-retry-mintimeout 20000
> npm config set fetch-retry-maxtimeout 120000

Thanks man! this worked for me <3

**Comment by natainditama** [comment] 2023-06-15 06:07
> I just had this issue and it helped changing timeouts:
> 
> npm config set fetch-retry-mintimeout 20000 npm config set fetch-retry-maxtimeout 120000

Nice!!. thank you

**Comment by eyluldnz** [comment] 2023-08-28 19:23
This worked for me, thanks ....

**Comment by reven-erlangga** [comment] 2023-09-07 16:26
> I just had this issue and it helped changing timeouts:
> 
> npm config set fetch-retry-mintimeout 20000 npm config set fetch-retry-maxtimeout 120000

Thanks bro, this worked for me....

**Comment by rexjoseph** [comment] 2023-11-01 12:29
> What works for me is to set the wait time between retries to a smaller value:
> 
> ```
> npm config set fetch-retry-mintimeout 2000
> ```
> 
> by default its 20s, I think 2s is enough for me

thanks. this works as of Nov. 1 2023
