### ISSUE TITLE
[BUG] Upgrading a workspace package

### ISSUE THREAD

**Issue by petermikitsh** [npm/cli#2706] opened 2021-02-16 02:43 UTC
### Current Behavior:

Editing a workspace package.json file and running `npm install` from the root fails to update the package.

### Expected Behavior:

- New package version is installed

### Steps To Reproduce:

- Clone https://github.com/petermikitsh/learn-single-spa/tree/853f1d4408ba8f1e466ab3057e5f32092ab5efc6
- Manually perform a version bump in a workspace `packages/root-app/package.json`. Ex: upgrade gh-pages from "2.2.0" to "^3.1.0".

```diff
--- a/packages/root-app/package.json
+++ b/packages/root-app/package.json
@@ -25,7 +25,7 @@
     "eslint-config-prettier": "^7.0.0",
     "eslint-config-ts-important-stuff": "^1.1.0",
     "eslint-plugin-prettier": "^3.2.0",
-    "gh-pages": "2.2.0",
+    "gh-pages": "^3.1.0",
     "husky": "^4.3.5",
     "jest": "^26.6.3",
     "jest-cli": "^26.6.3",
```
- Run `npm install` from root of workspace
- Observe installed package version does not change

Here's the lockfile diff:

```diff
diff --git a/package-lock.json b/package-lock.json
index 12818de..edcac09 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -34379,7 +34379,7 @@
         "eslint-config-prettier": "^7.0.0",
         "eslint-config-ts-important-stuff": "^1.1.0",
         "eslint-plugin-prettier": "^3.2.0",
-        "gh-pages": "2.2.0",
+        "gh-pages": "^3.1.0",
         "husky": "^4.3.5",
         "jest": "^26.6.3",
         "jest-cli": "^26.6.3",
@@ -39639,7 +39639,7 @@
         "eslint-config-prettier": "^7.0.0",
         "eslint-config-ts-important-stuff": "^1.1.0",
         "eslint-plugin-prettier": "^3.2.0",
-        "gh-pages": "2.2.0",
+        "gh-pages": "^3.1.0",
         "husky": "^4.3.5",
         "jest": "^26.6.3",
         "jest-cli": "^26.6.3",
@@ -39657,8 +39657,7 @@
       },
       "dependencies": {
         "gh-pages": {
-          "version": "2.2.0",
-          "resolved": "https://registry.npmjs.org/gh-pages/-/gh-pages-2.2.0.tgz",
+          "version": "https://registry.npmjs.org/gh-pages/-/gh-pages-2.2.0.tgz",
           "integrity": "sha512-c+yPkNOPMFGNisYg9r4qvsMIjVYikJv7ImFOhPIVPt0+AcRUamZ7zkGRLHz7FKB0xrlZ+ddSOJsZv9XAFVXLmA==",
           "dev": true,
           "requires": {
```

### Environment:

- OS: Mac OS X
- Node: v14.15.4
- npm: 7.5.4

**Comment by petermikitsh** [comment] 2021-02-16 02:52
> For `npm@7.0.x` alone the best way to handle them is manually editing the package.json for each child workspace and run npm install from the top-level 😊

https://github.com/npm/cli/issues/2036#issuecomment-716762752

@ruyadorno Has this workflow changed between 7.0.x and 7.5.4?

**Comment by ruyadorno** [comment] 2021-02-25 23:33
I tried a simplified reproduction and it doesn't seem to be a problem with updating the ranges in a nested workspace `package.json`, here's what it looks like:

```sh
$ cat package-lock.json
{
  "name": "test-upgrade-dep-version-in-workspace",
  "version": "1.0.0",
  "lockfileVersion": 2,
  "requires": true,
  "packages": {
    "": {
      "version": "1.0.0",
      "workspaces": [
        "a"
      ]
    },
    "a": {
      "version": "1.0.0",
      "dependencies": {
        "abbrev": "1.0.3"
      }
    },
    "node_modules/a": {
      "resolved": "a",
      "link": true
    },
    "node_modules/abbrev": {
      "version": "1.0.3",
      "resolved": "https://registry.npmjs.org/abbrev/-/abbrev-1.0.3.tgz",
      "integrity": "sha1-qgScln+ZkiKqQuFENPDFYu9GgkE=",
      "engines": {
        "node": "*"
      }
    }
  },
  "dependencies": {
    "a": {
      "version": "file:a",
      "requires": {
        "abbrev": "1.0.3"
      }
    },
    "abbrev": {
      "version": "1.0.3",
      "resolved": "https://registry.npmjs.org/abbrev/-/abbrev-1.0.3.tgz",
      "integrity": "sha1-qgScln+ZkiKqQuFENPDFYu9GgkE="
    }
  }
}
$ cat package.json
{
  "name": "test-upgrade-dep-version-in-workspace",
  "version": "1.0.0",
  "workspaces": [
    "a"
  ]
}
$ cat a/package.json
{
  "name": "a",
  "version": "1.0.0",
  "dependencies": {
    "abbrev": "1.0.3"
  }
}
```

By bumping the version range of `abbrev` to `^1.1.1` within `a/package.json` and running `npm install` again I get the following changes (as expected):

```patch
diff --git a/a/package.json b/a/package.json
index b9b716d..7a2d0d4 100644
--- a/a/package.json
+++ b/a/package.json
@@ -2,6 +2,6 @@
   "name": "a",
   "version": "1.0.0",
   "dependencies": {
-    "abbrev": "1.0.3"
+    "abbrev": "^1.1.1"
   }
 }
diff --git a/package-lock.json b/package-lock.json
index d79f079..3a10005 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -14,7 +14,7 @@
     "a": {
       "version": "1.0.0",
       "dependencies": {
-        "abbrev": "1.0.3"
+        "abbrev": "^1.1.1"
       }
     },
     "node_modules/a": {
@@ -22,25 +22,22 @@
       "link": true
     },
     "node_modules/abbrev": {
-      "version": "1.0.3",
-      "resolved": "https://registry.npmjs.org/abbrev/-/abbrev-1.0.3.tgz",
-      "integrity": "sha1-qgScln+ZkiKqQuFENPDFYu9GgkE=",
-      "engines": {
-        "node": "*"
-      }
+      "version": "1.1.1",
+      "resolved": "https://registry.npmjs.org/abbrev/-/abbrev-1.1.1.tgz",
+      "integrity": "sha512-nne9/IiQ/hzIhY6pdDnbBtz7DjPTKrY00P/zvPSm5pOFkl6xuGrGnXn/VtTNNfNtAfZ9/1RtehkszU9qcTii0Q=="
     }
   },
   "dependencies": {
     "a": {
       "version": "file:a",
       "requires": {
-        "abbrev": "1.0.3"
+        "abbrev": "^1.1.1"
       }
     },
     "abbrev": {
-      "version": "1.0.3",
-      "resolved": "https://registry.npmjs.org/abbrev/-/abbrev-1.0.3.tgz",
-      "integrity": "sha1-qgScln+ZkiKqQuFENPDFYu9GgkE="
+      "version": "1.1.1",
+      "resolved": "https://registry.npmjs.org/abbrev/-/abbrev-1.1.1.tgz",
+      "integrity": "sha512-nne9/IiQ/hzIhY6pdDnbBtz7DjPTKrY00P/zvPSm5pOFkl6xuGrGnXn/VtTNNfNtAfZ9/1RtehkszU9qcTii0Q=="
     }
   }
 }

```

**Comment by ruyadorno** [comment] 2021-02-25 23:36
@petermikitsh I suspect that in your original example the results might be a bit misleading given the fact that `gh-pages` is a dependency of many (if not all) workspaces AND the top-level `package.json` - maybe it's worth bumping all versions to the same version range and trying to run the install again?

**Comment by rkclark** [comment] 2021-03-04 14:01
My team is using npm 7 with workspaces, and whenever we pull down changes that include package upgrades at the root level, we have to manually remove our node_modules and re-install from scratch to get the upgraded versions to install 😢

**Comment by gijun19** [comment] 2021-05-25 23:20
I believe I was able to reproduce this error today @ruyadorno 

```bash
cat package.json

{
  "name": "test-workspace-deps-upgrade",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "workspaces": [
    "workspace-a"
  ],
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/gimli01/test-workspace-deps-upgrade.git"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/gimli01/test-workspace-deps-upgrade/issues"
  },
  "homepage": "https://github.com/gimli01/test-workspace-deps-upgrade#readme"
}
cat workspace-a/package.json
{
  "name": "workspace-a",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "gh-pages": "^2.2.0"
  }
}
```

`workspace-a` gets properly symlinked to the root project directory when running `npm install`. updating `workspace-a/package.json` and bumping to `gh-pages@3` from the workspace directory works. but am i incorrect in assuming here that from the root project directory `npm install gh-pages@3 --workspace=workspace-a` should update `workspace-a/package.json` and run `npm install` for the workspace?

if i `cd workspace-a && npm install gh-pages@3` works as expected
however, running `npm install gh-pages@3 --workspace=workspace-a` yields no changes.

**Comment by gijun19** [comment] 2021-05-27 22:53
@petermikitsh @rkclark

I can confirm this was an issue in version `7.5.4`. I had the same issue in a test repo I created.

I believe this is fixed in the most recent release of the CLI `7.15.0`. Can you please retry after running `npm i -g npm@latest` and see if that fixes the issue? 

```bash
npm i -g npm@7.15.0
```

Using the latest version of the CLI the results were as expected and running `npm install` from the root did in fact upgrade the workspace dependency in both `package.json` and `package-lock.json`

@darcyclarke

**Comment by rkclark** [comment] 2021-05-28 07:31
@gimli01 Hey! Thanks for the message. It seems to be working well for me on the version you mentioned. Will ask my entire team to upgrade and keep an eye on it 👍

**Closed as completed** 2021-05-28 16:12 UTC
Labels: Release 7.x, Bug, Priority 1

**Comment by maksnester** [comment] 2024-07-03 12:03
I still observe the same issue in npm v10.8.1

If I just edit some workspace's package.json

```diff
"name": "@my/workspace-package"
"dependencies": {
-  "foo": "1.1.1"
+  "foo": "6.6.6"
``` 

 and then do `npm i` from the root – I still have the locally installed versions to be the old version instead of the new one. 

Actually, nothing works for me to properly update the versions except doing this

```
npm remove foo -w @my/workspace-package 
npm i foo -S -w @my/workspace-package@6.6.6
```

or

```
rm -rf node_modules && npm i
```

This is quite annoying... 

---

OS: Mac OS 14.5 (23F79)
Node: v18.18.0
npm: v10.8.1
