### ISSUE TITLE
[BUG] installing a dependency in a package with a peer dependency changes the peerDependencies field

### ISSUE THREAD

**Issue by targos** [npm/cli#3096] opened 2021-04-18 08:19 UTC
### Current Behavior:

If you have a package with `something` in `peerDependencies` and then install that something in the same package as a devDependency, the peerDependencies field is changed and the dependency is added to `package.json`, but it inherits the semver string that the peer dependency had.

### Expected Behavior:

Installing a dev dependency should do the same change to the `package.json`, whether that dependency is already in `peerDependencies` or not.

### Steps To Reproduce:

```console
echo '{ "peerDependencies": { "typescript": "*" } }' > package.json
npm i -D typescript
cat package.json
```

```json
{"peerDependencies":{"typescript":"^4.2.4"},"devDependencies":{"typescript":"*"}}
```

### Environment:

- OS: macOS
- Node: 15.14.0
- npm: 7.10.0

**Comment by wraithgar** [comment] 2021-04-28 18:49
Closing this as a duplicate of https://github.com/npm/cli/issues/2647, as it's the same root cause.

**Closed as completed by wraithgar** 2021-04-28 18:49 UTC
Labels: Release 7.x, Bug, Needs Triage
