### ISSUE TITLE
[BUG] DeprecationWarning for git+ssh:// dependencies

### ISSUE THREAD

**Issue by shivamconan** [npm/cli#7839] opened 2024-10-16 09:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

We are facing [DEP0170](https://github.com/npm/cli/issues/6869) behavior in latest NPM.

```
{
  "dependencies": {
    "something-private": "git+ssh://git@<url>.example.com:group/project.git#commitish"
  }
}
```

throws - The URL <url>  is invalid. Future versions of Node.js will throw an error.

### Expected Behavior

URL should work as mentioned in [documentation](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#git-urls-as-dependencies)?

### Steps To Reproduce

Install npm 10.9.0
Install node 22.9.0
Specify a dependency as mentioned above
`yarn install`

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by milaninfy** [comment] 2024-10-17 13:50
Are you doing `yarn install` or `npm install` ?

**Comment by milaninfy** [comment] 2024-10-30 12:01
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.

**Closed as not planned by milaninfy** 2024-10-30 12:01 UTC
Labels: Bug, Needs Triage
