### ISSUE TITLE
[BUG] NPM deletes project files referenced by devDependencies when --production is used

### ISSUE THREAD

**Issue by cwilliamsonslyp** [npm/cli#2863] opened 2021-03-15 02:44 UTC
[npmBug.zip](https://github.com/npm/cli/files/6138471/npmBug.zip)
### Current Behavior:
When `npm i --production` is called, all project files referenced in devDependencies are deleted

### Expected Behavior:
npm doesn't delete our project files

### Steps To Reproduce:
1. Run `npm i --production` in the `main` directory of the attached zip. 
2. The `dependencies` folder will be deleted as a result of step 1

### Environment:
- OS: MacOS Catalina 10.15.7
- Node: 14.7.0
- npm: 7.6.3

**Comment by ssc-hrep3** [comment] 2021-03-15 17:24
When referencing local `devDependencies` in a project (`"project-a": "file:../project-a"`) and installing the dependencies with `npm install --only=production`, all symlinked folders are deleted (the actual folders, not only the symlink). This happens in `npm@7.6.3`.

Is there a workaround for this issue (e.g. something like `--skip-cleaning`)? Or is this on the road map? It is a blocker in our project.

**Comment by wraithgar** [comment] 2021-03-26 18:16
This is technically a duplicate of #2889 because both commands go through `arborist.reify`.  closing this in favor of the other issue.

**Closed as completed by wraithgar** 2021-03-26 18:16 UTC
Labels: Release 7.x, Bug, Needs Triage
