### ISSUE TITLE
[BUG] postinstall scripts not executed during `npm install`

### ISSUE THREAD

**Issue by AlCalzone** [npm/cli#2467] opened 2021-01-09 11:50 UTC
### Current Behavior:
postinstall script not executed

### Expected Behavior:
postinstall script should be executed.

### Steps To Reproduce:
1. Set up a VM you can trash later (the package modifies your global configuration)
2. Create directory `/opt/iobroker`, enter it
3. run `npm i iobroker@latest` as root

### Environment:
- OS: Debian Buster
- Node: 15.5.1
- npm: 7.3.0

**Comment by ljharb** [comment] 2021-01-09 15:31
Duplicate of #2194?

**Comment by Apollon77** [comment] 2021-01-09 17:11
@ljharb not really because here it is not about global packages, or? but yes maybe related :-)

**Comment by ljharb** [comment] 2021-01-09 17:17
Are you sure the script isn’t being executed? All output of postinstall scripts is suppressed in npm 7 unless the script fails.

**Comment by Apollon77** [comment] 2021-01-09 17:21
Yes we are sure because many things happen there in the example of the above case and nothing of this is done

**Comment by darcyclarke** [comment] 2021-01-15 19:29
Hey @AlCalzone, this does look to be like a duplicate (ie. potentially you are just not seeing output when scripts are run). We just tested this to see if postinstall scripts are working & they seem to be. I've posted a comment back here for some other context (ie. running with the `--foreground-scripts` flag or changing your `loglevel` should show output similar to v6): https://github.com/npm/cli/issues/2194#issuecomment-761140318 

Let us know if you think your scripts still aren't being run as of `v7.4.1`

**Closed as completed by darcyclarke** 2021-01-15 19:29 UTC
Labels: Release 7.x, Bug

**Comment by AlCalzone** [comment] 2021-01-15 20:44
@darcyclarke It seems like the underlying issue is something different. Our postinstall script does indeed run, but it modifies package.json, so we can install additional dependencies dynamically in the next install step. This used to work in npm6, but now the changes get overwritten later, causing the followup installation steps to be skipped.
