### ISSUE TITLE
NPX create-react-app error on install

### ISSUE THREAD

**Issue by Abdulhadi5692HDI** [npm/cli#3778] opened 2021-09-20 19:19 UTC
The error is that it occured in npm itself

**Comment by ljharb** [comment] 2021-09-20 19:21
Please fill out the entire issue template.

**Comment by Abdulhadi5692HDI** [comment] 2021-09-20 19:21
Logfile:
[2021-09-20T19_13_16_729Z-debug.log](https://github.com/npm/cli/files/7198196/2021-09-20T19_13_16_729Z-debug.log)

**Comment by lukekarrys** [comment] 2021-09-23 00:06
**Closing:** please use our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).

It also looks like this might be a duplicate of #3765. You can try some of the workarounds suggested in that issue.

**Closed as completed by lukekarrys** 2021-09-23 00:06 UTC
Labels: Duplicate

**Comment by Abdulhadi5692HDI** [comment] 2021-11-01 19:25
@lukekarrys I looked in that issue and didnt find anything then i tried again and same error.
Try looking into npx and npm's code
