### ISSUE TITLE
npm install is failing with error "Exit handler never called!"

### ISSUE THREAD

**Issue by sakkukasetty** [npm/cli#5040] opened 2022-06-18 20:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

In  CI/CD npm install is failing with error  
![image](https://user-images.githubusercontent.com/52789643/174551554-40c87569-20d6-40b6-b3e3-e69bb4d997df.png)
 reproduced same in my local machine 

i tried the following scenarios 
Deletion of package-lock.json file 
Downgrading and upgrading node version 
Any sugesstion will be very helpful

### Expected Behavior

npm insall sucessfully

### Steps To Reproduce

1. In this environment... Github Actions:ubuntu-20.04.4 and windows
2. With this config...
3. Run :npm install
4. See error...

### Environment

- npm:npm: '8.12.2',
  node: '14.19.3',
- Node.js:
- OS Name: Ubuntu:20.04.4
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by nlf** [comment] 2022-06-23 19:01
we need more information to reproduce this. can you share your `package.json`? or if the repository is public that would be even better. we need something to show us what npm is trying to install, though.

**Comment by sakkukasetty** [comment] 2022-06-23 20:13
"devDependencies": {
    "@angular/cli": "~8.0.3",
    "commander": "^2.17.1",
    "fast-xml-parser": "^3.17.6",
    "gulp": "^4.0.0",
    "through2": "^2.0.3",
    "xml2js": "^0.4.19"
  },
  "dependencies": {
    "global": "^4.3.2",
    "grunt": "^1.0.3",
    "grunt-cli": "^1.3.2"
  }

**Comment by sakkukasetty** [comment] 2022-06-23 20:14
Above is the json we tried to install

**Comment by fritzy** [comment] 2022-06-30 07:08
@sakkukasetty this seems to be a different dependency graph, as your warnings included left-pad, but these dependencies don't produce that package in my dependency tree. This seems to be incomplete?

**Comment by lukekarrys** [comment] 2022-12-07 02:22
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.

**Closed as completed by lukekarrys** 2022-12-07 02:22 UTC
Labels: Awaiting Information, Release 8.x, Bug, Needs Triage
