### ISSUE TITLE
[BUG] npm link is not CI friendly

### ISSUE THREAD

**Issue by dcheung2** [npm/cli#1120] opened 2020-04-07 02:59 UTC
# What / Why
`npm link` has two way to use it.
First, `npm link` symlink current folder from global node_modules pool.
Second, `npm link module` symlink the matching module from global to local node_modules.

There is a shortcut from of above `npm link ../module` which is an alias to above.

This is causing global lib/node_module folder pollution in a shared, multi-process CI environment.

A naive lock around `npm link` will not work because the symlinks are always pointing to the global lib folder, which redirect to last `npm link`.

## When
Local development or CI 

## Where
* n/a

## How
* Having a Jenkins CI pipeline, multi-branch scan and build concurrently.
* multiple branch checkout (e.g. `git worktree`) local development

### Current Behavior
* These linked module folder messed up.

### Steps to Reproduce
* git clone https://github.com/npm/cli
* cd cli; worktree add ../cliCanary origin/canary
* cd ..; mkdir myModule; npm init; npm link ../cli
* cd ..; mkdir myModuleCanary; npm init; npm link ../cliCanary

### Expected Behavior
* myModule/node_modules/npm -> ../../cli
* myModuleCanary/node_modules/npm -> ../../cliCanary

## Who
* n/a

## References
* n/a

## Workarounds
* lerna, but it does not work well in many cases
* using 'file:../cliCanary' in monorepo
* Dev in docker
* buy two or more PCs
* manual creation of symlink (and break package-lock.json)

**Comment by shadowspawn** [comment] 2020-04-07 07:10
I think of `npm link` as a developer feature, so I would not expect to use it in CI environment.

From `npm help developers`

> Link Packages
       npm link is designed to install a development package and see the changes in real time without having to keep re-installing it.  (You do need to either re-link or npm rebuild -g to update compiled packages, of course.)

**Comment by dcheung2** [comment] 2020-04-07 07:11
CI environment is a developer feature

**Comment by shadowspawn** [comment] 2020-04-07 07:21
Ok. What I meant was I think of `npm link' as a feature a developer uses on their local computer, to try out changes in a module in a client of that module without needing to publish or package or reinstall. For myself, I maintain a library, and I create lots of test programs that require the library using a link. This is great for reproducing issues against the current code on my machine, and seeing if my fixes work as intended. I don't publish or commit anything with links, it is all just on my computer.

For interest, how is `npm link` being used in your CI environment?

**Comment by dcheung2** [comment] 2020-04-09 01:49
It is about monorepo and peer and non-peer dependency management.

e.g.
```
common_1
 \- ext_module_1
 \- ext_module_2
common_2
 \- ext_module_1
 \- ext_module_3
 \- react (peer)
private_module_3
\- common_1 (peer)
\- react (peer)
 \- ext_module_3
 \- ext_module_4 (v1)
private_module_4
\- common_1 (peer)
\- common_2 (peer)
\- react (peer)
 \- ext_module_4 (v2)
.....etc
private_app
\- corejs
\- polyfills
\- common_1
\- common_2
\- private_module_3
\- private_module_4
\- private_module_5
\- private_module_6
\- private_module_7
\- private_module_8
\- private_module_9
```

Background:
They are private closed source project and none will publish to npm.
There are some deduped dependency managed as peers, while some other, we allow them to happen as they are less harmful.

Current workaround:
Currently we are using lerna to link them.
However it doesn't update package-lock well, and break command e.g. npm audit, npm list.
I am hacking the package-lock by using `npm i --package-lock-only --legacy-bundling ../relative-path` but it is way too slow due to their size.

It won't work without lerna and use pure relative path dependency, npm install takes forever and dedupe incorrectly.

**Comment by wesleyboar-fka-iosulfur** [comment] 2020-04-22 06:15
If you have not already considered it, then know that it is possible to create a private NPM registry.

- [a short summary of options (and a suggestion) from Medium](https://medium.com/engenharia-noalvo/ways-to-have-your-private-npm-registry-and-a-final-diy-solution-eed001a88e74)
- [an NPM article (which assumes audience is NPM Enterprise users)](https://docs.npmjs.com/configuring-your-registry-settings-as-an-npm-enterprise-user)

_**Disclaimer**: I have not set up a private NPM registry, but considered it as a solution to reduce redundant bandwidth for builds of projects with many dependencies._

**Comment by dcheung2** [comment] 2020-04-22 07:25
(private) registry is a solution to deployment, to publishing.

It is not a solution for development and tests.

**Comment by richardeschloss** [comment] 2020-05-14 19:31
Hi @dcheung2, is "install link" something that will work for your situation?
```
npm install --link ../module
```

**Comment by dcheung2** [comment] 2020-05-15 01:34
Never tried,  what does it do? And different between  `npm install ../relative-path` ?

```
The --link argument will cause npm to link global installs into the local space in some cases.
```

**Comment by richardeschloss** [comment] 2020-05-15 02:36
From my experience in the past couple days, it seems to have been easier to work with. I find it particularly more useful than "npm link" if I already have "npm linked' " another folder I want to install into my  workspace because the "npm install" also picks up the nested depenencies.

So, here's an example. Suppose I have "moduleA" I was working on in one folder, but want to easily reuse that in "myApp" in another folder. Here's an important assumption: assume moduleA has many dependencies.

In moduleA folder, I would run "npm link" to create a symbolic link in the npm global path to point back to moduleA's folder (really, here, "npm link" is just syntatic sugar for "ln -s", but is meant to work cross-platforms).

Then, in "myApp" folder, because that moduleA has dependencies, I don't actually want to just create a symbolic link, because, from my experience, there will be a tough time trying to resolve moduleA's dependencies. In the local environment, you'd want to instead *install* moduleA (and whatever dependencies it has) but at the same time, you don't want to clobber your local workspace. So, instead of running "npm install", you run "npm install --link moduleA", and npm will make the best effort to create only symlinks when possible, but in my experience, it's also had to copy in some of the deps (i.e., if moduleA is already in the global node folder, it'll try to link to that). I think that's what the docs mean by "some cases"...it could probably be more descriptive there.

Even still though, "npm install --link", while not perfect, has helped reduced node_modules folder size for me. It also has the advantage that if you already have deps listed in package.json, running just "npm install --link" will install link those deps.

Wrap up:
For local: consider trying "npm install --link"
For CI / CD: consider sticking to "npm install" // and let the CI system deal with the node_modules.

**Comment by richardeschloss** [comment] 2020-05-17 04:43
I just came across this: https://github.com/npm/rfcs/blob/latest/accepted/0011-npm-link-changes.md

It seems like npm7 will rollout with the fixes that are desired.

**Comment by darcyclarke** [comment] 2021-06-02 22:07
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 22:07 UTC
Labels: Bug
