### ISSUE TITLE
[BUG] error cb() never called!

### ISSUE THREAD

**Issue by sabeelmuttil** [npm/cli#1166] opened 2020-04-16 15:42 UTC
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/13.12.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   'react-player'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v13.12.0
4 verbose npm-session 7a90fc0402509a7a
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 warn registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning undefined: network timeout at: https://registry.npmjs.org/react-player
8 warn registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
9 http fetch GET 200 https://registry.npmjs.org/react-player 160110ms (from cache)
10 timing npm Completed in 235562ms
11 error cb() never called!
12 error This is an error with npm itself. Please report this error at:
13 error <https://npm.community>

**Comment by isaacs** [comment] 2020-04-18 01:14
This is interesting.  I expect that the network timeout was a transient or unrelated problem, but it still shouldn't result in `cb() never called`.

**Comment by RiZKiT** [comment] 2020-04-22 13:32
Maybe duplicate of https://github.com/npm/cli/issues/417?

**Comment by halisogluiskender** [comment] 2020-04-24 08:35
I do not know if it is right to write here. But when installing a package with npm,(npm install -g gulp-cli)  I get the following error.

Microsoft Windows 10
node -v : v14.0.0
npm -v  : 6.14.4

`npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\İskender Halisoğlu\AppData\Roaming\npm-cache\_logs\2020-04-24T08_20_21_230Z-debug.log`

**Log File**
[2020-04-24T08_20_21_230Z-debug.log](https://github.com/npm/cli/files/4527631/2020-04-24T08_20_21_230Z-debug.log)

**Comment by halisogluiskender** [comment] 2020-04-26 13:12
> I do not know if it is right to write here. But when installing a package with npm,(npm install -g gulp-cli) I get the following error.
> 
> Microsoft Windows 10
> node -v : v14.0.0
> npm -v : 6.14.4
> 
> `npm ERR! cb() never called!
> 
> npm ERR! This is an error with npm itself. Please report this error at:
> npm ERR! https://npm.community
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\İskender Halisoğlu\AppData\Roaming\npm-cache_logs\2020-04-24T08_20_21_230Z-debug.log`
> 
> **Log File**
> [2020-04-24T08_20_21_230Z-debug.log](https://github.com/npm/cli/files/4527631/2020-04-24T08_20_21_230Z-debug.log)

Since the user is a Turkish character in my name, the problem may be due to this. It worked when I reset the system to factory settings and solve the character problem and try again.

**Comment by darcyclarke** [comment] 2021-06-02 21:25
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 21:25 UTC
Labels: Release 6.x, Bug
