### ISSUE TITLE
[BUG] E503 - 503 Publish error from Cloudflare protection

### ISSUE THREAD

**Issue by sayem314** [npm/cli#1292] opened 2020-05-14 17:18 UTC
# What / Why

It seems like npm registry `https://registry.npmjs.org/` turned on CF protection which is causing publish issue. I and some of my social friends are having the issue as well. Tested from several VPS as well and from residential IP.

## When

`npm publish`

## Where
  * npm public registry

### Current Behavior

Refusing to publish

### Expected Behavior

Should publish normally

## References

![npmjs-cf503](https://user-images.githubusercontent.com/14138401/81964745-d9861700-9638-11ea-8624-7cbfdc648cf1.png)

![image](https://user-images.githubusercontent.com/14138401/81964812-f1f63180-9638-11ea-807d-cad58a799423.png)

```
...
18 http fetch PUT 503 https://registry.npmjs.org/hooman 80485ms attempt #3
19 verbose stack Error: 503 Service Unavailable - PUT https://registry.npmjs.org/hooman - Service Unavailable
19 verbose stack     at /usr/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:104:15
19 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
20 verbose statusCode 503
...
```

**Comment by zhantewei2** [comment] 2020-05-15 07:54
Me too!

**Comment by sayem314** [comment] 2020-05-15 08:19
Today there is a new issue.

![image](https://user-images.githubusercontent.com/14138401/82028140-0f69e080-96b7-11ea-93f6-db18806a3cca.png)

**Comment by sayem314** [comment] 2020-05-15 15:36
UPDATE: Both issues are resolved now (I was able to publish with the same IP) but it's not completely gone, it seems to re-appears and fixed automatically. There should be a persistent fix.

**Comment by aosq** [comment] 2020-08-01 14:37
I'm able to reproduce this error consistently. I've been trying to publish my package [tree-sitter-hack](https://github.com/antoniodejesusochoasolano/tree-sitter-hack) and I get the same error every time. I'm able to publish the same package under a different name (I published it privately for testing).

I also tried publishing an empty test package and every time I add the word "hack" to the name, I get the same 503 error. The same package without the word "hack" publishes successfully.

```
18 http fetch PUT 503 https://registry.npmjs.org/tree-sitter-hack 75289ms attempt #3
19 verbose stack Error: 503 Service Unavailable - PUT https://registry.npmjs.org/tree-sitter-hack - Service Unavailable
19 verbose stack     at /Users/antoniodejesusochoasolano/.nvm/versions/node/v14.7.0/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:114:15
19 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:93:5)
20 verbose statusCode 503
21 verbose pkgid tree-sitter-hack@0.0.1
```

**Comment by antoniotorres** [comment] 2020-09-08 19:13
@antoniodejesusochoasolano I also removed the hack word from the name and was able to publish my package. 

homebridge-garage-door-hack -> [homebridge-garage-door-gpio](https://www.npmjs.com/package/@toniotgz/homebridge-garage-door-gpio).

**Comment by aosq** [comment] 2020-09-08 20:03
@antoniotorres nice! It would save people time and frustration if NPM would return a useful error message and publicly document that you can’t have the word “hack” in NPM packages.

Turns out you can have the word hack in certain some cases though. I ended up calling my package [tree-sitter-hacklang](https://www.npmjs.com/package/tree-sitter-hacklang).

**Comment by darcyclarke** [comment] 2021-06-02 22:12
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is reproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 22:12 UTC
Labels: Bug
