### ISSUE TITLE
[BUG] preinstall script

### ISSUE THREAD

**Issue by alliresan** [npm/cli#4544] opened 2022-03-10 16:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Hello,
I want to execute preinstall script BEFORE the dependencies of my project describes in package.json are downloads, but it doesn't occurs in:$ npm --version8.5.3
Thanks in advance

### Expected Behavior

Execution the preinstall script BEFORE any action of the install script

### Steps To Reproduce

npm install
The preinstall script defined in package JSON executes AFTER the dependencies are downloaded, NOT BEFORE.

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by wraithgar** [comment] 2022-03-14 14:14
Duplicate of https://github.com/npm/cli/issues/2660

**Closed as completed by wraithgar** 2022-03-14 14:14 UTC
Labels: Release 8.x, Bug, Needs Triage
