### ISSUE TITLE
Cannot install firebase package

### ISSUE THREAD

**Issue by buju18887** [npm/cli#6407] opened 2023-04-28 15:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Error is displayed when I run the command "npm i firebase"

### Expected Behavior

firebase package expected to download

### Steps To Reproduce

1. In terminal
2. With this config...
3. Run 'npm i firebase'
4. See error..'This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>'

### Environment

- npm: 9.6.4
- Node.js: 20.0.0
- OS Name: Windows 10 pro
- System Model Name: dell
- npm config:
```ini
; copy and paste output from `npm config ls` here
; "builtin" config from C:\Program Files\nodejs\node_modules\npm\npmrc

prefix = "C:\\Users\\dell\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v20.0.0
; npm local prefix = C:\Users\dell\Desktop\Node
; npm version = 9.6.4
; cwd = C:\Users\dell\Desktop\Node
; HOME = C:\Users\dell
```

**Comment by milaninfy** [comment] 2024-05-10 13:29
@buju18887  can you try replicating this problem on the latest version of `npm`? (ie. `npm i -g npm`)

**Comment by milaninfy** [comment] 2024-05-16 12:47
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.

**Closed as not planned by milaninfy** 2024-05-16 12:47 UTC
Labels: Bug, Needs Triage, Release 9.x
