### ISSUE TITLE
[QUESTION] how to update center of react-google-map

### ISSUE THREAD

**Issue by FaiqueAli** [npm/cli#1123] opened 2020-04-07 13:08 UTC
I am getting latlng by placesautocomplete and want to update the map center location using react hooks, I update map center using setCoordinate but center is not getting update..

   ```
const gmap = useRef(null);
const handleSelect = async value => {
    const results = await geocodeByAddress(value);
    const latLng = await getLatLng(results[0]);    
    setAddress(value);
    setCoordinates(latLng);
    gmap.current.center={ lat: latLng.lat, lng: latLng.lng };    
  };

<PlacesAutocomplete
                value={address}
                onChange={setAddress}
                onSelect={handleSelect}
                >  
                  {({getInputProps, suggestions,getSuggestionItemProps,loading})=>(
                  <div>
                    <p>Latitude: {coordinates.lat}</p>
                  <p>Longitude: {coordinates.lng}</p>
                    <input {...getInputProps({placeholder:"input address"})} /><br/>
                    <div >
                      {loading?<div>loading..</div>:null}
                      {suggestions.map(suggestion=>{
                        const style = {
                          backgroundColor: suggestion.active ? "#41b6e6" : "#fff"
                        };
                       
                  return(<div {...getSuggestionItemProps(suggestion, {style})}>
                          {suggestion.description}
                    
```    </div>);
                        
                      })}
                    </div>
                  </div>)}
          </PlacesAutocomplete>
<Map
                googleMapURL="https://maps.googleapis.com/maps/api/js?key=APIKEY"
                loadingElement={<div style={{ height: `50%` }} />}
                containerElement={<div style={{ height: `400px`,width:`50%` }} />}
                mapElement={<div style={{ height: `100%` }} />}
                center={coordinates?coordinates:{lat: latval, lng: lngval}}
                zoom={9}
                ref={gmap}
            />

**Comment by shadowspawn** [comment] 2020-04-08 07:13
You are not likely to get an answer here, since this project is for the npm cli.

You might want to look at https://github.com/google-map-react/google-map-react which has lots of examples and documentation.

**Comment by darcyclarke** [comment] 2021-06-02 22:07
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 22:07 UTC
Labels: Awaiting Information
