### ISSUE TITLE
[BUG] `npm install -g` creates a folder in the current dir with the literal name `${XDG_DATA_HOME}`

### ISSUE THREAD

**Issue by lgarron** [npm/cli#3581] opened 2021-07-27 08:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`npm install -g` creates a folder with the literal name `${XDG_DATA_HOME}` in the current directory, and treats it as the data home dir.

<img width="210" alt="127120221-54e6ec3d-4a4c-4cd7-ac98-12b7f6f40c12" src="https://user-images.githubusercontent.com/248078/127122075-f49be28e-e4b2-4af8-814b-d392f915c826.png">

Presumably something in the code is not escaping the variable properly under some conditions.

Note that I do have `$XDG_HOME_DIR` [in my dotfiles](https://github.com/lgarron/dotfiles/blob/720ee35b2ea2655e31bf480c7e803958e88e6b39/dotfiles/xdg-basedir-workarounds/.config/fish/xdg-basedir-workarounds.fish#L11) and [using `launchctl`](https://github.com/lgarron/dotfiles/blob/720ee35b2ea2655e31bf480c7e803958e88e6b39/dotfiles/mac-boot/.config/boot.fish#L12). I have not been able to avoid the bug by un-setting the var.

This did not use to happen until the last few days. Unfortunately, this is rather annoying to debug because the bug itself specifically breaks global `npm` installation. So I can't run `npm install -g npm@7.0.0` or `npm install -g npm@7.20.1` to get a proper install of another version, for example.

### Expected Behavior

The command uses the value of the `XDG_DATA_HOME` env var (or the default), without creating a dir named `${XDG_DATA_HOME}`.

### Steps To Reproduce

Run `npm install -g` or `npx`. For example:

```
npm install -g jq
```

Running `npx jq` also gives this error:

```
node:internal/modules/cjs/loader:930
  throw err;
  ^

Error: Cannot find module 'commander'
Require stack:
- /Users/lgarron/.cache/npm/_npx/db665b9ed68ddd8b/node_modules/jq/bin/jq
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:15)
    at Function.Module._load (node:internal/modules/cjs/loader:772:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/lgarron/.cache/npm/_npx/db665b9ed68ddd8b/node_modules/jq/bin/jq:7:15)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/lgarron/.cache/npm/_npx/db665b9ed68ddd8b/node_modules/jq/bin/jq'
  ]
}
```
I don't know how related it is, but it's what led me to observing the directory issue.

### Environment

npm 7.19.1
node v16.5.0
macOS 11.5

I know this report is not super helpful, but I could use some advice on how to debug this.
I've spent an hour in `@npmcli/config` to figure out where this is coming from, but it uses a lot of indirection to load configs. Most useful would probably be to bisect some packages, but I don't know how to do that when `npm install -g` is not working. (I tried to symlink `./${XDG_DATA_HOME}` to the appropriate global directory, but that doesn't seem to work.)

**Comment by lgarron** [comment] 2021-08-16 03:54
For what it's worth, I've been able to upgrade to `npm` `7.20.3`, and this is still an issue for me. 😔

**Comment by lgarron** [comment] 2021-08-31 08:25
I blew away my `node`/`npm` installs and all caches I could find. After reinstall I'm now getting: `Error: Failed to replace env in config: ${XDG_DATA_HOME}` :-/

**Comment by nlf** [comment] 2022-04-27 18:38
@lgarron sorry for the extremely long delay in getting back to you about this. can you share the output of `npm config ls`? i'd like to try to reproduce this one, but in your linked dotfiles above i only see references to `XDG_CONFIG_HOME` in the `NPM_` prefixed env vars, while you're having issues with `XDG_DATA_HOME` so i'm not sure exactly which config is being set.

the `Failed to replace env in config` error is not one that we log any more. If the env var you reference is not defined, instead we will simply not replace it and you'll get the behavior you're seeing. it seems like somehow you're ending up in an environment where the env var isn't set but i'm not 100% sure how.

**Comment by lgarron** [comment] 2022-04-27 22:03
I no longer have the computer that this used to happen on, so unfortunately I don't know if I'll be able to repro. (Fortunately, though, this doesn't seem to be an issue on my current main computer.)

**Comment by nlf** [comment] 2022-05-02 18:19
Closing since this can no longer be reproduced. Please feel free to open a new issue if you see it happen again!

**Closed as not planned by nlf** 2022-05-02 18:19 UTC
Labels: Release 7.x, Bug, Needs Triage

**Comment by aichingm** [comment] 2022-06-14 19:14
@nlf I still can reproduce this with 

```
$ npm version
{
  npm: '8.5.5',
  node: '18.2.0',
  v8: '10.1.124.8-node.13',
  uv: '1.43.0',
  zlib: '1.2.12',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '108',
  nghttp2: '1.47.0',
  napi: '8',
  llhttp: '6.0.6',
  openssl: '1.1.1o',
  cldr: '41.0',
  icu: '71.1',
  tz: '2022a',
  unicode: '14.0'
}

```

Do we need a new issue for this? There is already so much information in this issue which would just be duplicated.
