### ISSUE TITLE
[BUG] NPM update issues

### ISSUE THREAD

**Issue by KingsleyJefe** [npm/cli#7093] opened 2023-12-20 01:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I installed NPM version 5.5.1 for a test today, but it does not allow me install packages, maybe because I still use the latest version of Node. Now I want to upgrade my npm back to 10.2.3 and it doeesn't work.

### Expected Behavior

I expect to successfully update NPM

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by stefnotch** [comment] 2023-12-21 08:53
This issue doesn't seem to have enough information to reproduce

**Comment by ljharb** [comment] 2023-12-21 17:56
npm 5 is years obsolete, and in my experience once you've installed a broken npm version, you have to reinstall node.

In the future, use `npx npm@5` etc if you want to test out npm 5 without installing it globally.

Closing because indeed there's no way to reproduce and installing npm 5 shouldn't ever be done anymore.

**Closed as not planned by ljharb** 2023-12-21 17:56 UTC
Labels: Bug, Needs Triage, Release 10.x
