### ISSUE TITLE
[BUG] the path resolution of npx is wrong when ancestor directory name include sign “&”

### ISSUE THREAD

**Issue by zihahahaha** [npm/cli#6376] opened 2023-04-19 03:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

on windows，if ancestor directory name include sign “&”，the path resolution will wrong when npx

### Expected Behavior

it's easy to repair just replace `SET dp0=%~dp0` width `SET "dp0=%~dp0"` in the batch script that npm generated
 

### Environment

- npm: 9.3.1
- Node.js: 18.14.1
- OS Name: windows
```

**Comment by Voltra** [comment] 2023-05-03 12:44
Same here:

* Node: 14.21.3
* NPM: 9.6.5
* OS: Windows 10 Pro (64 bits)

**Comment by milaninfy** [comment] 2024-08-30 20:04
**Closing:** this looks to be similar if not a duplicate of an existing issue,https://github.com/npm/cli/issues/7761. If you believe your instance is unique, please provide further clarifying details.

**Closed as not planned by milaninfy** 2024-08-30 20:04 UTC
Labels: Bug, Needs Triage, Release 9.x
