### ISSUE TITLE
[BUG] NPM run server failed compile

### ISSUE THREAD

**Issue by HoiDam** [npm/cli#1387] opened 2020-06-04 01:45 UTC
# What / Why

> after using the npm run server , it failed
![圖片](https://user-images.githubusercontent.com/66233626/83705547-daaed080-a647-11ea-9b71-797435898e47.png)
## When

*After window force update

## Where

*After window force update

### Current Behavior

* Cant compile

### Steps to Reproduce

* tried most of the solution on different site 

### Expected Behavior

* n/a

## Who

* n/a

## References

* n/a

**Comment by ljharb** [comment] 2020-06-04 03:26
chokidar is Mac-only; is it possible the project doesn't work on Windows?

**Comment by HoiDam** [comment] 2020-06-04 04:56
> 
> 
> chokidar is Mac-only; is it possible the project doesn't work on Windows?

em this project worked previously. After the windows update , it didnt work

**Comment by darcyclarke** [comment] 2021-06-02 22:20
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is reproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 22:20 UTC
Labels: Bug

**Comment by HoiDam** [comment] 2021-06-03 15:28
Thanks lol

**Comment by ljharb** [comment] 2021-06-03 16:04
@HoiDam are you getting this problem on npm 7? Since you didn’t fill out the issue template, there’s no way to know.
