### ISSUE TITLE
Getting 404 error while running "npm publish" from the terminal

### ISSUE THREAD

**Issue by Suraez** [npm/cli#2040] opened 2020-10-25 15:20 UTC
i checked the issue 1637 but couldn't find the solution.
The error I am getting is 
```
code E404
npm ERR! 404 Not Found - PUT https://npm.registry.github.com/suraj-ojha
npm ERR! 404 
npm ERR! 404  'suraj-ojha@1.0.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

Steps to reproduce :

1. clone this repo: gh repo clone bnb/bitandbang (https://github.com/bnb/bitandbang.git)
2. change the package name in package.json
3. login with the npm credentials: npm login
4. finally publish it to npm registry: npm publish

The environment I am on is :
- OS: Ubuntu 20.04
- Node: 10.19.0
- npm: 6.4.8

**Comment by darcyclarke** [comment] 2021-06-02 21:08
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 21:08 UTC
Labels: Release 6.x, Bug

**Comment by SkwalExe** [comment] 2022-04-13 11:41
The issue is still there in v8, this needs attention

**Comment by angelnext** [comment] 2023-02-07 15:25
Can confirm this still happens in v9
