### ISSUE TITLE
[BUG] npm bricked itself with npm update -g tsc

### ISSUE THREAD

**Issue by rsxdalv** [npm/cli#7832] opened 2024-10-14 15:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

```
PS C:...> npm i -g tsc
npm ERR! code EEXIST
npm ERR! path C:\Users\admin\AppData\Roaming\npm\tsc
npm ERR! File exists: C:\Users\admin\AppData\Roaming\npm\tsc
npm ERR! with --force to overwrite files recklessly.

npm ERR!     C:\Users\admin\AppData\Local\npm-cache\_logs\2024-10-14T15_28_08_921Z-debug.log
PS C:...> npm update -g tsc
removed 2019 packages, and audited 1 package in 8s

PS C:...> npm update -g tsc
npm error Class extends value undefined is not a constructor or null
```

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by rsxdalv** [comment] 2024-10-14 15:57
In order to fix it, I removed an old NVM installation and reinstalled node, but for a while I was in a limbo:
node --version gives 20.18,
npm --version gives 10.8.2
but any npm command fails.
After the uninstall and reinstall it still gives the same versions but actually works.

Editing the title to reflect only the initial bug of npm breaking

**Comment by ljharb** [comment] 2024-10-14 19:59
`npm update` should not be used with `-g` imo.

**Comment by rsxdalv** [comment] 2024-10-14 21:43
Is that a known thing? I usually don't have to use the global namespace so
I assumed that updating with "update" should be fine. I might have done too
many pip installs recently.

**Comment by milaninfy** [comment] 2024-10-15 13:35
**Closing:** this looks to be similar if not a duplicate of an existing issue, #7731.

**Closed as not planned by milaninfy** 2024-10-15 13:35 UTC
Labels: Bug, Duplicate

**Comment by rsxdalv** [comment] 2024-10-15 13:36
Thanks, I will comment the exact error I saw on that issue so that it can be found also by the error, not just the problematic command. I would suspect it's a duplicate.
