### ISSUE TITLE
[BUG] npm login functionality has been removed

### ISSUE THREAD

**Issue by jmcelroy58** [npm/cli#6501] opened 2023-05-25 20:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

We are currently using NOdejs and NPM that are supported by Microsoft Azure which right now is up to Nodejs v18; and we use NOdejs version 16 for our application which puts gives us use of the npm v8.X. Our company also is now using Jfrog SaaS which requires us to authenticate in order access our dependencies. Thus we need NPM login command to do this.

What we are seeing right now is when we call npm login we are getting back:

npm notice Log in on "Jfrog url"
npm verb web login before first POST
npm verb web login not supported, trying couch 
npm timing npm Completed in 338ms
npm verb unfinished npm timer command:adduser 1685042398576
npm info ok 
npm ERR! Exit handler never called! 

### Expected Behavior

We expect to atleast get a link to JFrog to complete authenticationa to allow our builds to continue:

npm notice Log in on"JFrog Url"
npm verb web login before first POST
npm verb web auth got response {
npm verb web auth   doneUrl: "JFrog Url"
npm verb web auth   loginUrl: "another JFrog url"
npm verb web auth }
npm verb web auth opening url pair
to complete your login please visit: "Url to authentication with company JFrog SaaS"

### Steps To Reproduce

1. Kick off build in GitHub Action 
2. With .npmrc configured with API token, company Jfrog url, always-auth=true, auth-type=legacy
3. the build script runs these commands:
    npm config set loglevel verbose
    export NPM_TOKEN=$RT_PUB_PASSWORD
     npm cache clear --force
     npm config set registry "company JFrog url" --auth-type=legacy --always-auth
     npm login 
     npm install
     npm run build:"env"
4. Build log error message reads this from the failure point:
    npm notice Log in on "Jfrog url"
    npm verb web login before first POST
    npm verb web login not supported, trying couch 
    npm timing npm Completed in 338ms
    npm verb unfinished npm timer command:adduser 1685042398576
    npm info ok 
    npm ERR! Exit handler never called! 

### Environment

- npm: v8.x
- Node.js: v16.3
- OS Name: none running in GitHub actions
- cannot provide anymore details as it would divulge company information.

Main Question: Is there a reason that the command npm login is only being supported in the latest version?

**Comment by milaninfy** [comment] 2024-08-30 19:59
**Closing:** this looks to be similar if not a duplicate of an existing issue, https://github.com/npm/cli/issues/7612. 
 Please update npm version to latest and try and use `auth-type` flag https://docs.npmjs.com/cli/v10/commands/npm-login#auth-type

**Closed as not planned by milaninfy** 2024-08-30 19:59 UTC
Labels: Release 8.x, Bug, Needs Triage
