### ISSUE TITLE
Remove all my api’s and reset all my accounts and balance to zero. Since, I was bugged and hacked.

### ISSUE THREAD

**Issue by ghost** [npm/cli#3623] opened 2021-08-07 15:22 UTC
Remove all my api’s and reset all my accounts and balance to zero. Since, I was bugged and hacked.

Thank you I really appreciate all the hard work and effort. 

__Originally posted by @F0o0De in https://github.com/Coinigy/api/pull/45__

**Comment by ljharb** [comment] 2021-08-07 15:40
Please stop filing duplicate issues.

Duplicate of #3622.

**Closed as completed by ljharb** 2021-08-07 15:40 UTC
