### ISSUE TITLE
npm ERR! cb() never called!

### ISSUE THREAD

**Issue by like359** [npm/cli#1014] opened 2020-03-12 08:41 UTC
Microsoft Windows [Version 10.0.18363.418]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\byr>npm install -g expo-cli
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\byr\AppData\Roaming\npm-cache\_logs\2020-03-12T08_35_11_476Z-debug.log

C:\Users\byr>

help me

**Comment by KESHAmambo** [comment] 2020-03-12 12:50
Same problem for me, attaching my debug log
[2020-03-12T12_46_30_862Z-debug.log](https://github.com/npm/cli/files/4324222/2020-03-12T12_46_30_862Z-debug.log)

**Comment by DanielRuf** [comment] 2020-03-12 23:04
Duplicate of #417

**Comment by arweekley** [comment] 2020-03-21 17:18
Similar problem...

arnold@MBP-16 dev-projects % npm i
npm WARN deprecated @angular/http@7.2.16: Package no longer supported. Use @angular/common instead, see https://angular.io/guide/deprecations#angularhttp
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
Unhandled rejection Error: EACCES: permission denied, open '/Users/arnold/.npm/_cacache/index-v5/7a/6a/a1d22adf3e0141128493d222f4944d754f914244b8cca9318ab5cef2cfed'

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:

**Comment by DanielRuf** [comment] 2020-03-21 19:27
@arweekley please see #417

Also provide the needed information (npm and node version).

**Comment by BCusack** [comment] 2020-08-12 11:06
Had the same issue, turns out it was my new AVG internet security. Turned it off, all works perfectly.
I'll add to exceptions. Not the first time...

**Comment by lewsea** [comment] 2020-10-07 12:46
> Had the same issue, turns out it was my new AVG internet security. Turned it off, all works perfectly.
> I'll add to exceptions. Not the first time...

how did you turn off the AVG internet security?

**Closed as completed** 2021-03-26 04:32 UTC
