### ISSUE TITLE
[BUG] npm install and npm ci produce bad symlinks on Linux distros and Mac OS

### ISSUE THREAD

**Issue by aviatrix** [npm/cli#1133] opened 2020-04-09 14:20 UTC
# What / Why

When installing a chain of **local** dependencies with `npm ci` and `npm install` on Debian, Ubuntu & Mac OS (but **not** Windows), the installation fails with an error
## When
Example local dependency chain : myProject -> libB -> libA
Example directory structure
```
.
├── @mycorp
│   ├── libA
│   │   └── package.json
│   └── libB
│       ├── package.json
│       └── package-lock.json
└── myproject
    ├── package.json
    └── package-lock.json
```

## Where

npm cli - `npm ci` and `npm install`

### Current Behavior

currently when using `npm ci` and `npm install` to install the same dependency chain, the installation produces the following dir tree
```
.
├── coverage
├── @mycorp
│   ├── libA
│   │   └── package.json
│   └── libB
│       ├── node_modules
│       │   └── liba -> ../../../../@mycorp/libA
│       ├── package.json
│       └── package-lock.json
└── myproject
    ├── node_modules
    │   └── libb -> ../../@mycorp/libB
    ├── package.json
    └── package-lock.json
```
Lib B has 1 extra `../` in its symbolic link for `libA` in it under `libB/node_modules` using both versions, but error is thrown only when using `npm ci`
Error thrown : 
```sh
root@THEARMADA:/mnt/c/VisualStudio/Projects/npmRepro/myproject $ npm ci
npm WARN prepare removing existing node_modules/ before installation
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /mnt/c/VisualStudio/Projects/npmRepro/myproject/node_modules/libb/node_modules/liba/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/mnt/c/VisualStudio/Projects/npmRepro/myproject/node_modules/l
ibb/node_modules/liba/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-09T13_53_59_369Z-debug.log
```

Result with `npm install`
```sh
root@THEARMADA:/mnt/c/VisualStudio/Projects/npmRepro/npmBug/myproject $ npm install
npm WARN myproject@1.0.0 No description
npm WARN myproject@1.0.0 No repository field.

added 2 packages and audited 1 package in 6.069s
```

### Steps to Reproduce

checkout the example repository that can reproduce the bug
https://github.com/aviatrix/npmBug
```sh
git clone https://github.com/aviatrix/npmBug.git
cd npmBug/myproject
npm ci
```
### Expected Behavior

`npm ci` and `npm install` should produce proper symlinks 
Example : 
```
.
├── coverage
├── @mycorp
│   ├── libA
│   │   └── package.json
│   └── libB
│       ├── node_modules
│       │   └── liba -> ../../../@mycorp/libA
│       ├── package.json
│       └── package-lock.json
└── myproject
    ├── node_modules
    │   └── libb -> ../../@mycorp/libB
    ├── package.json
    └── package-lock.json
```

## Who

* n/a

## References

* n/a

**Comment by ljharb** [comment] 2020-04-09 15:50
It looks like you’re mounting a windows machine; perhaps that’s the issue?

**Comment by aviatrix** [comment] 2020-04-09 18:12
We first observed the issue on our build instance in azure, that's running ubuntu 18.04.  (log below)
A colleague also experienced the same thing on his work Mac OS 

```
2020-04-08T07:09:12.8936341Z 6983 verbose stack Error: ENOENT: no such file or directory, open '/home/vsts/work/1/s/shop_admin/node_modules/@mycorp/frontend/node_modules/@mycorp/core/package.json'
2020-04-08T07:09:12.8936832Z 6984 verbose cwd /home/vsts/work/1/s/shop_admin
2020-04-08T07:09:12.8937239Z 6985 verbose Linux 5.0.0-1035-azure
2020-04-08T07:09:12.8937666Z 6986 verbose argv "/opt/hostedtoolcache/node/13.12.0/x64/bin/node" "/opt/hostedtoolcache/node/13.12.0/x64/bin/npm" "ci"
2020-04-08T07:09:12.8938029Z 6987 verbose node v13.12.0
2020-04-08T07:09:12.8938227Z 6988 verbose npm  v6.14.4
2020-04-08T07:09:12.8938467Z 6989 error code ENOENT
2020-04-08T07:09:12.8938652Z 6990 error syscall open
2020-04-08T07:09:12.8938993Z 6991 error path /home/vsts/work/1/s/shop_admin/node_modules/@mycorp/frontend/node_modules/@mycorp/core/package.json
2020-04-08T07:09:12.8939516Z 6992 error errno -2
2020-04-08T07:09:12.8940192Z 6993 error enoent ENOENT: no such file or directory, open '/home/vsts/work/1/s/shop_admin/node_modules/@mycorp/frontend/node_modules/@mycorp/core/package.json'
2020-04-08T07:09:12.8940703Z 6994 error enoent This is related to npm not being able to find a file.
```

**Comment by henock1** [comment] 2020-09-23 00:05
Experiencing the same issue
MacOS 10.15.6 
node 12.18.2
npm 6.14.5

**Comment by darcyclarke** [comment] 2021-06-02 21:25
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 21:25 UTC
Labels: Release 6.x, Bug
