### ISSUE TITLE
[BUG] Installing git+https stores git+ssh in package-lock

### ISSUE THREAD

**Issue by nVitius** [npm/cli#2804] opened 2021-03-01 20:22 UTC
### Current Behavior:
When installing a dependency using a `git+https` URL, npm resolves it to a `git+ssh` URL in `package-lock.json`.
This causes any CI processes to be unable to install the dependency, as npm will try to use SSH to fetch the repo.
Here is a screenshot displaying the behavior:
![image](https://user-images.githubusercontent.com/3804041/109553984-e7563d00-7a90-11eb-83a3-6584905ff2b2.png)

### Expected Behavior:
Installing a dependency via Git should resolve it with the same protocol that was used in the npm command.

### Steps To Reproduce:
`npm i --save git+https://github.com/nvitius/firestore-stream-helper\#master`

### Environment:
macOS 11.2.1
node 12.20.1
npm 7.6.0

**Comment by hmoffatt** [comment] 2021-03-03 03:55
I also see this with 7.6.0 on linux. The problem occurs in all version at least 7.2.0 and later. 6.14.11 works fine though.

Before `npm install` with v7.6.0 I have the following in `package-lock.json`:
```
    "perfect-scrollbar": {
      "version": "git+https://github.com/hmoffatt/perfect-scrollbar.git#ecbee115791b2630ac2a7cf31251f2d06f0d4197",
      "from": "git+https://github.com/hmoffatt/perfect-scrollbar.git#ecbee11"
    },
```

after:
```
    "perfect-scrollbar": {
      "version": "git+ssh://git@github.com/hmoffatt/perfect-scrollbar.git#ecbee115791b2630ac2a7cf31251f2d06f0d4197",
      "from": "perfect-scrollbar@git+https://github.com/hmoffatt/perfect-scrollbar.git#ecbee11"
    },
```

**Comment by tstibbs** [comment] 2021-03-10 09:51
I think this is a dupe of #2610?

**Comment by hmoffatt** [comment] 2021-03-10 11:39
> I think this is a dupe of #2610?

I agree.

**Comment by wraithgar** [comment] 2021-03-26 18:09
Yep dupe of #2610

**Closed as completed by wraithgar** 2021-03-26 18:09 UTC
Labels: Release 7.x, Bug, Needs Triage
