### ISSUE TITLE
[BUG] npm diff is not work in other registry

### ISSUE THREAD

**Issue by 827652549** [npm/cli#7338] opened 2024-04-04 05:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I want use `npm diff` command, but is only work in "https://registry.npmjs.com", it's not work in private registry in our company.

```bash
➜  ~ npm config list
; "user" config from /Users/mako/.npmrc

home = "http://npm/"
registry = "http://registry.npm.release.ctripcorp.com/"

; node bin location = /usr/local/bin/node
; node version = v20.11.1
; npm local prefix = /Users/mako
; npm version = 10.2.4
; cwd = /Users/mako
; HOME = /Users/mako
; Run `npm config ls -l` to show all defaults.
➜  ~ npm diff --diff=@cript/corpflighttravelstandard@1.1.20 --diff=@cript/corpflighttravelstandard@1.2.1-rc.1
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.com/@cript%2fcorpflighttravelstandard - Not found
npm ERR! 404
npm ERR! 404  '@cript/corpflighttravelstandard@1.2.1-rc.1' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in: /Users/mako/.npm/_logs/2024-04-04T05_29_00_565Z-debug-0.log
➜  ~
```

### Expected Behavior

I hope npm diff work in private registry

### Steps To Reproduce

If you don't have a private registry to use, you can set a non-existent string like “http://non-existent.com”, and see if the common npm packages work.

### Environment

- npm: 10.2.4
- Node.js: 20.11.1
- OS Name: macOS Sonoma 14.2.1 (23C71)

**Comment by milaninfy** [comment] 2024-04-12 19:32
@827652549 
I am not able to reproduce the issue... I ran local repository

` npm diff --diff=@test/test-diff@2.0.0 --diff=@test/test-diff@2.1.0 --dd`
```bash
npm verb cli /usr/local/bin/node /usr/local/bin/npm
npm info using npm@10.2.4
npm info using node@v20.11.1
npm verb title npm diff
npm verb argv "diff" "--diff" "@test/test-diff@2.0.0" "--diff" "@test/test-diff@2.1.0" "--loglevel" "verbose"
npm verb logfile logs-max:10 dir:/Users/user/.npm/_logs/2024-04-12T19_12_27_822Z-
npm verb logfile /Users/user/.npm/_logs/2024-04-12T19_12_27_822Z-debug-0.log
npm info diff { src: '@test/test-diff@2.0.0', dst: '@test/test-diff@2.1.0' }
npm http fetch GET 200 http://localhost:4873/@test%2ftest-diff 91ms (cache revalidated)
npm http fetch GET 200 http://localhost:4873/@test%2ftest-diff 91ms (cache revalidated)
npm http fetch GET 200 http://localhost:4873/@test/test-diff/-/test-diff-2.0.0.tgz 27ms (cache updated)
npm http fetch GET 200 http://localhost:4873/@test/test-diff/-/test-diff-2.1.0.tgz 27ms (cache updated)
diff --git a/semver.js b/semver.js
index v2.0.0..v2.1.0 100644
--- a/semver.js
+++ b/semver.js
@@ -13,6 +13,4 @@
 
... some diffing information...

npm verb exit 0
npm info ok 
```

also I used non existent url for registry 

```bash
npm ERR! code E404
npm ERR! 404 Not Found - GET http://non-existent.com/@test%2ftest-diff
npm ERR! 404 
npm ERR! 404  '@test/test-diff@2.0.0' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

based on Error logs it looks like it's picking up the registry url correctly.

**Comment by milaninfy** [comment] 2024-04-18 13:17
**Closing**  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.

**Closed as completed by milaninfy** 2024-04-18 13:17 UTC
Labels: Bug, Needs Triage, Release 10.x
