### ISSUE TITLE
Passing variables defined in package.json not working

### ISSUE THREAD

**Issue by toabm** [npm/cli#2816] opened 2021-03-04 09:44 UTC
When defining a variable inside package.json like a path:

    "devPath": "./myFolder"

and then using the variable to run a npm script defined in package.json:

      "scripts": {
    "build:dev": "node_modules/.bin/webpack --mode=development  --devPath=$npm_package_devPath",
  }

the parameter is not getting inizializated thow options.devPath

**Comment by ljharb** [comment] 2021-03-04 14:30
I believe this is by design; these variables are (for the most part) no longer available in npm 7.

(separately, you can just do `webpack`, you shouldn't need to hardcode node_modules/.bin inside an npm script)

**Comment by toabm** [comment] 2021-03-25 12:49
Thank you @ljharb !, I am not sure I fully understood you.  What you mean by "ardcode node_modules/.bin inside an npm script"?
I have all my config inside package.json: app name, build scripts, libs.... so it would be nice to have the output path there too. Evey more since I need 2 differents paths: 1 for develop mode and a different one for prod mode.

Does this make sense at all?....:) Thank you again for your reply!

**Comment by ljharb** [comment] 2021-03-25 14:01
I mean:
```
"build:dev": "webpack --mode=development  --devPath=$npm_package_devPath",
```

**Comment by toabm** [comment] 2021-03-25 14:14
Ok, and....how would you do it? I meen to run webpack and compile de app? Sorry if am an being too ignorant....:\

**Comment by ljharb** [comment] 2021-03-25 14:52
There’s lots of approaches; I’d probably use the same path for dev vs prod, but use an environment variable to configure it.

**Comment by darcyclarke** [comment] 2021-04-16 18:43
@toabm sorry for the confusion, we did remove these vars in `v7` - as @ljharb notes, there's many approaches to support this use case. Closing as this is the intended behaivor.

**Closed as completed by darcyclarke** 2021-04-16 18:43 UTC
Labels: Release 7.x, Bug

**Comment by toabm** [comment] 2021-05-21 12:26
I found a solution: https://stackoverflow.com/questions/66123394/how-can-i-use-variables-with-npm-7-x-x-in-package-json/67636751#67636751 

You just have to enclose your json variables inside the config object, then you can access them like we used to do ti, by usign $npm_package_config_devPath

I also suggest a nice way to add commentaries to our json files.

  "config": {
     "@comments devPath": "Path to build the develeping code.",
     "devPath": "../castorweb/src/dist/webapps/AQSAPP_TEMPLATE/tmp",
     "@comments prodPath": "Path to build the production code: When generating app versions",
     "prodPath": "../castorweb/src/dist/webapps/AQSAPP_TEMPLATE/dist"
  },

  scripts: {
    "try": " echo $npm_package_config_devPath"
  }
