### ISSUE TITLE
[BUG] Error running npm update : 'This is an error with npm itself.'

### ISSUE THREAD

**Issue by rgb4268** [npm/cli#795] opened 2020-02-11 01:27 UTC
Got log as -
....
17882 silly extract @angular/material@^8.2.3 extracted to /aaa/node_modules/.staging/@angular/material-c86959f3 (6596ms)
17883 silly extract rxjs@~6.4.0 extracted to /aaa/node_modules/.staging/rxjs-80013a51 (5195ms)
17884 timing npm Completed in 25058ms
17885 error cb() never called!
17886 error This is an error with npm itself. Please report this error at:
17887 error <https://npm.community>

on iMac, Mojave
node -v
v11.15.0

npm -v
6.7.0

**Comment by DanielRuf** [comment] 2020-02-18 06:25
Duplicate of https://github.com/npm/cli/issues/417

**Comment by darcyclarke** [comment] 2021-06-02 21:55
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 21:55 UTC
Labels: Bug
