### ISSUE TITLE
[BUG] <title>npm ERR! This is an error with npm itself.

### ISSUE THREAD

**Issue by Kevin8821** [npm/cli#3462] opened 2021-06-24 02:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

C:\WINDOWS\system32>npm install express -g
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Program Files\nodejs\node_cache\_logs\2021-06-24T02_53_38_393Z-debug.log

### Expected Behavior

C:\WINDOWS\system32>npm install express -g
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Program Files\nodejs\node_cache\_logs\2021-06-24T02_53_38_393Z-debug.log

### Steps To Reproduce

C:\WINDOWS\system32>npm install express -g
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Program Files\nodejs\node_cache\_logs\2021-06-24T02_53_38_393Z-debug.log

### Environment

C:\WINDOWS\system32>npm -v
6.14.13

**Comment by bpetrovbg** [comment] 2021-06-24 09:32
I encountered the same error, but in Gitlab CI/CD. I haven't changed anything in the ci/cd yml and saw that the pipeline started failing automatically when I pushed some new code (even tried to rerun some successful pipelines from yesterday, the result was that they are now failing because of that error...). Tried cleaning the npm cache, regenerate package-lock, etc...didn't help. So far I used:
image: buildkite/puppeteer:7.1.0, switching to the newer/older versions didn't help, too.

![image](https://user-images.githubusercontent.com/35259279/123239666-4597a780-d4e8-11eb-9643-4fe2aa8618fc.png)

**Comment by ghost** [comment] 2021-06-24 12:35
Perhaps [this page](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) will be of any help?

**Comment by bpetrovbg** [comment] 2021-06-24 15:08
> Perhaps [this page](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) will be of any help?

For some reason our pipelines are working again now, without changing anything...

**Comment by royrakesh** [comment] 2021-06-24 17:35
Same issue
Even after a fresh Nodejs Installation.

```
λ npm --versions                  
{                                 
  'rr-backend': '0.0.1',          
  npm: '7.18.1',                  
  node: '14.17.1',                
  v8: '8.4.371.23-node.67',       
  uv: '1.41.0',                   
  zlib: '1.2.11',                 
  brotli: '1.0.9',                
  ares: '1.17.1',                 
  modules: '83',                  
  nghttp2: '1.42.0',              
  napi: '8',                      
  llhttp: '2.1.3',                
  openssl: '1.1.1k',              
  cldr: '39.0',                   
  icu: '69.1',                    
  tz: '2021a',                    
  unicode: '13.0'                 
} 
```

**Comment by uc-vks** [comment] 2021-06-25 02:53
I have also facing same issue since yesterday.
![image](https://user-images.githubusercontent.com/50698759/123362634-9c57bc80-d58e-11eb-84bb-2e95e74c5931.png)

**Comment by wraithgar** [comment] 2021-06-25 03:35
This error needs much more information for us to try to debug it, see [this page](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) for more info

**Comment by royrakesh** [comment] 2021-06-25 03:41
I think enough information to reproduce the issue is already there but if need more information please ask which information you need . i will share all the possible information you need.

**Comment by wraithgar** [comment] 2021-07-15 21:15
npm `v7.20.0` added some things that should catch more of these network errors. It also added some new debugging messages specifically for this error message. Can you try with that version and also include any debug logs it generates?

**Comment by lukekarrys** [comment] 2021-09-28 19:14
**Closing:** We suspect this has to do with a combination of resource constraints within the device/program being used and the large amount of transient dependencies being installed by this command.

We've opened https://github.com/npm/statusboard/issues/395 for us to look deeper into this and track the discussion and fixes around it. You can also read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) for more information on why this issue might be happening currently and ways to debug it.

**Closed as completed by lukekarrys** 2021-09-28 19:14 UTC
Labels: Release 7.x, Bug, Needs Triage
