### ISSUE TITLE
[BUG] the package-lock.json generated by `npm i` errantly contains a ["packages"][""]["name"] property if the npm package is installed in a directory whose name differs from the npm package's name

### ISSUE THREAD

**Issue by sternam** [npm/cli#2812] opened 2021-03-03 03:06 UTC
### Current Behavior:
If the working directory's name differs from the name of the npm package it contains, then the generated package-lock.json has a ["packages"][""]["name"] property in violation of the npm v7 spec for the package-lock.json file per the docs at [https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json](https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json)
for example:
```
{
  "name": "impact-api",
  "version": "2.27.0",
  "lockfileVersion": 2,
  "requires": true,
  "packages": {
    "": {
      "name": "impact-api",
      "version": "2.27.0",
      "license": "UNLICENSED",
      "dependencies": {
...
```

### Expected Behavior:
The generated package-lock.json file should not have a "name" property under ["packages"][""]
for example:
```
{
  "name": "impact-api",
  "version": "2.27.0",
  "lockfileVersion": 2,
  "requires": true,
  "packages": {
    "": {
      "version": "2.27.0",
      "license": "UNLICENSED",
      "dependencies": {
...
```

### Steps To Reproduce:
1. clone an npm project/package e.g. from GitHub into a filesystem directory whose `name` differs from the name of the npm package
2. remove package-lock.json and the ./node_modules directory if they exist
3. Run `npm i`
4. The generated package-lock.json contains an errant ["packages"][""]["name"] property in violation of the npm v7 spec for the package-lock.json file per the docs at [https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json](https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json)

### Environment:
- OS: macOS Big Sur Version 11.1
- Node: 14.16.0
- npm: 7.6.0

**Comment by shadowspawn** [comment] 2021-03-03 05:01
Related: #2264 #2770

**Comment by darcyclarke** [comment] 2021-04-09 18:44
Closing as its a duplicate of https://github.com/npm/cli/issues/2264

**Closed as completed by darcyclarke** 2021-04-09 18:44 UTC
Labels: Release 7.x, Bug, Duplicate
