### ISSUE TITLE
[BUG] Fsevents hanging

### ISSUE THREAD

**Issue by MrRainbowCoding** [npm/cli#7567] opened 2024-05-29 14:49 UTC
My Fsevents is freezing when trying to install. I can't even CTRL+C out of it. I am stumped. Maybe a memory problem? Here's my 
my command line, OS info, and Node version if it helps:

```
Spotify-client-reactjs-master\Spotify-client-reactjs-master> npm cache clean -- force
npm WARN using -- force Recommended protections disabled.

C:\Users\Sara\Tech Wizard Dropbox\Alex Logsdon\PC\Downloads\Spotify-client-reactjs-master\Spotify-
client-reactjs-master>
C:\Users\Sara\Tech Wizard Dropbox\Alex Logsdon\PC\Downloads\Spotify-client-reactjs-master\Spotify-
client-reactjs-master>npm install fsevents -- force
npm WARN using -- force Recommended protections disabled.
] \ reify:fsevents: timing reifyNode: node_modules/react-
scripts/node_modules/fsevents Completed in 865ms

<--- Last few GCs --->

[52056:0000019AE914E370]   400345 ms: Scavenge 1135.3 (1219.6) -> 1135.2 (1218.6) MB, 2.68 / 0.00 ms  (average mu = 0.994, current mu = 0.995) allocation failure;
[52056:0000019AE914E370]   401022 ms: Scavenge 1136.0 (1218.6) -> 1135.7 (1219.6) MB, 2.45 / 0.00 ms  (average mu = 0.994, current mu = 0.995) allocation failure;
[52056:0000019AE914E370]   401955 ms: Scavenge 1136.2 (1219.6) -> 1136.0 (1218.6) MB, 2.49 / 0.00 ms  (average mu = 0.994, current mu = 0.995) allocation failure;


<--- JS stacktrace --->

FATAL ERROR: Committing semi space failed. Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 00007FF7D122C94B
 2: 00007FF7D1196764
 3: 00007FF7D1C149A1
 4: 00007FF7D1BFE0F8
 5: 00007FF7D1A5FBA0
 6: 00007FF7D1A179A3
 7: 00007FF7D1A69260
 8: 00007FF7D1A5C8C0
 9: 00007FF7D1A71F3A
10: 00007FF7D1A727B7
11: 00007FF7D1A810AF
12: 00007FF7D1741DD5
13: 00007FF7D1CC62CE
14: 00007FF7520D6919

```

OS: Windows 11
Node Version: 20.12.2

It's in the terminal app, the command prompt is running as Administrator. I had to censor the path so
you guys can't steal my info. I provided it. 

I can't use the bug formating because it doesn't fit the nature of my issue.

**Comment by milaninfy** [comment] 2024-05-29 14:54
which npm version are you using ?

**Comment by milaninfy** [comment] 2024-05-31 13:56
@MrRainbowCoding This issue should have been fixed on https://github.com/npm/cli/pull/7463. 
can you try replicating this problem on the latest version of `npm`? (ie. `npm i -g npm`)

**Comment by milaninfy** [comment] 2024-06-07 00:36
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.

**Closed as completed by milaninfy** 2024-06-07 00:36 UTC
