### ISSUE TITLE
[BUG] package-lock.json contains os specific path when using local dependencies

### ISSUE THREAD

**Issue by souravsaraf123** [npm/cli#4579] opened 2022-03-17 09:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

package-lock.json does not contain an os-independent string for local dependencies, therefore package-lock.json is always changing when it was committed from windows and then building on linux.

I think the issue might be that the lock file contains an OS-normalized string, while it should actually contain some string that is independent of the OS and only gets translated when the package-lock.json is parsed.

### Expected Behavior

Expected behaviour would be that the same package-lock.json is generated no matter the OS.

### Steps To Reproduce

1. In Windows 10, node --version v16.13.2, npm --version = 8.5.4 
2. Have a package json dependency like this: 

```
"dependencies": {
        "some-local-dependency": "file:../myproject/module"
    }
```

On windows, this produces a package-lock.json on windows that has this relevant section generated:

```
"dependencies": {
        "some-local-dependency": {
            "version": "file:\\myproject\\module"
        }
    }
```

On linux, the same package json results in the following package-lock.json (and therefore makes the committed package-lock.json dirty in git):

```
"dependencies": {
        "some-local-dependency": {
            "version": "file:../myproject/module"
        }
}
```

Both package-lock.json files shoud have the same path separator.

### Environment

- npm: 8.5.4
- Node.js: 16.13.2
- OS Name: Windows 10
- System Model Name: Dell
- npm config:
```
; "builtin" config from C:\Users\soura\AppData\Roaming\npm\node_modules\npm\npmrc

prefix = "C:\\Users\\soura\\AppData\\Roaming\\npm"

; "user" config from C:\Users\soura\.npmrc

msvs_version = "2019"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = 
; HOME = C:\Users\soura
; Run `npm config ls -l` to show all defaults.

```

**Comment by souravsaraf123** [comment] 2022-03-17 09:06
This issue was previously reported for npm6 and was fixed earlier.
https://github.com/npm/npm/issues/17338


Now I am facing the same in npm8.

**Comment by wraithgar** [comment] 2022-03-17 13:55
Closing as duplicate of https://github.com/npm/cli/issues/3291

**Closed as completed by wraithgar** 2022-03-17 13:55 UTC
Labels: Release 8.x, Bug, Needs Triage
