### ISSUE TITLE
[BUG] npm silently hangs up on its first execution on Windows when proxy config is wrong

### ISSUE THREAD

**Issue by kymok** [npm/cli#2276] opened 2020-12-02 12:31 UTC
### Current Behavior:

Any npm command including `npm` hangs with displaying nothing on Windows terminal.
Title bar of command prompt changes to `npm prefix`.

### Expected Behavior:

Error message or at least timeout.

### Steps To Reproduce:

1. In Windows 10 + node 15.3.0 with wrong proxy setting.
2. Install as instructed.
3. Start command prompt and type `npm -v`.
4. Terminal title changes to `npm prefix` and nothing happens.

I don't know if this happens on the same proxy situation after successful executions of npm command.

### Environment:
OS: Windows 10.
Node: 15.3.0
npm: 7.0.14.

**Comment by nlf** [comment] 2020-12-04 16:09
how is your proxy configured? system wide? in your npm config? environment variables consumed by node?

**Comment by kymok** [comment] 2020-12-08 11:04
Proxy is configured system wide and is set to automatically detect. 

After submitting this issue I found out that a Symantec cloud proxy service is installed in my employer's network, so the problem was caused because of the way the security service behaves.

**Comment by nlf** [comment] 2020-12-08 16:33
thanks for following up! since it sounds like you've found the root cause on your end, i'm going to go ahead and close this issue

**Closed as completed by nlf** 2020-12-08 16:33 UTC
Labels: Release 7.x, Bug, Needs Triage, platform:windows

**Comment by kymok** [comment] 2020-12-09 05:51
Thank you for taking your time!
