### ISSUE TITLE
[BUG] ERR! cb() never called! 

### ISSUE THREAD

**Issue by ShikoShintaro** [npm/cli#2993] opened 2021-03-30 12:15 UTC
$ npm install @discordjs/opus
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:

this is the error that i got on installing some packages for my app

**Comment by kiehnek** [comment] 2021-03-30 13:30
Duplicate of #417

**Closed as completed** 2021-03-30 13:53 UTC
Labels: Release 7.x, Bug, Needs Triage
