### ISSUE TITLE
[BUG] install monaca in windows 10 64bit

### ISSUE THREAD

**Issue by saifolanwar** [npm/cli#2709] opened 2021-02-16 14:01 UTC
### Current Behavior:
fail installation

### Expected Behavior:
able to install, load monaca

### Steps To Reproduce:
1. Install node.js
2. run npm install -g monaca
4. See error below
C:\Users\Resident>npm install -g monaca@latest
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, open 'C:\Users\Resident\AppData\Roaming\npm\node_modules\monaca\node_modules\monaca-lib\src\inspector-app\devtools\scripts\compiler-runner\closure-runner.jar'
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, open 'C:\Users\Resident\AppData\Roaming\npm\node_modules\monaca\node_modules\monaca-lib\src\inspector-app\devtools\scripts\closure\compiler.jar'
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Resident\AppData\Local\npm-cache\_logs\2021-02-16T13_56_41_301Z-debug.log

### Environment:
- OS: Windows 10
- Node: 14.5.5
- npm: 7.5.4

**Comment by nlf** [comment] 2021-02-16 16:41
hi there, by your error messages it looks like you're seeing some permissions errors. are you running these commands with elevated privileges?

are you experiencing this problem with any other packages, or just this specific one?

i'm unable to reproduce this. you might also try cleaning your cache `npm cache clean --force` and trying again

**Comment by saifolanwar** [comment] 2021-02-17 04:06
I doubt it's the case. 

The privilege of the Windows user is not Administrator, correct.

But I had earlier try to run the npm (command prompt) as Administrator too. 

facing the same issue.

**Comment by nlf** [comment] 2021-02-17 21:16
i'm still unable to reproduce this.

can you try it from a terminal running as administrator and attach the log here?

**Comment by saifolanwar** [comment] 2021-02-17 21:31
yup, sure

Microsoft Windows [Version 10.0.18363.1379]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\USER>npm install -g monaca
npm notice
npm notice New patch version of npm available! 7.5.1 -> 7.5.4
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.5.4
npm notice Run npm install -g npm@7.5.4 to update!
npm notice
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, open 'C:\Users\USER\AppData\Roaming\npm\node_modules\monaca\node_modules\monaca-lib\src\inspector-app\devtools\scripts\compiler-runner\closure-runner.jar'
npm WARN tar TAR_ENTRY_ERROR EPERM: operation not permitted, open 'C:\Users\USER\AppData\Roaming\npm\node_modules\monaca\node_modules\monaca-lib\src\inspector-app\devtools\scripts\closure\compiler.jar'
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USER\AppData\Local\npm-cache\_logs\2021-02-17T21_27_45_403Z-debug.log

**Comment by nlf** [comment] 2022-04-04 19:41
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.

**Closed as completed by nlf** 2022-04-04 19:41 UTC
Labels: Release 7.x, Bug, platform:windows
