### ISSUE TITLE
npm ERR! cb( ) never called!

### ISSUE THREAD

**Issue by himanshupal** [npm/cli#1131] opened 2020-04-09 05:07 UTC
I am using
- node v13.12.0
- npm v6.14.1
- Windows-x86 1909 Build 18363.752

I should first tell that I recently update nodejs on my system &
I was trying to install dependencies after cloning [Realworld](https://github.com/sveltejs/realworld) repo when I encountered this error.

This the npm generated log [2020-04-09T04_38_30_115Z-debug.log](https://github.com/npm/cli/files/4454106/2020-04-09T04_38_30_115Z-debug.log)

**Comment by AnjaliSinghal** [comment] 2020-04-10 03:12
same issue on my system

**Comment by redmosaic** [comment] 2020-04-10 06:13
Same issue with
node 10.15.0
npm 6.4.1
Linux 5.5.10-200.fc31.x86_64
fedora-coreos-31.20200310.3.0-qemu.x86_64

**Comment by Anan5a** [comment] 2020-04-10 08:23
Same issue on my system

**Comment by xsoheilalizadeh** [comment] 2020-04-10 12:24
Same issue on [eShopOnContainers](https://github.com/dotnet-architecture/eShopOnContainers)

**npm version**
```
{
  npm: '6.14.4',
  ares: '1.16.0',
  brotli: '1.0.7',
  cldr: '36.1',
  icu: '66.1',
  llhttp: '2.0.4',
  modules: '79',
  napi: '6',
  nghttp2: '1.40.0',
  node: '13.12.0',
  openssl: '1.1.1e',
  tz: '2019c',
  unicode: '13.0',
  uv: '1.35.0',
  v8: '7.9.317.25-node.30',
  zlib: '1.2.11'
}
```

[2020-04-10T12_11_37_472Z-debug.log](https://github.com/npm/cli/files/4461482/2020-04-10T12_11_37_472Z-debug.log)

**Comment by redmosaic** [comment] 2020-04-10 13:50
> Same issue on eShopOnContainers
>   npm: '6.14.4',
>   node: '13.12.0',

That's strange. Updating to node 13.12.0 and npm 6.14.4 solved this issue for me.

**Comment by Anan5a** [comment] 2020-04-10 15:54
> That's strange. Updating to node 13.12.0 and npm 6.14.4 solved this issue for me.

I'm also using the same versions  but problem persists.

**Comment by DanielRuf** [comment] 2020-04-12 17:01
Duplicate of #417

Please also try to upgrade npm to the latest available release.

**Comment by DanielRuf** [comment] 2020-04-12 17:02
Oh and try `npm i --force`and clear the cache before this using `npm cache clean --force`.

**Comment by Anan5a** [comment] 2020-04-13 04:38
@DanielRuf I already did that for couple of time.
And in the end I end up using ```yarn``` and it did work flawlessly :)

**Comment by yasirnoor234** [comment] 2020-04-14 18:07
Yes, i also this same issue continuously when i created a new project.
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

Although I used update nodejs.

**Closed as completed** 2021-06-02 21:21 UTC
Labels: Release 6.x
