### ISSUE TITLE
[BUG] npm error Exit handler never called!           

### ISSUE THREAD

**Issue by SxMAbel** [npm/cli#7639] opened 2024-07-11 01:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

1.648 npm warn using --force Recommended protections disabled.                                                                                                                
152.0 npm error Exit handler never called!                                                                                                                                    
152.0 npm error This is an error with npm itself. Please report this error at:
152.0 npm error     <https://github.com/npm/cli/issues>
152.0 
152.1 
152.1 npm error A complete log of this run can be found in: /root/.npm/_logs/2024-07-11T01_38_27_566Z-debug-0.log

### Expected Behavior

expected to build docker image but throws that error when it gets to npm install.

# Use the official Node.js image as a base
FROM node:18.20.4

# Set the working directory
WORKDIR /home/nick/backend

# Install app dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the TypeScript code
RUN npm run build

# Expose the port the app runs on
EXPOSE 35001

# Command to run the app
CMD ["node", "dist/index.js"]

### Environment

- npm: 10.8.2
- Node.js: 18.20.4
- OS Name: Ubuntu 22.04.4 LTS
- System Model Name: Server
- npm config:
```ini
; node bin location = /root/.nvm/versions/node/v18.20.4/bin/node
; node version = v18.20.4
; npm local prefix = /home/nick/backend
; npm version = 10.8.2
; cwd = /home/nick/backend
; HOME = /root
```

**Comment by SxMAbel** [comment] 2024-07-11 02:03
```ini
 => [2/6] WORKDIR /home/nick/backend                                                                                                                                    11.2s
 => [3/6] COPY package*.json ./                                                                                                                                          0.5s
 => ERROR [4/6] RUN npm install                                                                                                                                        444.5s
------                                                                                                                                                                        
 > [4/6] RUN npm install:                                                                                                                                                     
443.7 npm error Exit handler never called!                                                                                                                                    
443.7 npm error This is an error with npm itself. Please report this error at:                                                                                                
443.7 npm error     <https://github.com/npm/cli/issues>
443.7 
443.7 
443.7 npm error A complete log of this run can be found in: /root/.npm/_logs/2024-07-11T01_54_36_226Z-debug-0.log
------
Dockerfile:9
--------------------
   7 |     # Install app dependencies
   8 |     COPY package*.json ./
   9 | >>> RUN npm install
  10 |     
  11 |     # Copy the rest of the application code
--------------------
ERROR: failed to solve: process "/bin/sh -c npm install" did not complete successfully: exit code: 1
```

**Comment by milaninfy** [comment] 2024-07-11 14:29
this error can arise for a number of reasons; Please read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) & provide as much information as possible if you're able to **consistently reproduce** this error. Please includes things like package.json, lock file if exists, logs, steps to reproduce etc.

**Comment by ROD-MASAMI** [comment] 2024-07-12 10:51
i get this error too anyone with a solution

**Comment by knolleary** [comment] 2024-07-18 15:53
We are hitting this with our Node 22 CI builds (as 22 now include npm 10.8.2). I appreciate root cause could be completely different to the OP issue, but the timing is suspicious as the failures have only started with 10.8.2.

It fails with the following package file: https://github.com/node-red/node-red/blob/a1bf270ba6ba542b35b53447807801ce85b6d147/package.json

I'll see if I can narrow it down further.

**Comment by milaninfy** [comment] 2024-07-18 16:06
for which exact node version it's failing ? if you are using 22.5.0 and npm(10.8.2) and it's failing, could you please try with 22.4.1 and npm 10.8.2 if possible? 
This looks like similer to https://github.com/npm/cli/issues/7657

**Comment by knolleary** [comment] 2024-07-18 16:16
After commenting, I dug around and found the linked issue, including the one in the node repo. Looks like plenty of eyes are on it and not much I can usefully add - so will avoid generating any more noise. But I can confirm the install works with 22.4.1 and npm 10.8.2.

**Comment by steven-so** [comment] 2024-07-18 20:25
I started running into this issue in our docker build sometime in the last week. 

These are the versions I was running when it happened: 
node: v22.5.0
npm: 10.8.2

**Comment by avivkeller** [comment] 2024-07-18 20:28
This issue is being tracked at #7657 and is caused by https://github.com/nodejs/node/issues/53902.

**Comment by avivkeller** [comment] 2024-07-18 20:29
If you are curious on the progress to a solution, it is being discussed on Slack at <https://openjs-foundation.slack.com/archives/CTEDKHCTB/p1721324768673819>

**Comment by milaninfy** [comment] 2024-07-19 17:40
Fixed in Node.js v22.5.1 https://github.com/nodejs/node/issues/53902#issuecomment-2239263377

**Closed as completed by milaninfy** 2024-07-19 17:40 UTC
Labels: Bug, Needs Triage

**Comment by zhibirc** [comment] 2024-07-24 11:48
Are there any solutions for Node.js **v18.20.4** for that matter? Because initially bug was reported for this version. I have the same error.
