### ISSUE TITLE
[BUG] should not install optional peer dependencies

### ISSUE THREAD

**Issue by jcesarmobile** [npm/cli#2615] opened 2021-02-04 01:20 UTC
### Current Behavior:

@angular-devkit/build-angular has a peerDependenty to ng-packagr, but it’s marked as optional 

https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/package.json#L105

and ng-packagr has a peerDependency to tsickle, but also marked as optional
https://github.com/ng-packagr/ng-packagr/blob/master/package.json#L64

and tsickle has a peerDependency to typescript 3, while the other two require typescript 4 and fail to install because of the typescript version mismatch 

related
https://github.com/angular/tsickle/issues/1242

### Expected Behavior:

npm should not install optional peer dependencies.

### Steps To Reproduce:

1. `npm install typescript`
2. `npm install npm install ng-packagr@11.1.3 --save-exact`

you need to use that exact version because the optional dependency was removed in following versions

**Comment by SaadiSave** [comment] 2021-02-04 13:00
How long would a potential fix take? Angular is an important framework.

**Comment by darcyclarke** [comment] 2021-02-09 07:31
@jcesarmobile can you try the latest `npm`? (ie. `npm i -g npm`) We shipped fixes in [`7.5.3`](https://github.com/npm/cli/releases/tag/v7.5.3) on Monday which should have resolved this - tested locally & `optional` `peerDependencies` do seem to be behaiving correctly (ie. not being installed or warning of conflicts by default).

**Comment by jcesarmobile** [comment] 2021-02-09 13:00
It's still not working.
I'm updating the steps to reproduce since `@angular-devkit/build-angular` was updated to force npm 6 and the problem can't be reproduced there anymore, but can still be reproduced by using an older version of  `ng-packagr`

**Comment by darcyclarke** [comment] 2021-02-23 21:00
@jcesarmobile can you try updating to the latest v7 (ie. `npm i -g npm` - `v7.5.6`) - this problem should have actually been resolved in `v7.5.5` https://github.com/npm/cli/releases/tag/v7.5.5; Please let me know if you're still experiencing issues & I'll reopen this ticket (I just tried and couldn't reproduce).

**Closed as completed by darcyclarke** 2021-02-23 21:00 UTC
Labels: Release 7.x, Bug, Priority 1

**Comment by jcesarmobile** [comment] 2021-02-25 17:41
I confirm it works, thanks!

**Comment by Gouvernathor** [comment] 2026-03-21 14:08
This behavior now reoccurs, not sure since when : when installing module A, _optional_ peer dependencies are installed along with it, even though they are _optional_, and it does break/block the installation of module A if that causes a version conflict.
I will be opening a new issue.
