### ISSUE TITLE
[BUG]  npm install jQuery -S    ERR! cb() never called!

### ISSUE THREAD

**Issue by dell-mylife-git** [npm/cli#468] opened 2019-11-11 10:42 UTC
# What / Why

> ERR! cb() never called!

## When

* n/a

## Where

* n/a

### Current Behavior

*npm install jQuery -S

### Steps to Reproduce

* n/a

### Expected Behavior

* n/a

## Who

* n/a

## References

* n/a

**Comment by DanielRuf** [comment] 2019-11-11 18:09
Duplicate of https://github.com/npm/cli/issues/417

Please try to force-clear the npm cache and upgrade npm.

**Closed as completed** 2019-11-13 20:14 UTC

**Comment by keshaviagg** [comment] 2021-04-15 14:12
> Duplicate of #417
> 
> Please try to force-clear the npm cache and upgrade npm.

done everything still facing the same error.
![gitIssue](https://user-images.githubusercontent.com/51402838/114883635-bd7b8e80-9e22-11eb-9056-64647b8c7312.png)
