### ISSUE TITLE
npm ERR! cb() never called![BUG] 

### ISSUE THREAD

**Issue by keshaviagg** [npm/cli#3097] opened 2021-04-18 13:46 UTC
### Current Behavior:
on running npx create-react-app or npm I'm seeing this error

### Expected Behavior:
a new app shud be created or dependencies should be installed.

**Comment by ljharb** [comment] 2021-04-18 13:50
#417

**Comment by keshaviagg** [comment] 2021-04-18 13:52
> #417

the solution provided is not working.
I tried clearing cache and updating npm version but nothing changed still getting same error

**Comment by ljharb** [comment] 2021-04-18 13:55
Could you fill out the entire issue template then?

**Comment by keshaviagg** [comment] 2021-04-18 14:11
> Could you fill out the entire issue template then?

Current Behavior:
on running npx create-react-app or npm I'm seeing this error

Expected Behavior:
a new app shud be created or dependencies should be installed.

Steps To Reproduce:
Environment: run command npx create-react-app my-app or npm i

Environment: npm : v7.7.0
node v14.16.1
OS : ubuntu v18.x

**Comment by zizopixels** [comment] 2021-04-18 16:23
Same issue is with me ( npm ERR! cb() never called )
Googled everything but nothing is working for me.

**Comment by nlf** [comment] 2021-04-22 16:07
try updating to the latest release with `npm i -g npm` and see if that helps, i'm not able to reproduce this

**Comment by keshaviagg** [comment] 2021-04-22 16:12
Still the same issue

**Comment by nlf** [comment] 2021-04-22 16:32
are you running from an empty directory? can you share the output of `npm config ls`?

**Comment by FarooqueAhmeed** [comment] 2021-04-22 16:42
In my case, I installed the latest versions of the node and npm

**Comment by darcyclarke** [comment] 2021-06-04 18:35
Closing: Not enough information to reproduce unfortunately - see: https://github.com/npm/cli/wiki/"cb()-never-called%3F--I'm-having-the-same-problem!"

**Closed as completed by darcyclarke** 2021-06-04 18:35 UTC
Labels: Release 7.x, Bug, Needs Triage
