### ISSUE TITLE
[BUG] npm outdated exit code should not be set with json output

### ISSUE THREAD

**Issue by wraithgar** [npm/cli#3844] opened 2021-10-06 16:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

See https://github.com/npm/cli/issues/1109

Fix will be.

```diff
diff --git a/lib/outdated.js b/lib/outdated.js
index b3b630421..68002bf19 100644
--- a/lib/outdated.js
+++ b/lib/outdated.js
@@ -88,13 +88,14 @@ class Outdated extends ArboristWorkspaceCmd {
     // sorts list alphabetically
     const outdated = this.list.sort((a, b) => localeCompare(a.name, b.name))
 
-    if (outdated.length > 0)
-      process.exitCode = 1
-
     // return if no outdated packages
     if (outdated.length === 0 && !this.npm.config.get('json'))
       return
 
+    if (!this.npm.config.get('json'))
+      process.exitCode = 1
+
+
```

### Environment

- npm: 7.24.2

**Comment by ljharb** [comment] 2021-10-06 17:51
Why not?

**Comment by wraithgar** [comment] 2021-10-06 18:00
See https://github.com/npm/cli/issues/1109

**Comment by wraithgar** [comment] 2021-10-06 18:01
I did try to replicate this and `npm outdated --json > output` piped the outdated content to stdout.

**Comment by wraithgar** [comment] 2021-10-06 18:02
This may not be a problem, this PR is where we can find out

**Comment by ljharb** [comment] 2021-10-06 18:31
To me it seems identically a problem - or not a problem - regardless of the output format.

It will be very surprising to me if changing the output format has ANY impact on the exit code; the two are not semantically related.

**Comment by wraithgar** [comment] 2021-10-06 18:51
Perhaps @boostvolt can elaborate on how what is in place is broken?

**Comment by lukekarrys** [comment] 2021-10-07 00:30
> It will be very surprising to me if changing the output format has ANY impact on the exit code; the two are not semantically related.

I can confirm that this is not the current behavior, and I agree it shouldn't be. It might have been in the past, if I'm reading #1109 correctly? I would consider #1109 still resolved, since we now output `npm outdated --json` to stdout.

I think it's worth noting that there were other requests in #1109 to never have `npm outdated` set the exit code, regardless of `--json`. That's directly opposed to #2556 which was fixed in #3799. So I think that is what needs discussion here.

**Comment by ljharb** [comment] 2021-10-07 02:47
I have no opinion on whether outdated sets the exit code or not, altho i can see the argument for both.

I have a strong opinion that the output format should never dictate the exit code.

**Comment by boostvolt** [comment] 2021-10-07 09:57
When I use `npm outdated --json` with npm 7.24.2 I get: `Command failed with exit code 1: npm outdated --json` and the generated json  is printed as error to the console. But if I use `npm outdated` everything works fine. On npm 7.24.1 `npm outdated --json` as well as `npm outdated` worked without problems.

**Comment by lukekarrys** [comment] 2021-10-07 17:52
> When I use `npm outdated --json` with npm 7.24.2 I get: `Command failed with exit code 1: npm outdated --json` and the generated json is printed as error to the console. But if I use `npm outdated` everything works fine. On npm 7.24.1 `npm outdated --json` as well as `npm outdated` worked without problems.

I'm not able to reproduce that behavior. I see the only output printed to stdout and the only difference being the exit code set by the command. Here's what I'm getting in `7.24.1` vs `7.24.2`:

`7.24.1`
```sh
$ npm --version
7.24.1

$ npm outdated --json 2> /dev/null; echo "code: $?"
{
  "@npmcli/arborist": {
    "current": "3.0.0",
    "wanted": "2.10.0",
    "latest": "3.0.0",
    "dependent": "3844",
    "location": "/Users/lukekarrys/Desktop/npm-sandbox/3844/node_modules/@npmcli/arborist"
  }
}
code: 0

$ npm outdated 2> /dev/null; echo "code: $?"
Package           Current  Wanted  Latest  Location                       Depended by
@npmcli/arborist    3.0.0  2.10.0   3.0.0  node_modules/@npmcli/arborist  3844
code: 0
```

`7.24.2`
```sh
$ npm --version
7.24.2

$ npm outdated --json 2> /dev/null; echo "code: $?"
{
  "@npmcli/arborist": {
    "current": "3.0.0",
    "wanted": "2.10.0",
    "latest": "3.0.0",
    "dependent": "3844",
    "location": "/Users/lukekarrys/Desktop/npm-sandbox/3844/node_modules/@npmcli/arborist"
  }
}
code: 1

$ npm outdated 2> /dev/null; echo "code: $?"
Package           Current  Wanted  Latest  Location                       Depended by
@npmcli/arborist    3.0.0  2.10.0   3.0.0  node_modules/@npmcli/arborist  3844
code: 1
```

**Comment by boostvolt** [comment] 2021-10-08 07:04
I just tried this out as well. If I run the command in the terminal everything works. As soon as I call it as Node.js child process I get the exit code 1 error message.

**Comment by lukekarrys** [comment] 2021-10-11 19:12
@boostvolt thanks for the follow up information. As I mentioned in https://github.com/npm/cli/issues/3871#issuecomment-940371175, this is working as intended right now, so an [RFC issue](https://github.com/npm/rfcs) with some details on how this should be changed is the best way forward.

**Closed as completed by lukekarrys** 2021-10-11 19:12 UTC
Labels: Needs Discussion, Release 7.x, Bug
