### ISSUE TITLE
Keep package versions synced?

### ISSUE THREAD

**Issue by mokone91** [npm/cli#3757] opened 2021-09-15 11:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi there!
I going to migrate my monorepo from lerna to npm 7 and faced with the next issue:
when I doing npm --workspaces version pach - my packages updated as expected, but dependency in "package-a" still have old dependency version of "package-b"

how can i solve this issue?

**Comment by jharvey10** [comment] 2021-10-28 23:07
I'm not an npm maintainer or anything, but I hit the same thing moving off of Lerna. I think what you describe is the "value add" that Lerna offers.

`npm update` on its own won't pick up the new local version either. It'll instead resolve your dep against the latest version from the remote registry. It also appears that once a package has been resolved against a remote registry, it is not possible to "switch back" to a locally managed version by using another `npm update` command. You could instead run another `npm install` of the package and that will try the local version first if the version matches, but it's not ideal.

The way I'm going to approach this is to do something like:
```
npm --workspace <my_pkg> version patch
npm --workspace <some_workspace_that_uses_my_pkg> pkg set "dependencies.<my_pkg>=^x.y.z"
npm install
```
Where x.y.z is the new package version created by the version command.

I really wish that `npm update` would resolve against the new local dep first though. That would make this whole thing super simple. This looks to have a similar open issue over at https://github.com/npm/cli/issues/3940

**Comment by wraithgar** [comment] 2022-03-16 19:41
Closing as a duplicate of https://github.com/npm/cli/issues/3403

**Closed as completed by wraithgar** 2022-03-16 19:41 UTC
Labels: Release 7.x, Bug, Needs Triage
