### ISSUE TITLE
[BUG] Ctrl+C / SIGINT propagation to child processes broken since 10.3.0

### ISSUE THREAD

**Issue by sobolk** [npm/cli#7693] opened 2024-07-31 18:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When a binary / child process is called by `npx` the SIGINT handler registered in child script isn't called.

### Expected Behavior

When a binary / child process is called by `npx` the SIGINT handler registered in child script should be called.

### Steps To Reproduce

1. Create repro app

`package.json:`
```
{
  "name": "testapp037",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "bin": {
    "testapp037executable": "testapp037executable.js"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}

```

`testapp037executable.js`

```
#!/usr/bin/env node
console.log('In testapp037executable');

const intervalId = setInterval(() => { console.log('waiting')}, 1000);

process.once('SIGINT', async () => {

    // sleep to simulate delay / race condition.
    await new Promise(resolve => setTimeout(resolve, 5000));

    console.log('Handling SIGINT');
    clearInterval(intervalId)
    console.log('Interval Cleared');
});
```

2. Run with Node 18.19.1 ( and npm 10.2.4), observe output (child process handles sigint gracefully):
```
$ nvm use 18.19.1
Now using node v18.19.1 (npm v10.2.4)
$ npx testapp037executable
In testapp037executable
waiting
waiting
^Cwaiting
waiting
waiting
waiting
waiting
Handling SIGINT
Interval Cleared
$
```

3. Run with Node 18.20.0 (and npm 10.5.0), observe output (child process is killed eagerly):
```
$ nvm use 18.20.0
Now using node v18.20.0 (npm v10.5.0)
$ npx testapp037executable
In testapp037executable
waiting
waiting
waiting
waiting
^C
$
```

I also tried with npm `10.3.0` which seems to behave same way as `10.5.0`.
It seems that this commit might have caused it https://github.com/npm/cli/commit/796d1c7507d69382181e515d6c6987930c9ec636 .
It's listed in 10.3.0 changelog https://docs.npmjs.com/cli/v10/using-npm/changelog#1030-2024-01-10 .

### Environment

- npm: 10.2.4 works, 10.3.0+ don't
- Node.js: 18.x
- OS Name: MacOS
- System Model Name: Macbook Pro
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by milaninfy** [comment] 2024-07-31 19:58
**Closing:** this looks to be similar if not a duplicate of an existing issue, #7511. No need to track it twice.  If you believe your instance is unique, please provide further clarifying details.

**Closed as not planned by milaninfy** 2024-07-31 19:58 UTC
Labels: Bug, Duplicate

**Comment by sobolk** [comment] 2024-07-31 21:10
@milaninfy I saw the https://github.com/npm/cli/issues/7511 . It seems be the same root cause, just wanted to provide repro steps that match our use case. 
I.e. in our real use case we do have logic in sigint handler that takes longer to complete and seems to be running into race condition with parent process now. I.e. parent process seems to be hard killing our child process before child logic has a chance to complete.
