### ISSUE TITLE
[BUG] <npm update -g detox DELETED ALL NPM GLOBAL PACKAGES>

### ISSUE THREAD

**Issue by vitorbetani** [npm/cli#3882] opened 2021-10-12 19:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I was about to update my global package I has in my machine. Turns out, when I did it DELETED all my global packages.

![image](https://user-images.githubusercontent.com/12274383/137017120-997d5271-1387-4f66-a7bd-84538c33f71f.png)

After it, I had to reinstall the npm. 

Also looking at /usr/local/bin the npm wasn't there anymore.

I can't remember the exactly version I had , it was deleted, but my node version is 14.17.0 and I was using the npm version that comes with it.

### Expected Behavior

To update the global package

### Steps To Reproduce

1. npm update -g detox
2. See the attached image

### Environment

- OS: MAC OS 
- Node: 14.17.0
- npm: ????

**Comment by ljharb** [comment] 2021-10-12 19:44
`npm update -g` should error out, since there's no package.json to know how to do those updates.

Once your npm is deleted, you generally have to reinstall node to get it back, in my experience.

**Comment by lukekarrys** [comment] 2021-10-22 02:45
Closing as duplicate of #3175.

**Closed as completed by lukekarrys** 2021-10-22 02:45 UTC
Labels: Release 7.x, Bug, Needs Triage
