### ISSUE TITLE
[BUG] Run npm ci fails from dockerfile

### ISSUE THREAD

**Issue by DevHasher** [npm/cli#7682] opened 2024-07-24 08:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

![image](https://github.com/user-attachments/assets/b2cc20ad-b2ae-42df-84c5-5f0db9b6c0a0)
I'm running docker in my windows and the dockerfile code looks like the code on the above in attached image
On running 'docker-compose up -d --build',  i get the error as shown in the attached image on the bottom

Below is the data from log file
![image](https://github.com/user-attachments/assets/00a639a7-72ef-4e61-a401-3bc0bd437720)

### Expected Behavior

The build should pass and container should get created

### Environment

- npm: 10.5.0
- Node.js: 20.12.0
- OS Name: Windows 11
- System Model Name: Dell precision
- npm config:
 node bin location = C:\Program Files\nodejs\node.exe
; node version = v20.12.0
; npm local prefix = C:\Users\XXXXX\XXXXXXXXX\Documents\Proj\Proj1Repo\server
; npm version = 10.5.0

**Comment by milaninfy** [comment] 2024-07-24 13:09
@DevHasher This error can arise for a number of reasons; Please read [this document](https://github.com/npm/cli/wiki/%22cb()-never-called%3F-Exit-handler-never-called%3F-I'm-having-the-same-problem!%22) & provide as much information (package.json, package-lock.json, logs etc) as possible if you're able to **consistently reproduce** this error.

**Comment by milaninfy** [comment] 2024-07-31 12:46
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.

**Closed as not planned by milaninfy** 2024-07-31 12:46 UTC
Labels: Bug, Needs Triage
