### ISSUE TITLE
[QUESTION] How to properly get rid of npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents

### ISSUE THREAD

**Issue by OnkelTem** [npm/cli#1112] opened 2020-04-06 08:49 UTC
Hi all. 

I found several topics discussing how to get rid of messages like these:

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

and it seems like `npm i -f` is gonna "fix" this issue, but unfortunately what has never been explained is **what** exactly it's doing and **how** it's working.

Another advice was to run `npm i` with parameter `--no-optional`. 
Well, first - I'm not gonna skip other optionals as well just because npm complains about this one (which one cannot even install on Linux). 
And second - it's not convenient to run npm with additional `--no-optional` parameter every time, eh?

So my question is: how to get rid of this specific warning about "fsevents" which is not supposed to be installed on Linux? Is there a way to add some "rule" or something into package.json to not warn on standard OSes like Linux and keep it showing on proprietary ones?

**Comment by jakerobb** [comment] 2020-07-09 00:45
Hey @jacksonrayhamilton, it's been just about two years since [you said you'd do this in a year or two](https://github.com/npm/npm/pull/19198#issuecomment-403995460). How about resubmitting that PR? 🙂

**Comment by jacksonrayhamilton** [comment] 2020-07-09 01:52
:laughing: I was being sarcastic.

Someone else already resubmitted it here: https://github.com/npm/cli/pull/169

I stumbled on this blog post recently which alludes to the problem being fixed in v7: https://blog.npmjs.org/post/617484925547986944/npm-v7-series-introduction

> **Coming Attractions**
> In the coming npm v7 posts, we’ll cover:
> - Fixing the “noisy chokidar/fsevents” problem

Hopefully someone from the NPM org will stop by some of these open issues and confirm that explicitly.

**Comment by jakerobb** [comment] 2020-07-20 17:30
> 😆 I was being sarcastic.

Oh, I know. I was mostly trolling the project organizers for the ridiculousness that was this thread and the fact that this is still an issue. 🙃

> Someone else already resubmitted it here: #169
> 
> I stumbled on this blog post recently which alludes to the problem being fixed in v7: https://blog.npmjs.org/post/617484925547986944/npm-v7-series-introduction
> 
> > **Coming Attractions**
> > In the coming npm v7 posts, we’ll cover:
> > 
> > * Fixing the “noisy chokidar/fsevents” problem
> 
> Hopefully someone from the NPM org will stop by some of these open issues and confirm that explicitly.

Awesome!

**Comment by jacksonrayhamilton** [comment] 2020-07-31 19:33
https://github.com/npm/cli/pull/169#issuecomment-667304732

Yep, it’s fixed in v7.

**Comment by darcyclarke** [comment] 2021-06-02 22:07
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 22:07 UTC
Labels: Awaiting Information
