### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by achmad-sycn** [npm/cli#1006] opened 2020-03-11 09:31 UTC
16696 silly extract google-closure-compiler-java@20190415.0.0 extracted to /data/data/com.termux/files/home/craze/fir>16697 http fetch GET 200 https://registry.npmjs.org/firebase/-/firebase-7.5.2.tgz 336498ms                            16698 silly extract firebase@7.5.2 extracted to /data/data/com.termux/files/home/craze/firebaseui-web/node_modules/.s>16699 http fetch GET 200 https://registry.npmjs.org/google-closure-compiler-linux/-/google-closure-compiler-linux-201>16700 silly extract google-closure-compiler-linux@20190415.0.0 extracted to /data/data/com.termux/files/home/craze/fi>16701 http fetch GET 200 https://registry.npmjs.org/google-closure-library/-/google-closure-library-20190415.0.0.tgz 316702 silly extract google-closure-library@20190415.0.0 extracted to /data/data/com.termux/files/home/craze/firebaseu>16703 timing npm Completed in 397469ms                                                                                16704 error cb() never called!                                                                                        16705 error This is an error with npm itself. Please report this error at:                                            16706 error <https://npm.community>

**Comment by DanielRuf** [comment] 2020-03-12 23:05
Duplicate of #417

**Closed as completed** 2020-10-30 20:56 UTC
