### ISSUE TITLE
[BUG] can't install

### ISSUE THREAD

**Issue by rmrfchik** [npm/cli#7565] opened 2024-05-29 08:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Running on Debian box:
```
$ curl -qL https://www.npmjs.com/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3755  100  3755    0     0   8792      0 --:--:-- --:--:-- --:--:--  8793
fetching: https://registry.npmjs.org/npm/-/npm-10.8.0.tgz
removing existing npm
installing npm@latest
npm error code EACCES
npm error syscall mkdir
npm error path /usr/lib/node_modules
npm error errno -13
npm error [Error: EACCES: permission denied, mkdir '/usr/lib/node_modules'] {
npm error   errno: -13,
npm error   code: 'EACCES',
npm error   syscall: 'mkdir',
npm error   path: '/usr/lib/node_modules'
npm error }
npm error
npm error The operation was rejected by your operating system.
npm error It is likely you do not have the permissions to access this file as the current user
npm error
npm error If you believe this might be a permissions issue, please double-check the
npm error permissions of the file and its containing directories, or try running
npm error the command again as root/Administrator.
npm error A complete log of this run can be found in: /home/paul/.npm/_logs/2024-05-29T08_18_06_311Z-debug-0.log
failed!
```

### Expected Behavior

Installation completes successfully

### Steps To Reproduce

1. Debian unstable
2. 
3. Run ```curl -qL https://www.npmjs.com/install.sh | sh```
4. See error Error: EACCES: permission denied, mkdir '/usr/lib/node_modules'

### Environment

- npm: 10.8.0
- Node.js: v20.10.0
- OS Name: Debian
- System Model Name: Unstable
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by milaninfy** [comment] 2024-05-29 12:45
@rmrfchik This looks like permissions issue. Try running installation with proper access e.g. Root/Admin. 

> npm error If you believe this might be a permissions issue, please double-check the
npm error permissions of the file and its containing directories, or try running
npm error the command again as root/Administrator.

**Comment by rmrfchik** [comment] 2024-05-30 08:53
npm must be install as root?
(btw, other debian box hasn't this problem and npm install into ~/.local/bin, i dunno why).

**Comment by milaninfy** [comment] 2024-05-31 12:29
I think if the current user has appropriate permission to install and access to this directory then it would work.

**Comment by milaninfy** [comment] 2024-06-07 00:23
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.

**Closed as not planned by milaninfy** 2024-06-07 00:23 UTC
Labels: Bug, Needs Triage
