### ISSUE TITLE
[BUG] ERESOLVE peer dep conflict reported when no conflict exists

### ISSUE THREAD

**Issue by ljharb** [npm/cli#3138] opened 2021-04-23 21:56 UTC
### Current Behavior:
in `eslint-plugin-react`'s repo, on master, i ran `npx npm@7 install --save-dev @types/eslint @types/node eslint-plugin-eslint-plugin@3 semver sinon typescript typescript-eslint-parser`.

I got https://gist.github.com/ljharb/dc643e6f094d5dfc912633a5e55637ab as output. Note:
```
npm ERR! Conflicting peer dependency: eslint@7.24.0
npm ERR! node_modules/eslint
npm ERR!   peer eslint@"^7.0.0" from eslint-plugin-eslint-plugin@3.0.2
```

### Expected Behavior:
It should have installed and saved these dev deps. `^7.0.0` is compatible with `v7.24.0`.

### Steps To Reproduce:
Clone the repo, run `npm install`, then run the above command.

### Environment:
- OS: Mac
- Node: 15.14.0
- npm: 7.11.0 and v7.10.0

(this does _ not_ appear to be the same issue as #3113 or #2823)

**Comment by darcyclarke** [comment] 2021-06-11 18:20
@ljharb can you reproduce on latest? (ie. `7.17.0`) I know we've made numerous changes/bug fixes since `7.10.0`

**Comment by ljharb** [comment] 2021-06-12 07:03
@darcyclarke yes, i can reproduce it on latest npm:
```sh
code ERESOLVE
ERESOLVE unable to resolve dependency tree

Found: eslint-plugin-eslint-plugin@2.3.0
node_modules/eslint-plugin-eslint-plugin
  dev eslint-plugin-eslint-plugin@"3" from the root project

Could not resolve dependency:
dev eslint-plugin-eslint-plugin@"3" from the root project

Conflicting peer dependency: eslint@7.28.0
node_modules/eslint
  peer eslint@"^7.0.0" from eslint-plugin-eslint-plugin@3.0.3
  node_modules/eslint-plugin-eslint-plugin
    dev eslint-plugin-eslint-plugin@"3" from the root project
```

<details>
<summary>`eresolve-report.txt`:</summary>

```json
# npm resolution error report

2021-06-12T07:00:59.767Z

Found: eslint-plugin-eslint-plugin@2.3.0
node_modules/eslint-plugin-eslint-plugin
  dev eslint-plugin-eslint-plugin@"3" from the root project

Could not resolve dependency:
dev eslint-plugin-eslint-plugin@"3" from the root project

Conflicting peer dependency: eslint@7.28.0
node_modules/eslint
  peer eslint@"^7.0.0" from eslint-plugin-eslint-plugin@3.0.3
  node_modules/eslint-plugin-eslint-plugin
    dev eslint-plugin-eslint-plugin@"3" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

Raw JSON explanation object:

{
  "code": "ERESOLVE",
  "current": {
    "name": "eslint-plugin-eslint-plugin",
    "version": "2.3.0",
    "location": "node_modules/eslint-plugin-eslint-plugin",
    "isWorkspace": false,
    "dependents": [
      {
        "type": "dev",
        "name": "eslint-plugin-eslint-plugin",
        "spec": "3",
        "error": "INVALID",
        "from": {
          "location": "$PWD"
        }
      }
    ]
  },
  "currentEdge": null,
  "edge": {
    "type": "dev",
    "name": "eslint-plugin-eslint-plugin",
    "spec": "3",
    "error": "INVALID",
    "from": {
      "location": "$PWD"
    }
  },
  "peerConflict": {
    "name": "eslint",
    "version": "7.28.0",
    "whileInstalling": {
      "name": "eslint-plugin-react",
      "version": "7.24.0",
      "path": "$PWD"
    },
    "location": "node_modules/eslint",
    "isWorkspace": false,
    "dependents": [
      {
        "type": "peer",
        "name": "eslint",
        "spec": "^7.0.0",
        "from": {
          "name": "eslint-plugin-eslint-plugin",
          "version": "3.0.3",
          "whileInstalling": {
            "name": "eslint-plugin-react",
            "version": "7.24.0",
            "path": "$PWD"
          },
          "location": "node_modules/eslint-plugin-eslint-plugin",
          "isWorkspace": false,
          "dependents": [
            {
              "type": "dev",
              "name": "eslint-plugin-eslint-plugin",
              "spec": "3",
              "from": {
                "location": "$PWD"
              }
            }
          ]
        }
      }
    ]
  },
  "strictPeerDeps": false,
  "force": false
}
```
</details>

**Comment by isaacs** [comment] 2021-07-27 22:59
This is a reporting error.

```
$ npm view @typescript-eslint/parser@"^2.34.0" peerDependencies
{ eslint: '^5.0.0 || ^6.0.0' }

$ npm view eslint-plugin-eslint-plugin@3 peerDependencies
eslint-plugin-eslint-plugin@3.0.0 { eslint: '^7.0.0' }
eslint-plugin-eslint-plugin@3.0.1 { eslint: '^7.0.0' }
eslint-plugin-eslint-plugin@3.0.2 { eslint: '^7.0.0' }
eslint-plugin-eslint-plugin@3.0.3 { eslint: '^7.0.0' }
eslint-plugin-eslint-plugin@3.1.0 { eslint: '^7.0.0' }
eslint-plugin-eslint-plugin@3.2.0 { eslint: '^7.0.0' }
eslint-plugin-eslint-plugin@3.3.0 { eslint: '^7.0.0' }
eslint-plugin-eslint-plugin@3.4.0 { eslint: '^7.0.0' }
eslint-plugin-eslint-plugin@3.5.0 { eslint: '^7.0.0' }
eslint-plugin-eslint-plugin@3.5.1 { eslint: '^7.0.0' }
```

You're trying to use `@typescript-eslint/parser@"^2.34.0"` alongside `eslint-plugin-eslint-plugin@3`, but these two have incompatible peer deps.

So the `ERESOLVE` is the correct outcome, but the reporting here leaves much to be desired.

I'm in the midst of upgrading the cli to @npmcli/arborist@2.8.0, and the report got even more broken. 😅  So I'm going to dig into that now.

**Comment by isaacs** [comment] 2021-07-27 23:12
Ok, the error was easy to work around.  Caused by the ERESOLVE explanations getting a bit more useful in arborist 2.8, ironically enough, but no longer squishing a direct conflict in with the extended peerDep conflict, which was losing some information.

Fixed report looks like this, and I'm going to call this a by-design crash, with a reporting error that'll be fixed on the next release:

```
$ npm i --save-dev @types/eslint @types/node eslint-plugin-eslint-plugin@3 semver sinon typescript typescript-eslint-parser
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: eslint-plugin-react@7.24.0
npm ERR! Found: eslint@6.8.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^3 || ^4 || ^5 || ^6 || ^7" from the root project
npm ERR!   peer eslint@"^5.0.0 || ^6.0.0" from @typescript-eslint/parser@2.34.0
npm ERR!   node_modules/@typescript-eslint/parser
npm ERR!     dev @typescript-eslint/parser@"^2.34.0" from the root project
npm ERR!   2 more (eslint-config-airbnb-base, eslint-plugin-import)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev eslint-plugin-eslint-plugin@"3" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: eslint@7.31.0
npm ERR! node_modules/eslint
npm ERR!   peer eslint@"^7.0.0" from eslint-plugin-eslint-plugin@3.5.1
npm ERR!   node_modules/eslint-plugin-eslint-plugin
npm ERR!     dev eslint-plugin-eslint-plugin@"3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/isaacs/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/isaacs/.npm/_logs/2021-07-27T23_10_48_034Z-debug.log
```

**Comment by ljharb** [comment] 2021-07-28 15:36
I see the conflict, thanks.

**Closed as completed** 2021-07-29 16:06 UTC
Labels: Release 7.x, Bug
