### ISSUE TITLE
Problem installing sqlite3

### ISSUE THREAD

**Issue by ghost** [npm/cli#715] opened 2020-01-21 13:50 UTC
# It sends an error
I was gonna install sqlite3 through npm but suddenly an error occured
![Screenshot_20200121-214553](https://user-images.githubusercontent.com/59103946/72810002-bbfefd00-3c97-11ea-8ca4-17909af74d21.jpg)

**Comment by ljharb** [comment] 2020-01-21 17:11
Duplicate of #417

**Closed as completed** 2020-10-14 02:09 UTC
