### ISSUE TITLE
[BUG] Installing dependencies from git+ssh is broken in 6.14.0

### ISSUE THREAD

**Issue by eonicle** [npm/cli#948] opened 2020-02-26 08:35 UTC
# What / Why
> When installing any dependency via git+ssh// protocol with colon in URL, I get ERR_INVALID_URL error.
Install works when downgrading to 6.13.7.

## Where
* Module installed from private GitLab instance

### Current Behavior

* Install fails (debug log attached)

> 0 info it worked if it ends with ok
1 verbose cli [ '/Users/REDACTED/.nvm/versions/node/v10.16.3/bin/node',
1 verbose cli   '/Users/REDACTED/.nvm/versions/node/v10.16.3/bin/npm',
1 verbose cli   'i',
1 verbose cli   '--package-lock-only' ]
2 info using npm@6.14.0
3 info using node@v10.16.3
4 verbose npm-session a7e85c5c83ee5136
5 silly install runPreinstallTopLevelLifecycles
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 verbose stack TypeError [ERR_INVALID_URL]: Invalid URL: git+ssh://git@mygit.domain.com:group/path/project.git#1.0.0
8 verbose stack     at onParseError (internal/url.js:241:17)
8 verbose stack     at new URL (internal/url.js:319:5)
8 verbose stack     at parseGitUrl (/Users/REDACTED/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/hosted-git-info/index.js:112:20)
8 verbose stack     at fromUrl (/Users/REDACTED/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/hosted-git-info/index.js:43:16)
8 verbose stack     at Function.module.exports.fromUrl (/Users/REDACTED/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/hosted-git-info/index.js:32:18)
8 verbose stack     at resolve (/Users/REDACTED/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:73:28)
8 verbose stack     at npa (/Users/REDACTED/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:52:10)
8 verbose stack     at computeVersionSpec (/Users/REDACTED/.nvm/versions/node/v10.16.3/lib/node_modules/npm/lib/install/deps.js:314:17)
8 verbose stack     at Installer.normalizeCurrentTree (/Users/REDACTED/.nvm/versions/node/v10.16.3/lib/node_modules/npm/lib/install.js:410:68)
8 verbose stack     at Array.<anonymous> (/Users/REDACTED/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
8 verbose stack     at LOOP (/Users/REDACTED/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
8 verbose stack     at /Users/REDACTED/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
8 verbose stack     at iferr (/Users/REDACTED/.nvm/versions/node/v10.16.3/lib/node_modules/npm/lib/install.js:368:5)
8 verbose stack     at a (/Users/REDACTED/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/iferr/iferr.js:3:64)
8 verbose stack     at asyncMap (/Users/REDACTED/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/slide/lib/async-map.js:27:18)
8 verbose stack     at exports.getAllMetadata (/Users/REDACTED/.nvm/versions/node/v10.16.3/lib/node_modules/npm/lib/install/deps.js:224:3)
9 verbose cwd /Users/REDACTED/git-repos/content-library-ui
10 verbose Darwin 19.3.0
11 verbose argv "/Users/REDACTED/.nvm/versions/node/v10.16.3/bin/node" "/Users/REDACTED/.nvm/versions/node/v10.16.3/bin/npm" "i" "--package-lock-only"
12 verbose node v10.16.3
13 verbose npm  v6.14.0
14 error code ERR_INVALID_URL
15 error Invalid URL: git+ssh://git@mygit.domain.com:group/path/project.git#1.0.0
16 verbose exit [ 1, true ]

### Steps to Reproduce
* Install any dependency with `npm i ` from URL like git+ssh://git@mygit.domain.com:group/path/project.git#1.0.0
* Changing colon to slash, install works as expected: git+ssh://git@mygit.domain.com/group/path/project.git#1.0.0

### Expected Behavior
* Install should work successfully

## References
* Issue seem to be caused by this [commit](https://github.com/npm/cli/commit/760214606d7cc4dfbb2f07e47a7e6f319a3f333d)

**Comment by jwandrews** [comment] 2020-10-20 15:33
Also present in `npm@7`

**Comment by jwandrews** [comment] 2020-10-20 15:57
it seems to be related to using non-'standard' git hosts. so anything other than `github.com`/`gist.github.com`, `gitlab.com`, `bitbucket.org`. 

basically any git host thats not configured in this file: https://github.com/npm/hosted-git-info/blob/latest/git-host-info.js

**Comment by jwandrews** [comment] 2020-10-20 16:03
RunKit example: https://runkit.com/embed/d9o6efuy12dp

**Comment by Idrinth** [comment] 2020-11-18 06:18
still an issue with 7.0.8

**Comment by ljharb** [comment] 2020-11-18 06:46
@Idrinth what about v7.0.12?

**Comment by darcyclarke** [comment] 2021-06-02 21:25
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 21:25 UTC
Labels: Release 6.x, Bug
