### ISSUE TITLE
 cb() never called!

### ISSUE THREAD

**Issue by davidAg9** [npm/cli#957] opened 2020-02-27 14:01 UTC
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'react-native',
1 verbose cli   '-g'
1 verbose cli ]
2 info using npm@6.13.7
3 info using node@v13.9.0
4 verbose npm-session 79805b57611e048e
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/react-native 4310ms (from cache)
8 silly pacote tag manifest for react-native@latest fetched in 4344ms
9 timing stage:loadCurrentTree Completed in 4371ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule react-native@0.61.5 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/@react-native-community%2fcli 830ms (from cache)
18 silly pacote range manifest for @react-native-community/cli@^3.0.0 fetched in 836ms
19 silly resolveWithNewModule @react-native-community/cli@3.2.0 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/art 5692ms (from cache)
21 silly pacote range manifest for art@^0.10.0 fetched in 5693ms
22 silly resolveWithNewModule art@0.10.3 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/@react-native-community%2fcli-platform-ios 5916ms (from cache)
24 http fetch GET 304 https://registry.npmjs.org/escape-string-regexp 5913ms (from cache)
25 silly pacote range manifest for @react-native-community/cli-platform-ios@^3.0.0 fetched in 5920ms
26 silly resolveWithNewModule @react-native-community/cli-platform-ios@3.2.0 checking installable status
27 silly pacote range manifest for escape-string-regexp@^1.0.5 fetched in 5917ms
28 silly resolveWithNewModule escape-string-regexp@1.0.5 checking installable status
29 http fetch GET 304 https://registry.npmjs.org/event-target-shim 5110ms (from cache)
30 silly pacote range manifest for event-target-shim@^5.0.1 fetched in 5111ms
31 silly resolveWithNewModule event-target-shim@5.0.1 checking installable status
32 http fetch GET 304 https://registry.npmjs.org/@react-native-community%2fcli-platform-android 6511ms (from cache)
33 silly pacote range manifest for @react-native-community/cli-platform-android@^3.0.0 fetched in 6513ms
34 silly resolveWithNewModule @react-native-community/cli-platform-android@3.1.4 checking installable status
35 http fetch GET 304 https://registry.npmjs.org/invariant 2293ms (from cache)
36 http fetch GET 304 https://registry.npmjs.org/abort-controller 8240ms (from cache)
37 http fetch GET 304 https://registry.npmjs.org/jsc-android 1729ms (from cache)
38 http fetch GET 304 https://registry.npmjs.org/fbjs 2545ms (from cache)
39 http fetch GET 304 https://registry.npmjs.org/create-react-class 8239ms (from cache)
40 http fetch GET 304 https://registry.npmjs.org/hermes-engine 2322ms (from cache)
41 http fetch GET 304 https://registry.npmjs.org/base64-js 8241ms (from cache)
42 http fetch GET 304 https://registry.npmjs.org/@babel%2fruntime 8248ms (from cache)
43 http fetch GET 304 https://registry.npmjs.org/connect 8242ms (from cache)
44 http fetch GET 304 https://registry.npmjs.org/fbjs-scripts 2327ms (from cache)
45 silly pacote range manifest for invariant@^2.2.4 fetched in 2302ms
46 silly resolveWithNewModule invariant@2.2.4 checking installable status
47 silly pacote range manifest for abort-controller@^3.0.0 fetched in 8249ms
48 silly resolveWithNewModule abort-controller@3.0.0 checking installable status
49 silly pacote range manifest for fbjs@^1.0.0 fetched in 2557ms
50 silly resolveWithNewModule fbjs@1.0.0 checking installable status
51 silly pacote range manifest for jsc-android@^245459.0.0 fetched in 1742ms
52 silly resolveWithNewModule jsc-android@245459.0.0 checking installable status
53 silly pacote range manifest for create-react-class@^15.6.3 fetched in 8252ms
54 silly resolveWithNewModule create-react-class@15.6.3 checking installable status
55 silly pacote range manifest for base64-js@^1.1.2 fetched in 8255ms
56 silly resolveWithNewModule base64-js@1.3.1 checking installable status
57 silly pacote range manifest for connect@^3.6.5 fetched in 8258ms
58 silly resolveWithNewModule connect@3.7.0 checking installable status
59 silly pacote range manifest for @babel/runtime@^7.0.0 fetched in 8268ms
60 silly resolveWithNewModule @babel/runtime@7.8.4 checking installable status
61 silly pacote range manifest for fbjs-scripts@^1.1.0 fetched in 2342ms
62 silly resolveWithNewModule fbjs-scripts@1.2.0 checking installable status
63 http fetch GET 304 https://registry.npmjs.org/prop-types 1162ms (from cache)
64 http fetch GET 304 https://registry.npmjs.org/promise 1167ms (from cache)
65 http fetch GET 304 https://registry.npmjs.org/metro-source-map 1174ms (from cache)
66 http fetch GET 304 https://registry.npmjs.org/metro-react-native-babel-transformer 1178ms (from cache)
67 http fetch GET 304 https://registry.npmjs.org/nullthrows 1174ms (from cache)
68 http fetch GET 304 https://registry.npmjs.org/react-refresh 1165ms (from cache)
69 http fetch GET 304 https://registry.npmjs.org/pretty-format 1172ms (from cache)
70 http fetch GET 304 https://registry.npmjs.org/metro-babel-register 1182ms (from cache)
71 http fetch GET 304 https://registry.npmjs.org/react-devtools-core 1171ms (from cache)
72 silly pacote range manifest for prop-types@^15.7.2 fetched in 1173ms
73 silly resolveWithNewModule prop-types@15.7.2 checking installable status
74 silly pacote range manifest for promise@^7.1.1 fetched in 1181ms
75 silly resolveWithNewModule promise@7.3.1 checking installable status
76 silly pacote range manifest for metro-source-map@^0.56.0 fetched in 1186ms
77 silly resolveWithNewModule metro-source-map@0.56.4 checking installable status
78 silly pacote range manifest for metro-react-native-babel-transformer@^0.56.0 fetched in 1196ms
79 silly resolveWithNewModule metro-react-native-babel-transformer@0.56.4 checking installable status
80 silly pacote range manifest for nullthrows@^1.1.0 fetched in 1192ms
81 silly resolveWithNewModule nullthrows@1.1.1 checking installable status
82 silly pacote range manifest for pretty-format@^24.7.0 fetched in 1189ms
83 silly resolveWithNewModule pretty-format@24.9.0 checking installable status
84 silly pacote range manifest for metro-babel-register@^0.56.0 fetched in 1198ms
85 silly resolveWithNewModule metro-babel-register@0.56.4 checking installable status
86 silly pacote range manifest for react-refresh@^0.4.0 fetched in 1184ms
87 silly resolveWithNewModule react-refresh@0.4.2 checking installable status
88 silly pacote range manifest for react-devtools-core@^3.6.3 fetched in 1184ms
89 silly resolveWithNewModule react-devtools-core@3.6.3 checking installable status
90 http fetch GET 304 https://registry.npmjs.org/whatwg-fetch 663ms (from cache)
91 http fetch GET 304 https://registry.npmjs.org/stacktrace-parser 666ms (from cache)
92 http fetch GET 304 https://registry.npmjs.org/regenerator-runtime 673ms (from cache)
93 silly pacote range manifest for whatwg-fetch@^3.0.0 fetched in 665ms
94 silly resolveWithNewModule whatwg-fetch@3.0.0 checking installable status
95 silly pacote range manifest for stacktrace-parser@^0.1.3 fetched in 669ms
96 silly resolveWithNewModule stacktrace-parser@0.1.9 checking installable status
97 silly pacote range manifest for regenerator-runtime@^0.13.2 fetched in 675ms
98 silly resolveWithNewModule regenerator-runtime@0.13.3 checking installable status
99 http fetch GET 304 https://registry.npmjs.org/scheduler 671ms (from cache)
100 silly pacote version manifest for scheduler@0.15.0 fetched in 675ms
101 silly resolveWithNewModule scheduler@0.15.0 checking installable status
102 timing npm Completed in 2499711ms
103 error cb() never called!
104 error This is an error with npm itself. Please report this error at:
105 error <https://npm.community>

**Comment by eglcode** [comment] 2020-02-27 20:51
npm config set proxy http://proxy.company.com:8080
npm config set https-proxy http://proxy.company.com:8080

https://jjasonclark.com/how-to-setup-node-behind-web-proxy/

**Comment by DanielRuf** [comment] 2020-03-09 08:56
Duplicate of #417

**Comment by davidAg9** [comment] 2020-03-13 14:21
thank you i try all these

**Closed as completed** 2021-03-26 04:32 UTC
