### ISSUE TITLE
[BUG] Inconsistent Dependency Resolution in Nested Workspaces with Peer Dependencies

### ISSUE THREAD

**Issue by rsalim0** [npm/cli#7817] opened 2024-10-05 10:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

In NPM workspaces with nested packages, peer dependencies are inconsistently resolved. This causes:
- Multiple versions of the same peer dependency to be installed across sub-packages.
- Peer dependencies missing from some packages, leading to runtime errors.
- Conflicting versions of shared dependencies within the same workspace.

### Expected Behavior

NPM should resolve peer dependencies consistently in nested workspaces, avoiding duplication or missing dependencies, and ensuring the correct versions are installed across the workspace.

### Steps To Reproduce

1. Create an NPM workspace `A` with two nested packages `B` and `C`.
2. Declare a peer dependency `D` in both `B` and `C`, but with different versions.
3. Run `npm install` in the workspace root.
4. Check `node_modules` in `B` and `C` for multiple versions of `D` or missing dependencies.

### Environment

- **NPM version**: 8.x
- **Node version**: 16.x
- **OS**: macOS/Windows/Linux
- **Package Manager**: NPM with workspaces enabled

**Comment by milaninfy** [comment] 2024-10-07 13:16
Could you please try to replicate this issue on latest npm (10.9.0) and relevant version of node and edit the information in the issue ?

**Comment by milaninfy** [comment] 2024-10-16 13:31
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.

**Closed as not planned by milaninfy** 2024-10-16 13:31 UTC
Labels: Bug, Needs Triage
