### ISSUE TITLE
[BUG] <title> error in RUN npm install

### ISSUE THREAD

**Issue by Weighshell** [npm/cli#7769] opened 2024-09-08 08:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

When building image with the command 'docker build -t welcome-to-docker .' there's always an error saying' ERROR [6/6] RUN npm install     && npm install -g serve     && npm run build     && rm -fr node_modules      279.7s'

### Steps To Reproduce

1. In this environment...
2. With this config...
3. Run '...'
4. See error...

### Environment

- npm:
- Node.js:
- OS Name:
- System Model Name:
- npm config:
```ini
; copy and paste output from `npm config ls` here
```

**Comment by milaninfy** [comment] 2024-09-09 13:23
@Weighshell If the issue is related npm cli, then please provide all the important details like steps to reproduce the issue, logs, failure message or actual error when it fails etc. Providing these important details will help us triage this issue.

**Closing** this as there are not enough information to recreate the issue. Please create a new issue with all the details of our [issue template](https://github.com/npm/cli/issues/new/choose) &/or review our [contributing guidelines](https://github.com/npm/cli/blob/latest/CONTRIBUTING.md#reporting-bugs).

**Closed as not planned by milaninfy** 2024-09-09 13:23 UTC
Labels: Bug, Needs Triage
