### ISSUE TITLE
[BUG] peer dependency not auto install in workspace

### ISSUE THREAD

**Issue by lake2** [npm/cli#4718] opened 2022-04-09 16:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Steps To Reproduce

1. git clone https://github.com/lake2/npm_bug
2. cd ./npm_bug/b
3. npm i
4. antd is not be auto installed in b/node_modules

see https://github.com/npm/rfcs/blob/main/implemented/0025-install-peer-deps.md

### Environment

- npm: 8.1.0
- Node.js: v16.12.0
- OS Name: windows
- System Model Name: windows
- npm config:
```ini
; "user" config from C:\Users\LH\.npmrc

//registry.npmjs.org/:_authToken = (protected)
registry = "https://registry.npmjs.org/"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = D:\work\npm_bug\b
; HOME = C:\Users\LH
; Run `npm config ls -l` to show all defaults.
```

**Comment by ljharb** [comment] 2022-04-09 16:12
Can you try npm v8.6?

**Comment by lake2** [comment] 2022-04-09 16:15
I try npm v8.6, problem still exists.

**Comment by lukekarrys** [comment] 2022-04-10 07:27
Closing as a duplicate of #2650.

**Closed as completed by lukekarrys** 2022-04-10 07:27 UTC
Labels: Release 8.x, Bug, Priority 2
