### ISSUE TITLE
[BUG] NPM not running my script "This is related to npm not being able to find a file."

### ISSUE THREAD

**Issue by harrisonhoward** [npm/cli#3786] opened 2021-09-23 04:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The resulting error is from running any script, no matter the project.

#### package.json
The error results from all packages. However, this was the package mentioned in "Full Log".
```json
{
    "name": "mongo-web-app",
    "version": "1.0.0",
    "description": "A MongoDB web application",
    "main": "./index.js",
    "scripts": {
        "server": "node backend/server"
    },
    "repository": {
        "type": "git",
        "url": "git+https://github.com/Forbidden-Duck/mongo-web-app.git"
    },
    "author": "Harrison Howard (Forbidden-Duck)",
    "license": "MIT",
    "bugs": {
        "url": "https://github.com/Forbidden-Duck/mongo-web-app/issues"
    },
    "homepage": "https://github.com/Forbidden-Duck/mongo-web-app#readme",
    "dependencies": {
        "@forbidden_duck/super-mongo": "^1.0.1",
        "body-parser": "^1.19.0",
        "cookie-parser": "^1.4.5",
        "cors": "^2.8.5",
        "dotenv": "^10.0.0",
        "express": "^4.17.1",
        "express-rate-limit": "^5.3.0",
        "helmet": "^4.6.0",
        "http-errors": "^1.8.0",
        "jsonwebtoken": "^8.5.1",
        "moment": "^2.29.1",
        "mongo-sanitize": "^1.1.0",
        "mongodb": "^4.1.2",
        "on-finished": "^2.3.0",
        "on-headers": "^1.0.2",
        "rate-limit-mongo": "^2.3.2"
    },
    "devDependencies": {
        "@types/express": "^4.17.13",
        "@types/express-rate-limit": "^5.1.3",
        "@types/jsonwebtoken": "^8.5.5"
    }
}

```

#### Full Log
```
0 verbose cli [
0 verbose cli   'D:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Users\\My Name\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'run',
0 verbose cli   'server'
0 verbose cli ]
1 info using npm@7.24.0
2 info using node@v14.17.6
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:C:\Users\My Name\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:C:\Users\My Name\Desktop\mongo-web-app\.npmrc Completed in 0ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:C:\Users\My Name\.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:C:\Users\My Name\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 10ms
19 timing npm:load:configload Completed in 10ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 0ms
22 timing config:load:flatten Completed in 3ms
23 timing npm:load:cleanupLog Completed in 1ms
24 timing npm:load:configScope Completed in 0ms
25 timing npm:load:projectScope Completed in 1ms
26 timing npm:load Completed in 17ms
27 timing command:run-script Completed in 30ms
28 verbose stack Error: spawn bash ENOENT
28 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
28 verbose stack     at onErrorNT (internal/child_process.js:467:16)
28 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:82:21)
29 verbose pkgid mongo-web-app@1.0.0
30 verbose cwd C:\Users\My Name\Desktop\mongo-web-app
31 verbose Windows_NT 10.0.19042
32 verbose argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\My Name\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "server"
33 verbose node v14.17.6
34 verbose npm  v7.24.0
35 error code ENOENT
36 error syscall spawn bash
37 error path C:\Users\My Name\Desktop\mongo-web-app
38 error errno -4058
39 error enoent spawn bash ENOENT
40 error enoent This is related to npm not being able to find a file.
41 verbose exit -4058

```

#### Notes
I did a fresh install of Node and NPM (deleting all traces). I did a fresh install of the project and manually installed it all again (inc. [the repository](https://github.com/Forbidden-Duck/mongo-web-app)).
The script used is just `node backend/server`. **yes it works without npm**

### Expected Behavior

Run my scripts without the resulting error.

### What I have tried

* Re-installing Node and NPM (Including on installed version V6)
* `npm cache clear -f`
* Deleting node_modules, package-lock.json & package.json
* Running scripts in other projects that I have confirmed to work
* Create a project with just the package.json and index.js

### Steps To Reproduce

1. Install Node 14.17.6
2. Install npm@7.24.0
3. Run `npm init -y`
4. Create a script (can be anything, doesn't matter what the script does)
5. Run the script `npm run <script-name>`

### Environment

- OS: Windows 10 @ v20H2
- Node: 14.17.6
- npm: 7.24.0

**Comment by harrisonhoward** [comment] 2021-09-23 06:04
Using `GIT BASH` works completely fine with NPM.

**Comment by gauravshah27** [comment] 2021-09-23 23:35
I have a similar issue when running with npm 7.24.0 and node 14.17.6 (same as @Forbidden-Duck) . Here is the error log that I am seeing:

`npm verb stack CwdError: ENOENT: Cannot cd into 'C:/Users/.../Downloads/npm7-dummy/node_modules/@jest/reporters/node_modules/has-flag'
npm verb stack     at C:\...\node_modules\npm\node_modules\tar\lib\mkdir.js:43:12
npm verb stack     at callback (C:\...\node_modules\npm\node_modules\graceful-fs\polyfills.js:299:20)
npm verb stack     at FSReqCallback.oncomplete (fs.js:192:21)
npm verb cwd C:\Users\...\Downloads\npm7-dummy
npm verb Windows_NT 10.0.14393
npm verb argv "C:\...\\nodejs14\\latest\\node.exe" "C:\...\\node_modules\\npm\\bin\\npm-cli.js" "i" "@craco/craco@6.2.0" "--save-dev" "--verbose"
npm verb node v14.17.6
npm verb npm  v7.24.0
npm ERR! code ENOENT
npm ERR! path C:/Users/.../Downloads/npm7-dummy/node_modules/@jest/reporters/node_modules/has-flag
npm ERR! enoent ENOENT: Cannot cd into 'C:/Users/.../Downloads/npm7-dummy/node_modules/@jest/reporters/node_modules/has-flag'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
npm verb exit 1
npm timing npm Completed in 86957ms
npm verb unfinished npm timer reify 1632439453283
npm verb unfinished npm timer reify:unpack 1632439503987
npm verb unfinished npm timer reifyNode:node_modules/@jest/reporters/node_modules/has-flag 1632439504158
npm verb unfinished npm timer reifyNode:node_modules/@jest/reporters/node_modules/type-fest 1632439504159
npm verb unfinished npm timer reifyNode:node_modules/@jest/reporters/node_modules/read-pkg-up 1632439504159
npm verb unfinished npm timer reifyNode:node_modules/@jest/reporters/node_modules/color-name 1632439504159
npm verb unfinished npm timer reifyNode:node_modules/@jest/reporters/node_modules/color-convert 1632439504159
npm verb unfinished npm timer reifyNode:node_modules/@jest/reporters/node_modules/supports-color 1632439504159
npm verb unfinished npm timer reifyNode:node_modules/@jest/reporters/node_modules/ansi-styles 1632439504159
npm verb unfinished npm timer reifyNode:node_modules/@jest/reporters/node_modules/source-map 1632439504160
npm verb unfinished npm timer reifyNode:node_modules/@jest/reporters/node_modules/jest-resolve 1632439504160
npm verb unfinished npm timer reifyNode:node_modules/@jest/reporters/node_modules/chalk 1632439504160
npm verb unfinished npm timer reifyNode:node_modules/@jest/core/node_modules/has-flag 1632439504162
npm verb unfinished npm timer reifyNode:node_modules/@jest/core/node_modules/type-fest 1632439504162
npm verb unfinished npm timer reifyNode:node_modules/@jest/core/node_modules/read-pkg-up 1632439504162
npm verb unfinished npm timer reifyNode:node_modules/@jest/core/node_modules/color-name 1632439504163
npm verb unfinished npm timer reifyNode:node_modules/@jest/core/node_modules/color-convert 1632439504163
npm verb unfinished npm timer reifyNode:node_modules/@jest/core/node_modules/supports-color 1632439504163
npm verb unfinished npm timer reifyNode:node_modules/@jest/core/node_modules/ansi-styles 1632439504163
npm verb unfinished npm timer reifyNode:node_modules/@jest/core/node_modules/jest-resolve 1632439504163
npm verb unfinished npm timer reifyNode:node_modules/@jest/core/node_modules/chalk 1632439504163
npm verb code 1`

Couple of things that I have noticed:
1) The error line points to the file system related files (fs.js, graceful-fs etc.). Is there a file-system change that would make it fail by any chance ?
2) Its failing on specific packages (so far I have found @craco/craco and react-scripts). My work machine is where I get the error above which is windows 10 based. My personal laptop is also windows 10 (probably a differrent build of windows 10 ?), I don't see the error there.

Please let me know if anyone knows anything more about it. Thanks

**Comment by DanielRuf** [comment] 2021-10-03 09:46
Do you have a space in the user name / user folder?

**Comment by harrisonhoward** [comment] 2021-10-03 10:22
> Do you have a space in the user name / user folder?

Yes, I've never had issues with it before

**Comment by DanielRuf** [comment] 2021-10-03 10:59
Then this is probably the issue and that the space is not escaped by npm.

**Comment by harrisonhoward** [comment] 2021-10-03 11:00
> Then this is probably the issue and that the space is not escaped by npm.

How do I fix that?

**Comment by wraithgar** [comment] 2022-03-16 22:26
Windows command escaping has been updated since this issue was created.  Is this still an issue for you?

**Comment by nlf** [comment] 2022-05-31 16:20
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.

**Closed as not planned by nlf** 2022-05-31 16:20 UTC
Labels: Release 7.x, Bug, Needs Triage
