### ISSUE TITLE
[BUG] running `npm view` does not always respect the `--registry` option

### ISSUE THREAD

**Issue by Lunatix89** [npm/cli#7659] opened 2024-07-18 08:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

I have a setup where I use `npm view` in my CI/CD pipelines to list all published versions of a package to detect whether a package was already deployed with the version currently being built or not.

However, we also have a dev setup to test our our release process or to create dev builds for testing purposes.
And lately I was wondering why it reported a version as published which was actually never published to the dev registry.

I found out that running the command `npm view @my/package --registry https://DEV-registry`  would not respect the `--registry` option when running inside a directory which contains a `.npmrc` file with a `@my:registry=https://PROD-registry` - it will always use the registry from the `.npmrc`.

Running the same command in a directory without the `.npmrc` file suddenly works as expected.

### Expected Behavior

The `npm view` command should favour the `--registry` argument instead of using the registry from the `.npmrc` file.

### Steps To Reproduce

1. Create a project
2. Add a `.npmrc` file with a "prod" registry entry
3. Have a second, "dev" registry which also defines versions for the package 
4. Run the command `npm view my-package --versions --registry $DEV_REGISTRY` inside the project root dir with the `.npmrc`
5. Observe that the result is actually listing the versions from the PROD registry
6. cd outside of the project
7. Run the command again
8. Observe that it now lists the versions from the DEV registry

### Environment

- npm: 10.8.0
- Node.js: 22.2.0
- OS Name: Windows 10
- System Model Name: HP ZBOOK
- npm config:
```ini
; "user" config from C:\Users\<redacted>\.npmrc

//localhost:4873/:_authToken = (protected)
//pkgs.dev.azure.com/<org-name-redacted>/_packaging/<org-name-redacted>/npm/registry/:_password = (protected)
//pkgs.dev.azure.com/<org-name-redacted>/_packaging/<org-name-redacted>/npm/registry/:username = (protected)
//pkgs.dev.azure.com/<org-name-redacted>/_packaging/<org-name-redacted>/npm/:_password = (protected)
//pkgs.dev.azure.com/<org-name-redacted>/_packaging/<org-name-redacted>/npm/:email = (protected)
//pkgs.dev.azure.com/<org-name-redacted>/_packaging/<org-name-redacted>/npm/:username = (protected)
//pkgs.dev.azure.com/<org-name-redacted>/_packaging/<org-name-redacted>/npm/registry/:_password = (protected)
//pkgs.dev.azure.com/<org-name-redacted>/_packaging/<org-name-redacted>/npm/registry/:username = (protected)

//pkgs.dev.azure.com/<org-name-redacted>/<project-name-redacted>/_packaging/<registry-name-redacted>/npm/registry/:_password = (protected)
//pkgs.dev.azure.com/<org-name-redacted>/<project-name-redacted>/_packaging/<registry-name-redacted>/npm/registry/:username = (protected)
//pkgs.dev.azure.com/<org-name-redacted>/<project-name-redacted>/_packaging/<registry-name-redacted>/npm/registry/:_password = (protected)
//pkgs.dev.azure.com/<org-name-redacted>/<project-name-redacted>/_packaging/<registry-name-redacted>/npm/registry/:username = (protected)

//pkgs.dev.azure.com/<org-name-redacted>/<project-name-redacted>/_packaging/<registry-name-redacted>/npm/registry/:_password = (protected)
//pkgs.dev.azure.com/<org-name-redacted>/<project-name-redacted>/_packaging/<registry-name-redacted>/npm/registry/:username = (protected)
//pkgs.dev.azure.com/<org-name-redacted>/<project-name-redacted>/_packaging/<registry-name-redacted>-dev/npm/registry/:_password = (protected)
//pkgs.dev.azure.com/<org-name-redacted>/<project-name-redacted>/_packaging/<registry-name-redacted>-dev/npm/registry/:username = (protected)
cache = "c:\\dev\\npm\\cache"
email = (protected)

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v22.2.0
; npm local prefix = C:\Users\<redacted>
; npm version = 10.8.0
; cwd = C:\Users\<redacted>
; HOME = C:\Users\<redacted>
; Run `npm config ls -l` to show all defaults.
```

**Comment by milaninfy** [comment] 2024-07-22 19:12
@Lunatix89 In your project where you have .npmrc file, do you have package.json file initialized in your project or it's empty folder with only .npmrc?

**Comment by Lunatix89** [comment] 2024-07-23 08:41
I also have a package.json file in the same directory.
But we are running other `npm` commands which override the registry with the `--registry` flag and all of them use the override rather than what's defined in the `.nmprc` file.

**Comment by milaninfy** [comment] 2024-07-23 15:04
I have similer setup where I have a .npmrc file. As from the logs it looks like it's picking up the value from command and not from .npmrc. 
```bash
~/workarea/rep $ cat .npmrc
registry=http://localhost:4873
~/workarea/rep $ npm view @npm/read versions --registry http://non-ext.com --dddd
npm info using npm@10.8.2
npm info using node@v22.5.1
npm http fetch GET http://non-ext.com/@npm%2fread attempt 1 failed with ENOTFOUND
⠼^C%    
```      
Could you please run the command in log level silly (`-ddd`) and provide logs if possible ?

**Comment by Lunatix89** [comment] 2024-07-24 07:53
Sure, here you can see that it recognized my `--registry` argument and that I wanted to force it to using my local npm feed, namely verdaccio, but in the end it queried our prod feed from the npmrc (https://pkgs.dev.azure.com..).

```
PS C:\dev\repos\myorg\myrepo> npm view @mynamespace/react versions -ddd --registry http://localhost:4873                     
npm verbose cli C:\Program Files\nodejs\node.exe C:\Users\my.name\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
npm info using npm@10.8.0
npm info using node@v22.2.0
npm silly config load:file:C:\Users\my.name\AppData\Roaming\npm\node_modules\npm\npmrc
npm silly config load:file:C:\dev\repos\myorg\myrepo\.npmrc
npm silly config load:file:C:\Users\my.name\.npmrc
npm silly config load:file:C:\Users\my.name\AppData\Roaming\npm\etc\npmrc
npm verbose title npm view @mynamespace/react versions
npm verbose argv "view" "@mynamespace/react" "versions" "--loglevel" "silly" "--registry" "http://localhost:4873"
npm verbose logfile logs-max:10 dir:c:\dev\npm\cache\_logs\2024-07-24T07_45_06_347Z-
npm verbose logfile c:\dev\npm\cache\_logs\2024-07-24T07_45_06_347Z-debug-0.log
npm silly logfile start cleaning logs, removing 1 files
npm silly logfile done cleaning log files
npm http fetch GET 200 https://pkgs.dev.azure.com/myorg/_packaging/myorg/npm/registry/@mynamespace%2freact 1150ms (cache 
updated)
[
  '0.1.0-ci.1228',   '0.1.0-ci.1231',   '0.1.0-ci.1233',  '0.1.0-ci.1235',
  '0.1.0-ci.1236',   '0.1.0-ci.1238',   '0.1.0-ci.1241',  '0.1.0-ci.1243',
  '0.1.0-ci.1251',   '0.1.0-ci.1253',   '0.1.0-ci.1255',  '0.1.0-ci.1257',
  '0.1.0-ci.1262',   '0.1.0-ci.1263',   '0.1.0-ci.1264',  '0.1.0-ci.1268',
  '0.1.0-ci.1269',   '0.1.0-ci.1273',   '0.1.0-ci.1274',  '0.1.0-ci.1275',
  '0.1.0-ci.1281',   '0.1.0-ci.1285',   '0.1.0-ci.1286',  '0.1.0-ci.1287',
  '0.1.0-ci.1289',   '0.1.0-ci.1290',   '0.1.0-ci.1291',  '0.1.0-ci.1294',
  '0.1.0-ci.1295',   '0.1.0-ci.1297',   '0.1.0-ci.1307',  '0.1.0-ci.1319',
  '0.1.0-ci.1321',   '0.1.0-ci.1322',   '0.1.0-ci.1323',  '0.1.0-ci.1324',
  '0.1.0-ci.1325',   '0.1.0-ci.1326',   '0.1.0-ci.1327',  '0.1.0-ci.1329',
  '0.1.0-ci.1334',   '0.1.0-ci.1336',   '0.1.0-ci.1338',  '0.1.0-ci.1340',
  '1.0.0-alpha.1',   '1.0.0-alpha.2',   '1.0.0-alpha.3',  '1.0.0-alpha.4',
  '1.0.0-alpha.5',   '1.0.0-alpha.6',   '1.0.0-alpha.7',  '1.0.0-alpha.8',
  '1.0.0-alpha.9',   '1.0.0-alpha.10',  '1.0.0-alpha.11', '1.0.0-alpha.12',
  '1.0.0-beta.0',    '1.0.0-beta.1',    '1.0.0-beta.2',   '1.0.0-beta.3',
  '1.0.0-beta.4',    '1.0.0-beta.5',    '1.0.0-beta.6',   '1.0.0-beta.7',
  '1.0.0-beta.8',    '1.0.0-beta.9',    '1.0.0-beta.12',  '1.0.0-dev.22547',
  '1.0.0-dev.28277', '1.0.0-dev.28703', '1.0.0',          '1.0.1',
  '1.0.2',           '1.0.3',           '1.0.4',          '1.0.6',
  '1.0.7',           '1.1.0-alpha.0',   '1.1.0-alpha.1',  '1.1.0-alpha.2',
  '1.1.0',           '1.1.1',           '1.1.2',          '1.1.3',
  '1.1.4',           '1.1.5',           '1.2.0-alpha.0',  '1.2.0-alpha.1',
  '1.2.0',           '1.2.1',           '1.2.2',          '1.2.3',
  '1.2.4',           '1.2.5',           '1.3.0-alpha.1',  '1.3.0',
  '1.3.1',           '1.3.2',           '1.3.3',          '1.4.0-alpha.0',
  '1.4.0-alpha.1',   '1.4.0-alpha.2',   '1.4.0-alpha.3',  '1.4.0-alpha.4',
  '1.4.0-beta.0',    '1.4.0-beta.1',    '1.4.0-beta.2',   '1.4.0-beta.3',
  '1.4.0-beta.4',    '1.4.0',           '1.4.1',          '1.4.2',
  '1.4.3',           '1.4.4',           '1.4.5',          '1.5.0-alpha.0',
  '1.5.0-alpha.1',   '1.5.0-alpha.2',   '1.5.0-alpha.3',  '1.5.0-beta.0',
  '1.5.0-beta.1',    '1.5.0-beta.2',    '1.5.0-beta.3',   '1.5.0',
  '1.5.1',           '1.5.2',           '1.5.3',          '1.5.4',
  '1.5.5',           '1.5.6',           '1.6.0-alpha.0',  '1.6.0-alpha.4',
  '1.6.0-alpha.5',   '1.6.0-alpha.6',   '1.6.0-alpha.7',  '1.6.0-alpha.8',
  '1.6.0-alpha.9',   '1.6.0-alpha.10'
]
npm verbose cwd C:\dev\repos\myorg\mypackage
npm verbose os Windows_NT 10.0.19045
npm verbose node v22.2.0
npm verbose npm  v10.8.0
npm verbose exit 0
npm info ok
```

**Comment by Lunatix89** [comment] 2024-07-24 08:18
I'm just wondering but could it be because in my npmrc I have an entry specific for my namespace?
I just realized that I never posted the npmrc here so here it is:

```
registry=https://registry.npmjs.org
@mynamespace:registry=https://pkgs.dev.azure.com/myorg/_packaging/myorg/npm/registry/
always-auth=true

//localhost:4873/:_authToken="12345"
```

When I run `npm view react versions --registry http://localhost:4873` it queries the `localhost:4873` address instead of `registry.npmjs.org`.
But.. imho it should still use the registry from the argument provided to the command?

**Comment by milaninfy** [comment] 2024-07-26 19:52
@Lunatix89 Yes. Once the scope is associated with registry in config then all the request for that scoped package will be done to that scoped registry endpoint, It's happening because npm merges your all your configs i.e. Global, User, Project and then command line flags and you are only overriding registry value and not the scoped:registry value. You can try something like this
`npm view @namespace/react versions --@namespace:registry=http://localhost:4873`

Closing this as it's working as intended.

**Closed as completed by milaninfy** 2024-07-26 19:52 UTC
Labels: Bug, Needs Triage

**Comment by Lunatix89** [comment] 2024-07-30 08:57
That really makes sense, I somehow did not concider that one could provide a "dynamic" `@namespace:registry` argument.
However, this seems to trigger another bug, `output.endsWith is not a function`, like you can see here:

```
npm view @namespace/lib versions --@namespace:registry http://localhost:4873 -ddd
npm verbose cli C:\Program Files\nodejs\node.exe C:\Users\user.name\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
npm info using npm@10.8.2
npm info using node@v22.2.0
npm silly config load:file:C:\Users\user.name\AppData\Roaming\npm\node_modules\npm\npmrc
npm silly config load:file:C:\WINDOWS\system32\.npmrc
npm silly config load:file:C:\Users\user.name\.npmrc
npm silly config load:file:C:\Users\user.name\AppData\Roaming\npm\etc\npmrc
npm verbose title npm view @namespace/lib versions http://localhost:4873
npm verbose argv "view" "@namespace/lib" "versions" "--@namespace:registry" "http://localhost:4873" "--loglevel" "silly"
npm verbose logfile logs-max:10 dir:c:\dev\npm\cache\_logs\2024-07-30T08_53_53_136Z-
npm verbose logfile c:\dev\npm\cache\_logs\2024-07-30T08_53_53_136Z-debug-0.log
npm silly logfile start cleaning logs, removing 2 files
npm verbose stack TypeError: output.endsWith is not a function
npm verbose stack     at removeTrailingSlashes (C:\Users\user.name\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\util\trailing-slashes.js:4:17)
npm verbose stack     at new RegistryFetcher (C:\Users\user.name\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\registry.js:36:28)
npm verbose stack     at FetcherBase.get (C:\Users\user.name\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\fetcher.js:478:14)
npm verbose stack     at packument (C:\Users\user.name\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\index.js:21:30)
npm verbose stack     at #getData (C:\Users\user.name\AppData\Roaming\npm\node_modules\npm\lib\commands\view.js:135:26)
npm verbose stack     at #viewPackage (C:\Users\user.name\AppData\Roaming\npm\node_modules\npm\lib\commands\view.js:112:47)
npm verbose stack     at View.exec (C:\Users\user.name\AppData\Roaming\npm\node_modules\npm\lib\commands\view.js:70:28)
npm verbose stack     at C:\Users\user.name\AppData\Roaming\npm\node_modules\npm\lib\npm.js:251:63
npm verbose stack     at Object.start (C:\Users\user.name\AppData\Roaming\npm\node_modules\npm\node_modules\proc-log\lib\index.js:101:21)
npm verbose stack     at #exec (C:\Users\user.name\AppData\Roaming\npm\node_modules\npm\lib\npm.js:250:17)
npm error output.endsWith is not a function
npm verbose cwd C:\WINDOWS\system32
npm verbose os Windows_NT 10.0.19045
npm verbose node v22.2.0
npm verbose npm  v10.8.2
npm verbose exit 1
npm verbose code 1
npm error A complete log of this run can be found in: c:\dev\npm\cache\_logs\2024-07-30T08_53_53_136Z-debug-0.log
```

So either it's not officially supported or there is a bug the code.

**Comment by milaninfy** [comment] 2024-07-30 13:33
@Lunatix89 you need to use the `=` sign 
`npm view @namespace/lib versions --@namespace:registry=http://localhost:4873 -ddd`

**Comment by Lunatix89** [comment] 2024-07-31 08:10
Oh.. that makes sense now.
Thanks a lot, it works like a charm :)
