### ISSUE TITLE
[BUG] npm docs with no pkgname arg returns undefined

### ISSUE THREAD

**Issue by Ocean-OS** [npm/cli#7709] opened 2024-08-07 20:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

The `npm docs` command is used to find the documentation for a specific package. However, if you run `npm docs` with no pkgname given, it returns `https://npmjs.org/package/undefined`. This is because the pkgname argument (undefined) is converted to a string, and then concatenated with `https://npmjs.org/package/`. 

### Expected Behavior

There isn't a specific thing that this should do, but in a (now closed) [PR I made](https://github.com/npm/cli/pull/7689), I made it return the [NPM docs](https://docs.npmjs.org), which seemed like the logical thing to do. One thing I have noticed after testing it more is that my PR has a minor bug where it does not work when the active directory does not have a package.json present. 

### Steps To Reproduce

1. Open your command prompt
2. Run `npm docs` or `npm docs --no-browser` in a directory with a package.json present
3. See that the URL opened/returned is `https://npmjs.org/package/undefined`

### Environment

- npm: 10.8.2
- Node.js: 20.9.0
- OS Name: Windows 11
- System Model Name: Lenovo Thinkpad Yoga
- npm config:
```ini
; "builtin" config from C:\Users\username\AppData\Roaming\npm\node_modules\npm\npmrc

prefix = "C:\\Users\\username\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v20.9.0
; npm local prefix = C:\Users\username
; npm version = 10.2.5
; cwd = C:\Users\username
; HOME = C:\Users\username
; Run `npm config ls -l` to show all defaults.
```

**Comment by milaninfy** [comment] 2024-08-07 20:53
@Ocean-OS I am not able to reproduce the issue on 10.8.2 with Windows or on MacOs 
Please provide full logs of running both commands to inspect further `npm docs -ddd` & `npm docs --no-browser -ddd` also the package.json that is being used to replicate the behaviour similer to yours.

**Comment by milaninfy** [comment] 2024-08-13 15:27
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.

**Closed as not planned by milaninfy** 2024-08-13 15:27 UTC
Labels: Cannot Reproduce
