### ISSUE TITLE
[BUG] Single -- separator fails to pass arguments to npm script in version 10.9.0

### ISSUE THREAD

**Issue by leebailey88** [npm/cli#7880] opened 2024-10-27 20:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Instead of executing the mtm script with the specified arguments, npm outputs the current version (10.9.0) and exits.

## Workaround
npm run mtm -- -- -l 1 -s 0 -h 160000 -f vix/vix-ta-macro-advanced --vix --bci --seasonal --cpi --effr --bond10 --bond2 --aaii --m2 --cape --fileToSheetName -v

### Expected Behavior

Running the following command should execute the `mtm` script in `package.json` with the provided arguments:

```bash
npm run mtm -- -l 1 -s 0 -h 160000 -f vix/vix-ta-macro-advanced --vix --bci --seasonal --cpi --effr --bond10 --bond2 --aaii --m2 --cape --fileToSheetName -v```

### Steps To Reproduce

### Steps to Reproduce
1. Create an `mtm` script in `package.json`:
   ```json
   {
     "scripts": {
       "mtm": "node path/to/your-script.js"
     }
   }
   ```
2. Run the command with arguments after a single `--` separator:
   ```bash
   npm run mtm -- -l 1 -s 0 -h 160000 -f vix/vix-ta-macro-advanced --vix --bci --seasonal --cpi --effr --bond10 --bond2 --aaii --m2 --cape --fileToSheetName -v
   ```
3. Observe that npm prints its version instead of executing the script with the arguments.

### Additional Notes
This behavior change only started after upgrading to npm 10.9.0; the command worked correctly on 10.8.0. This change may be a bug or a new feature, but it’s currently undocumented.

### Environment
- **npm version**: 10.9.0
- **Node.js version**: 20.11.0
- **Operating system**: Windows 11

**Comment by milaninfy** [comment] 2024-10-29 13:02
Are you running in powershell? `---` is also valid as far as i know. This is powershell behaviour.

**Comment by milaninfy** [comment] 2024-10-29 13:06
**Closing:** this looks to be similar if not a duplicate of an existing issue, [7375](https://github.com/npm/cli/issues/7375). If you believe your instance is unique, please provide further clarifying details.

**Closed as not planned by milaninfy** 2024-10-29 13:06 UTC
Labels: Bug, Duplicate
