### ISSUE TITLE
[BUG] Cannot read property 'resolve' of undefined on 64-bit npm installation

### ISSUE THREAD

**Issue by castrojo** [npm/cli#1604] opened 2020-08-03 15:03 UTC
# What / Why
I'm running an app workshop with a node example app. It runs fine with npm on OSX/Linux, but the 64 bit installer gives us this error. Removing the 64-bit installer and installing the 32-bit installer resolves this. I'm not the author of the app or the workshop, just reporting this in case it's an npm bug. 

## When
Given this example app: https://github.com/miroslawmajka/sample-express-app
Run `npm install` on the root gives:

Screenshot of error provided by student: 

![Screenshot (98)](https://user-images.githubusercontent.com/1264109/89196698-90c76580-d578-11ea-9cc4-5ea66788050b.png)

**Comment by bnb** [comment] 2020-08-06 17:07
thanks for filing this @castrojo ❤️

**Comment by bzoz** [comment] 2020-08-10 20:40
@castrojo Sorry, cannot reproduce. Are there maybe some setup instructions that we could follow to try to reproduce it?

**Comment by darcyclarke** [comment] 2021-06-02 21:08
npm `v6` is no longer in active development; We will continue to push security releases to `v6` at our team's discretion as-per our [Support Policy](https://github.com/npm/cli/wiki/Support-Policy).

If your bug is preproducible on `v7`, please re-file this issue using our [new issue template](https://github.com/npm/cli/issues/new?assignees=&labels=Bug%2CNeeds+Triage%2CRelease+7.x&template=bug_7.yml&title=%5BBUG%5D+%3Ctitle%3E).

If your issue was a feature request, please consider opening a new [RRFC](https://github.com/npm/rfcs/issues) or [RFC](https://github.com/npm/rfcs). If your issue was a question or other idea that was not CLI-specific, consider opening a discussion on our [feedback repo](https://github.com/npm/feedback)

**Closing:** This is an automated message.

**Closed as completed by darcyclarke** 2021-06-02 21:08 UTC
Labels: Release 6.x, Bug
