### ISSUE TITLE
[BUG] npm -g ls or outdated won't show/update some packages

### ISSUE THREAD

**Issue by tavrez** [npm/cli#3928] opened 2021-10-21 18:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have some global installed packages which I can't see in `npm -g ls`. I also can't see them being outdated with `npm -g outdated`. These packages are eslint, yarn, semver
I tried to remove and re-install them(`npm -g remove eslint yarn semver && npm -g i eslint yarn semver`) But no luck, they still won't appear in `npm -g ls`. I also purged npm cache once before re-installation

### Expected Behavior

Update/View these packages like others

### Steps To Reproduce

1. `npm -g ls`
2. I have 20 packages in %appdata%\npm\node_modules but I only see 17

### Environment

- OS: Windows 10 21H1
- Node: 14.18.1
- npm: 8.1.0

**Comment by tavrez** [comment] 2021-10-21 18:56
I've tested again with npm 8.0.0 and npm@7 and I still can't see these 3 packages

**Comment by ljharb** [comment] 2021-10-21 19:24
What does `which eslint` print out vs `npm root -g`? Perhaps it's coming from a different node install.

**Comment by tavrez** [comment] 2021-10-21 19:44
I only have one version of node installed, all global packages are in %appdata%\npm (eslint and others, also npm root)
Adding and removing those problematic packages works successfully, but they're still not available in npm -g ls list

**Comment by ljharb** [comment] 2021-10-21 20:38
and `npm ls -g --depth=0`?

**Comment by tavrez** [comment] 2021-10-21 20:57
Same as npm -g ls
All my packages expect those 3, while all of them are installed in the same directory!

**Comment by ljharb** [comment] 2021-10-21 22:31
(separately from this issue, eslint shouldn't be installed globally - it should be installed locally per-project, and if a package "expects" them, then it `require`s them, which means they must be locally installed - you can't require global packages, which are only for non-project-specific command line tools)

**Comment by lukekarrys** [comment] 2021-10-22 02:43
Closing as a duplicate of #3877.

**Closed as completed by lukekarrys** 2021-10-22 02:43 UTC
Labels: Release 8.x, Bug, Needs Triage

**Comment by tavrez** [comment] 2021-10-23 18:47
@ljharb just to answer, I do use eslint in projects I need. The global one is for vscode, for when I want to quickly edit js files outside of projects(linting and formatting)
