### ISSUE TITLE
[BUG] error 'could not determine executable to run' when using 'npm init' with a scoped package in a private registry 

### ISSUE THREAD

**Issue by grahaml** [npm/cli#2726] opened 2021-02-18 20:15 UTC
Hello! I am having an issue that may or may not be related to #1845 - it's the same error output, but a different setup. 

I have a project initializer, designed to work via `npm init @myscope/lib`. The package is published to a registry through my company's self-hosted GitLab instance. 

I have created a small repo to reproduce the issue: https://github.com/grahaml/create-npm-initializer-bug-with-scope, but it's a bit hard to provide a complete example, as the issue only happens when the package is published to another registry, and in my case that's private to the company I work for.

So far I've tried narrowing this down through the following methods using the package linked above:

- publish to `npm` registry with no scope (see https://www.npmjs.com/package/create-npm-initializer-bug) -- WORKS
- publish to `npm` registry with my personal scope (see https://www.npmjs.com/package/@glosee/create-npm-initializer-bug-with-scope) -- WORKS
- publish to GitLab registry with my personal scope on GitLab (unfortunately can't share this due to it being a private instance, but I have published the same `@glosee/create-npm-initializer-bug-with-scope` to our private GitLab registry) -- DOES NOT WORK

Given this, it's possible that the issue is with GitLab and not `npm`. I thought, however, that it would be good to start here, as this is the tool that's throwing the error, and the bug may have to do with module resolution within `npm` itself when the package is in another registry. 

### Current Behavior:

Given a component with the following package.json config (irrelevant fields removed for brevity) published to a registry on a GitLab instance

```
{
  "name": "@myscope/create-lib",
  "main": "dist/index.js",
  "bin": {
    "create-lib": "dist/index.js"
  },
  "publishConfig": {
    "@myscope:registry": "https://gitlab.my-company.com/api/v4/projects/1234/packages/npm/"
  }
}
```

When I run the following command with `npm@7.x.x`

```
npm init @myscope/lib --loglevel=silly
```

Then I get the following output (with just the URL edited to obscure our private host)

```
npm verb cli [
npm verb cli   '/Users/grlosee/.asdf/installs/nodejs/15.2.0/bin/node',
npm verb cli   '/Users/grlosee/.asdf/installs/nodejs/15.2.0/.npm/bin/npm',
npm verb cli   'init',
npm verb cli   '@myscope/lib',
npm verb cli   '--loglevel=silly'
npm verb cli ]
npm info using npm@7.4.0
npm info using node@v15.2.0
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:/Users/grlosee/.asdf/installs/nodejs/15.2.0/.npm/lib/node_modules/npm/npmrc Completed in 1ms
npm timing config:load:builtin Completed in 1ms
npm timing config:load:cli Completed in 1ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:/Users/grlosee/Projects/sandbox/test-initializer/.npmrc Completed in 0ms
npm timing config:load:project Completed in 1ms
npm timing config:load:file:/Users/grlosee/.npmrc Completed in 1ms
npm timing config:load:user Completed in 1ms
npm timing config:load:file:/Users/grlosee/.asdf/installs/nodejs/15.2.0/.npm/etc/npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:cafile Completed in 0ms
npm timing config:load:validate Completed in 1ms
npm timing config:load:setUserAgent Completed in 0ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 7ms
npm verb npm-session a7e7b532a48a075a
npm timing npm:load Completed in 16ms
npm http fetch GET 304 https://gitlab.mycompany.com/api/v4/packages/npm/@myscope%2fcreate-lib 246ms (from cache)
npm timing command:exec Completed in 254ms
npm timing command:init Completed in 294ms
npm verb stack Error: could not determine executable to run
npm verb stack     at getBinFromManifest (/Users/grlosee/.asdf/installs/nodejs/15.2.0/.npm/lib/node_modules/npm/lib/exec.js:264:23)
npm verb stack     at exec (/Users/grlosee/.asdf/installs/nodejs/15.2.0/.npm/lib/node_modules/npm/lib/exec.js:178:15)
npm verb stack     at processTicksAndRejections (node:internal/process/task_queues:93:5)
npm verb cwd /Users/grlosee/Projects/sandbox/test-initializer
npm verb Darwin 19.6.0
npm verb argv "/Users/grlosee/.asdf/installs/nodejs/15.2.0/bin/node" "/Users/grlosee/.asdf/installs/nodejs/15.2.0/.npm/bin/npm" "init" "@myscope/lib" "--loglevel=silly"
npm verb node v15.2.0
npm verb npm  v7.4.0
npm ERR! could not determine executable to run
npm verb exit 1
npm timing npm Completed in 459ms
```

Following the same steps above with `npm@6`,  everything works as expected (my script runs without error).

### Expected Behavior:

Given the steps above, I would expect that my script `@myscope/lib` would run without error and do its thing (creating some directories and writing some files). 

### Steps To Reproduce:

See detailed steps above.

### Environment:
- OS: MacOS 10.15.7
- Node: 15.2.0 (installed via `asdf`)
- npm: 7.4.0 (I have also tried 7.0.2, 7.5.2, 7.5.4 and gotten the same results)

FWIW I followed the stack trace in the error output above, which says that the error is thrown by `getBinFromManifest` here: https://github.com/npm/cli/blob/e703362b02d672a14a98af8e2f99ae75c1bab945/lib/exec.js#L258. If I am following that logic correctly, the first thing it does is try to get `bin` from the manifest. If there is only one entry in the `bin` object, then it will return the key of that entry. If there is a key on `bin` that is equal to the `name` without the scope, then it will return the value of that key (eg. `manifest[nameWithoutScope]`). Otherwise, it throws this "could not determine executable to run" error. I know for sure that my manifest has a `bin` field, and specifically it has `bin.nameOfPackage`, which leads me to believe that the `mani` being passed in to `getBinFromManifest` is either non-existant or incomplete (but that's a complete shot in the dark - just guessing based on spending a few mins trying to read your source code).

I realize this is a bit obscure and will be difficult for anyone else to replicate. Please let me know what (if anything) else I might be able to add to help.

**Comment by isaacs** [comment] 2021-02-19 20:15
Are there other bins defined in your package.json file?

This works fine:

```
$ npm init @isaacs/test
Need to install the following packages:
  @isaacs/create-test
Ok to proceed? (y) y
hello this is a test script
```

Using this package: `https://registry.npmjs.org/@isaacs/create-test`

1.0.0 works because there is exactly 1 bin.  1.0.1 works because there is a bin named `create-test`.

The minified manifest that the default npm registry returns for this package is this:

<details>

<summary>hidden because long</summary>

```
$ pacote manifest @isaacs/create-test
{
  name: '@isaacs/create-test',
  version: '1.0.1',
  bin: {
    'some-other-thing': 'dist/other.js',
    'create-test': 'dist/index.js'
  },
  dist: {
    integrity: 'sha512-AjFtqMuVJixjqSTuSy2V0XN8Lzy4c1LIRxzi6QCl7aLTQwhbqDfBiMqWi2SPxZYGLCpzTStsVbRT7axIIvMm+Q==',
    shasum: '47b2f21d4b88c74f440c1a723c353240f012cf38',
    tarball: 'https://registry.npmjs.org/@isaacs/create-test/-/create-test-1.0.1.tgz',
    fileCount: 3,
    unpackedSize: 378,
    'npm-signature': '-----BEGIN PGP SIGNATURE-----\r\n' +
      'Version: OpenPGP.js v3.0.13\r\n' +
      'Comment: https://openpgpjs.org\r\n' +
      '\r\n' +
      'wsFcBAEBCAAQBQJgMBtPCRA9TVsSAnZWagAAVNAQAIylIubIOj9GcjBtwTLL\n' +
      'v3Rfk287Pxqw3ZFHYYc21pwdeQwqd4SBna7nGCrx9CIfLVy2xUiJnw5+b+XP\n' +
      'wG4VS52+lW+01+cmRJHm65wuKyGa7z2jZLc4XOW9NUK3wcI7A0n8hSQow2YK\n' +
      'F2HkKLXZI1CQs1ugCy65ahRVdPvA1zqIg81BssRUr57dDE2IWYwBJ3GgEJtI\n' +
      '0BBREdyWcUD/tiMaOR4vr8OZFCNo3yOP4VfFSZ+8xhEGT2cxG7XNCvdRGBtO\n' +
      'e/3zNRMrZYbYV1O81EHnX2RUmFrOL4AWfwkITb9Vv7av8u4O6ZM+3Ta2NXUS\n' +
      'R7IWuHEyeClzvODRKbMgRC7l3Y/zWqa1ykwJPpiMVp462pxFbPdnvc3Q1G5y\n' +
      'NNA65QQIHC2xNCApmzrb3UBffZ+jg+BVUa9nIQQYmGca5r4bPQIza7/qi05H\n' +
      'Wv9PXd16VPU7xiYZbF218EWY/Q4dClTJ0HdQ/0elAYlZS48cbhdcn2QPwuXl\n' +
      'qPRxxULS+bevu5xag7zwtrW/TzV5x6nbF+8OCYByTOdEQ6xB0VR/xxgUN436\n' +
      'ELVHXrPX02gWdu4WYqWlG48/7hKG6sqeRCdymmqVfrhn4VwsmHvlHEBtO2ps\n' +
      'CqFJ/kI5unrM4sif+N88HWOvUpdRP7NTNAwqX56fVmqyoT4ltFLZlQ4X5dLw\n' +
      'G73m\r\n' +
      '=Nbia\r\n' +
      '-----END PGP SIGNATURE-----\r\n'
  },
  _resolved: 'https://registry.npmjs.org/@isaacs/create-test/-/create-test-1.0.1.tgz',
  _from: '@isaacs/create-test@',
  _integrity: 'sha512-AjFtqMuVJixjqSTuSy2V0XN8Lzy4c1LIRxzi6QCl7aLTQwhbqDfBiMqWi2SPxZYGLCpzTStsVbRT7axIIvMm+Q=='
}
```

</details>

Can you try running this command and see if the returned object has the proper `bin` object you expect?

```
npx pacote manifest @myscope/create-lib --registry= https://gitlab.my-company.com/api/v4/projects/1234/packages/npm/
```

But, of course, replace `myscope` and `my-company` and `1234` with the actual values you are using.

If the problem is that your internal registry is not telling you which bins the package has, well... there's not much I can do to help you there.

**Comment by grahaml** [comment] 2021-02-22 20:52
Thanks very much for the detailed reply (and for teaching me about `pacote`). It took me a few mins to get it to work -- needed to pass `--token` as well -- but now I can see that there is actually no `bin` whatsoever in the manifest.

```
{
  name: '@myscope/create-lib',
  version: '0.0.1-beta.6',
  dist: {
    shasum: ....,
    tarball: 'https://gitlab.mycompany.com/api/v4/projects/1234/packages/npm/@myscope/create-lib/-/@myscope/create-lib-0.0.1-beta.6.tgz'
  },
  dependencies: { ... },
  devDependencies: { ... },
  _resolved: 'https://gitlab.mycompany.com/api/v4/projects/1234/packages/npm/@myscope/create-lib/-/@myscope/create-lib-0.0.1-beta.6.tgz',
  _from: '@myscope/create-lib@',
  _integrity: ...
}
```

Compared to the output you showed above, and that from my own test project... there are actually a handful of fields missing. The issue is clearly on GitLab's side then, with how it exposes manifests. 

FWIW I can workaround this by having my team downgrade to `npm@6` for the time being. I will be reaching out to GitLab support to try to dig in to this further. 

Thanks again very much for taking the time to reply! I think this issue can be closed now then.

**Comment by grahaml** [comment] 2021-02-22 21:16
Oh one final thought - my initializer _does_ work with `npm@6`. I know that there was a significant amount of refactoring in `npm@7`. Any thoughts on what might have changed that could cause this issue?

Using `npm@6` I get the same output from `pacote manifest`, but I am actually able to do `npm init @myscope/lib`. What's different here?

**Comment by grahaml** [comment] 2021-02-23 15:52
Wanted to let you fine folks know that GitLab is aware of this issue and has it on their Backlog. Just in case anyone else stumbles upon this. For reference: https://gitlab.com/gitlab-org/gitlab/-/issues/275992 <- this is the exact issue I am facing.

Thanks again for all you do for the JS community <3

**Comment by isaacs** [comment] 2021-03-08 21:36
Added a note: https://gitlab.com/gitlab-org/gitlab/-/issues/275992#note_524624026

In the meantime, it _might_ make sense for exec to do a `fullMetadata:true` manifest request if the one we get doesn't have any bin present, on the assumption that you _probably_ picked a thing that you expect to have a bin already, so the filtering might be doing the wrong thing.

**Comment by grahaml** [comment] 2021-03-12 14:19
That's amazing - thank you very much @isaacs for taking the time to comment on their thread! Here's hoping it helps move the issue along on their side. Cheers!

**Comment by darcyclarke** [comment] 2021-05-03 18:39
Closing: GitLab is working on resolving this https://gitlab.com/gitlab-org/gitlab/-/issues/275992#note_549498038

**Closed as completed by darcyclarke** 2021-05-03 18:39 UTC
Labels: Release 7.x, Bug, Priority 1
