### ISSUE TITLE
[BUG] npm ci executes locally but fails on all other machines

### ISSUE THREAD

**Issue by urbullet** [npm/cli#6666] opened 2023-07-22 00:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

Whenever I try to modify the package-json file (add new dependency, update existing one, removing one), I seem to have no issue in doing that and generating a new package-lock file. This used to work fine and I was able to share the changes with other machines and pipelines. 

However, recently something changed and its no longer working. It would execute with no issues on my machine but whenver I commit the package-lock file and some other machine runs `npm ci` it immediately fails, but if I was to do the same thing on my machine it would have no issues.

All the machins share the same node and npm versions. I have tried doing a fresh install of node js and a fresh code repository but no change there. When someone else runs `npm install` and commits that file the exact same way I did, the pipeline would no longer fail and the other machines (including mine) are able to run `npm ci` with no issues. 

I have tried verifying the cache and clearing it completely with force. I have also tried deleting the node_modules file and package-lock file to force generate a new one but no changes happens. When I run `npm install` nothing changes and it would work on my machine only. 

Not sure what else I can try. 

I am using Macos 13.4 (22F66)
Node v16.17.1
npm v8.15.0

### Expected Behavior

When I update the package.json file and run npm install I expect the new package-lock file to be valid

### Environment

- npm: 8.15.0
- Node.js: 16.17.1
- OS Name: Macos 13.4 (22F66)
- System Model Name: Macos 13.4 (22F66)
- npm config:
```ini
; "user" config from /Users/bullet/.npmrc

legacy-peer-deps = true 

; node bin location = /Users/bullet/.nvm/versions/node/v16.17.1/bin/node
; node version = v16.17.1
; npm local prefix = /Users/bullet/IdeaProjects/ris
; npm version = 8.15.0
; cwd = /Users/bullet/IdeaProjects/ris
; HOME = /Users/bullet
; Run `npm config ls -l` to show all defaults.

```

**Comment by kchindam-infy** [comment] 2024-09-06 20:51
@urbullet  Can you add more details
1. The exact error message on failing machines
2. Steps to recreate the issue
3. If any, differences in machine configurations. 
This will help for better diagnosis and find the root casue.

**Comment by kchindam-infy** [comment] 2024-09-16 20:44
**Closing** due to age.  If this is still a problem please feel free to reopen this issue, or create a new issue w/ steps to reproduce.

**Closed as not planned** 2024-09-16 20:45 UTC
Labels: Release 8.x, Bug, Needs Triage
